### ISSUE TITLE
DependencyChecker - Parrallel scans 

### ISSUE THREAD

**Issue by seanboylan** [dependency-check/DependencyCheck#100]
Hi, 
I was running scans on multiple projects in parallel. Dependencycheck hung and I killed the application. I now cannot run a single scan.
- Does dependency check support multiple scans in parallel ?
- How do I fix this problem bar re-installing dependencychecker?

The following is the point in the logs where it hangs:

Mar 25, 2014 12:01:18 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory getConnection
FINE: Connection String: jdbc:h2:file:/opt/app/dependencychecker/data/cve.2.9;AUTO_SERVER=TRUE;AUTOCOMMIT=ON;
Mar 25, 2014 12:01:18 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory getConnection
FINE: Database User: dcuser
Mar 25, 2014 12:01:18 PM org.owasp.dependencycheck.utils.Settings getDataFile
FINE: Settings.getDataFile() - file: '/opt/app/dependencychecker/data'
Mar 25, 2014 12:01:18 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory getConnection
FINE: Need to create DB Structure: false
Mar 25, 2014 12:01:18 PM org.owasp.dependencycheck.data.nvdcve.ConnectionFactory getConnection
FINE: Loading driver: org.h2.Driver

**Comment by colezlaw** [comment]
I'm guessing that the problem is that h2 doesn't allow multiple simultaneous connections to the DB. So your options are going to be:
1) Fan out the data directories (use a unique data dir for each execution) - not ideal
2) Rather than using the data directory, use a database server (even H2 will do). You can configure the driver class, connection string, etc., in the CLI and other tools.
3) It's _possible_ that things won't go haywire if you specify not to update, then use some other process to do the update when no scans are occurring.

To recover from your current situation, you can either delete the whole data directory, or you might be able to just delete the .lock file in the data directory.

**Comment by jeremylong** [comment]
The H2 database _should_ support multiple connections. I have tested this
and it did work on my machine (windows) due to the inclusion of the
"AUTO_SERVER=TRUE".
However, apparently this does not work on your system. If you are no longer
able to run a scan, you can try deleting the data directory on your system
which appears to be: '/opt/app/dependencychecker/data'. Then run a single
scan to update the database (may take anywhere from 5-20+ minutes depending
on several factors such as Internet speed).

I will do some more testing on linux (or are you on a mac?) to see if I can
isolate the bug.  You do have the option of using a more robust DB Server
by setting the connection string and database driver (see the configuration
settings herehttp://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html).
(you would need to create the table structure using a script such as the
one for MySQL found
herehttps://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/data/initialize_mysql.sqlhttps://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/data/initialize_mysql.sql
).

Sorry for any inconvenience...

--Jeremy

**Comment by jeremylong** [comment]
Will - thanks for pointing out the option of setting it not to perform an
update when doing the scanning. This also should work - but you definitely
do need to setup a process to update the data at least weekly if not more
often.

--Jeremy

**Comment by seanboylan** [comment]
Removing the lock file meant I could run again. I will investigate your suggestion as parrallel scan is a must have for me.

I am using RHAT Linux 6.

I am experiencing a new problem in the log file - not sure if its related:

FINE: Begin Analysis of '/opt/app/creditcardservice/ri-iphoneportal/creditcardservice-iphoneportal_staging/WEB-INF/lib/DbResourceBundle-10.3.jar'
Mar 25, 2014 12:39:55 PM org.owasp.dependencycheck.data.nexus.NexusSearch searchSha1
FINE: Searching Nexus url http://repository.sonatype.org/service/local/identify/sha1/8e4844d31462047c9a72e818c1b47a012064acb2
Mar 25, 2014 12:40:16 PM org.owasp.dependencycheck.analyzer.NexusAnalyzer analyze
FINE: Could not connect to nexus repository
java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
    at org.owasp.dependencycheck.data.nexus.NexusSearch.searchSha1(NexusSearch.java:82)
    at org.owasp.dependencycheck.analyzer.NexusAnalyzer.analyze(NexusAnalyzer.java:160)
    at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:322)
    at org.owasp.dependencycheck.App.runScan(App.java:107)
    at org.owasp.dependencycheck.App.run(App.java:86)
    at org.owasp.dependencycheck.App.main(App.java:56)

**Comment by colezlaw** [comment]
Looks now like you're using an older version of Dependency Check as in 1.1.3, it will disable the Nexus analyzer if it can't connect to the Nexus server. There are several options for configuring how this works:
1) --nexus <URL> is a URL to an internal Nexus server (usually ends in /service/local/) to use instead of Central
2) If you want to just use Central, and you're behind a proxy, configure --proxyurl, --proxyport, --proxyuser, --proxypass so that connections can be made to Nexus
3) --disableNexus will disable the Nexus analyzer entirely

Also, I found yesterday that Nexus has set HTTP connections to redirect to HTTPS, however the HTTP libraries we're using don't follow redirects. So if you see that you're getting 301's from Nexus, you'll need to change the Nexus URL (if you want to use Central) to https://repository.sonatype.org/service/local/ until 1.1.4 is released which sets the default URL to this.

**Comment by seanboylan** [comment]
Apologies - I got laylaid with other work so wasn't able to follow up on the thread. 
I have upgraded to version 1.1.4 and the errors are now resolved. I am getting the warning below in the logs: I don't understand the post above in relation to Nexus. 

What is nexus being used for?- is it to check the sHA1 hash of the jar?
I presume I just need to set the -nexus option in order to pickup or local nexus server?

VERSION 1.1.4 logs:
Mar 31, 2014 9:15:12 AM org.owasp.dependencycheck.analyzer.NexusAnalyzer initializeFileTypeAnalyzer
WARNING: There was an issue getting Nexus status. Disabling analyzer.

FINE: Initializing Nexus Analyzer
Mar 31, 2014 9:14:51 AM org.owasp.dependencycheck.analyzer.NexusAnalyzer initializeFileTypeAnalyzer
FINE: Initializing Nexus Analyzer
Mar 31, 2014 9:14:51 AM org.owasp.dependencycheck.analyzer.NexusAnalyzer initializeFileTypeAnalyzer
FINE: Nexus Analyzer enabled: true
Mar 31, 2014 9:14:51 AM org.owasp.dependencycheck.analyzer.NexusAnalyzer initializeFileTypeAnalyzer
FINE: Nexus Analyzer URL: https://repository.sonatype.org/service/local/
Mar 31, 2014 9:14:51 AM org.owasp.dependencycheck.data.nexus.NexusSearch <init>
FINE: Not using proxy

**Comment by jeremylong** [comment]
the Nexus analyzer will check central (or whatever server you configure) for the SHA1 hash and may add additional information to the analysis evidence (GAV).

Regarding Parallel Scans - we are testing a change to the connection string that will hopefully resolve the issue.

--Jeremy

**Comment by seanboylan** [comment]
Thnaks - I will grab the released version once available.

**Comment by jeremylong** [comment]
Sean,

Can you confirm that the issue with Parallel Scans can now be closed?

**Comment by seanboylan** [comment]
Yes this issue can be clsoed. Thanks Sean
