### ISSUE TITLE
Pipeline Disabling audit Bundle

### ISSUE THREAD

**Issue by sharmeelamn2018** [dependency-check/DependencyCheck#1023]
Hi Steve,

I ran into this error when running Dependency Checker as a pipeline script. I am not using Ruby and would like to disable auditBundle.
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.InitializationException
[DependencyCheck] Cause: bundle-audit initialization failure; this error can be ignored if you are not analyzing Ruby. Otherwise ensure that bundle-audit is installed and the path to bundle audit is correctly specified

I checked your other posts where you've advised to have the auditBundle disabled. But I could not find the alternative groovy command for "analyzer.bundle.audit.enabled=false (or) `-Danalyzer.bundle.audit.enabled=false'". Could you please help me with this. Thanks!

**Comment by stevespringett** [comment]
@sharmeelamn2018 Enabling/disabling analyzers is a Jenkins global configuration option, not available on individual jobs. Unlike other tools in the Dependency-Check ecosystem, the Jenkins plugin ships with everything enabled by default. This is due to the high likelihood that a Jenkins cluster will likely support many different technology stacks.

You can 1) disable the analyzer globally, or 2) specify the types of files you want to scan in the job config. By default, the Jenkins plugin will attempt to scan everything in the project workspace which is often overkill.

In the next release, the Bundle analyzer will be disabled by default. It will be the only analyzer that will be disabled.

Refer all future comments to https://issues.jenkins-ci.org/browse/JENKINS-46746
