### ISSUE TITLE
CLI script has problems finding database .jar

### ISSUE THREAD

**Issue by CarlInglisBJSS** [dependency-check/DependencyCheck#1029]
I am writing an auto update scheduled job using our own database and trying to call the dependency check script using this command:

```
dependency-check.sh \
  --updateonly  \
  --connectionString jdbc:mysql://[my DB host]/owasp \
  --dbDriverName com.mysql.jdbc.Driver \
  --dbPassword [my DB password]\
  --dbUser [my DB user]
```

When I run this I get the error "[ERROR] Unable to load database driver". 

If I modify the dependency-check.sh script to include the path to my database.jar at the end of the CLASSPATH this fixes the issue.

Clearly I'm missing something, since it shouldn't be required to modify the script to make the provided DB functionality work.

Pointers to how to deal with this in a way that doesn't require manual intervention would be much appreciated.

**Comment by jeremylong** [comment]
You need to specify the path to the database driver as we can't ship with all possible drivers/connectors.  You can add the driver/connector by specifying `--dbDriverPath <path/to/driver.jar>`. See the [documentation site](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) for more configuration options.

Alternatively, I just realized another way to solve the problem. Put the `mysql-connector-java-8.0.8-dmr.jar` in the `dependency-check\plugins` directory. This directory is added to the classpath so that if one wrote an additional analyzer it would be easy to add to dependency-check; but that directory can be used for database drivers as well.

**Comment by CarlInglisBJSS** [comment]
Fantastic, thanks - didn't realise I could add a full path. I'll go that way since it doesn't require me to modify your distribution.

Much appreciated.
