### ISSUE TITLE
Utilize additional data in CPE identifiers to reduce false positives

### ISSUE THREAD

**Issue by tazle** [dependency-check/DependencyCheck#1037]
### False positive, Distro-specific script issue reported against PostgreSQL JDBC driver
https://nvd.nist.gov/vuln/detail/CVE-2017-8806 is reported against 
- Dependency GAV: `org.postgresql:postgresql:9.4.1212.jre7`
- False positive CPE: `cpe:/a:postgresql:postgresql:9.4.1212.jre7`
- CPE filters that match?
   - `cpe:2.3:a:postgresql:postgresql:-:*:*:*:*:debian:*:*`
   - `cpe:2.3:a:postgresql:postgresql:-:*:*:*:*:ubuntu:*:*`

Is "target_sw" generally used to indicate distro-specificity in CPE filters on CVEs? If yes, should DependencyCheck perhaps ignore CPE filters that filter on "target_sw"?

**Comment by jeremylong** [comment]
The handling of the driver/connectors for databases was resolved as part of the fix for #946 (pending release). However, I agree that a long term enhancing the support for all of the portions of the CPE would help reduce some FP. I'm going to rename this issue and mark this as an enhancement request as the specific FP was already cleaned up.

**Comment by jeremylong** [comment]
additional filtering was added in 5.0.0.
