### ISSUE TITLE
Vulnerabilties different in maven and jenkins

### ISSUE THREAD

**Issue by ammy1999** [dependency-check/DependencyCheck#1041]
Hello, 
I add dependency check as a plugin jenkins then I add it as plugin maven,
But the result is different !! the vunerabilties are not the same, So How can I know the right one, 
Thanks

**Comment by stevespringett** [comment]
That is expected behavior. The Jenkins plugin doesn't know anything about build systems. It operates nearly identical to the command line interface where it simply scans a directory of files. The results between Jenkins and the CLI should be very close or possibly the same.

If you have a Maven build and the project conforms to the strict Maven semantics of using specific directories of src, resources, and webapps, then these projects should always use the Maven plugin. It will typically be more accurate. The resulting XML from the Maven plugin can then be used by the publisher step in the Jenkins plugin to visualize results in the build.

**Comment by ammy1999** [comment]
thanks @stevespringett  for your response, but can you please simplify more, I can't unterstand what I should integrate !!

**Comment by stevespringett** [comment]
If the project is a Maven project, then add the Dependency-Check Maven plugin to the POM. Refer to https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html for details. The Maven plugin will output only HTML by default. Change the 'format' option so that it outputs either XML or ALL. Refer to https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

Configure the Jenkins plugin by adding a new publisher to the job. The job should not have a Dependency-Check build step, only a publisher step. Thats all. The Jenkins plugin will read in the results from the Maven plugins output.
