### ISSUE TITLE
Invalid argparse4j vulnerability reported

### ISSUE THREAD

**Issue by renatoathaydes** [dependency-check/DependencyCheck#1055]
### Reporting False Positive

False positive on library argparse4j (tried versions 0.7.0 - used by latest Dropwizard - and latest version, 0.8.1).

CPE: `cpe:/a:python:python:0.8.1` and `cpe:/a:python_software_foundation:python:0.8.1`
GAV: [`net.sourceforge.argparse4j:argparse4j:0.8.1`](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22argparse4j%22)
[Lib docs](https://argparse4j.github.io/)

Report:

```
One or more dependencies were identified with known vulnerabilities in system-test-base:

authorization-server-2.0.12-SNAPSHOT.jar/META-INF/maven/net.sourceforge.argparse4j/argparse4j/pom.xml (net.sourceforge.argparse4j:argparse4j:0.8.1, cpe:/a:python:python:0.8.1, cpe:/a:python_software_foundation:python:0.8.1) : CVE-2017-17522
```

[CVE-2017-17522](https://nvd.nist.gov/vuln/detail/CVE-2017-17522)

This vulnerability seems to refer to the Python library, not the Java library... I checked the jar and found no references to the Python version.

**Comment by jeremylong** [comment]
@renatoathaydes I would highly recommend reading [How does dependency-check work?](https://jeremylong.github.io/DependencyCheck/general/internals.html) and [How To Read The Reports](https://jeremylong.github.io/DependencyCheck/general/thereport.html). That information would have made it obvious that this is a FP - no need to go ask the maintainer of the project that the FP was reported against.

I will include a suppression rule in the next release that will correct this FP.

**Comment by renatoathaydes** [comment]
I still don't see how that's obvious.

**Comment by renatoathaydes** [comment]
Are you saying it should be obvious that a Java port of a Python library is not affected by the original Python library's issue? How can you be so sure?

They could have been using the exact same Python code via JPython, which might make the vulnerability affect them as well.

I spent a few hours trying to verify this was not the case. So, thank you very much for pointing me to the documentation, but I would consider not assuming ignorance from your FP reporters.

**Comment by jeremylong** [comment]
I apologize about my original reply - I've been pulled in to way to many conversations with other FOSS maintainers, Mitre, NVD, etc. because people that do not fully understand the FP issues and how to determine if the obvious ones really are FP. It takes a ton of time to maintain a FOSS project and I always hate wasting other maintainers time.

I did make one mistake - in that I did not realize argparse is a core Python library - not a library maintained outside of core python. That being said, if argparse or argparse4j did anything with opening a web browser - I'd be fairly concerned...

Regardless, I'll put a suppression rule in the next release for this.

**Comment by renatoathaydes** [comment]
Ok, thank you. I also maintain several projects (though nothing as crucial as this project) and can relate with the feeling... I appreciate your great work with this library and appreciate you taking the time to help us all make our code safer.

Cheers.

**Comment by eoftedal** [comment]
Recently hit this FP as well
