### ISSUE TITLE
Possible DriverLoader.load(className, pathToDriver) issue

### ISSUE THREAD

**Issue by anderruiz** [dependency-check/DependencyCheck#1059]
According to the javadoc:

`
@param pathToDriver the path to the JAR file containing the driver; note, this can be a semi-colon separated list of paths
`

However in the code pathToDriver is being splitted using File.pathSeparator which I think is wrong and could cause really weird errors (URLClassLoader is including any file from the root path)

`final String[] paths = pathToDriver.split(File.pathSeparator);`

**Comment by jeremylong** [comment]
Thanks for pointing this out.  I don't think this is used more then passing in the path to a single driver class though - so no one has likely run into this issue.

**Comment by jeremylong** [comment]
Going back to review this I don't think this is an issue because while yes ODC does split the provided paths - however, it converts each part into a URI and re-combines them:

https://github.com/jeremylong/DependencyCheck/blob/78cca2d0a5fcc57f0fe6d8efabcbca35b85577c5/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/DriverLoader.java#L134
