### ISSUE TITLE
ZIP extensions does not work for Jenkins plugin

### ISSUE THREAD

**Issue by vchirvasuta** [dependency-check/DependencyCheck#106]
Hello, I am trying to use zip extension option to include in scan some libraries that are included in the a jar file but this does not work with the jenkins plugin 1.1.3.
I have tried the option using the command line with the same version of DependencyCheck and it is working fine.

Regards,
Valerica

**Comment by stevespringett** [comment]
So the jar has other jars in it? This should be handled automatically without the need for the zip extension. Does the jar contain zip files with a non-zip extension? Is this the functionality that does not work?

**Comment by vchirvasuta** [comment]
We have an aggregate jar that contains other jars. By default even when using the command line version of dependency check the libraries inside the aggregator jar are not scanned. Using the "--zipExtensions jar" make the dep. check to check inside that jar but this option does not work with the Jenkins plugin.

**Comment by stevespringett** [comment]
@jeremylong I tested with 1.1.4 CLI and verified that a JAR within a JAR is no longer being scanned by default. I thought this functionality use to work. I know jars within wars use to work. So this seems to be an issue with the core.  We also do not have a unit test for this. We have jars with a tar, but not within another jar. Perhaps this is because JarAnalyzer does not extend ArchiveAnalyzer?

**Comment by jeremylong** [comment]
Jars within jars was not supported by default. It would be easy to add
though, we'll just need to add the jar extension to the archive analyzer.

Jeremy

**Comment by stevespringett** [comment]
@vchirvasuta This issue has been resolved in 1.1.5-SNAPSHOT
