### ISSUE TITLE
MongoDB in Springboot - FP?

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#1067]
Hi

I am using MongoDB in Springboot, and dependency check has came with several vulnerabilities

https://nvd.nist.gov/vuln/detail/CVE-2017-15535
https://nvd.nist.gov/vuln/detail/CVE-2013-2132
https://nvd.nist.gov/vuln/detail/CVE-2012-6619

I have reported those to spring team, and they claim those are either false positives, or they are protecting those vulnerabilities with their own controls-- https://github.com/spring-io/initializr/issues/573

Should it be included in your false positive list?

Thanks

**Comment by snicoll** [comment]
>  they claim those are either false positives, or they are protecting those vulnerabilities with their own controls

For the record, that's [not what I claimed](https://github.com/spring-io/initializr/issues/573#issuecomment-357709143).

**Comment by javixeneize** [comment]
You said "My experience is that either it is a false positive (because specific to a very narrowed environment) or not applicable to what Spring Boot does by default or via configuration.", so it means for me what i said

In any case, i agree with your views, im not blaming you in any way, sorry if it was misunderstood. What i would like to know is if should be marked as false positive

**Comment by snicoll** [comment]
> so it means for me what i said

It doesn't. What I meant is that often those aren't either applicable anymore or they aren't applicable at all (there is also a minority of cases where a lib upgrade is the right thing to do).

I have no opinion on the three you've mentioned because I didn't look at them. But now I did, Take `CVE-2013-2132` for instance that is related to `mongo-python-driver` (which you will not use in a Java-based application.

**Comment by jeremylong** [comment]
@javixeneize I'd have to agree that these are all likely all FP. In general, dependency-check is going to flag the client/connector/driver/etc for a database server. These are not be default flagged as FP as in many cases the vulnerability is in the server - but occasionally it really does affect the client. The issue is 90% of the time the CPE for the client and server are the same. 

So that is the background. In the future I would recommend looking at the description of the CVE - it is generally pretty clear that the CVE is for either the client or server. If it is for the server, make sure you've either upgraded your server or checked the configuration (depending on the CVE). Next, if it really does affect the client/connector/driver - check to make sure it is the same tech stack (java/.net/python/ruby/etc). If it is a different tech stack it likely doesn't affect you. To be 100% sure you could pose the question to the Mongo developers (i.e. does the same flaw found in CVE-2013-2132 affect any of the other mongo drivers?).

When I get ready to push the next release I will cycle through the FP reports and include appropriate suppression rules.

**Comment by javixeneize** [comment]
Hi

In my case it’s a false positive and I have suppressed that. The goal of
this issue is to help to improve dependency check tool and see if it could
come as a FP by default

Thanks
