### ISSUE TITLE
Victi.ms checking

### ISSUE THREAD

**Issue by moxious** [dependency-check/DependencyCheck#107]
I have some interest in this space, and I've been using the DependencyCheck tool.   I'm wondering if the devs have looked into victi.ms, a service that RedHat has put together to enumerate the hashes of known vulnerable JAR files.   This might be an interesting additional source of detection data for DependencyCheck.

https://victi.ms/about.html

There's a github repo for a java client for this service licensed under GNU Affero GPL.   Looks to me like they compute SHA1 hashes of JAR files and then send them to the victi.ms service and look for matches.   Unlike say NVD, they have an enumerated list of known bad samples.

https://github.com/victims/victims-client-java

The guts of what seems to be going on can be found in the ScanFileCommand (the source is structured like a CLI; they have other commands but this is what you'd use on a JAR)
https://github.com/victims/victims-client-java/blob/master/src/main/java/com/redhat/victims/cli/commands/ScanFileCommand.java

**Comment by jeremylong** [comment]
Yes, I actually had several emails back and forth with people working on the project when I first started dependency-check. It is a very interesting and useful project. However, due to the AGPL licensing it is a bit restrictive. I even moved away from GPLv3 as some companies may not let a GPL tool in the front door. I want to ensure there are no obstacles in place for people that want to bring dependency-check into their organization; whether it is simply to prove the point to management that there are risks that need to be managed and they should investigate other commercial offerings or just use one of the OSS solutions to monitor.

Regardless, I would recommend running both tools. Anything found by Victims is of course going to be an exact match with much higher confidence - but at only 528 hashes at the time of posting this reply there are many more vulnerable libraries then are contained in the database. We may eventually add hash file matching - but one of the concerns with doing this is of course maintenance. We are just volunteers and I can't commit the time/effort required to maintain a high-quality collection of hashes mapping to CPE/CVE. This is actually why I came up with doing the evidence based detection that we are currently using.
