### ISSUE TITLE
Support for cpe:/o and cpe:/h not working

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#1076]
I'm experimenting with Settings.KEYS.CVE_CPE_STARTS_WITH_FILTER and have specified 'cpe:' as the filter, but it doesn't appear to have any effect.

If I supply evidence of an operating system such as Microsoft Windows XP, I would expect to get more than a few results back. I'm not getting any results when using the scan agent.

Looking at the code it appears that "cpe:/a" is hardcoded in NvdCve20Handler, NvdCve12Handler, and CPEAnalyzer, so I don't think the setting is actually being used, or I'm not understanding what it actually does.

**Comment by jeremylong** [comment]
Unfortunately, that is currently only used in dead code (the CPEHandler - which was used to read in the CPE dictionary separate from the CPE data). I planned on supporting this filter when we migrate to the JSON data feeds instead of the XML data feeds. The reason I have not yet implemented the JSON data feed parser is that it is still listed as `beta`. If they changed their schema it could easily break all installations...

**Comment by jeremylong** [comment]
This has been resolved in 5.0.0
