### ISSUE TITLE
Issues with dotnet core 2.0 assemblies analysed via docker image

### ISSUE THREAD

**Issue by peasey** [dependency-check/DependencyCheck#1135]
Hi

I'm trying to use dependency check to analyse dotnet core 2.0 assemblies for use in an AWS Lambda environment. I'm using the docker image (https://hub.docker.com/r/owasp/dependency-check/) to run the dependency check.

Please see the following gist for the test script (test.sh) and the log output (dc.log) from an unsuccessful run: https://gist.github.com/peasey/6370cefea7239801c186e40807e4e4ff

When I run this I get the following error per assembly as follows:

`ERROR - Failed to read the Assembly Analyzer results. On some systems mono-runtime and mono-devel need to be installed.`

The reports are generated at the end of the run (see the above gist for an example) and they do report some issues against one of the assemblies (false positive), but the  process fails with a non-zero exit code.

I've also trued running this against a modified docker image that adds mono-devel as per the suggestion in the error message, but with the same results (https://hub.docker.com/r/apsage/owasp-dependency-check/~/dockerfile/).

My questions are:
1. Does dependency check support analysing dotnet core assemblies?
2. Is your docker image suitable for analysing dotnet core assemblies?
3. Although there are errors at the end of the run, the reports are generated with some false positives, so did the analysis actually fail?

Thanks in advance for your assistance.
Adrian

**Comment by jeremylong** [comment]
Some of the .NET analysis we need to go back and review. I just validated that on my system the grok assembly can correctly produce the necassary output for one of the libraries that failed for you above.  The team will need to spend some more time looking into this. So to answer your specific question:

1. Yes, dotnet core assemblies are supported.
2. In limited testing I believe so - but obviously you've run into an issue so more research will need to be done here.
3. If you look at any of the "evidence" in the HTML report for libraries where you see `WARN  - An error occurred while analyzing '/src/Amazon.Lambda.APIGatewayEvents.dll' (Assembly Analyzer).
2018-03-08 14:48:51,172 org.owasp.dependencycheck.AnalysisTask:91` - these libraries may be missing sufficient evidence (vendor, product, and version) to match CPEs and thus report on CVEs. This means there may be false negatives.

**Comment by thomasd-** [comment]
Hello,

I ran into the same problems. and here is what I found : 

The error is due to GrokAssembly.exe, which loads a dll and extract usefull informations from it. When executed from mono (the default on a linux based docker image), mono add an error to the result on some cases : 

```
Can't find custom attr constructor image: /tmp/build/4929bc50/extracted/Microsoft.Extensions.Hosting.Abstractions.dll mtoken: 0x0a00000e due to Could not load file or assembly or one of its dependencies. assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:<none>
<?xml version="1.0" encoding="utf-8"?><assembly><product>Microsoft.Extensions.Hosting.Abstractions</product><version>2.0.1.0</version><fullname>Microsoft.Extensions.Hosting.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60</fullname><types><type>Microsoft.Extensions.Hosting.IHostedService</type></types></assembly>
```

The result is a non valid xml, which triggers a SaxParseException.

A solution would be to :
- Port GrokAssembly to be run with .NET Core
- Change the AssemblyAnalyzer to use this new version of GrokAssembly along with the .NET Core runtime.

**Comment by thomasd-** [comment]
So, here it is : 
- [A port of GrokAssembly to run with .NET Core](https://github.com/thomasd-/GrokAssemblyCore)
- [A pull request with the change I mentioned in my last message.](https://github.com/jeremylong/DependencyCheck/pull/1144)

**Comment by jeremylong** [comment]
@thomasd- thank you very much for the analysis and the PR! Truly appreciate it.

**Comment by thomasd-** [comment]
Thank you @jeremylong.

Any update on the review of this PR ? Did you have time to look at it ? Do you have doubts about it ?

**Comment by jeremylong** [comment]
See my comments on the PR.

**Comment by chiemeleakoma** [comment]
hi, i wanted to know if this issue was fixed in the 5.0.0-M1 release as im getting the same error message using the cli (5.0.0 version) and latest docker image.

***this is from running the latest docker image using the script in your github***
[INFO] Check for updates complete (204505 ms)
[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[Fatal Error] :1:301: Content is not allowed in trailing section.
[ERROR] ----------------------------------------------------
[ERROR] Failed to read the Assembly Analyzer results. On some systems mono-runtime and mono-devel need to be installed.
[ERROR] ----------------------------------------------------
[WARN] An error occurred while analyzing '/src/src/Cosmos.NewsfeedLanguageProcessor/bin/Release/netcoreapp2.1/Cosmos.NewsfeedLanguageProcessor.Configuration.dll' (Assembly Analyzer).
[Fatal Error] :1:273: Content is not allowed in trailing section.
[ERROR] ----------------------------------------------------
[ERROR] Failed to read the Assembly Analyzer results. On some systems mono-runtime and mono-devel need to be installed.
[ERROR] ----------------------------------------------------
[WARN] An error occurred while analyzing '/src/.sonarqube/bin/SonarScanner.MSBuild.Common.dll' (Assembly Analyzer).
[Fatal Error] :1:271: Content is not allowed in trailing section.
[ERROR] ----------------------------------------------------
[ERROR] Failed to read the Assembly Analyzer results. On some systems mono-runtime and mono-devel need to be installed.
[ERROR] ----------------------------------------------------
[WARN] An error occurred while analyzing '/src/.sonarqube/bin/SonarScanner.MSBuild.Tasks.dll' (Assembly Analyzer).
[Fatal Error] :1:273: Content is not allowed in trailing section.
[ERROR] ----------------------------------------------------
[ERROR] Failed to read the Assembly Analyzer results. On some systems mono-runtime and mono-devel need to be installed.
[ERROR] ----------------------------------------------------
[WARN] An error occurred while analyzing '/src/src/Cosmos.NewsfeedLanguageProcessor/bin/Release/netcoreapp2.1/Cosmos.NewsfeedLanguageProcessor.dll' (Assembly Analyzer).
[Fatal Error] :1:317: Content is not allowed in trailing section.
[ERROR] ----------------------------------------------------
[ERROR] Failed to read the Assembly Analyzer results. On some systems mono-runtime and mono-devel need to be installed.
[ERROR] ----------------------------------------------------
[WARN] An error occurred while analyzing '/src/src/Cosmos.NewsfeedLanguageProcessor/bin/Release/netcoreapp2.1/Cosmos.NewsfeedLanguageProcessor.SourceLanguageService.dll' (Assembly Analyzer).
[Fatal Error] :1:261: Content is not allowed in trailing section.
[ERROR] ----------------------------------------------------
[ERROR] Failed to read the Assembly Analyzer results. On some systems mono-runtime and mono-devel need to be installed.
[ERROR] ----------------------------------------------------
[WARN] An error occurred while analyzing '/src/dll/FastText.NetStandardWrapper.dll' (Assembly Analyzer).
[INFO] Finished Assembly Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (3 seconds)
[INFO] Skipping CPE Analysis for npm
[INFO] Finished CPE Analyzer (3 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (5 seconds)
[ERROR] Couldn't parse Assembly Analyzer results (GrokAssembly)

**Comment by jeremylong** [comment]
&lt;sarcasm&gt;It's almost like we didn't mark the issue closed or pending release&lt;sarcasm&gt;...  M1 was the NVD XML to NVD JSON data feed migration. A ton of changes were required to make that work. M2 will be dotnet core - tentatively expected to be released this weekend. However, this may get delayed because we investigating some nuget APIs that may assist in analysis.

**Comment by chiemeleakoma** [comment]
im sorry jeremy, i wasnt sure. thanks for clarifying. and again thanks for your efforts!

**Comment by jeremylong** [comment]
@chiemeleakoma no worries - you caught me on an off day thus the above snarky response. sorry about that.  Trying to get the updates finalized soon.
