### ISSUE TITLE
Improve update speed by using checksum for past years

### ISSUE THREAD

**Issue by lathspell** [dependency-check/DependencyCheck#1140]
Everytime a CVS update is done during a build, it takes e.g. 27s just to download the CVEs for 2007.
As I doubt that any CVS-2007-* entries will be ever be updated, it might be worth to first download a checksum for all years and then only load CVEs from those years where it does not match the local database. The checksum entries could be hosted on github by this project until the CVE server itself has anything similar.

**Comment by jeremylong** [comment]
If you run dependency-check once at least every 7 days the update speed is fairly quick as it only downloads the `modified` xml files (we will be switching to the JSON feed soon). If you are doing a lot of builds/scans you may want to consider using a [centralized database](https://jeremylong.github.io/DependencyCheck/data/database.html) (if your company uses a lot of containers take a look at [dependencycheck-central-mysql](https://hub.docker.com/r/stefanneuhaus/dependencycheck-central-mysql/)).

Now, regarding the updating of old CVEs - all you have to do is look at the NVD data feed page to see that the old CVEs are being updated (see https://nvd.nist.gov/vuln/data-feeds#XML_FEED). I haven't dug into this a lot because my normal usage just requires processing the modified xml instead of all of the XML fiels.
