### ISSUE TITLE
Used DependencyCheck to scan the Java libraries hosted on Maven Central

### ISSUE THREAD

**Issue by mcadariu** [dependency-check/DependencyCheck#117]
Hi Jeremy, 

I am currently engaged in a research project concerning the security of third-party components used in software projects.  As part of the project, I have used DependencyCheck to get a glimpse of how many Java libraries in the Maven central repository have reported CVE vulnerabilities.  Basically, I used only the library metadata (groupid, artefactid and version) and started a batch DependencyCheck analysis.  

After the batch scan was done, I had to manually clean up the false positives in order to be able to create my "known vulnerability catalog" of the Maven dataset.  The question is now, what can I contribute back to the project as a result of this batch scan. 

The result of the scan might be used in creating a filtering component that would come into play after the step when results are retrieved from the Lucene index.  The filtering component would encapsulate a series of heuristics that we learned after consulting the result of the batch scan that I described previously. 

If there is another way in which my work can provide a useful contribution to the project, please let me know. 

Cheers,
Mircea

**Comment by jeremylong** [comment]
Mircea,

Interesting...  One thing would be if you have a list of false positives (hopefully, with the SHA1 hash, or in the form of a suppression file) we could incorporate that and/or examine why they were false positives and either just suppress them or tune the analyzers so that they no longer get reported incorrectly.

I've considered building a HashAnalyzer that has a local DB of known hashes to CPEs. But if you have gotten the matches from dependency-check, the tool will already identify these. Another reason why I haven't started working on a HashAnalyzer is the maintenance around the database. It would be a full time job to try and keep it up to date.

Regardless, I would love to see the false positive information you have.

Thanks!

**Comment by jeremylong** [comment]
As we haven't heard back from Mircea - I am going to close this issue in github. If the data on false positives can be provided then a new issue can be created.
