### ISSUE TITLE
False positives for tomcat-annotations-api-7.0.82.jar

### ISSUE THREAD

**Issue by davewichers** [dependency-check/DependencyCheck#1186]
Issue 1: For: for CVE-2016-5388, DC is reporting this as a known vuln for tomcat-annotations-api-7.0.82.jar, but the description of this CVE specifically states Tomcat 7.x through 7.0.70 is vulnerable to this issue, so this CVE should not be flagged for this version of this library.

Issues 2-3: On a related note, this version of this library was released: 2017-10-03, and yet these other CVEs are also being reported for this library:

CVE-2016-5425
CVE-2016-6325

The CVE descriptions for these seem to be about how Tomcat is packaged on certain platforms, like RHEL 7, Fedora, CentOS, JBoss, and NOT specific to tomcat libraries themselves. As such, I think these 2 CVEs should not be reported for Tomcat libraries at all.

Issue 4: CVE-2017-6056 is also being reported for this library, and yet it says it's only relevant for Debian before 7.0.56-3+deb8u8.

Feel free to break this into separate tickets if that's better/easier to manage.

ALSO; Issue 1 is also being reported for: tomcat-embed-core-7.0.82, but the 3 other CVEs are NOT being reported for this particular Tomcat library.  Not sure why.

**Comment by jeremylong** [comment]
Thanks for the report - I'll look into issue 1.

Issue 2-3 - we do not evaluate when a library was published. Instead we use the information from the NVD that states all version are vulnerable.

Issue 4 - if the issue is not relevant to your installation simply create a [suppression file](https://jeremylong.github.io/DependencyCheck/general/suppression.html) and include it in future analysis.

**Comment by jeremylong** [comment]
For issue 1 - I just realized that this will likely be corrected when we update to use the JSON data feeds as the vulnerable version information is better. This is related to #1088
