### ISSUE TITLE
Different results from mvn plugin

### ISSUE THREAD

**Issue by cacert** [dependency-check/DependencyCheck#1235]
Hello,

I have an mvn spring boot(1.4.4) project, on which trying to add support for dependency plugin. When I run dependency plugin locally with the following command it finds  7 high severity vulnerabilities. However, when I run the same command on ci the plugin founds 8 high severity vulnerabilities. What can be the reason for that difference?

Command: 
mvn clean jar:jar org.owasp:dependency-check-maven:3.1.2:check  
the different high vulnerability which is found on ci but not on local is 

spring-boot-1.4.4.RELEASE.jar:0 -- CVE-2017-8046

**Comment by jeremylong** [comment]
What version of the Jenkins plugin is being used in the CI?

**Comment by cacert** [comment]
same with maven one 3.1.2

**Comment by jeremylong** [comment]
Sorry for the delayed response - the core dependency-check team has always advocated using the plugin that is as specific to the build in question as possible. Use dependency-check-maven for Maven builds, dependency-check-gradle for gradle builds, etc. This is because evidence from the build system itself can help dependency-check.

With your specific case - as more information is available dependency-check is able to suppress the false positive.  This specific vulnerability only affects `spring-data-rest`.  See the [Pivotal announcement](https://pivotal.io/security/cve-2017-8046) for this vulnerability:

> ## Affected Pivotal Products and Versions
> Severity is critical unless otherwise noted.
> 
> Spring Data REST versions prior to 2.6.9 (Ingalls SR9), 3.0.1 (Kay SR1)
> Spring Boot (if Spring Data REST module is used) versions prior to 1.5.9, 2.0 M6

Had your application also included a vulnerable version of `spring-data-rest` the CVE would have been flagged.
