### ISSUE TITLE
OWASP dependency check analysis finds fewer flaws with the new versions.

### ISSUE THREAD

**Issue by AnthonyDasse** [dependency-check/DependencyCheck#1254]
Hello,

One of my teams migrated the Jenkins plugin from 1.4.5 to 3.1.2.
Problem, the analysis finds fewer flaws with the new versions.
There is changes on the analysis strategy? I have the same with the cli ....

### With 3.1.2
 - dependency-check version: 3.1.2
 - Report Generated On: avr. 30, 2018 at 11:32:52 +02:00
 - Dependencies Scanned: 204 (143 unique)
 - Vulnerable Dependencies: 27
 - Vulnerabilities Found: 52

###  With 1.4.5
 - dependency-check version: 1.4.5
 - Report Generated On: avr. 30, 2018 at 11:21:08 +02:00
 - Dependencies Scanned: 204 (142 unique)
 - Vulnerable Dependencies: 28
 - Vulnerabilities Found: 69

**Comment by jeremylong** [comment]
There have been tons of changes since 1.4.5 that could account for this.  In reality, I'm kinda surprised 1.4.5 still works.

- There are more suppression rules for known false positives
- The dependency bundling/merging has undergone some tweaks; I would be curious to know what the one new unique dependency that was found using 3.1.2 is?
- Changes to the vulnerable library identification routine
- etc.

While the report from 1.4.5 may have "found" more - without knowing what the differences are I'd have a hard time pointing out a specific thing. However, were any of the things from 1.4.5 valid findings or did the number of false positives go down?

**Comment by AnthonyDasse** [comment]
I investigated a little more, indeed it was false positives.
Thanks for your return. I closed the issue.
