### ISSUE TITLE
git clone pulls 859 MB of data

### ISSUE THREAD

**Issue by blackomegax** [dependency-check/DependencyCheck#129]
I'm not sure if this is intentional, bloat, or an error. This app does not seem like it should be anywhere near that size given the function.

If somehow required I'd happily accept explanation but could find none.

**Comment by jeremylong** [comment]
Thanks for pointing this out...  I believe the issue is due to the 'test/resources'. My guess is the history on things like data.zip (which is a 36mb file) is rather large as I have replaced this test data several times.

I am researching the various options to truncate the history on the test resources.

**Comment by jeremylong** [comment]
I have cleaned up the history a bit - but I did break some old test cases if you go back in the commit history/old tags. The resources required for some of the test cases were deleted to reduce the overall size of the repo. The cleanup was done following this post:
https://confluence.atlassian.com/display/BITBUCKET/Maintaining+a+Git+Repository

A clone of the repo now pulls ~100mb:

   Receiving objects: 100% (32415/32415), 100.20 MiB

There is still some cleanup that can be done - but I'm considering this issue closed.
