### ISSUE TITLE
False positive/bug? on non-existing dependency

### ISSUE THREAD

**Issue by helaar** [dependency-check/DependencyCheck#1341]
Full description here: https://github.com/helaar/depcheck-test/blob/master/README.md

It seems that DependencyCheck maven plugin introduces a non-existing dependency to a vendor/product/version. I discovered it on a mongodb-driver dependency. 

**If** your module depends on a third party library, your module is named in a way that it can be resolved to the vendor of that third party library ( my-&lt;thirdpartyvendor&gt;-proxy can be resolved to &lt;thirdpartyvendor&gt;) and your module has a version number on witch there is a vulnerability in NVB on the particular vendor. **Then** modules depending on your module will fail the dependency check referring to a non-existing dependency.

In my case is `(cpe:/a:mongodb:mongodb:2.17.2, org.codehow:test-mongodb-dependency:2.17.2) : CVE-2014-8180` a false positive, but it is not a solution to suppress it as the dependency is related to the version of my library not the one from mongodb.  

Example code: https://github.com/helaar/depcheck-test

**Comment by jeremylong** [comment]
This is expected behavior. Please see the [How does dependency-check work](https://jeremylong.github.io/DependencyCheck/general/internals.html). What you are describing is not `non-existent` dependency - but rather a mis-identified dependency. In cases like this one should utilize a [suppression file](https://jeremylong.github.io/DependencyCheck/general/suppression.html).
