### ISSUE TITLE
NPM analisys: add package license information (enhancement)

### ISSUE THREAD

**Issue by carloreggiani** [dependency-check/DependencyCheck#1354]
We are using depcheck also to inventory open source licenses used in our application, very powerfull features for maven/java component!

For npm depcheck analisys (v. 3.2.1) is still missing any component license info in the reports, also for package.json with the corret tag compiled (SPDX expressions):

(from https://docs.npmjs.com/files/package.json)

```
{ "license": "ISC" }

{ "license": "(MIT OR Apache-2.0)" }

{ "license" : "SEE LICENSE IN <filename>" }
```

**Comment by jeremylong** [comment]
This maybe due to an overall issue with the NSP and NPM analyzers that was resolved in PR #1361. If you look at the code in the [AbstractNpmAnalyzer](https://github.com/jeremylong/DependencyCheck/blob/08cdd31f8b909de3448001447ceb7f58991d9173/core/src/main/java/org/owasp/dependencycheck/analyzer/AbstractNpmAnalyzer.java#L268) the license information should be being collected.

I will hopefully be pushing a new version within the week and I would ask you to re-test then.
