### ISSUE TITLE
Analyzing dotnet core dependencies (project.assets.json)

### ISSUE THREAD

**Issue by omerlh** [dependency-check/DependencyCheck#1409]
Hey,
Currently, there is some support for dotnet via assembly analyze and NuGet. It seems there is no support for the new nuget format - which create `project.assets.json` after restoring packages. Is this is something in the roadmap? What is the plan for dotnet core support?

**Comment by jeremylong** [comment]
To better support .NET analysis GrokAssembly will switch to using dotnet core. As for analysis - we continue to add support for new sources of information as we learn about them and have time to implement.  I know on the .NET side some time needs to be spent getting the identifiers created so that we can more easily create suppression rules.  To that end - the identifiers collection will soon be split into two - one for development/repo identifiers (i.e. GAV, nuget coordinates, etc.) and one for vulnerability identifiers (i.e. CPEs).  Then when we parse something like a `project.assets.json` we can create virtual dependencies, add evidence, and add the correct identifiers.

**Comment by omerlh** [comment]
Thanks :) looking forward to it!

**Comment by jeremylong** [comment]
I missed closing this issue when 5.0.0 was released. 5.0-5.3 required the used of dotnet core 2.x. With the soon to be released 5.4 we will be requiring dotnet 3.1.
