### ISSUE TITLE
Provide Absolute Path to Vulnerable Jar

### ISSUE THREAD

**Issue by sbehrens** [dependency-check/DependencyCheck#143]
Hello,

When scanning JAR files that contains Libraries that contain libraries etc., DependencyCheck only flags the highest JAR and maps it to a CVE.  It would be useful if the tool could tell provide the chain that the vulnerable JAR is in.  So an example would be

```
MyApp.jar 
|
Foo.jar
|
Bar.jar Sue.jar 
              |
              Vulnerable.jar
```

The full chain would show (MyApp.jar -> Foo.Jar -> Sue.jar -> Vulnerable.jar)

**Comment by jeremylong** [comment]
Do you have a specific example that could be shared?

Jeremy

**Comment by sbehrens** [comment]
HI Jeremy

Currenlty I do not have an example I can share.  At Netflix we are using a few JAR files that are a collection of libraries (think of common libraries being bundled together for convenience).  I'll try to look around and see if I can find something I could send.

-Scott

**Comment by jeremylong** [comment]
This issue was discussed further via email. Unfortunately, while dependency-check may be able to detect a vulnerable library within a shaded jar it cannot figure out what the original JAR file path would be (as this information would be lost when the JAR was bundled/shaded/etc.).

Scott, let me know if I am missing something - but I am going to close this issue.
