### ISSUE TITLE
Is there any no scan mode?

### ISSUE THREAD

**Issue by nilp0inter** [dependency-check/DependencyCheck#1445]
Hi,

I was wondering if there is a way of executing the tool bypassing the scan stage, providing the dependencies directly.

As an example, instead of running the tool with the path of my python/java project, I'd like to pass the name and version of a library I am using.

Is this possible?

**Comment by stevespringett** [comment]
The [ScanAgent](https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/java/org/owasp/dependencycheck/agent/DependencyCheckScanAgent.java) does this, but its not directly executable. But it allows you to programmatically supply the evidence (instead of scanning for it). This is what [Dependency-Track](https://dependencytrack.org/) does behind the scenes.

**Comment by nilp0inter** [comment]
Neat!

Does Dependency-Track have any API allowing this kind of query?

**Comment by stevespringett** [comment]
Dependency-Track handles scanning automatically. The easiest thing to do is upload the software bill of material and let the system do it's thing. When a BoM is uploaded, all the components are immediately scanned and will continue to be scanned every day. But if you don't want a full system for this, you could easily use the ScanAgent, as mentioned above, and write a simple utility to supply it the evidence for the scan yourself.

**Comment by nilp0inter** [comment]
Thank you!
