### ISSUE TITLE
False Positives on Struts2 JAR files

### ISSUE THREAD

**Issue by sbehrens** [dependency-check/DependencyCheck#146]
Hello,

I am receiving false positives for the following JAR files:

struts2-core-2.3.16.3.jar
struts2-*-2.3.16.3.jar

Dependency Check is flagging these JARs having the following CWE's

CWE-20 Improper Input Validation
CWE-264 Permissions, Privileges, and Access Controls  
CWE-94 Improper Control of Generation of Code ('Code Injection')

Here are some example for 'code injection'

CVE-2012-0394
CVE-2013-1965
CVE-2013-1966
CVE-2013-2115
CVE-2013-2134
CVE-2013-2135

This particular build of Struts2 is not vulnerable to any of the CVE's listed above.  Could you please look into why they are being flagged as positive?

Thanks,

Scott

**Comment by colezlaw** [comment]
Odd - that's not getting a version number in the CPE, which is the culprit.

There are a few problems at play here:

1) Nexus search is not returning any package information for that jar when
you search by SHA-1. (If you go to search.maven.org and search by the
SHA-1, it returns the correct one, however, the service doesn't. Nexus
isn't overall broken, though, because it finds asm, ognl, etc.)
2) POM parsing gets the version, but because the Nexus search should
presumably be more accurate (compared to shaded jars, etc.) then the POM
parser automatically sets its confidence to LOW, so the version information
from that is not being chosen
3) file/name is getting 2.3.16.3 as a version number, however, the
identified CPE is cpe:/a:apache:struts

The identified CPE is the real problem - the reasons for it are primarily
because of Nexus, but I'm not sure why the version number is not being
included in the CPE match.

I _thought_ the reason might be that there wasn't a CPE yet for 2.3.16.3,
but there is one - there just aren't any vulnerabilities for it.

So I'm not sure at this point why all the other things that got version
information aren't applying that version information during the search for
the CPE.

**Comment by jeremylong** [comment]
Any chance you could share the report with me (jeremy.long@owasp.org)?  I'm
working on a bunch of changes to the maven plugin atm - hopefully, I'll
have time to look at this over the weekend.

Thanks!

Jeremy

**Comment by jeremylong** [comment]
The way this works (currently) is that if it identifiers that something is
Apache Struts, but the version being analyzed isn't listed with a specific
version (from the CPE listings) - then I believe it throws the base
"cpe://a:apache:struts" on there. I think if there is a version from Nexus
I should just use that (or maybe just cycle through and use the highest
confidence version number).

--Jeremy

**Comment by colezlaw** [comment]
I had a guess that might be what was happening - however, there IS a CPE
for 2.3.16.3. There are no CVE's for it, but there is a CPE.

**Comment by sbehrens** [comment]
Hi Jeremy,

Sorry for the delay, let me scrub out some details and send you over the report.

-Scott

**Comment by jeremylong** [comment]
If the CPE doesn't exist in NVD CVE listing it is not currently included in
the local dependency-check database. In other words, the tool does not
download the CPE listing from NIST; it only downloads the CVE data which
includes the CPE identifiers for the vulnerable software listings. This may
be an improvement we could make for a future version.

--Jeremy

**Comment by jeremylong** [comment]
I had some offline conversations regarding this issue. We believe the resolution to this class of false positives will be best fixed with two modifications:

1) If we find a CPE for Vendor:Product - but do not match a specific version from the NVD we will use the version from the POM/Nexus (if one exists).
2) Download the CPE listing from the NVD in addition to using what is in the NVD CVE data.

I will implement item 1 (which should fix this issue) as part of this issue and open a new issue for incorporating the CPE data.

--Jeremy

**Comment by jeremylong** [comment]
I just committed some changes that should solve the Struts 2.3.16.3 false positives (and others). I'm hoping to have a full release pushed within a week (prior to AppSec USA).
