### ISSUE TITLE
False positive on Spring Jars

### ISSUE THREAD

**Issue by asudhak** [dependency-check/DependencyCheck#147]
Whenever the plugin detects something like 'spring- \* - 1.1.0.jar', it automatically thinks I'm inclduing spring framework 1.1.0

example:

spring-retry-1.1.0.RELEASE.jar

cpe: cpe:/a:springsource:spring_framework:1.1.0   Confidence:HIGHEST   suppress
maven: org.springframework.retry:spring-retry:1.1.0.RELEASE   Confidence:LOW

**Comment by jeremylong** [comment]
Sorry about the delay replying to this issue. When this was posted I did start an offline conversation to discuss a possible fix for this specific issue and related false positives regarding spring libraries. 

For background information on why false positives are detected/exist the following three links are helpful:
- [How does dependency-check work](http://jeremylong.github.io/DependencyCheck/internals.html)
- [How to read the report](http://jeremylong.github.io/DependencyCheck/thereport.html)
- [Suppressing False Positives](http://jeremylong.github.io/DependencyCheck/suppression.html)

To resolve the issue for Spring related dependencies, dependency-check may need to do some special processing around "spring" jars. My initial thoughts are:
1.  Maintain an internal listing of the "core" spring libraries - the set of libraries that are versioned together (spring-core, spring-web, spring-mvc, spring-etc. - using the group and artifact from the POM). If we get a hit on cpe:/a:springsource:spring_framework check the list of core spring libraries to determine if we have a false positive.
2.  Same idea as above - but can we use a nexus search instead of maintaining the list internally?
3.  While writing this I may have just noticed a pattern that can be used to remove these false positives. The GroupId for the non-core spring libraries always has an additional identifier after "org.springframework". In this case "org.springframework.retry". The logic for the suppression should be if the maven GroupId is "org.springframework.XXX", then XXX must exist in the CPE - otherwise the CPE will be considered a false positives.

--Jeremy

**Comment by jeremylong** [comment]
Changes have been pushed to 1.2.5-SNAPSHOT to resolve this issue. The next release of dependency-check should be available within a week.

Thanks for reporting the issue!
