### ISSUE TITLE
Need Clarification: Running check on windows server

### ISSUE THREAD

**Issue by tpruthi** [dependency-check/DependencyCheck#1470]
I am running Dependency check on windows server 2012 where i have tomcat and other dependency jars.
But the result is showing me list of vulnerabilities with confirmation link as redhat/Linux environment.

Example CVE which are coming
CVE-2015-5182
CVE-2015-5183
CVE-2015-5184

how can i confirm that the vulnerability is also present in windows server environment

**Comment by jeremylong** [comment]
The are reports on Active MQ which can run anywhere Java is installed. What I would first focus on - instead of the individual CVEs is the identified library -> CPE match. I would highly recommend reading [How does dependency-check work?](https://jeremylong.github.io/DependencyCheck/general/internals.html) and [How To Read The Reports](https://jeremylong.github.io/DependencyCheck/general/thereport.html).

I really need to create a quick start guide and an enterprise deployment guide...
