### ISSUE TITLE
Allow for filepath patterns when specifying scan directories

### ISSUE THREAD

**Issue by scheffelaar** [dependency-check/DependencyCheck#153]
It would be very convenient if, when specifying which directories should be scanned for vulnerabilities, it would be possible to use glob-style filepath patterns instead of having to specify hard filepaths. As far as I can tell, the CLI version will take the first path specified by a pattern (ie. if you give the argument -s "/*" in a dir with multiple subdirectories it'll only search one of them) while the Jenkins plugin doesn't seem to be able to handle wildcards at all.

This would be useful for automated testing in an environment where filepaths change -- in my case, I'd like to specify filepaths that contain version numbers that would get changed every time someone tags a release.

**Comment by stevespringett** [comment]
It is unclear if you want this enhancement made to the CLI or Jenkins plugin.

For the Jenkins plugin, you can specify valid Jenkins environment variables such as WORKSPACE and BUILD_NUMBER and the plugin will replace the vars with the actual values. The plugin currently does not allow for Ant-style wildcards, but this should be able to be easily added.

**Comment by jeremylong** [comment]
Thank you for pointing out the bug in the CLI. Currently, the only wild
card support was added to support only scanning specific file types. So
that one could (in theory) specify \directory*.jar   and then only JAR
files in the specified directory would be scanned. However, if one
specified the scan directory as just  -s "directory" then all files in all
sub-directories would get scanned. The bug, in the current implementation,
is if you add a single asterisk at the end of the path the behavior is not
what was intended.

In your case, likely specifying the directory without a wild card may work.

Regardless, the single asterisk at the end of the path is generating
unexpected behavior and will be fixed. Additionally, documentation will be
updated.

--Jeremy

**Comment by scheffelaar** [comment]
Steve: Ideally, both. I was mostly trying to point out the current functionality in both plugins as I understood them.

Also, probably worth noting that I was using the CLI plugin on Linux.

Jeremy: Whoops, probably a mediocre example on my part. The wildcard works the same even if it's in the middle of the file path. So, in this structure:

```
basedir -- dirA -- target -- some jars
        |- dirB -- target -- some jars
```

Providing the argument "-s basedir/*/target" will work but will only scan one of the target dirs, presumably which one is first in the resulting set.

**Comment by stevespringett** [comment]
Ant style pattern sets have been added to the Jenkins plugin (1.2.5-SNAPSHOT). This will allow for using various wildcard patterns in the scan path.

**Comment by jeremylong** [comment]
This issue is resolved. The CLI now accepts ant style paths for the scan directory. Additionally, you can now specify one or more excludes via the --exclude argument. The code changes have been commited to the 1.2.6-SNAPSHOT. I am expecting a full release within the next week or two.

**Comment by hansjoachim** [comment]
Hi, I was looking at the apache-package in the repo and traced it's origin back to this issue. It looks like it was modified in some way when it was added, but I can't find any details on what was changed. Could someone please elaborate a bit on this?

**Comment by jeremylong** [comment]
Only the part's of apache-ant that are required to scan the directories are included. The only changes to the original source code would have been minor removal of methods/imports that caused a dependency on other parts of Ant.

**Comment by hansjoachim** [comment]
> Only the part's of apache-ant that are required to scan the directories are included.

Ok. :)

I should probably elaborate a bit. The reason I discovered this package since roughly half of the issues found by static analysis tools or IDEs in the DependencyCheck source are in this section. This makes it harder to notice when new issues are added other places in DependencyCheck.

Apart from the minor changes, the sources are copied from ant, so I don't think it gives much value to resolve these issues in DependencyCheck. (Though it may suggest that someone contributing to Apache should take a look at it...) This leads me to another question though: how are new ant releases and bug fixes handled? If ant fixes a bug which also affects the copied sources in DependencyCheck, it would be nice to get that fix included. Note that fixing code issues on the DependencyCheck side would also make this harder, since it increase the chance of conflicts when applying new patches.

I did a small experiment locally, and found that if I added ant as a dependency to dependency-check-cli and updated the imports, everything ran fine. While ant is used elsewhere, it would involve adding an additional dependency for this particular module. It might seem slightly excessive in order to access a single class, though would make it easier to keep it up to date and in sync with the latest bug fixes. I don't know whether the size of the cli.jar is a concern as well, as this would also grow if ant was added as a dependency. 

I realize this option may have been already considered when the copy sources approach was chosen instead, but I haven't been able to find this discussion if it is documented somewhere. Was it simple considered overkill to introduce the dependency for one class' sake, or was there some other reason for it?
