### ISSUE TITLE
Throw an Error when No Dependencies are Scanned

### ISSUE THREAD

**Issue by markdenihan** [dependency-check/DependencyCheck#1539]
As a user
I want to be alerted if my Dependency Check Runs on 0 dependencies
So that I know I need fix my scan configuration

Scenario:
Dependency Check Configured to scan a specific folder of dependencies in CI Jenkins Job (eg: /scan/everything/after/this/**)
Specific Folder is moved and Dependency Check config is not updated
Dependency Check Scans 0 dependencies but Returns 0 vulnerabilities found result - Job Passes

I feel like if you scanned 0 dependencies you likely have run the scan incorrectly and should be given an error.

**Comment by stevespringett** [comment]
Are you using the Dependency-Check command-line interface, or the Jenkins plugin to do the scanning?

**Comment by markdenihan** [comment]
Mostly via Jenkins but there are CLI scanners being used too

**Comment by stevespringett** [comment]
The scan path may consist of an absolute or relative path, or may be an ant-style pattern. In the case of the Jenkins plugin, the scan path may be separated by commas so that you can specify multiple scan paths. Each scan path may or may not be an ant-style pattern.

The Jenkins plugin (I think the CLI does the same), first checks for the exact path. If the path is not found, it will attempt to use ant-style patterns. It may be possible to put a check in the ant-style matching that if no matches are found, put the build into a failed state. So in the case of specifying multiple scan paths, if one of the paths could not be found, the entire build would fail. This would obviously need to be a configurable option that would need to be disabled by default, but I think it could be implemented - at least in the Jenkins plugin.

**Comment by markdenihan** [comment]
The Ant Style matching is actually the scenario I had in mind. Would it be easier to implement a check before creating the report if the total dependencies was > 0 before failing? That was it could be implemented on all variants of the tool?
