### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by shreyaskgit** [dependency-check/DependencyCheck#1542]
When I run dependency maven with my local h2 database in my local system with autoupdate ="false", it works perfectly. 
When I change the connection string to another machine in the same network, connection string tried to search for a dc.mv.db file.

The plugin I used in pom.xml
<plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>3.3.2</version>
                
				<configuration>
					<cveUrl12Base>http://***.**.***.**/home/***/NVD/NVD_Database/nvdcve-%d.xml</cveUrl12Base>
                    <cveUrl20Base>http://***.**.***.**/home/***/NVD/NVD_Database/nvdcve-2.0-%d.xml</cveUrl20Base>
					<cveUrl12Modified>http://***.**.***.**/home/***/NVD/NVD_Database/nvdcve-modified.xml.gz</cveUrl12Modified>
                    <cveUrl20Modified>http://***.**.***.**/home/***/NVD/NVD_Database/nvdcve-2.0-modified.xml.gz</cveUrl20Modified>
					<dataDirectory>http://***.**.***.**/home/***/NVD/dc.h2.db</dataDirectory>
					<connectionString>jdbc:h2:http://***.**.***.**/home/***/NVD/dc;MV_STORE=FALSE;AUTOCOMMIT=ON;LOG=0;CACHE_SIZE=65536;</connectionString>
					<databaseUser>dcuser</databaseUser>
					<databasePassword>******</databasePassword>
					
					<databaseDriverName>org.h2.Driver</databaseDriverName>
					<failBuildOnCVSS>2</failBuildOnCVSS>
					<cveValidForHours>0</cveValidForHours>
					<autoUpdate>false</autoUpdate>
                </configuration>
				
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
				
            </plugin>

**Comment by jeremylong** [comment]
While not intentional - in its current state ODC does not work using H2 in server mode. This is something I will look into for a future version.

**Comment by niddhig** [comment]
I am trying to connect to the H2 database when i used the cli-command for dependency-check.
The location of the database i am trying to access:
/Users/ngarg/.m2/repository/org/owasp/dependency-check-data/4.0/odc.mv.db
Username and password from the settings file:
data.user=dcuser
data.password=DC-Pass1337!

I am able to connect successfully but i don't see any tables there. I guess its creating a new one and not opening the one which was already created.

Please help!

**Comment by priyanka270** [comment]
I am using jenkins plugin for owasp dependency check. It worked by installing jenkins and OWASP in same server. But, now there is  no internet to jenkins server. We have kept nist-data-mirror in other server where we have internet access. I ran the following in "invoke dependency check":
--cveUrlModified http://*.**.***.*/mirror/nvdcve-1.0-modified.json.gz
--cveUrlBase http://*.**.***.*/mirror/nvdcve-1.0-%d.json.gz

Got error as "unable to download metafile from http://*.**.***.*/mirror/nvdcve-1.0-modified.meta"
Meta file is present in mirror directory. Could you please help me on this?

**Comment by jeremylong** [comment]
Are you mirroring the 1.0 or the 1.1 files?

**Comment by priyanka270** [comment]
> Are you mirroring the 1.0 or the 1.1 files?

In the mirrored data folder, I see both 1.0 and 1.1 files. I even tried passing in below format too. Got same error as above.

--cveUrlModified file:///*.*.*.*/opt/tools/nvd/nvdcve-1.0-modified.json.gz
--cveUrlBase file:///*.*.*.*/opt/tools/nvd/nvdcve-1.0-%d.json.gz

This was tried on client servers. 
I don't know what mistake i am doing here, Please help me to solve this issue.

**Comment by jeremylong** [comment]
Add the `--log odc.log` to the command and either post the file or review it for errors.

**Comment by priyanka270** [comment]
Hi Jeremy,

Please find the attached log:
[odc.log.docx](https://github.com/jeremylong/DependencyCheck/files/4937388/odc.log.docx)

I am passing below parameters in jenkins:
--cveUrlModified http://35.209.27.*/mirror/nvdcve-1.0-modified.json.gz
--cveUrlBase http://35.209.27.*/mirror/nvdcve-1.0-%d.json.gz
--disableRetireJS true
--data /var/lib/jenkins/workspace/owasp
--log odc.log

1. Jenkins and where nist-mirror-data is present are linux servers.
2. Do we need web server installed where nist-mirror-data is present? Please let me know if any configuration has to be made after installing web server(Apache).
3. Initially i faced connection issue(unable to connect) due to port 80 was not opened on server where nist-mirror-data is present.
   Now port 80 is opened.

But now  I am getting error as meta file content is invalid. LastModifiedDate not found in meta file(I checked in meta file, lastmodified date is present). Sending output here ifincase not able to view logs. Same error is generated in odc.log.

Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/owasp
[DependencyCheck] [INFO] Checking for updates
[DependencyCheck] [ERROR] Meta file content is invalid: http://35.209.27.246/mirror/nvdcve-1.0-modified.meta
[DependencyCheck] org.owasp.dependencycheck.data.update.exception.UpdateException: Meta file content is invalid: http://35.209.27.246/mirror/nvdcve-1.0-modified.meta
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:345)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getUpdatesNeeded(NvdCveUpdater.java:385)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:122)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:936)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:737)
[DependencyCheck] 	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:667)
[DependencyCheck] 	at org.owasp.dependencycheck.App.runScan(App.java:254)
[DependencyCheck] 	at org.owasp.dependencycheck.App.run(App.java:186)
[DependencyCheck] 	at org.owasp.dependencycheck.App.main(App.java:81)
[DependencyCheck] Caused by: org.owasp.dependencycheck.data.update.exception.InvalidDataException: lastModifiedDate not found in meta file
[DependencyCheck] 	at org.owasp.dependencycheck.data.nvd.json.MetaProperties.<init>(MetaProperties.java:121)
[DependencyCheck] 	at org.owasp.dependencycheck.data.update.NvdCveUpdater.getMetaFile(NvdCveUpdater.java:341)
[DependencyCheck] 	... 8 common frames omitted
[DependencyCheck] [WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[DependencyCheck] [ERROR] Unable to continue dependency-check analysis.
[DependencyCheck] [ERROR] One or more fatal errors occurred
[DependencyCheck] [ERROR] Meta file content is invalid: http://35.209.27.246/mirror/nvdcve-1.0-modified.meta
[DependencyCheck] [ERROR] No documents exist
Build step 'Invoke Dependency-Check' changed build result to FAILURE
[DependencyCheck] Collecting Dependency-Check artifact
[DependencyCheck] Unable to find Dependency-Check reports to parse
Finished: FAILURE

In same server, if i keep jenkins and nist-mirror-data, I am able to achieve it by passing
--cveUrlModified file:///mirror/nvdcve-1.0-modified.json.gz
--cveUrlBase file:///mirror/nvdcve-1.0-%d.json.gz

But not when jenkins and nist-mirror-data are in different servers.
Please let me to know what wrong i am doing here. Kindly help me to solve this.

**Comment by smokaleksander** [comment]
Any updates here? Did you manage to solve the issue?

**Comment by jeremylong** [comment]
The wrong files are being mirred. Sorry for the really late reply. We switched to using the JSON datafeeds.

**Comment by smokaleksander** [comment]
I have the same issue; InvalidDataException: lastModifiedDate not found in meta file. All nvd cve`s file are stoted in self-hosted gitlab repository and cveUrlModified, cveUrlBase and retireJsUrl are set like that:

`<cveUrlModified>https://my-gitlab/repo/-/raw/master/owasp/nvdcve-1.1-modified.json.?inline=false</cveUrlModified>
 <cveUrlBase>https://my-gitlab/repo/-/raw/master/owasp/nvdcve-1.1-%d.json.?inline=false</cveUrlBase>
 <retireJsUrl>https://my-gitlab/repo/-/raw/master/owasp/jsrepository.json</retireJsUrl>
`
Do you have any ideas how to solve it?

**Comment by jeremylong** [comment]
are mirroring the meta files and the json files?

**Comment by smokaleksander** [comment]
Yes, I have nvdcve-1.1-2022.meta, .json and .json.gz all the way till 2003 and also nvdcve-1.1-modified in .json, .meta, .json.gz files types

**Comment by smokaleksander** [comment]
So I am getting this error
`UpdateException: Meta file content is invalid: https://myigitlab/repo/-/raw/master/owasp/nvdcve-1.1-modifimeta
caused by InvalidDataException: lastModifiedDate not found in meta file
NoDataException: No documents exist`

and of course it is not found cause the url is broken, the corrent one and so the one in pom is:
https://myigitlab/repo/-/raw/master/owasp/nvdcve-1.1-modified.meta

Do you know why url is being changed like that?
