### ISSUE TITLE
Version number containing letter is incorrectly identified

### ISSUE THREAD

**Issue by stevespringett** [dependency-check/DependencyCheck#155]
If a component having a version number containing a letter is found, DC will incorrectly identify the version.

For example: If OpenSSL 1.0.0n is presented as evidence, it will be flagged for all vulnerabilities in 1.0.0 up until version n.

**Comment by stevespringett** [comment]
In addition to letters, hyphens seem to be an issue as well. As of DC 1.2.5, jsf-impl-2.2.8-02.jar is incorrectly flagged.

**Comment by jeremylong** [comment]
Steve,

I just pushed changes to resolve the 1.0.0n issue. With jsf-impl-2.2.8-02.jar it is now being identified as:

cpe: cpe:/a:oracle:mojarra:2.2.8.02   Confidence:LOW

Can this issue be closed?

**Comment by jeremylong** [comment]
This issue is resolved, as best as it can be, in the 1.2.6-SNAPSHOT. The libraries with trailing letters in the version number, such as openssl, are now correctly identified. There are still false positives but this is due to the data in the NVD. openssl 1.0.0o is still being reported as being vulnerable to CVE-2013-6449 even though this has been patched in the 1.0.0 branch prior to 'o'. The reason it is still being flagged is 1.0.1e is marked as having all previous versions being vulnerable.
