### ISSUE TITLE
Scanning Folder & Scanning Each File individually gives different result

### ISSUE THREAD

**Issue by isaurabh2001** [dependency-check/DependencyCheck#1550]
scanning files inside folder & scanning individually producing different results:

How to reproduce:

1) create following folder  d:/scanjar

2) Put following jar inside that:

spring-boot-1.4.0.RELEASE.jar
spring-boot-actuator-1.4.0.RELEASE.jar
spring-core-4.3.2.RELEASE.jar

3) Scan using following command:

dependency-check.bat --project "Neelkamal" -s "d:/scanjar" -o "d:/folderScanReport.html" -f HTML

4) Now use following command:

dependency-check.bat --project "Neelkamal" -s "d:/scanjar/spring-boot-actuator-1.4.0.RELEASE.jar" -o "d:/SpringActuatorScanReport.html" -f HTML

while seeing "folderScanReport.html", you can see that it is completely ignoring "spring-boot-actuator-1.4.0.RELEASE.jar" like it does not exist. But individually, it is reporting 2 cve for spring-boot-actuator-1.4.0.RELEASE.jar.
Can you Please tell what I am missing?

**Comment by jeremylong** [comment]
If you expand spring-core in the HTML report scan of the directory - you will see a "Related Dependencies" section (click to expand).  Actuator is listed there.

**Comment by jeremylong** [comment]
I might have gotten that wrong - it may be under spring-boot as a related dependency.

**Comment by isaurabh2001** [comment]
Thank You Jeremy. this was tough for me to figure this out alone. Do we have some option to view all CVE at one place(not in related dependency). I am nearly sure, this is standard format which should not be changed, but I feel better to ask.

**Comment by jeremylong** [comment]
This has been a huge debate - whether or not to continue to bundle libraries.  This feature was originally implemented to be able to bundle all of the related libraries for a given framework. For instance, if you are using lucene-core, lucene-analyzers-common, lucene-queryparse, etc. if you needed to upgrade due to a vulnerability - you would be upgrading the entire framework/tool suite - not a single component (as it would break).  This is similar with other frameworks - such as Spring. However, with Spring there are "core" components that all get upgraded together and then there are a bunch of add ons that at times are hard to differentiate (in an automated fashion) from the core framework libraries.

If you wanted to disable the bundling you could set an environment variable to disable the dependency bundling analyzer; example:

`mvn -Danalyzer.dependencybundling.enabled=false verify`
