### ISSUE TITLE
False positive for intellij-core-26.2.1.jar on CVE-2015-5237

### ISSUE THREAD

**Issue by alixwar** [dependency-check/DependencyCheck#1564]
Vulnerability (CVE-2015-5237) reported for intellij-core-26.2.1.jar:

(shaded: com.google.protobuf:protobuf-java:2.6.1): ids:(cpe:/a:google:protobuf:2.6.1, com.google.protobuf:protobuf-java:2.6.1)

From protobufs issue tracker it seems that the vulnerability was introduced for version 3.4.0:

> https://github.com/protocolbuffers/protobuf/issues/760#issuecomment-345015734

- https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar
- No product affected according to: https://www.cvedetails.com/cve/CVE-2015-5237/

**Comment by jeremylong** [comment]
Per the NVD data - CVE-2015-5237 does affect versions prior to 3.4.0 - 3.4.0 is the version the vulnerability was actually fixed within.

However, in this case I believe this to be a false positive for the Java implementation of protobuf as the CVE discusses a heap overflow which is pretty hard to do in a memory managed environment.  I'll do a little investigation on this and likely add a suppression for the specific CVE in a future release.

Thanks for reporting this!

**Comment by jeremylong** [comment]
this is resolved in the 5.0.0-m2 milestone release.

**Comment by yunj** [comment]
![image](https://user-images.githubusercontent.com/18545475/56955940-d091e700-6b96-11e9-8cad-2aa0e8df1482.png)

@jeremylong can you please explain how you fix it in 5.0.0-m? 4.0.1 flags protobuf-java-2.6.1.jar as a vulnerability but 5.0.0-m2 not. Is this because the dependency does not have cpe found, as shown in the screenshot, or is suppressed? Thanks for your reply.
