### ISSUE TITLE
Suppression in XML

### ISSUE THREAD

**Issue by T0hha** [dependency-check/DependencyCheck#1597]
Is there any way to completely suppress false positives in XML report? I use XML report in Dependency Track and there problem is that this report contains all findings despite most of them were suppressed. As far as I understand the suppression happens only on presentation level in HTML reports.

**Comment by stevespringett** [comment]
Wrong project. Auditing and suppression in Dependency-Track is unrelated to Dependency-Check.

* Dependency-Track is not a container for Dependency-Check reports
 * Dependency-Track treats Dependency-Check reports as BOMs - although they're actually not, more like pseudo-boms. 
* Dependency-Track imports the components from it's BOMs and will continuously perform analysis on them.
* Dependency-Track doesn't honor Dependency-Check suppressions, because 
  * they lack a signed audit trail
  * there are other scanners in Dependency-Track. Dependency-Check suppressions only affect findings identified from Dependency-Check, not the same finding identified by another internal scanner.

Refer to https://docs.dependencytrack.org/triage/auditing-basics/ for instructions on auditing.
