### ISSUE TITLE
Several false positives with version 4.0.1

### ISSUE THREAD

**Issue by GFriedrich** [dependency-check/DependencyCheck#1637]
This is a continued issue of #1580 with version 4.0.1
Even though the number of false positives has reduced, there are still several false positives left, e.g.:
```
javax.annotation-api-1.2.jar: ids:(cpe:/a:oracle:glassfish:1.2, javax.annotation:javax.annotation-api:1.2) : CVE-2013-2566, CVE-2015-2808
jersey-apache-client4-1.19.1.jar: ids:(cpe:/a:oracle:oracle_client:1.19.1, com.sun.jersey.contribs:jersey-apache-client4:1.19.1) : CVE-2006-0550
```
Simply incrementing the filter score to 30 is no proper solution.
You will end up with several more false positives with the new version in contrast to version 3.3.4 (as you can already see by the list of created issues in the recent days).
And even more important: As the score of searches can't be predicted in any way (it might be 5 or one million), you might even end up with false negatives, which would be even more worse.

**Comment by coheigea** [comment]
This partially duplicates the existing issue: https://github.com/jeremylong/DependencyCheck/issues/1629

**Comment by jeremylong** [comment]
@GFriedrich I'm not sure how long you've been using dependency-check or if you've read some of the docs like [How does dependency-check work?](https://jeremylong.github.io/DependencyCheck/general/internals.html). However, the FP above are somewhat expected and easily suppressed.

I am open to other ideas - but at the moment the ODC project does not maintain a large curated list of GAV to CPE (or other mechanism to identify the CPE for a given library). There are several commercial options available. In addition, there is the [OSS-Index](https://ossindex.sonatype.org/). Early next year we are hoping to complete an integration that will utilize data from the OSS-Index.

**Comment by GFriedrich** [comment]
@jeremylong I'm using dependency-check for about a year now and I really appreciate the work on this project. I'm familiar with the solution to suppress false positives and that they may appear.
Nevertheless my feeling is that with the current solution (after updating the Lucene version and adapting the filter score) the situation worsened by a factor X (in both ways: false positives and false negatives) and I'm wondering whether there is a better solution to this.
I've thought about it in the last couples of days and I'm wondering whether it's possible to kind of "disable" the breaking build for identifiers with a "low" confidence, because at least to me the false positives only happened for these.
So instead of breaking the build for all vulnerabilities, it should only print a warning for those with a "low confidence". What do you think about that? Do you have "real world" situations, where only the low confidence identities match the real vulnerabilities?
I think I will try that solution with a patch and get back at you with the results once I'm done.

**Comment by ercpe** [comment]
With 4.0.2 (same in 4.0.1) we still see FP of Quartz because it's identified as Jenkins (#1582 and #1580):

`quartz-2.2.3.jar (cpe:/a:jenkins:jenkins:2.2.3, org.quartz-scheduler:quartz:2.2.3) : CVE-2018-1000169, CVE-2018-1000067, CVE-2018-1000068, CVE-2017-1000400, CVE-2017-1000401, CVE-2017-1000504, CVE-2017-17383, CVE-2017-2608, CVE-2017-1000354, CVE-2017-1000398, CVE-2017-1000355, CVE-2017-1000399, CVE-2017-1000396, CVE-2017-1000353, CVE-2017-1000356, CVE-2016-9299, CVE-2018-1999043, CVE-2018-1999042, CVE-2018-1000195, CVE-2018-1999005, CVE-2017-1000391, CVE-2018-1999004, CVE-2018-1000193, CVE-2018-1999007, CVE-2018-1000194, CVE-2018-1999006, CVE-2017-1000394, CVE-2018-1999001, CVE-2018-1999045, CVE-2017-1000395, CVE-2018-1000170, CVE-2018-1000192, CVE-2018-1999044, CVE-2017-1000392, CVE-2018-1999003, CVE-2018-1999047, CVE-2017-1000393, CVE-2018-1999002, CVE-2018-1999046
`

**Comment by malejpavouk** [comment]
@GFriedrich I have similar observation and I think the warning only for low confidence is a really good idea. I am trying to enforce owasp check at work and these FPs make it quite hard...

**Comment by jeremylong** [comment]
Sorry about the delay in responses - I've been heads down working on 5.0.  The 4.x branch was very much a rushed release with, as you've seen, insufficient testing. We all love when our dependencies have known vulnerabilities (which was the impetus for 4.x)...

I believe the work on 5.0.0 has reached milestone-1 and I am considering releasing M1 soon.  However, I would really appreciate feedback on https://github.com/jeremylong/DependencyCheck/tree/jsonDataFeeds_M1.  @GFriedrich, @stevespringett, and @hansjoachim - any chance you could pull the jsonDataFeeds_M1 branch and give it a test drive?  I've changed a lot of how the lucene index built and queried.

**Comment by GFriedrich** [comment]
@jeremylong: Thanks for the heads up!
Can you tell whether this branch will work in combination of the dependency-check-gradle 4.0.2 when I simply replace the "dependency check" library with your branch? Because I'm using the check as part of the Gradle build system, so I need a working Gradle plugin.

**Comment by jeremylong** [comment]
No - I have not worked on the gradle plugin.  I can probably get that done today.

**Comment by GFriedrich** [comment]
That would be great - then I will be able to check my projects and can give you an update.
Really appreciate your work!

**Comment by jeremylong** [comment]
@GFriedrich I just pushed teh 5.0.0-snapshot code branch to github: https://github.com/jeremylong/dependency-check-gradle/tree/5.0.0-snapshot

__Note - clone/build instructions updated based on feedback below__
```
git clone https://github.com/jeremylong/DependencyCheck.git
cd DependencyCheck
git checkout jsonDataFeeds_M1
mvn install -DskipTests=true
cd ..
git clone https://github.com/jeremylong/dependency-check-gradle.git
cd dependency-check-gradle
git checkout 5.0.0-snapshot
./gradlew install
```

Then you can test out `org.owasp:dependency-check-gradle:5.0.0-SNAPSHOT` in your gradle build.

**Comment by GFriedrich** [comment]
@jeremylong: Ok, I will give it a try. Thanks a lot for the update.

**Comment by GFriedrich** [comment]
@jeremylong: Ok I did some basic testing with one of my projects.
These are my findings:
1. Your block above is not mentioning that you need to checkout the ```5.0.0-SNAPSHOT``` branch of the Gradle plugin project. As this was quite obivous nevertheless, I did this by myself.
2. I tried to run an analyze task, but the run failed due to a missing data file. I digged deeper into it and found that you've increased the version and renamed the file. But as the ```task.properties``` in the Gradle plugin also contains the ```data.directory```, this needs to be updated too. (There is also a default in the DataExtension class that should be updated.)
3. The directory is missing a ```../``` as otherwise the "dependency-check-data" directory ends up in the wrong parent directory (seems that this is also broken for the current released version).
4. The purge task has a hardcoded ```dc.h2.db``` filename which is now broken.
5. Will there be some default cleanup when a new version is used or does a user need to take care of this? Because it's a quite huge additional disk consumption for each possible version.
6. The DB size has increased by a factor of about 2.5
7. And last but not least - the results of a run: There are still a lot of false positives, but I have different results now:
```
jaxb-impl-2.3.0.1.jar (pkg:maven/com.sun.xml.bind/jaxb-impl@2.3.0.1, cpe:2.3:a:sun:java:2.3.0.1:*:*:*:*:*:*:*, cpe:2.3:a:sun:java_se:2.3.0.1:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107, CVE-2009-2676
jaxb-core-2.3.0.1.jar (pkg:maven/com.sun.xml.bind/jaxb-core@2.3.0.1, cpe:2.3:a:sun:java_se:2.3.0.1:*:*:*:*:*:*:*) : CVE-2009-2676
jaxb-xjc-2.2.11.jar (pkg:maven/com.sun.xml.bind/jaxb-xjc@2.2.11, cpe:2.3:a:sun:java:2.2.11:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
jaxb-xjc-2.2.11.jar (pkg:maven/org.glassfish.jaxb/jaxb-xjc@2.2.11, cpe:2.3:a:sun:java:2.2.11:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
codemodel-2.2.11.jar (pkg:maven/org.glassfish.jaxb/codemodel@2.2.11, cpe:2.3:a:sun:java:2.2.11:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
jaxb-core-2.2.11.jar (pkg:maven/org.glassfish.jaxb/jaxb-core@2.2.11, cpe:2.3:a:sun:java:2.2.11:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
xsom-20140925.jar (pkg:maven/com.sun.xsom/xsom@20140925, cpe:2.3:a:sun:java:-:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2005-2527, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
rngom-2.2.11.jar (pkg:maven/com.sun.xml.bind.external/rngom@2.2.11, cpe:2.3:a:sun:java:2.2.11:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
dtd-parser-1.1.jar (pkg:maven/com.sun.xml.dtd-parser/dtd-parser@1.1, cpe:2.3:a:sun:java:1.1:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2005-2527, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
txw2-2.2.11.jar (pkg:maven/org.glassfish.jaxb/txw2@2.2.11, cpe:2.3:a:sun:java:2.2.11:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
javax.ejb-api-3.2.2.jar (pkg:maven/javax.ejb/javax.ejb-api@3.2.2, cpe:2.3:a:oracle:glassfish:3.2.2:*:*:*:*:*:*:*) : CVE-2013-2566, CVE-2015-2808
spring-security-jwt-1.0.9.RELEASE.jar (pkg:maven/org.springframework.security/spring-security-jwt@1.0.9.RELEASE, cpe:2.3:a:json-jwt_project:json-jwt:1.0.9:*:*:*:*:*:*:*) : CVE-2018-1000539
netflix-eventbus-0.3.0.jar (pkg:maven/com.netflix.netflix-commons/netflix-eventbus@0.3.0, cpe:2.3:a:git:git:0.3.0:*:*:*:*:*:*:*, cpe:2.3:a:git_project:git:0.3.0:*:*:*:*:*:*:*) : CVE-2008-5516, CVE-2010-2542, CVE-2010-3906, CVE-2013-0308, CVE-2014-9938, CVE-2015-7082, CVE-2015-7545, CVE-2017-14867
archaius-core-0.7.4.jar (pkg:maven/com.netflix.archaius/archaius-core@0.7.4, cpe:2.3:a:git:git:0.7.4:*:*:*:*:*:*:*, cpe:2.3:a:git_project:git:0.7.4:*:*:*:*:*:*:*) : CVE-2008-5516, CVE-2010-2542, CVE-2010-3906, CVE-2013-0308, CVE-2014-9938, CVE-2015-7082, CVE-2015-7545, CVE-2017-14867
netflix-infix-0.3.0.jar (pkg:maven/com.netflix.netflix-commons/netflix-infix@0.3.0, cpe:2.3:a:git:git:0.3.0:*:*:*:*:*:*:*, cpe:2.3:a:git_project:git:0.3.0:*:*:*:*:*:*:*) : CVE-2008-5516, CVE-2010-2542, CVE-2010-3906, CVE-2013-0308, CVE-2014-9938, CVE-2015-7082, CVE-2015-7545, CVE-2017-14867
jersey-apache-client4-1.19.1.jar (pkg:maven/com.sun.jersey.contribs/jersey-apache-client4@1.19.1, cpe:2.3:a:apache:apache:1.19.1:*:*:*:*:*:*:*, cpe:2.3:a:oracle:oracle_client:1.19.1:*:*:*:*:*:*:*) : CVE-2006-0550
jsr311-api-1.1.1.jar (pkg:maven/javax.ws.rs/jsr311-api@1.1.1, cpe:2.3:a:sun:java:1.1.1:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2005-2527, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
activation-1.1.jar (pkg:maven/javax.activation/activation@1.1, cpe:2.3:a:sun:java:1.1:*:*:*:*:*:*:*) : CVE-1999-0142, CVE-1999-0440, CVE-2005-2527, CVE-2009-1102, CVE-2009-1103, CVE-2009-1104, CVE-2009-1105, CVE-2009-1107
```
So to me it looks like there is still some room for improvement, but as said: Thanks for working on it!

**Comment by jeremylong** [comment]
1. Fixed the instructions above for checkout/build.
2. I updated the DataExtension and task.properties
3. I'll have to look more into whether or not an additional ..\ is needed in the path. So you are saying that the task.properties should be set to: `data.directory=[JAR]/../../../dependency-check-data/4.0`
4. With regards to the hard-coded dc.h2.db - you might have been looking at the master branch instead of 5.0.0; see https://github.com/jeremylong/dependency-check-gradle/blob/93d126a238606102d85e5f5770a3356bf49bce4b/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Purge.groovy#L53
5. Cleanup .- great point. I will have to add that to the release notes.  Use the old version and call dependencyCheckPurge (or similar for cli/maven/etc.).
6. Yes, the DB size did increase. This is due to both the new H2 format and the fact that we are storing more data on each vulnerability (yet you'll notice a large improvement in performance).
7. Excellent - a lot of FP; but they appear to be being triggered by something common that we can subsequently filter out using a fairly broad suppression rule.

On a side note, I've made some [additional updates](https://github.com/jeremylong/DependencyCheck/commit/d19a2001d079112e9664b6cc8e25b732d61a88b2) to the core ODC library that fix identified analysis bugs (NPE and Lucene parsing errors in certain cases) and  improved the performance. Huge fan of JProfiler...

**Comment by malejpavouk** [comment]
Just a quick question. Performance of creation of db or searching for vulnerabilities?

 In our experience the biggest issue is the data import, which takes several minutes. The analysis itself takes 10-15 seconds....which is not that significant in the build (especially when compared to cold start).

// we have our own nvd file proxy, so downloading the data files is negligible

**Comment by GFriedrich** [comment]
@jeremylong:
3. Yes, thats correct.
4. Oh ... must admit that I've checked the ```Purge``` class in the core library and did not saw that there is an additional task class for Gradle. Also I didn't try to execute it. But I guess the class in core needs to be adapted for Ant, right?
7. Ok - looking forward to it. Will check more of my projects once you did the necessary changes.

@malejpavouk: Mhhh I don't really mind that the creation of the DB takes a moment, as this is only done once and subsequent updates are normally much faster.

**Comment by jeremylong** [comment]
@malejpavouk 

 Running a full update: 
- Using 4.0.2 CLI -:
   `[INFO] Check for updates complete (136559 ms)`
- Using 5.0.0-SNAPSHOT - full update:
   `[INFO] Check for updates complete (163898 ms)`

So the update time has unfortunately increased slightly. However, we are storing a data in a more parsed version (for instance, CPEs instead of being stored as vendor, product, CPE - each field of the CPE:2.3 is stored separately); in the end this helps improves the analysis. However, if implemented correctly in an environment the data file would be stored between executions - so the ~2-3 minutes to perform the update should really be a one time hit.

Scanning my entire local maven repository -
- Using 4.0.2 CLI
   `[INFO] Analysis Complete (448 seconds)`
- Using 5.0.0-SNAPSHOT CLi
   `[INFO] Analysis Complete (228 seconds)`

The biggest improvements were around the JAR and Archive Analyzers. So for some projects the improvement is likely negligible. But I know we have a few users with very large projects that will see a definite improvement (of course only when they are able to save the DB between builds).
