### ISSUE TITLE
Log messages routed to home/java.log

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#164]
In some cases log messages are being routed to the default log file location for JUL. This may be an opportunity to switch to logback.

**Comment by jeremylong** [comment]
After further investigation the log files going to the default log file location for JUL was caused during unit testing. This ticket is being changed from a bug to an enhancement request to change from JUL to logback (or other logging framework).

**Comment by jaypatrickhoward** [comment]
In lieu of a all-out migration off of JUL, in the interim, could you just modify the owasp JUL logging so that it respects the global JUL configuration?  My logging.properties file is this:

handlers=java.util.logging.ConsoleHandler
.level=OFF

And I have stderr and stdout redirected to /dev/null.  When I run the dependency check plugin I still get "INFO" log statements from the following loggers written to ~/java0.log:

org.owasp.dependencycheck.Engine
org.owasp.dependencycheck.data.update.StandardUpdate
org.owasp.dependencycheck.data.update.task.DownloadTask
org.owasp.dependencycheck.data.update.task.ProcessTask

**Comment by jeremylong** [comment]
JUL is no longer in use.
