### ISSUE TITLE
False positive for geronimo-validation

### ISSUE THREAD

**Issue by coheigea** [dependency-check/DependencyCheck#1656]
There is a false positive for geronimo-validation - it is picking up a drupal CVE:

geronimo-validation_1.1_spec-1.0.jar (org.apache.geronimo.specs:geronimo-validation_1.1_spec:1.0, cpe:/a:bean_project:bean:7.x-1.0::~~~drupal~~) : CVE-2013-4499

**Comment by rmannibucau** [comment]
+1, same happens also with geronimo-metrics, geronimo-health etc, this is quite troublesome.

Side note: sonatype ossindex does not have these false positives so would be great to fix them, in particular because Geronimo Server is no more maintained and its CVE match subprojects which have no link with the old server.

**Comment by jeremylong** [comment]
resolved in the 6.x releases.
