### ISSUE TITLE
Changing artifact version numbers affect new issue calculation with jenkins plugin

### ISSUE THREAD

**Issue by SMUnlimited** [dependency-check/DependencyCheck#1698]
@stevespringett 
We want to setup our jenkins instance to fail our builds when the number of "new" issues is more than 0. 

But currently we can't do this as when the version number of any scanned file changes it counts as new issues rather than existing issues. The version number of our artifacts to scan changes on daily basis.

It seems the problem is that new issues are keyed on the detected files themselves.
So either the jenkins scan should be clever and detect the version number has changed somehow, or the issues are keyed on CWE instead of by filename. 

We are currently using 4.0.2

### Example ###
`/workspace/release-package/.m2/repository/tools/3.3.9-a14/tools-3.3.9-a14-bundle.zip/lib/guava-20.0.jar`

is re-raised every day as new as the version number 3.3.9-a14 changes to 3.3.9-a15 etc.

**Comment by stevespringett** [comment]
This is expected behavior. In this scenario, a component is being replaced by another version of the same component. A finding dropped off because a component was no longer used and a new finding is created on the new component just added. There's no possible way to correctly identify this type of change with a dependency-check xml report. If every component used semantic versioning, versions were always incremented, filenames could not be altered, and forks didn't exist, what you're suggesting would be easily achievable, but it's not.

If component versions dynamically change, then perhaps dynamically changing a suppression file could also be done.

**Comment by SMUnlimited** [comment]
We could use the supression file, but that would be an abuse of functionality built for false positives. These are still valid vulnerabilities and we really want them to still be reported.

Sounds like we will have to create our own tool to parse the CWE list from jenkins or OWASP Xml and match that against our known list and fail builds if the lists do not match.
