### ISSUE TITLE
plans for v5

### ISSUE THREAD

**Issue by SingingBush** [dependency-check/DependencyCheck#1766]
I just saw the [v5.0.0-M1 build](https://github.com/jeremylong/DependencyCheck/releases/tag/v5.0.0-M1). I think it would be good to state the planned goals for this next major version.

Can you confirm if v5 is going to drop support for Java < 8? If so then there's a few old dependencies in the project that could be updated, not to mention Joda-time that could be removed/replaced with `java.time`.

**Comment by jeremylong** [comment]
Yes, the 5.0 branch is Java 8+. I have not gone back and worked on upgrading some of the dependencies yet.  PRs are always welcome.  And yes, if you look at the PR list today there are some older ones in there - we are normally much better about keeping up with things but the 5.0 branch has taken a ton of work.  We will catch up soon.

**Comment by CarlInglis** [comment]
Our automatic update has switched us to v5 of the client, however there doesn't appear to be a script for updating the DB to v5; we're getting a "...database schema must be upgraded..." message, with a link to github, however the link on that page pointing to the update scripts is 404ing. 

There doesn't appear to be a specific "update to v5" script in the sql directory in the "core/src/main/resources/data" directory.

Could you advise how we go about updating please?

Thanks!

**Comment by jeremylong** [comment]
I'm a huge fan of automated upgrades - glad you are using one!

You will need to re-run one of the initialization scripts located in [core/src/main/resources/data](https://github.com/jeremylong/DependencyCheck/tree/master/core/src/main/resources/data). Due to the massive changes in the DB schema we need to start with an empty database (the initialize scripts will drop existing tables as necessary).  We believe the scripts are correct for other relational databases but *I* have not tested them all myself as I do not have all of the various databases running in my environment. Let us know if you run into trouble and we'll get the script corrected.

Also - we should point out that the 5.0.0 release is not near final yet. 5.0.0-M1 indicates that we reached milestone 1 in the development process (and we are currently stabilizing milestone 2). If you have an automated process to upgrade you may want to see if there is a way to configure it not to upgrade to milestone or release candidates (e.g. M1, RC2, alpha, beta).

**Comment by CarlInglis** [comment]
Hi, thanks for that. I've done the blow-it-away-and-rebuild process and it's currently downloading the updates.

We get our "what's current" from "https://jeremylong.github.io/DependencyCheck/current.txt" - would it possible to maintain a "latest_stable.txt" or something like that which we could look at instead?

Or can we assume that if there's any characters other than 0-9 and dot, we're looking at a milestone or release candidate and therefore we should ignore it. :)

**Comment by jeremylong** [comment]
I just realized that the automated process updated the `current.txt` - and it should not have. Sorry about that. This is the first (and probably last time) that the ODC project will have a release where we wanted to do milestone releases. The plan this for the 5.0.0 is:
- Milestone 1: upgrade from XML data feeds to JSON data feeds (complete)
- Milestone 2: improve .NET analysis and upgrade to dotnet core (in stabilization)
- Milestone 3: add [OSS-index](https://github.com/jeremylong/DependencyCheck/pull/1391) support.

**Comment by CarlInglis** [comment]
No worries. I assume you're not going to update it for M2 & M3? In which case I'll just leave it where is and we'll get the next release. Thanks for the quick responses; it's appreciated.
