### ISSUE TITLE
"A new version of dependency-check is available." inconsistent warning

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#1798]
There are two parts to this. First there should be a way to suppress this warning, especially if it's a major version (or prerelease) upgrade.

The more confusing issue is that this warning only appears on my Linux machine, and not my Windows machine.

Plugin version is 4.0.2. Warning appears when running `dependency-check:check`.
Both use the same Maven version (3.6.0) but different JDKs.

https://gist.github.com/OrangeDog/8a79971dc1be7c3de44e6aa90d5dc00b

**Comment by jeremylong** [comment]
This is likely due to the mistake publishing the milestone releases. There is a [current.txt](Begin Engine Versi) that gets automatically updated when a new tagged version is pushed. We did not mean for this to get updated beyond 4.0.2 for the milestone releases. However, the file was updated.  I have since reset the file to be 4.0.2.

Looking at the code - I believe the difference in the error messages was caused by me reverting the current.txt.  

You can disable the engine version check using the configuration `versionCheckEnabled`.  We will try to do better - and only a single milestone release is planned. Lesson learned - we will ensure that the current.txt file is updated correctly when this is released.
