### ISSUE TITLE
I want clarification on FP

### ISSUE THREAD

**Issue by baldegit** [dependency-check/DependencyCheck#1803]
Hello,

for the first use of owasp, I find some difficulty in understanding what is said in doc. so I have the following questrion.

what does the false positive mean? is the cpe that is not clickable ?
is there a way to automate the deletion of false positive ??

Merci

**Comment by aikebah** [comment]
A False Positive is a fairly common terminology in binary classification that indicates a "true" outcome that should have been "false" outcome. (similarly there exist False Negatives: a "false" outcome that should've been a "true" outcome)

In the case OWASP Dependency Check this means that the tool is reporting a vulnerability where none exists. (And the false negative indicates a case where OWASP Dependency Check raises no alarm in spite of having scanned a known-vulnerable library)

You typically get rid of the false positives by creation of a suppression file: [https://jeremylong.github.io/DependencyCheck/general/suppression.html](https://jeremylong.github.io/DependencyCheck/general/suppression.html)

In order to not have to repeat those suppressions over and over you could publish a suppression file at some public location to use for your suppressions throughout multiple projects. The tools of the project support specifying multiple suppression files allowing the use of both such a global suppression file as well as a project/scan-specific suppression file.

If the false positive is on a public library you should consider also raising an issue here at GitHub so that it's detection can be attempted to be mitigated for all users (by inclusion in internal suppression filters or improvement of scanning/matching code)

**Comment by baldegit** [comment]
Hello, thank you for your response.
In the generate report, how to tell the difference between a  false positive and a "true positive". so that I can put them in the deletion file.
In other words my problem is that I have difficultyto  identify a false positive

tks

**Comment by mprins** [comment]
When you read the CVE, which is linked to in the html report, you can determine if you are vulnerable. Note that having a vulnerability reported in a library that you use does not necessarily make your product vulnerable, it depends on the attack vector.

**Comment by baldegit** [comment]
thank you for your response.
