### ISSUE TITLE
vulnerable jars

### ISSUE THREAD

**Issue by Mayabhai** [dependency-check/DependencyCheck#1856]
Hi Team,

I am using Apache Tika 1.5 and it has some vulnerabilities in apache pdfbox. But we are not using pdfbox in the application. Is it still vulnerable if we are not using apache pdfbox? or application is still vulnerable?

**Comment by jeremylong** [comment]
That is always a million dollar question - transitive dependencies.  In some cases you would not be vulnerable - in other cases you might. Very few of the SCA tools do anything in this space (especially the free ones).  My suggestion is to try and keep everything as up-to-date as possible all the time.  I frequently suggest folks use tools like @dependabot[bot] (see https://dependabot.com/).

**Comment by THausherr** [comment]
It isn't vulnerable if you are sure that you'll never process PDF files. Nevertheless I recommend you update TIKA. 1.5 sounds old, the project is at 1.21 now. By keeping old versions you're denying yourself the joy of all the good things that the developers have created since then.

**Comment by jeremylong** [comment]
If your code is on github - checkout dependabot. This makes upgrading/patching just part of your normal lifecycle by continually getting PRs when new versions of a dependency come out. What is great about doing this is you can stay ahead of discovered vulnerabilities and if an emergency/zero day event - patching/upgrading is already part of the lifecycle and you can respond quicker. Both because you are likely using a very recent version (patches are only sometimes backported) and because patching is already part of the standard development sprints.
