### ISSUE TITLE
old NVD CVE 2019 in the report while updates done before

### ISSUE THREAD

**Issue by githubhs17** [dependency-check/DependencyCheck#1919]
using docker image dependency-check version: 4.0.2

In the log I see that there was a check for updates and that there are updates downloaded and processed:

03:11:56 [INFO] Checking for updates
03:11:56 [INFO] starting getUpdatesNeeded() ...
03:11:59 [INFO] Download Started for NVD CVE - Modified
03:12:02 [INFO] Download Complete for NVD CVE - Modified  (2875 ms)
03:12:02 [INFO] Processing Started for NVD CVE - Modified
03:12:05 [INFO] Processing Complete for NVD CVE - Modified  (3577 ms)
03:12:05 [INFO] Begin database maintenance.
03:12:07 [INFO] End database maintenance.
03:12:07 [WARN] A new version of dependency-check is available. Consider updating to version 5.0.0.m1.
03:12:09 [INFO] Check for updates complete (12393 ms)

But in the report the data for NVD CVE 2019 are old (from March):
...
NVD CVE 2016: 02/03/2019 03:57:16
NVD CVE 2017: 02/03/2019 03:57:15
NVD CVE 2018: 02/03/2019 03:57:14
NVD CVE 2019: 01/03/2019 08:01:31
NVD CVE Checked: 14/05/2019 08:13:46
NVD CVE Modified: 14/05/2019 05:15:33
VersionCheckOn: 1556717936668

**Comment by jeremylong** [comment]
hm..  I see your point - but it is accurately showing the last time that the given NVD CVE file was downloaded.  There was no need to download the 2018 files again because the `modified` file has been downloaded more recently (and no time span more than 7 days has occurred between the updates).  Maybe it would be better to just show the last modified date rather then the time stamp for each file.
