### ISSUE TITLE
False Positive on Apache Tika's tika-parsers on excluded dependencies

### ISSUE THREAD

**Issue by tballison** [dependency-check/DependencyCheck#1961]
Apologies...I don't know if this is a bug or a false positive.

When Tilman Hausherr ran 5.0.0.M3 on Apache Tika, he got the following in the tika-parsers module

```
cpe:2.3:a:apache:tika:0.1
cpe:2.3:a:apache:tika:0.8:
```

I _think_ what's happening is that two of our dependencies -- vorbis and the sentiment-analysis-parser -- depend on an older version of tika-core.  We've excluded those in our pom, but I think those exclusions are not being picked up by DependencyCheck.

Many, many thanks for this tool!

tika-parser's pom: https://github.com/apache/tika/blob/master/tika-parsers/pom.xml

Exclusions:
```
      <groupId>org.gagravarr</groupId>
      <artifactId>vorbis-java-tika</artifactId>
      <version>${vorbis.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.tika</groupId>
          <artifactId>tika-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
and

```
    <dependency>
      <groupId>edu.usc.ir</groupId>
      <artifactId>sentiment-analysis-parser</artifactId>
      <version>0.1</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.tika</groupId>
          <artifactId>tika-parsers</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.tika</groupId>
          <artifactId>tika-batch</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.tika</groupId>
          <artifactId>tika-translate</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.tika</groupId>
          <artifactId>tika-langdetect</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.tika</groupId>
          <artifactId>tika-core</artifactId>
        </exclusion>
...
      </exclusions>
    </dependency>
```

Reference issue: https://issues.apache.org/jira/browse/TIKA-2878?focusedCommentId=16844146&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16844146

**Comment by jeremylong** [comment]
I would need more of the full pom for you build to really help. If you can't post the full pom - can you generate the XML or JSON reports and just post the two tika dependencies (0.1 and 0.8).

I can suggest a few things to look at - for the older version of tika that is being identified take a close look at the file paths. Is there a chance that the old version of tika is being identified because it is embedded in another jar you have as a dependency (i.e. shaded, onejar, uberjar)?

**Comment by tballison** [comment]
Ugh.  Sorry for my delay.  The full pom is here: https://github.com/apache/tika/blob/master/tika-parsers/pom.xml 

I confirmed that tika-core code is not bundled inside the vorbis-java-tika 0.8 jar or the sentiment analysis parser jar.

Here's the html report:
[dependency-check-report.zip](https://github.com/jeremylong/DependencyCheck/files/3462259/dependency-check-report.zip)

I've just rerun 5.2.0 and confirm this issue still exists.

**Comment by jeremylong** [comment]
Thanks - When you had originally posted the issue I thought there might be something going on in the project due to shaded JARs. However, these are fairly generic false positives that occur because of how dependency-check works.  Generating a suppression file is simple enough using the HTML report.  However, as with most FP reports I will include the suppression rules in the core.
