### ISSUE TITLE
Various issues with 5.0.0-M3.1 gradle plugin

### ISSUE THREAD

**Issue by emartynov** [dependency-check/DependencyCheck#1971]
**Describe the bug**
Since I have an issue with 4.0.2 now I decided to give a try 5.0.0 version.
I got one new CVE reported
```
guava-23.5-jre.jar (pkg:maven/com.google.guava/guava@23.5-jre) : CVE-2018-10237
```
That is new from 4.0.2 checks. I wonder why it happens in comparing to 4.0.2. I was able to add suppression but it still fails with issues below

It also crashes OWASP check with exception:
```
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        Failed to initialize the RetireJS repo
```

** Version of dependency-check used **
The problem occurs using version 5.0.0-M3.1 of the gradle plugin

**To Reproduce**
Just run gradle check.

**Comment by jeremylong** [comment]
Are you behind a proxy?  The RetireJS analyzer tries to download a data file from github?

Unfortunately - there are some configuration issues in the milestone releases that have been fixed in the 5.0.0-SNAPSHOT builds. When 5.0.0 is released shortly, you will be able to disable the retireJS analyzer or change the URL to a local mirror of the data file.

**Comment by emartynov** [comment]
I'm not behind a proxy but we don't have also perfect internet setup.

**Comment by jeremylong** [comment]
If you have spotty connections - consider mirroring things locally.
