### ISSUE TITLE
missing finding - CVE-2010-1622 for spring-beans-2.5.5.jar

### ISSUE THREAD

**Issue by bedirhan** [dependency-check/DependencyCheck#2]
According to the below CVE entry spring-beans-2.5.5.jar has a security vulnerability which I couldn't get DependencyCheck to report. It might be because of CVE updates don't include it. I'm not sure, is it an expected result?

http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-1622

**Comment by jeremylong** [comment]
Could you provide the JAR file you scanned, the resulting HTML report, and the version of the DependencyCheck you used?

**Comment by bedirhan** [comment]
I've first used spring-beans-2.5.5.jar, then realized that related vulnerability doesn't include that specific jar details in nvdcve-2.0-2010.xml. It included springframework jar details, so, I downloaded and scan spring-framework-3.0.2.RELEASE.zip.

I didn't look at the code, but the problem might be the extra RELEASE keyword in the Manifest.mf file.

cheers.

**Comment by jeremylong** [comment]
I've looked into this a bit more and found that it is not picking this up because "springsource" has not put their name anywhere in the spring-core.jar. It is not in the manifest, file name, package names, etc. I've been planning on re-working the CPEAnalyzer and my planned changes should correctly identify the spring-core jar files. I'll try and have this fixed this weekend (but it is a holiday weekend in the US, so it may slip into next week).

**Comment by jeremylong** [comment]
Okay, the spring CPE/CVE entries should now be identified. The bug was slightly more complicated because there were two issues:

1) SpringSource does not include their name as the vendor anywhere within the spring jar files.
2) The CPE.xml file hosted by NIST does not contain all of the CPE entries referenced in the NVD CVE hosted by NIST. I've reported this possible bug to them and I have updated the NVD CVE Importer to also add CPE entries to the CPE Index. I felt this is somewhat hackish though... I plan on reworking things a bit.

There is an issue with the patch (kind of) in that it will report the same CPE/CVE data for Spring-Beans-2.5.5.jar as for Spring-Core-2.5.5.jar when the entries really only belong to 'core'. I don't feel this is too much of a bug, because to use any of the sub-jars like 'beans' you need to include core. However, this may show up in other packages.

Overall, this bug has me re-thinking how I am storing and querying the CPE/CVE data.

Thanks for the bug report - please continue to let me know if you find any other issues like this.
