### ISSUE TITLE
False positives for ch.qos.logback:logback-classic:1.1.2

### ISSUE THREAD

**Issue by rpuch** [dependency-check/DependencyCheck#206]
Here is the demo project:
https://github.com/rpuch/test-owasp-maven-plugin

'mvn clean site' produces target/site/dependency-check-report.html which contains references to vulnerabilities of cpe:/a:springsource:spring_framework:1.1.2 which do not even reference logback. Nevertheless, they are reported as vulnerabilities of ch.qos.logback:logback-classic:1.1.2.

I've seen the same for com.artofsolving:jodconverter:2.2.1: for it, vulnerabilities of cpe:/a:openoffice:openoffice:2.2.1 where reported.

It seems to be a pattern here: component identifier (like ch.qos.logback:logback-classic) is substituted with the identifier of another component (like cpe:/a:springsource:spring_framework), while version remains the same.

**Comment by hansjoachim** [comment]
Thanks for reporting this issue.

I have also seen false positives with logback-classic which presumably is the same issue (it mentioned something spring-related at least). However, I've only been able to trigger this on one machine. When setting up a PoC similar to yours on another machine, I was not able to trigger it. Neither did it find any when I tested your sample pom. 

Since you seem to be able to trigger the issue too, it looks like there might be something here though. But I still find it strange that the false positives aren't listed consistently.
Machine I've seen it on: running Windows w/Oracle JDK 8 (don't remember exact version off the top of my head)
Machine where I can't reproduce it: running Ubuntu Vivid (development) w/openJDK 7u75-2.5.4-3.

Could it be as simple as something being interpreted differently by 7 and 8?

**Comment by rpuch** [comment]
Yes, you are right.

Java 8:

```
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /home/rpuch/soft/jdk1.8.0_31/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-48-generic", arch: "amd64", family: "unix"
```

In this configuration false positives are produced.

Java 7:

```
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_15, vendor: Oracle Corporation
Java home: /home/rpuch/soft/jdk1.7.0_15/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-48-generic", arch: "amd64", family: "unix"
```

In this configuration I don't see false positives.

**Comment by hansjoachim** [comment]
Hm, I remember I ran into some failing tests when I tried to build dependency-check with jdk8 a while back. Maybe that's related.

**Comment by jeremylong** [comment]
Thank you for the bug report. Apparently, there have been a few reported issues with Java 8 that I need to dig into. In case I am unable to reproduce this exact problem can you provide the HTML report that contains the false positive?

Thanks!

Jeremy

**Comment by rpuch** [comment]
Here it is:
https://github.com/rpuch/test-owasp-maven-plugin/blob/master/src/main/resources/dependency-check-report.html

**Comment by jeremylong** [comment]
A patch has been added to resolve this issue. The problem was with the Evidence's compare method - part of the method was doing case insensitive comparison and part of it was case sensitive. It has been updated to be case insensitive and test cases have been added. This will be part of the 1.2.10 release.
