### ISSUE TITLE
CLI Classpath issue on Windows

### ISSUE THREAD

**Issue by derek126** [dependency-check/DependencyCheck#2062]
**Describe the bug**
Out of the box on Windows Server 2016 dependency check Jenkins plugin wont work when installing automatically. Works fine if I install myself and specify the location.

** Version of dependency-check used **
5.10 and 5.0.1 Jenkins plugin

** Log file **
13:28:42 Unpacking https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.1.0-release.zip to E:\Jenkins\tools\org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation\dependency-check on Jenkins
13:28:51 [DependencyCheck] The input line is too long.
13:28:51 [DependencyCheck] The syntax of the command is incorrect.
13:28:51 Build step 'Invoke Dependency-Check' changed build result to FAILURE

**To Reproduce**
1. Install latest Jenkins on Windows with the 5.0.1 plugin.
2. Select to install dependency check automatically from bin tray,

**Expected behavior**
I expect the plugin to work correctly and scan my work space with default arguments.

**Comment by stevespringett** [comment]
If there error is in the download, extraction, or installation of the tool, please report the issue to the Jenkins team as these things are outside of the plugins control and handled by Jenkins itself.

If the issue is that the plugin cannot successfully or unsuccessfully execute dependency-check.bat (on Windows), that would be a Dependency-Check Jenkins plugin issue.

If the issue occurs while running dependency-check.bat, that is something the core Dependency-Check team can look info, but we'll need a lot more info.

However, it sounds like Jenkins is having issues with downloading, extracting, and installation on Windows which needs to be reported to the Jenkins core team.

**Comment by derek126** [comment]
I guess this falls under Jenkins install.

If I run 
`.\dependency-check.bat --scan E:/Workspace --format XML --project Workspace`
from 
`E:\Jenkins\tools\org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation\5.1.0`
I get the same issue.

But if I run the same command by copying the files to E:\dependency-check it works fine.

It just seems that on Windows the path may be too long.

**Comment by Kelly12612** [comment]
I'm having this issue with Dependency-Checker 5.0.2 with the Jenkins plugin on a windows system.
I did a bit of digging, and the problem is the set CLASSPATH in dependency-check.bat, which seems to be the cause of this problem reported against the Dependency-Check  Jenkins plugin [https://issues.jenkins-ci.org/browse/JENKINS-58402](https://issues.jenkins-ci.org/browse/JENKINS-58402).
In my windows jenkins agent, the path to the tool BASEDIR is 135 characters, so the fully expanded CLASSPATH value would be 10841 characters, the longest command line for modern windows is 8191.

I'll add this info to that ticket as well, not sure the best way to solve it, although for Java 9, that may be to use a manifest jar file.

I should have pointed out that you don't need a windows machine to see this, you could just add "echo $CLASSPATH | wc -c" to dependency-check.sh, after CLASSPATH is set.  If the length is over 8191, then it won't work on windows.

**Comment by jeremylong** [comment]
Updated the app assembler plugin to use wildcard classpaths.  This will resolve the issue with the classpath length on Windows.
