### ISSUE TITLE
Add Python Analyzer

### ISSUE THREAD

**Issue by dwvisser** [dependency-check/DependencyCheck#207]
Analyzer should gather evidence from the various downloadable artifacts from the [Cheese Shop](https://pypi.python.org/pypi):
- Eggs: .egg and .zip extensions
- Wheels: .whl extension
- Sdists: .tar.gz extension

Also gather evidence from a Python installation's site-packages (e.g., a system's installed packages, or a virtualenv's installed packages):
- .dist-info/MANIFEST
- .egg-info/PKG-INFO
- .egg/EGG-INFO/PKG-INFO
- actual Python package folders

I already have a prototype successfully parsing out MANIFEST files and PKG-INFO files from the file system and .whl archives. I need to finish that part, and add scanning of the actual Python packages (in file system and sdists).

P2exe- and Py2app-deployed code (i.e., compiled) is out of scope for this issue tracker. Certain kinds of applications that embed the Python interpreter may by scannable though.

**Comment by jeremylong** [comment]
+1 - I know several people that have asked for Python.

In addition to the core Analyzer we likely need to enhance the suppression analyzer and base suppression XML file to limit some of the obvious false positives. One thought I had was to enable to suppression to be based off of the description within the CVE entry - specifically because most of the python related CVEs  appear to have a '.py' or 'python' listed in the description. So if those are not present the CVE may not be related to python library (this would need to be researched to ensure valid matches are not masked).

**Comment by jeremylong** [comment]
see pull #217
