### ISSUE TITLE
wrong main class in shellscript

### ISSUE THREAD

**Issue by davidkarlsen** [dependency-check/DependencyCheck#2085]
5.2.0 seems to have a an error in the shellscript to launch odc:

Step 6/9 : RUN	/usr/local/dependency-check/bin/dependency-check.sh --updateonly && npm set registry ${NPM_REGISTRY} && yarn config set registry ${NPM_REGISTRY} && chown -R node:node /home/node /usr/local/dependency-check/data && chmod -R a+w /usr/local/dependency-check/data
---> Running in 8d70a102189f
Error: Could not find or load main class org.owasp.dependencycheck.App

**Comment by adrian-frugtniet** [comment]
Previous release had a repo folder with .jar files. This is missing from the download .zip file this time.

**Comment by jeremylong** [comment]
Sorry about that - with 5.2.0 we changed from using a "repo" structure to using a flat lib structure as some users were running into classpath length limitations on Windows. I missed updating `release.xml` to include the lib instead of the repo folder.  

I just re-published the CLI and Docker files for version 5.2.0.
