### ISSUE TITLE
Issue with the CLI --exclude option

### ISSUE THREAD

**Issue by Jarl-dev** [dependency-check/DependencyCheck#2107]
I am trying to use the --exclude option to exclude files.
This is working well with other folders and files. But for some reason I cannot seem to exclude the following file path: 

\node_modules\jquery-sortable\node_modules\jquery\package.json

What i have tried is:
\node_modules\jquery-sortable\node_modules\jquery\\**
\node_modules\jquery-sortable\node_modules\jquery\\*
\node_modules\jquery-sortable\node_modules\jquery\package.json

Even during the same check other paths seem to be excluded fine.
Any idea why its not successfully excluding in this specific case?
Maybe because its a package.json?

Also would it be an option to have the excluded files / paths visible in the results?

**Comment by jeremylong** [comment]
With Node analysis this is likely being included because it is identified in the package.lock (or similar) at the root of the project.  The exclude tells ODC not to inspect a specific file on disk - however, the analyzers that work off of a file that defines dependencies (i.e. some form of package manager) it uses the contents of the package manager.

**Comment by Jarl-dev** [comment]
Yeah that sounds logical. 

The strange thing is that it started over the weekend when we did not make any changes.
(We do an automated build and check every night).

Before that, the package.json did not show up, just the files themselves, which we could exclude.

My assumption is that NPM updated something in their results, which caused this file to appear.
