### ISSUE TITLE
CLI exit code is always 0, even if there are errors

### ISSUE THREAD

**Issue by dylemma** [dependency-check/DependencyCheck#215]
It's difficult to tell when Dependency-Check fails to run. For example, if it can't update the database due to internet issues, or if the analysis crashes for one reason or another.

I've got a solution in place that reads the log file and looks for `SEVERE` messages, but it seems dirty. Could the CLI return a non-zero exit code when a fatal error happens? It would be extra helpful to have a few different codes to signify different meanings.

**Comment by jeremylong** [comment]
Yes, I can make this happen. However, since this change will need to alter more then just the CLI plugin I won't be able to implement in the upcoming release (which will be within a week). I'll put this on the road map for 1.2.11 depending on what other changes get bundled.

Thanks for the suggestion!

--Jeremy

**Comment by jeremylong** [comment]
Quick note for myself as I implement this - be sure to include the following as non-zero exit codes:
- unable to download NVD
- incorrectly configured suppression file
- scanning non-existent directory
- check the code base for any error logging (as opposed to warn/info/debug) - the errors may need to be added to the non-zero exit code list.

**Comment by jeremylong** [comment]
This has been resolved in 1.4.2

**Comment by dylemma** [comment]
Thanks for doing this!
