### ISSUE TITLE
cpe:2.3:a:gradle:gradle:3.5.0:*:*:*:*:*:*:* on gradle-api-3.5.0

### ISSUE THREAD

**Issue by bblackbelt** [dependency-check/DependencyCheck#2178]
cpe: `cpe:2.3:a:gradle:gradle:3.5.0:*:*:*:*:*:*:*`

```xml
<!-- https://mvnrepository.com/artifact/com.android.tools.build/gradle-api -->
<dependency>
    <groupId>com.android.tools.build</groupId>
    <artifactId>gradle-api</artifactId>
    <version>3.5.0</version>
</dependency>
```
the Vulnerability was fixed in `Gradle 5.6`. After upgrading to it, the CVE is still being reported. am I missing something ?

**Comment by jeremylong** [comment]
[CVE-2019-11065](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-11065) - affects version up-to-including 5.3.1.

[CVE-2019-15052](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-15052) - affects version up-to-excluding 5.6.

You are seeing these because the `gradle-api` is version 3.5.0 and is possibly being mis-identified as the entire gradle build platform.

**Comment by bblackbelt** [comment]
go it. Thanks @jeremylong
