### ISSUE TITLE
False Positive : db2jcc4-4.23.42.jar reported as  cpe:2.3:a:ibm:db2

### ISSUE THREAD

**Issue by OlivierJaquemet** [dependency-check/DependencyCheck#2185]
- The location of the dependency (Maven GAV, URL to download the dependency, etc.)
https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads

- The CPE that is believed to be false positive
`db2jcc4-4.23.42.jar (pkg:maven/com.ibm.db2/db2jcc4@4.23.42, cpe:2.3:a:ibm:db2:4.23.42:*:*:*:*:*:*:*) : CVE-2007-2582, CVE-2007-3676, CVE-2007-5090, CVE-2007-5652, CVE-2008-3958, CVE-2008-3959, CVE-2008-4691, CVE-2008-4692, CVE-2008-4693, CVE-2009-1239, CVE-2009-1905, CVE-2009-2858, CVE-2009-2859, CVE-2009-2860, CVE-2010-1560, CVE-2011-0731, CVE-2011-0757, CVE-2011-1373, CVE-2011-1846, CVE-2011-1847, CVE-2012-3324
`

Dependency declared in our pom with the following *internal* local maven id
```xml
      <dependency>
        <groupId>com.ibm.db2</groupId>
        <artifactId>db2jcc4</artifactId>
        <version>4.23.42</version>
      </dependency>
```

**Comment by aikebah** [comment]
As this is not a public library I would advise on creating an enterprise suppression file to mitigate this false positive. If you make the suppression-file available via a URL to anyone who might use it and run dependency-check (e.g. by hosting it on an internal http-server). You can use it as a standard first suppression-file for the maven-plugin
The vulnerabilities of IBM's DB2 JDBC driver are linked to the DB2 version itself (there is no separate JDBC driver cpe entry and the issues are linked to the DB2-version not the JDBC-driver-version within the NIST NVD, see e.g. [CVE-2017-1677](https://nvd.nist.gov/vuln/detail/CVE-2017-1677)).

Dependency-check does a best effort guess for linking public- and non-public libraries to NIST NVD entries (CPE identifiers), but especially for private coordinates like these it makes no sense to include suppression of FPs in the global suppression lists as they will vary from company to company (e.g. in our company we version the JDBC-driver in our internal 3rd party repository in a similar fashion as NIST NVD classifies the CVEs: by version / fixpack of DB2 that it belongs to rather than internal driver version number).

To suppress them use for example:
```xml
<suppress>
  <notes><![CDATA[
    Suppress false-positives on the proprietary IBM DB2 JDBC driver
  ]]></notes>
  <gav regex="true">com\.ibm\.db2:db2jcc4.*</gav>
  <cve>CVE-2007-2582</cve>
  <cve>CVE-2007-3676</cve>
  ...etcetera...
</suppress>
```

In the dependency-check plugin configuration you can then use the <suppressionFiles> configuration to configure both the global enterprise suppressions of internal library / properietary library FPs and a project-local FP suppression file if needed conform Example 7 of https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html

To reduce the number of false positives to suppress you might consider to version the jdbc library not by its private library version, but by the corresponding DB2 fixpack version, which would make a better automated match against the NVD listed vulnerabilities of DB2 (but still hitting server- and non-JDBC client library CVEs alongside true JDBC library CVE entries as in the NVD there is no distinction between the server and the various client libraries for linking a CVE to a software product)

**Comment by OlivierJaquemet** [comment]
Thank you @aikebah for your complete and very detailed answer.

We are well aware of all this and we had already excluded this library.
However, even though we were using "made up" maven group/artefact id, I felt it was still worth it to report the false positive as this official IBM jdbc driver is publicly downloadable.

You might see that I have previous record of[ false positive reports](https://github.com/jeremylong/DependencyCheck/issues?utf8=%E2%9C%93&q=author%3AOlivierJaquemet+) ;) 

Your suggestion to use the latest JDBC driver (corresponding to the DB2 with all fix pack) is very interesting and I will have a look into it !

Thanks again for the time you took to take this report in consideration and to write this answer.

**Comment by jeremylong** [comment]
I do not have an IBM account and as such cannot download the JAR file indicated.  In most cases the JDBC drivers are false positives.  As you've already suppressed this locally - I am going to close this issue.

**Comment by OlivierJaquemet** [comment]
Thank you @jeremylong
