### ISSUE TITLE
False Positive on any JARs that mention Jenkins in MANIFEST.MF

### ISSUE THREAD

**Issue by arjopoldervaart** [dependency-check/DependencyCheck#2244]
I attached a sample JAR (renamed to zip) with a MANIFEST.MF that contains URLs to our build server. When I run dependency check, we get a lot of false positives on Jenkins libraries.

I attached the report and our suppression file.

The suppression.xml I use, is from github: https://raw.githubusercontent.com/jeremylong/DependencyCheck/master/core/src/main/resources/dependencycheck-base-suppression.xml

To which I added as the first entry:
    <suppress base="true">
        <notes><![CDATA[
        This suppresses false positives identified on Jenkins from MyCompany manifest file
        ]]></notes>
        <gav regex="true">^.*mycompany.*$</gav>
        <cpe>cpe:/a:jenkins:jenkins</cpe>
    </suppress>

[report+suppression.zip](https://github.com/jeremylong/DependencyCheck/files/3702315/report%2Bsuppression.zip)

#### Example
False positive on library foo.jar - reported as cpe:/a:apache:tomcat:7.0
```xml
<dependency>
   <groupId>org.sample</groupId>
   <artifactId>foo</artifactId>
   <version>1.0</version>
</dependency>
```

[QuickConnect-1.1.zip](https://github.com/jeremylong/DependencyCheck/files/3702285/QuickConnect-1.1.zip)

**Comment by aikebah** [comment]
@arjopoldervaart The problem is that maven coordinates are not part of the collected evidence, so it cannot suppress the cpe for jenkins based on your maven coordinates wildcard.

An alternative approach you can use for suppressing this matching is removal of the build-url from the collected evidences by the HintAnalyzer in case the manifest indicates that it's a company private artefact.

The HintAnalyzer is mainly meant for removal of false negatives but it allows for both addition and removal of evidence, so in case of wrong CPE matching it can also be employed to remove false positives. On the [Resolving false negatives](https://jeremylong.github.io/DependencyCheck/general/hints.html) page in the documentation you find more info on the hints.xml file.

The ability to remove evidence is not directly documented there, but is present and has been improved in the past to support regular expressions with #704

Using the following hints.xml should resolve the issues for your scenario (assuming that all of your company artefacts have the given Implementation-Vendor, otherwise you would have to modify the criteria to a more proper match):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<hints xmlns="https://jeremylong.github.io/DependencyCheck/dependency-hint.1.3.xsd">
    <hint>
        <given>
            <evidence type="vendor" name="Implementation-Vendor" value="Funatic B.V."/>
        </given>
        <remove>
            <evidence type="product" name="build-url" value=".*" source="Manifest" regex="true"/>
            <evidence type="vendor" name="build-url" value=".*" source="Manifest" regex="true"/>
        </remove>
    </hint>
</hints>
```

**Comment by arjopoldervaart** [comment]
@aikebah , thanks Hans.  I have added the hints.xml and it resolves our issues. 

I have two questions/remarks regarding the documentation:
1. Is my hints.xml in addition to the default hints file or does it replace it?
2. I could not find in the documentation how to specify the location and use of the hints file, there is no mention of it on the documentation page of the command line arguments (https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html), I found the option "hintsFile" on the Ant page, but this failed, but did point me to the correct argument "hints".

**Comment by aikebah** [comment]
@arjopoldervaart the hints file you specify on the command-line will be used in addition to the default hints file included in dependency-check. First the hints of the default hints file are loaded and then the hints from the supplied hints file are added.

Regarding the documentation for the cli: Thanks for reporting it. I've created a separate issue for that. It's clearly something we should fix and I hope to make a PR for that this weekend.

**Comment by arjopoldervaart** [comment]
@aikebah , thanks again :)
