### ISSUE TITLE
MD5 from HTML report output differs from md5sum/openssl

### ISSUE THREAD

**Issue by Itrustbecci** [dependency-check/DependencyCheck#2269]
I ran DC CLI verison 5.2.2 on several Ubuntu systems against some directory containing jar, war and other files, creating HTML report.
In the report I view ALL dependencies and search for a particular file. The report provides me File path and MD5/SHA1/SHA256 of that file, same for all "Related Dependencies".

However, when comparing those digests against ones I create on the same system using either md5sum or openssl digest -md5 the hashes differ for the same file.
I got puzzled and compiled the Checksum class from git source of your project and fed it with the same file and to my surprise the hash corresponds to md5sum and openssl as it should.
Question is...why does the one in the html report differ ??

**Comment by Itrustbecci** [comment]
update: I just came across an instance where the hashes match - this was for a file which was NOT inside a WAR or JAR, whereas the ones which didn't match up, all were from files inside WAR files.
Upon manually extracting them and checking with md5sum they turn out to be the same files ....
so possibly the issue is with processing WAR contents ?

**Comment by jeremylong** [comment]
> Upon manually extracting them and checking with md5sum they turn out to be the same files

If the report has `WAR.jar/some.jar` and it reports the md5sum as `efaec2fac998dce5bc118362bf724527`.  Then when you extract it from the WAR and run md5sum against `some.jar` it returns `efaec2fac998dce5bc118362bf724527`. This is the expected behavior.  We are presenting the hashes of the file analyzed which is a JAR file that is contained in an archive.
