### ISSUE TITLE
Could not download NVD data feed update since version 1.2.6 (include)

### ISSUE THREAD

**Issue by wmaintw** [dependency-check/DependencyCheck#228]
Hi Jeremy,

We are trying to use DependencyCheck in our organisation, but we met a problem, that is from version 1.2.6 (include this version), the DependencyCheck could not download NVD data feed, the version 1.2.5 works fine.

According to the error log, the update process failed at `retrieveCurrentTimestampsFromWeb()` method, and what this method trying to do is fetch `CVE_MODIFIED_20_URL`, and determine if there's any update.

After looking at the code changes between 1.2.6 and 1.2.5, we found that, the `cveUrl20Modified` url used by that method was changed from `http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-modified.xml` to `https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-Modified.xml.gz`

Once we change the configuration to use the old url in 1.2.6, it works.

Would you please confirm if this is an issue?

**More information:**

We are behind an internal proxy, but we can download NVD data feed directly using the new url with browser, or curl command. 

1.2.5 works fine, but 1.2.6 and higher version don't work, the only thing changed between 1.2.5 and 1.2.6 in this scenario is the NVD data feed url.

**Comment by jeremylong** [comment]
I am not sure why the new URLs are not working for you. In 1.2.6 we updated the URLs to match the [NVD Data Feeds](https://nvd.nist.gov/download.cfm#CVE_FEED) from NIST. In fact, several users had to upgrade because of problems with the original URLs.

I am assuming you correctly configured the proxy settings? I believe that we changed a few of the [command line arguments](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html) in 1.2.6+ (specifically, I believe the "short" argument name was removed on a few): 

| Argument | Parameter | Description |
| --- | --- | --- |
| --proxyserver | <server> | The proxy server to use when downloading resources. |
| --proxyport | <port> | The proxy port to use when downloading resources. |
| --proxypass | <pass> | The proxy password to use when downloading resources. |
| --proxyuser | <user> | The proxy username to use when downloading resources. |

Please let us know if this solved your problem. If not, please create a more detailed log file (using the --log argument or appropriate setting for Ant, Maven, etc.).

--Jeremy

**Comment by wmaintw** [comment]
Hi Jeremy, thanks for you reply.

We are using the latest maven plugin, and we resolved this problem by modify the `cveUrl20Modified` URL to use the original URL, so far so good. :)
