### ISSUE TITLE
Related Dependencies

### ISSUE THREAD

**Issue by dmhatre08** [dependency-check/DependencyCheck#2283]
How does OWASP dependency checker determines related dependencies in **dependency-check-report.xml**.

If a dependency is vulnerable with bunch of CVE, are all of its related dependencies also vulnerable? 

Example: in below mentioned snippet, dependency **'XYZ.jar'** is vulnerable. It has **'XYZ-related.jar** in related dependencies. Does that implies **XYZ-related.jar** is also vulnerable with same list of CVE which **XYZ.jar** has?

`<dependency isVirtual="false">
    <fileName>XYZ.jar</fileName>
    <relatedDependencies>
         <relatedDependency>
            <filePath>...../XYZ-related.jar</filePath>
         </relatedDependency>
    <vulnerabilities>
         <vulnerability>
            <vulnerability source="NVD"></vulnerability>
     </vulnerabilities>
  </dependency>`

**Comment by jeremylong** [comment]
It tries to do a best effort to collapse the related JARs - that would all be upgraded at once because they are related jars (i.e. they all have similar coordinates with the same version #). In some cases it is difficult to know exactly which component is vulnerable without research.

My best recommendation is upgrade them all.  In fact upgrade everything all the time.  Use automation to do this (such as dependabot).

**Comment by dmhatre08** [comment]
That helped. Thank you.
