### ISSUE TITLE
false positiv on com.springsource.javax.validation

### ISSUE THREAD

**Issue by ahi** [dependency-check/DependencyCheck#229]
Dependency Check identifies com.springsource.javax.validation as spring Framework 1.0.0 (it seems so that this version doesn't exist http://www.cvedetails.com/version-list/9664/17274/2/Springsource-Spring-Framework.html?sha=5c069faa228ea1cf109c75135f2c8428ee28106d&order=1&trc=65 )

The dependency informations:

``` xml
<fileName>com.springsource.javax.validation-1.0.0.GA.jar</fileName>
<filePath>E:\repository\javax\validation\com.springsource.javax.validation\1.0.0.GA\com.springsource.javax.validation-1.0.0.GA.jar</filePath>
```

Results in this identifiers:

``` xml
<identifiers>
    <identifier type="cpe" confidence="LOW">
        <name>(cpe:/a:springsource:spring_framework:1.0.0)</name>
    </identifier>
    <identifier type="cpe" confidence="LOW">
        <name>(cpe:/a:vmware:springsource_spring_framework:1.0.0)</name>
    </identifier>
    <identifier type="maven" confidence="LOW">
        <name>(javax.validation:validation-api:1.0.0.GA)</name>
    </identifier>
</identifiers>
```

Why is the confidence of the maven identifier LOW? It should be HIGH because that's the right identifier.

**Comment by jeremylong** [comment]
The confidence on the maven GAV has been increased to HIGH. My initial guess is that the scan was run on a machine that does not have access to the Internet or the Central Analyzer was disabled and a Nexus server was not specified?  If the sha1 hash is found in Central (or Nexus) then the confidence of the maven identifier should be reported as HIGHEST and a URL to the JAR file should also be provided.

Regarding why the non-existent CPE entries are being reported. Basically, the tool is making a best guess as to the CPE. It first tries to do fuzzy matching based on the product/vendor evidence collected from the JAR and matches it to the product/vendor from the CPE entries. If there is a product/vendor match then a CPE identifier will be recorded. If the version number doesn't exist the tool makes a guess at the CPE entry by using its highest confidence version information. By doing this, the tool still correctly identifies some CVE entries - however, it does also create false positives. The trade off between false positives and false negatives is a balancing act.

Much of what I have discussed above is documented in the following pages and I would recommend reading them if you have not:
- [Internet Access Required](https://github.com/jeremylong/DependencyCheck/blob/master/src/site/markdown/data/index.md)
- [How does dependency-check work?](https://jeremylong.github.io/DependencyCheck/general/internals.html)
- [How to read the report](https://jeremylong.github.io/DependencyCheck/general/thereport.html)
- [Suppressing False Positives](https://jeremylong.github.io/DependencyCheck/general/suppression.html)

**Comment by ahi** [comment]
Thanks for the explanation and for increasing maven GAV to HIGH. 
Now i tested it with the new version (and with a HIGH maven identifier). The result is the same, because dependency check searches for vulnerabilities for the LOW identifier to. 

Now i have two questions.
Is it possible to search for vulnerabilities only with a maven GAV?
Is there a configuration, that allows only searching for HIGH confidence (and LOW confidence only if there is not a HIGH confidence)?

**Comment by jeremylong** [comment]
Sorry for the delayed response, I've been on vacation.

1) It is not possible to reliably search for vulnerabilities only on a Maven GAV.
2) The way the tool works is it categorizes the evidence into vendor, product, and version buckets and rates the evidence from LOW to HIGHEST confidence. It starts with the highest confidence evidence and works its way down - if a CPE is identified by high confidence evidence then the confidence of the CPE identifier will also be high. Once a CPE has been identified the identification analysis stops (i.e. lower confidence evidence will not be used to identify the library). Make sense?

While I will take a closer look at this and try to adjust things for libraries in the spring family so that these false positives are reduced. That being said, what you can do locally for this is to create a suppression XML file (using the HTML report's suppress buttons) to suppress the specific CPE that is an incorrect match. This is a fairly simply process (see [Suppressing False Positives](https://jeremylong.github.io/DependencyCheck/general/suppression.html)) and should not take long when onboarding the dependency-check plugin into a new app.

**Comment by jeremylong** [comment]
I was looking for another thread that is related to this - but I cannot find it right now.  This appears to be an OSGI bundle - this is still one source of false positives. I have some thoughts on how to resolve this.

**Comment by jeremylong** [comment]
A patch has been added to remove the bundle vendor from the collected evidence. We will need to monitor this for false negatives as the bundle vendor is accurate in some cases (specifically many Spring libraries); however, in the case of the bundles of other libraries that are maintained by SpringSource the bundle-vendor is not accurate.
