### ISSUE TITLE
Does DependencyCheck check transitive dependencies

### ISSUE THREAD

**Issue by aschei** [dependency-check/DependencyCheck#2293]
The following case can be reproduced using this sandbox project: https://github.com/aschei/depchecktest

The project depends on `io.projectreactor.netty:reactor-netty:0.9.0.RELEASE` which in turn depends on `io.netty:netty-*:4.1.39.Final` (can be checked with `gradle -q dependencies`) which is vulnerable to CVE-2019-16869 according to https://nvd.nist.gov/vuln/detail/CVE-2019-16869, but not vulnerable to CVE-2015-2156, CVE-2014-3488.

`gradle dependencyCheckAnalyze` false positively reported CVE-2015-2156, CVE-2014-3488 additionally to CVE-2019-16869 because it undesirably matches reactor-netty to `cpe:2.3:a:netty:netty:0.9.0:*:*:*:*:*:*:*`.

Therefore I have excluded the undesired cpe match using 
```
    <suppress>
       <packageUrl regex="true">^pkg:maven/io\.projectreactor\.netty/reactor\-netty@.*$</packageUrl>
       <cpe>cpe:/a:netty:netty</cpe>
    </suppress>
```
Now, `gradle dependencyCheckAnalyze` false negatively succeeds and does not report CVE-2019-16869.

In my understanding the suppression should only suppress the library match itself and should not have any effect on dependent libraries. I suppose DepencyCheck processes transitive dependencies, so it should report CVE-2019-16869 here.

Is this a bug or what did I wrong?

**Comment by aikebah** [comment]
Neither.... 4.1.39 is not vulnerable according to the NVD vuln detail page classification

`cpe:2.3:a:netty:netty:*:*:*:*:*:*:*:*`     [Show Matching CPE(s)](https://nvd.nist.gov/vuln/detail/CVE-2019-16869/cpes?expandCpeRanges=true)  **Up to (excluding)4.1.36**

So this looks like a genuine mis-classification by the NIST analysis which leads to DependencyCheck not detecting it. See also [this comment](https://github.com/netty/netty/issues/9571#issuecomment-538966941) in the original bugreport that led to the CVE. As that comment was already 23 days ago I've sent an email not NIST to make sure that this gets their attention to be fixed in future updates of the NVD datafeeds.

As 0.9.0 is < 4.1.36 it was originally in your report for the netty-reactor project. But also at that time  not for the netty dependency itself.
You should be able to find the netty transitive dependency in your report when you click the link 'Showing Vulnerable Dependencies (click to show all)'.

**Comment by aikebah** [comment]
Received feedback from NIST NVD. Corrections have been made in the NVD listing and should appear within 24hrs in their datafeeds. The website already shows the updated entry, so I ran a local test with the maven-plugin (don't have gradle on my dev-box) but apparently the datafeeds are not yet re-published; updated datafeeds that allow DependencyCheck to properly detect the CVE should appear within 24 hours.

**Comment by aschei** [comment]
Yes, checked that too a minute ago with the same result. Thanks for caring!

**Comment by aikebah** [comment]
Thanks for reporting here which allowed me to investigate and notify the NIST to the benefit of all users of their NVD datafeeds.

**Comment by aschei** [comment]
Today, it's fixed. When suppressing the cpe for reactor-netty, it correctly reports CVE-2019-16869.
After upgrading to io.projectreactor.netty:reactor-netty:0.9.**1**.RELEASE which depends on netty 4.1.43, the report is green.
