### ISSUE TITLE
Dependency check v5.2.5 release date

### ISSUE THREAD

**Issue by Anshu2405** [dependency-check/DependencyCheck#2421]
We are looking forward to the next release of dependency-check i.e. v5.2.5. Can you please provide an approximate ETA when the version will be officially released?.

Thank you for your continuous support.

**Comment by jeremylong** [comment]
5.3.0 will be released in the next day or two.

**Comment by Anshu2405** [comment]
@jeremylong 
It would be helpful if you can give information about the changes going to be released as a part of v5.3.0. 
Is there any major change expected from new version?
Is there any plan to release v5.2.5 for only bug fixes?

**Comment by jeremylong** [comment]
More detailed releases notes can ussually be found in google groups: https://groups.google.com/forum/#!forum/dependency-check

We have also recently started tagging all issues with the milestone release. So you can look at all of the closed issues and PR within Github using the milestone version number.

We won't be release 5.2.5 - instead just releasing 5.3.0. Honestly, the only reason we are publishing 5.3.0 instead of 5.2.5 is that we have a new schema for the XML report and a new field in the JSON report to better report "unscored" vulnerabilities. There is no other change that would have caused us to increment the minor version.
