### ISSUE TITLE
[5.3.0] dependency-check-core contains commons-beanutils with CVE-2019-10086

### ISSUE THREAD

**Issue by albuch** [dependency-check/DependencyCheck#2449]
**Describe the bug**
dependency-check-core:5.3.0 contains vulnerable dependency commons-beanutils:1.9.2 for CVE-2019-10086 https://snyk.io/vuln/SNYK-JAVA-COMMONSBEANUTILS-460111 

See #2332  as well.

**Version of dependency-check used**
5.3.0 

**Log file**
See Snyk analysis: https://app.snyk.io/org/albuch/project/d94fb5ab-fc33-4437-a44b-103c4e384a3f/pr-check/38c9167e-72af-4e71-8d14-ce96ddaf7b76?refs=df99b5da901494b7ab3a0ebbb6e290e4ab226a45..628a9ee17e0c5c2a14e90046acca1e94bbe774bf 

**Expected behavior**
no vulnerable dependencies included

**Comment by mprins** [comment]
> dependency-check-core:5.3.0 contains vulnerable dependency commons-beanutils:1.9.2

your analysis is wrong, see: https://github.com/jeremylong/DependencyCheck/blob/1a31fad785a3b09a52bfa0ccb9c75029922c9cd3/pom.xml#L940-L944

check your dependency tree and report upstream

**Comment by albuch** [comment]
> your analysis is wrong, see: 

No it's not, as dependency-check-core does NOT include commons-beanutils explicitly in the fixed version it pulls it as a transitive dependency from commons-validator, which indeed contains the vulnerable version. See https://github.com/jeremylong/DependencyCheck/blob/master/core/pom.xml#L434

**Comment by jeremylong** [comment]
So here is the fun thing about transitive dependencies - you are both right.... depending on which component of ODC we are talking about.  5.3.0 does correctly upgrade beanutils for `cli`, `ant`, `maven`, `core`, etc.  You can see this by checking out 5.3.0 and running the following:

```bash
07:57 $ mvn dependency:copy-dependencies
...
07:56 $ find . -name "*beanutil*"
./ant/target/dependency/commons-beanutils-1.9.4.jar
./core/target/test-classes/commons-beanutils-1.9.4.jar
./core/target/dependency/commons-beanutils-1.9.4.jar
./maven/target/dependency/commons-beanutils-1.9.4.jar
./cli/target/dependency/commons-beanutils-1.9.4.jar
./cli/target/release/lib/commons-beanutils-1.9.4.jar
```

This is because as @mprins points out - we explicitly define that the build should use 1.9.4 in the dependency management section. As such, the core projects built within the maven build do correctly bundle 1.9.4 into the deployment.  Where this breaks down is when other builds depend on `core` (or any of the other jar files) - at this point the transitive dependencies are used as originally defined instead of the override in the maven dependency-management section. As such, this currently affects the gradle plugin, lien plugin, and sbt plugin (plus probably others that haven't explicitly upgraded beanutils).

To resolve the issue we will explicitly define the version of beanutils in `core` so that other uses of `core` will bring in the patched version of `beanutils`.
