### ISSUE TITLE
False Negative on Zookeeper

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#2465]
**Describe the bug**
```xml
<dependency>
    <groupId>org.apache.zookeeper</groupId>
    <artifactId>zookeeper</artifactId>
    <version>3.5.3-beta</version>
    <type>pom</type>
</dependency>
```

zookeeper-3.5.3-beta.jar is vulnerable as per NVD [CVE-2018-8012](https://nvd.nist.gov/vuln/detail/CVE-2018-8012) 
cpe : `cpe:2.3:a:apache:zookeeper:3.5.3:beta:*:*:*:*:*:*`
**Version of dependency-check used**
The problem occurs using version 5.0.0.M3 and 5.3.0 as well of the OWASP dependency checker

**Expected behavior**
This should be identified by tool as it is exact match of cpe mentioned in NVD

**Comment by jeremylong** [comment]
While there is an underlying bug - I would also contest that you do not actually have the server code in your build that is vulnerable. This is because of the dependency `<type>pom</type>`. If you remove this then the zookeeper JAR file (as opposed to just the transitive dependencies) would be included in the build and via the OSS Analyzer these findings are flagged.

See the `dependency:tree`:
```
[INFO] +- org.apache.zookeeper:zookeeper:pom:3.5.3-beta:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.5:compile
[INFO] |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  +- log4j:log4j:jar:1.2.17:compile
[INFO] |  \- io.netty:netty:jar:3.10.5.Final:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------
```

Only the POM is included in the build.
