### ISSUE TITLE
Interpreting missing CPEs

### ISSUE THREAD

**Issue by mr-duke** [dependency-check/DependencyCheck#2562]
Hello everybody,

for an important university project I need to use dependency-check.
After reading through your documentation thoroughly, I'm still not quite sure how to interpret missing CPEs in my report correctly.
I've got countless examples with high evidence counts, but with missing confidence-ratings and missing CPEs.

Now for my question: How shall I interpret those cases? As false positives or false negatives? Or is it that there are simply no publicly known vulnerabilites in the NVD for those maven dependencies? In that case shouldn't there at least be a CPE for every package?
(Also, why does dependency-check not analyze npm-packages although Node.js Analyzer is used?)

Thank you very much for your response and keep up the good work!

**Comment by jeremylong** [comment]
When a CPE is not identified it usually indicates that there are no-known vulnerabilities published in the NVD. There is not a registered CPE for everything. I would point out that in some cases there might be a false negative. If you haven't I would read https://jeremylong.github.io/DependencyCheck/general/internals.html, https://jeremylong.github.io/DependencyCheck/general/thereport.html, https://jeremylong.github.io/DependencyCheck/general/suppression.html, and https://jeremylong.github.io/DependencyCheck/general/hints.html.

The current support for node.js requires a package.json and package-lock.json.  would also recommend running `npm install` before running ODC.  Note that the current implementation is going to produce very similar results as just using `npm audit`.

**Comment by mr-duke** [comment]
@jeremylong Thank you! 
The main reason for my question was that I found this while reading https://jeremylong.github.io/DependencyCheck/general/hints.html :
> false negatives may occur (a CPE was NOT identified for a library).

So, I was wondering if a missing CPE would (always?) indicate a false negative or if there might be other reasons. 
If I got you correctly, you're saying a missing CPE usually tells me there are no publicly disclosed vulnerabilities. But to be absolutely sure I need to do a manual CPE dictionary search, right?

**Comment by jeremylong** [comment]
Correct.  I know of some companies that actually run 3 different SCA tools because they find that some do better on certain technologies vs others. Most security tools have false positives and false negatives. When you compare tools against each other you will see that they find a lot of the same items - but each will likely find something that the other missed and vs. versa. In the SCA space this will depend a lot (in the commercial space) upon the private vulnerability databases that each company has built, how they identify libraries, and whether your company builds-their-own-binaries - while somewhat rare some companies don't use the officially published binary and instead build the officially published source and place the binary into the internal repo. There is also the problem of shaded/uber jars, just including the source (or part of the source) for a library directly in the application, etc.

I'm more of the opinion today - worry less about SCA tools (you still need them) and instead just use automation to make sure you are using the latest version of the published libraries. Tools like dependabot are awesome for this. I did a talk a few years ago on the topic, "The (Application) Patching Manifesto": https://www.youtube.com/watch?v=qVVZrTRJ290

**Comment by mr-duke** [comment]
Thanks @jeremylong!  One last question before I can close this because I also need to do a rough analysis on how many false positives/negatives ODC produces for my project:

Dependency: neo4j-ogm-core-3.2.2.jar
CPE: cpe:2.3: a: neo4j:neo4j:3.2.2:*:*:*:*:*:*:*
Confidence : Highest
Evidence count: 27
**CVE Count: 0**

How would you interpret that? ODC is pretty sure the CPE is correct, however there are no CVEs for it. Would that be a false positive?

**Comment by jeremylong** [comment]
Rather then me doing your homework for you - I would recommend researching the NVD and see if you can find any vulnerabilities for that version of neo4j.  Now, what I might question is whether or not neo4j-ogm-core is really the same as neo4j.

**Comment by mr-duke** [comment]
No no @jeremylong  you don't have to do my homework ;) I already checked out the NVD before.
The crucial question for my test is (maybe it'll become clearer now)
_Existing CPE with high confidence + no corresponding CVEs -> false positive ?_
Is this conclusion correct? (If not, I wonder why there would be a CPE  then in the first place)

**Comment by jeremylong** [comment]
I'd ask what is a false positive? Is using the latest non-vulnerable version of a library a false positive? For instance:
```
pkg:maven/commons-beanutils/commons-beanutils@1.9.4
cpe:2.3:a:apache:commons_beanutils:1.9.4:*:*:*:*:*:*:* 
```
Was the correct CPE identified for the library?

What about:
```
pkg:maven/com.h3xstream.retirejs/retirejs-core@3.0.2
cpe:2.3:a:xstream_project:xstream:3.0.2:*:*:*:*:*:*:*
```
What about issue #2575?
