### ISSUE TITLE
False Positive on GoogleUtilities

### ISSUE THREAD

**Issue by sachinvas** [dependency-check/DependencyCheck#2575]
Hi,

I don't know how to check the CPE.
Can you please take a look at the experimental CocoaPods dependency check?

It is reporting a false positive in GoogleUtiilities - https://github.com/firebase/firebase-ios-sdk/issues/5113

**Comment by jeremylong** [comment]
See https://jeremylong.github.io/DependencyCheck/general/thereport.html

Does the library name match the CPE? When you look at the related vulnerabilities do they look like they are for the given library?

FP reports like this get very difficult for things like GoogleUtilities because the library is part of a much larger repo.

**Comment by jeremylong** [comment]
Also - the developers already answered your question.

**Comment by sachinvas** [comment]
@jeremylong  Yes the developers have answered the question related to the query.

However, this is a false positive bug. Are you going to fix the false positive?
