### ISSUE TITLE
About the odc.mc.db's size in different system 

### ISSUE THREAD

**Issue by wjcIvan** [dependency-check/DependencyCheck#2614]
Why the odc.mc.db's size has a large difference between Mac OS and centos?
In centos,is has about  180MB. 
In Mac OS,is has about 430MB. 
What makes the difference?

**Comment by aikebah** [comment]
Most likely due to more frequent updates on the Mac OS system... (unrecovered stale database space in the database storage file)
when I run 
mvn dependency-check:purge
which will get rid of my local data followed by an 
mvn verify
(which will run dependency-check maven plugin v5.3.2) among others on a local Mac OS system the result for the database is:

```
abu:4.0 aikebah$ ls -ltrh odc*
-rw-r--r--  1 aikebah  staff   130M Apr 27 13:47 odc.mv.db
```

**Comment by jeremylong** [comment]
ODC makes an attempt to compact the database by calling:
https://github.com/jeremylong/DependencyCheck/blob/9ef87be14638bbc97ce2400fa81957fd56a169d6/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/CveDB.java#L1496

As @aikebah  stated - the size difference is likely due to unrecovered database space.

**Comment by aikebah** [comment]
@jeremylong Looking at https://github.com/h2database/h2database/issues/301 we might get better compaction if we include RETENTION_TIME in the default h2 JDBC URL to for a value less than the default 45 seconds https://github.com/h2database/h2database/issues/301#issuecomment-506132787 as the SHUTDOWN DEFRAG is called much closer to the maintenance tasks that created stale items than 45 seconds.

**Comment by OrangeDog** [comment]
There may be a deeper problem here. Most of the time my DB is around 140MB, but occasionally something happens and the data directory suddenly (over ~15 minutes) fills the whole disk and breaks. Last time it got up to 5GB.

Edit: this sounds like #2598
