### ISSUE TITLE
False positive: Tomcat

### ISSUE THREAD

**Issue by MrT2** [dependency-check/DependencyCheck#262]
Hi,

I 'm getting CVE-2011-3190 and CVE-2014-0230 based on the presence of tomcat-juli-7.0.62.jar

But https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2011-3190 and http://nvd.nist.gov/nvd.cfm?cvename=CVE-2014-0230 tells me that this version in not vulnerable.

**Comment by jeremylong** [comment]
What version of dependency-check are you using? There was a bug previously reported similar to this that has been resolved (issue #180).

--Jeremy

**Comment by MrT2** [comment]
Version 1.2.11
The issue you mentioned is similar, but the problem isn't a  "and all previous versions" statement in the NVD details. The used tomcat version is just not listed. Could it be that term "juli" in the filename  triggers the false-positive?

**Comment by jeremylong** [comment]
The issue is the specification version in the manifest. This creates a false positive for cpe:/a:apache:tomcat:7.0.0. I've seen the specification version cause false positives like this before. I am working on a better solution for this. Possibly only use the specification version as evidence if the implementation version is missing.

**Comment by jeremylong** [comment]
A patch was committed to 1.2.12-SNAPSHOT to resolve the incorrect matching of tomcat 7.0.0. Now the only CVE entries that appear for tomcat-juli-7.0.62.jar are those in the NVD CVE listing that do not specify a version number (i.e. cpe:/a:apache:tomcat).
