### ISSUE TITLE
Looking for local copy of NVD

### ISSUE THREAD

**Issue by mr-duke** [dependency-check/DependencyCheck#2632]
> OWASP dependency-check maintains a local copy of the NVD CVE data hosted by NIST. 

My idea is to take that local copy and include it in a Docker image which I could then use for jobs in my CI-pipeline. Otherwise, all the files would have to be downloaded for every new pipeline. (Mirroring of the NVD is not possible for several reasons)
So my question is: Does this make sense and if so, where exactly does dependency-check store the local copy of the NVD ?

**Comment by mprins** [comment]
the maven plugin stores this in a h2 database in <M2 REPO>/org/owasp/dependency-check-data/4.0

**Comment by jeremylong** [comment]
You can control the location of the data directory. It is one of the configurable parameters (also, the default location should be listed in the documentation): 
* cli: `--data <path>`: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html
* maven: `<dataDirectory>`: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

See the documentation for gradle, ant, etc.

**Comment by mr-duke** [comment]
I managed to pack the NVD into a Docker image. 
However, whenever I use that image in my CI-pipeline, all the files are downloaded _again_, although I used <dataDirectory> and the right path to the directory in my project's pom.
What am I missing?

**Comment by jeremylong** [comment]
The output from ODC might say "downloading" - but that just is indicating it is retrieving the file from the specified location and processing it.

**Comment by aikebah** [comment]
When you don't want to download the NIST NVD datafeeds you should make sure that the database pointed to by dataDirectory within your image is up-to-date (last updated less than `cveValidForHours` hours ago) or disable the autoUpdate (override the autoUpdate configuration property for the Maven plugin). 

**_NOTE: the second option would mean that you will NEVER receive updates until you regenerate your database, the former will mean that if you forget to update your container image in time your builds will start downloading datafeeds again for every build if NVD metadata shows that changes have occurred since the last update of your CVE database._**

A better solution, if possible in your environment, might be to host the cve-data in a separate database server accessible from your docker containers, point the dependencycheck configuration in your poms to that central database with the autoUpdate switched off and periodically (e.g. every 4 hours) run dependencycheck with the updateOnly flag to update your central database of cached NVD vulnerability data.
See also https://jeremylong.github.io/DependencyCheck/data/database.html
