### ISSUE TITLE
Gradle plugin and cli versions give different results

### ISSUE THREAD

**Issue by vvanag** [dependency-check/DependencyCheck#2639]
I run the latest dependency-check cli and I get a report (on a folder with jars)

`cxf-core-3.1.10.jar` | `cpe:2.3:a:apache:cxf:3.1.10:*:*:*:*:*:*:*` | `pkg:maven/org.apache.cxf/cxf-core@3.1.10` | HIGH | 7 | Highest | 41
-- | -- | -- | -- | -- | -- | --
`spring-security-core-3.2.6.RELEASE.jar` | `cpe:2.3:a:vmware:springsource_spring_security:3.2.6:release:*:*:*:*:*:*` | `pkg:maven/org.springframework.security/spring-security-core@3.2.6.RELEASE` | HIGH | 3 | Low | 36

If I scan again with latest gradle dependency check plugin 5.3.2.1 I see

`dc.war: cxf-core-3.1.10.jar` | `cpe:2.3:a:apache:cxf:3.1.10:*:*:*:*:*:*:*` | `pkg:maven/org.apache.cxf/cxf-core@3.1.10` | HIGH | 7 | Highest | 41
-- | -- | -- | -- | -- | -- | --
`dc.war: groovy-all-2.4.17.jar` | `cpe:2.3:a:apache:groovy:2.4.17:*:*:*:*:*:*:*` |   | HIGH | 1 | Highest | 27

To give more context the second is on a war and the first is on the WEB-INF/lib folder of the war after unarchiving. 

In another case, we see diffence in evidence count for the same vulnerability

**Comment by jeremylong** [comment]
We would need a bit more information to explain the results. Specifically, the build files (build.gradle) so we can replicate the package management side of the build.

The difference in the evidence count is that the CLI will generally be lower then using one of the build plugins because information can be obtained from the build system itself - this is why in general the build plugins are more accurate.

**Comment by vvanag** [comment]
I will try to narrow it down because of sensitive business data.

**Comment by vvanag** [comment]
I reproduced in a public project what I do. The vulnerable dependencies differ

https://github.com/fithisux/grails-dc

**Comment by jeremylong** [comment]
@vvanag sorry about the delayed response on the ticket. I finally had a chance to test the provided project. These are actually expected results. The differences are from the fact that we are scanning different things. If you build the application and then you want to scan with the CLI you should just scan the deployable artifacts (in this case the WAR). However, instead of using the CLI I would highly recommend that you using the build plugin instead of the CLI. In general the build plugin will be more accurate.
