### ISSUE TITLE
False positives for tomcat-jdbc

### ISSUE THREAD

**Issue by scrain** [dependency-check/DependencyCheck#266]
Dependency Check version: 1.2.11

Tomcat JDBC library is being used for connection pooling, etc as part of several grails projects in our organization and is being mis-identified as the tomcat container.  I've worked around using a suppression file, but thought I would pass along.

GAV:   org.apache.tomcat, tomcat-jdbc, 7.0.50.
SHA1: 3abdaedb1f190607b50ebfc5945231cab173e89a
CVEs: CVE-2002-0493, CVE-2007-5461, CVE-2009-2696, CVE-2013-0346, CVE-2013-2185, 
           CVE-2013-4322, CVE-2013-4590, CVE-2014-0050, CVE-2014-0075, CVE-2014-0096, 
           CVE-2014-0099, CVE-2014-0119, CVE-2014-0227, CVE-2014-0230, CVE-2014-7810

Thanks,

Shawn

**Comment by jeremylong** [comment]
Unfortunately, this is somewhat how dependency-check is supposed to function. While this may not be an issue for your specific application it can indicate a problem in the environment (i.e. your production Tomcat is using an older version). The problem is individual applications may not be kept in sync with the production version (with regards to point releases) and in addition, the application teams may have no control over the point release on the servers because a separate team may own this activity. Thus, this appears to be a false positive.

This issue crops up for most containers and database drivers. I have added issue #265 so that users can just blanket suppress container and database server related findings (Tomcat, WebSphere, Oracle, MySQL, etc.).
