### ISSUE TITLE
How do I scan my iOS Swift repository which contains Podfile.lock and Package.resolved files?

### ISSUE THREAD

**Issue by SubParDev** [dependency-check/DependencyCheck#2660]
I'm trying to run this command: 
`dependency-check --enableExperimental --project ProjectName --out . --scan path_to_project` 

In OSX Terminal but the only dependencies being scanned are the node_modules. How can I scan the pods and the package manager? When I've tried to scan them individually with:
`dependency-check --enableExperimental --project ProjectName --out . --scan path_to_project/Podfile.lock`
and
`dependency-check --enableExperimental --project ProjectName --out . --scan path_to_project/Package.resolved`

respectively, the report shows that 0 dependencies were scanned.

**Comment by mprins** [comment]
As stated in the documentation the swift scanner scans Package.swift so that is what you need.
See https://jeremylong.github.io/DependencyCheck/analyzers/swift.html

**Comment by jeremylong** [comment]
The Coacoa Pods analyzer does appear to scan Podfile.lock per
https://jeremylong.github.io/DependencyCheck/analyzers/cocoapods.html

However, this was code provided via PR. The podfile.lock may be different
or may have been updated since this code was contributed.  This is an
experimental analyzer.  Can you add `--log odc.log` to the execution and
see if there are any errors in the log?

--Jeremy
