### ISSUE TITLE
When will .NET (dotnet) Core 3.1 support be released?

### ISSUE THREAD

**Issue by stevehipwell** [dependency-check/DependencyCheck#2759]
When will the code committed in PR #2574 to solve issues #2155 & #1464 be released? The original comments suggested that this would be released in _v3.4_ but it now looks like we're waiting for _v6_?

**Comment by jeremylong** [comment]
Correct, this will be part of the 6.0.0 release. We decided that some breaking changes needed to be made to resolve a long standing performance issue and resolve a handful of issues - and rather then have multiple breaking releases we are trying to wrap them all up into the 6.0.0 release.  The good news is we are close; the bad news is due to other commitments my time to work on the project has dwindled.  The tasks left for 6.0.0 are:

1. Update the XML and JSON reports to output the additional CVSS information per #2547 - the changes have already been implemented to import in the extra data so finishing this up should be fairly quick.
2. In order for Oracle, Postgresql, and MSSQL [external databases](https://jeremylong.github.io/DependencyCheck/data/database.html) to be available options with 6.0.0 we need help with #2755, #2754, and #2753.
