### ISSUE TITLE
dependency-check-data still over 200MB

### ISSUE THREAD

**Issue by hgomez** [dependency-check/DependencyCheck#28]
We had discussion about CVE/CPE storage size on mailing list.
I did a fresh build in Jenkins, using DC Jenkins Plugin 1.0.3, cleaning workspace and noticed dependency-check-data database is still huge, more than 200MB.

Is it a normal behaviour ?

```
227M    dependency-check-data/cve
 1,6M   dependency-check-data/cpe  
 228M   dependency-check-data/
```

This could be a show stopper for us as we have tons of jobs running on many Jenkins slaves, some created dynamically and with limited storage allocated

**Comment by jeremylong** [comment]
An earlier comment you may have seen about the 50mb size I realize now was in error. A zip of the data directory is under 50mb; however, the uncompressed version of the data store is currently ~230mb.

I am working on a way to use the same data directory for multiple instances/jobs. But at the moment each instance requires a full copy of the data.

Steve - another way we might solve the data problem would be to have an agent that would collect the evidence and then send the collection to your dependency-track for analysis.

To finalize the answer to the bu report - yes, this is expected behavior and efforts to solve this problem are under different tickets.
