### ISSUE TITLE
CVE Source for Dependency Check

### ISSUE THREAD

**Issue by ParthibanSG** [dependency-check/DependencyCheck#2857]
I am using Dependency Check (5.3.2) via Jenkins and have mirrored NVD CVE's to our Artifactory instance. I specify the artifactory URL via parameters (cveBase and cveURLModified) and I would like to know whether I can use only NVD data source to parse and find the vulnerabilities or is it possible to define other vulnerability data sources like OSS Sonatype Index, NPM, Ruby etc

I did use Dependency Track as well which provided options for data sources for NVD, OSS Index, etc and I am trying to achieve the same via Dependency Check now. Could you please let me know if its possible or did I understand Dependency Check functionality wrongly?

**Comment by mprins** [comment]
most of those are built-in and switched on by default, check the docs: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html specifically the advanced options.

Als please use a current, supported version like 6.0.2

**Comment by jeremylong** [comment]
OSS Index is an external analysis that you can't cache locally.
If you are scanning ruby - we do wrap `bundle-audit` so you'll likely want to run `bundle-audit update` from time to time.
You can cache the Retire.JS file locally (see the documentation mentioned above).
ODC also currently uses the same web api as `npm audit` - so that cannot be cached locally (yet)
