### ISSUE TITLE
Mirror support

### ISSUE THREAD

**Issue by hgomez** [dependency-check/DependencyCheck#29]
CVE/CPE fetch for NIST are pretty huge and could take long to be downloaded.
For security and reproductibility reasons, we'd like to use an internal mirror.

Questions
- Is it possible to mirror using curl/wget/rsync, NIST CVE/CPE contents ?
- If so, would it be possible to told Dependency Check and its Jenkins Plugin to use local HTTP mirror ?

Thanks

**Comment by stevespringett** [comment]
When Dependency-Check is used in combination with Dependency-Track, yes,
you will be able to mirror NIST data. A future version of Dependency-Check
will support this (hopefully the next release). Dependency-Track already
supports this use case and the DATA directory can simply be downloaded by
specifying the following URL to a Dependency-Track installation.

Once Dependency-Check fully supports this, the Jenkins plugin will be
updated to allow for the plugin's global configuration of the local mirror.
It's basically a pre-processed data directory in a zip archive.

http://hosthame/dtrack/dcdata

**Comment by hgomez** [comment]
Dependency-Check will mandate use of Dependency-Track to support an internal mirror ?

**Comment by stevespringett** [comment]
It's not necessary, but it makes it easier since the data directory has
already been pre fetched, indexed and the database created. So it's more
than just a mirror. But no, you can easily do the same thing manually, it
just takes more work. We're also working on a way to distribute (freely)
the data dir on the internet as well. But this doesn't solve the firewall
issue.

**Comment by hgomez** [comment]
That's why I was wondering if DC could make use of internally fetch CPE/CVE XML files 

http://nvd.nist.gov/download.cfm#CVE_FEED reference many CVE/CPE files and they could be easily mirrored internaly into a location where DC could check them. 

dependencycheck.properties contains a bunch of URLs to be downloaded so I guess it should be overridable by configuration, hacking dependencycheck.properties won't be a clean solution.

What do you think ?

**Comment by stevespringett** [comment]
Yes, I believe that use case already works. Jeremy may have to clarify as I
have not tested this.

**Comment by hgomez** [comment]
Thanks, it will be very helpfull, and not so complex I guess

I found here, in GitHub, another tool using CVE/CPE, Python/MongoDB based - https://github.com/wimremes/cve-search.

Interesting approach as using MongoDB bring NoSQL approach and allow concurrent access.

Any plan to use NoSQL backend ?

**Comment by jeremylong** [comment]
To answer your question - yes, the properties file can be updated to point to a different URL. This is done by setting the following properties:

# the path to the modified nvd cve xml file.
cve.url-1.2.modified=http://nvd.nist.gov/download/nvdcve-modified.xml
cve.url-2.0.modified=http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-modified.xml
cve.startyear=2002
cve.url-2.0.base=http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-%d.xml
cve.url-1.2.base=http://nvd.nist.gov/download/nvdcve-%d.xml

These can be set as environment/system variables or by hacking the properties file. These URLs can be changed to file:/// if needed (however, FTP is currently not supported).

The base mechanism to provide a path to an external properties file was built in the core, but I just realized I never exposed it through the CLI, Maven, or Ant interfaces (and as such, it never made it into Jenkins). I'll correct that shortly. In the meantime, you could set these as environment/system variables and the core engine will use those values instead of whats in the properties file.

**Comment by hgomez** [comment]
If I could override default values by -Dcve.url-2.0.base=http://myveryownmirrors/feeds/xml/cve/nvdcve-2.0-%d.xml or by defining cve.url-2.0.base as en environment variable, it should be fine.

**Comment by jeremylong** [comment]
Oh, just realized I forgot to answer the question about NoSQL backend. In
reality, it is using two backend databases. One is a traditional SQL
database, and you could setup all instances to use the same database
server. However, the other database is a lucene index (so, yes it is using
NoSQL). The lucene index is used for fuzzy matching of evidence from the
JAR files to identify the correct CPE. Unfortunately, this can't be run in
a "server" mode (yes, solr is available but I don't think it would be easy
to get this setup with the custom analyzers etc.). Anyway, an update is in
progress to utilize locking so that a single data directory can be used by
multiple instances.

--Jeremy

**Comment by hgomez** [comment]
Hi Jeremy

About Lucene and locking, will it be to prevent concurrent instances to update it at same time or also from concurrent read access ?

Locking for concurrent update/write accesses is OK, but locking for read accesses (ie without update CVE/CPE databases) will be a show stopper for us.

Thanks

**Comment by jeremylong** [comment]
The locking would only be for the update. However, after thinking about the
problem more and reading some threads on the lucene mailing list - I may
have come up with a new update scheme that shouldn't require the locking
and will make it possible to just utilize a single shared database for all
instances. I can't promise anything yet as I need to do some testing.

Also, I am about to push 1.0.4 which includes the ability to turn on more
verbose logging (to see if we can track down the NPE in the Jenkins plugin).

--Jeremy

**Comment by hgomez** [comment]
Thanks for 1.0.4 to track NPE

Did you plan to add a way to override cve urls in properties from the outside ?
It will be required for our planned usage of Dependency Check Jenkins Plugin (who should also allow this).

Cheers

**Comment by stevespringett** [comment]
Henri,

It was planned for 1.0.4 but the code had to be removed in order to get
1.0.4 released on time. I'll be adding it back into the next release.
Possibly a 1.0.4.1 release depending on the timing of 1.0.5.

--Steve

**Comment by hgomez** [comment]
Cool.

Thanks guys, I'll take a look to 1.0.4 but 1.0.5 with mirrors URL overridable in Jenkins Plugin is my target.

**Comment by hgomez** [comment]
More on properties overrided in Jenkins Plugin.
- https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/dependencycheck.properties

There are many properties to be defined / overrided, and they may change in future releases

Providing all of them of environment will be a bit painfull, especially when you have hundred of jobs registered in Jenkins.

That's why it would be nice to have Jenkins Plugin define a single alternate URL for http://nvd.nist.gov and http://static.nvd.nist.gov, ie, http://mysys.mycorp.org/nistmirror/.

mirroring task should just ensure that layout is preserved aka : 
- http://mysys.mycorp.org/nistmirror/feeds/xml/cve/
- http://mysys.mycorp.org/nistmirror/download/
- http://mysys.mycorp.org/nistmirror/feeds/xml/cpe/dictionary/*

Steven and you mentioned using Dependency Track to avoid mirroring but in many organisations/companies, Dev or CI guys won't have choice and will have to stick with simple mirroring instead

**Comment by stevespringett** [comment]
Henri,

The Jenkins plugin has a global setting that allows a user to specify one
of two types of data mirroring options.

1) Using a data archive
2) Overriding the NIST URLs

Since it's a global option, you'll only need to specify the settings in one
place, not on a per-build basis. The settings will continue to work
regardless of how they're implemented in dependency-check-core.

For option 2, you'll need to specify all four URLs, since they provide
different services in different formats and have different URL constructs.
But again, you'll only have to specify them on time.

This enhancement will be included in v1.0.4.1 or 1.0.5 of the Jenkins
plugin, whichever comes first. A partial implementation is already in the
trunk. I plan on completing this work next week.

--Steve

**Comment by hgomez** [comment]
Good news.

I'll try them as soon as available, we have tons of jobs to test with such settings :)

**Comment by stevespringett** [comment]
Henri,

The Jenkins plugin now supports NIST CPE/CVE data mirrors. The configuration is global and can be made on the Jenkins Configuration screen. The master and all jenkins slave nodes will use the mirrors you specify. 

v1.0.4.1 was just pushed to Jenkins-ci.org and should be available later today. Additionally, I have published a simple command-line tool that can be used to mirror NIST CPE/CVE data. It's freely available at: https://github.com/stevespringett/nist-data-mirror . Also, the Dependency-Track trunk now has this functionality built-in and refreshes the NIST data every 24 hours.

**Comment by hgomez** [comment]
Very good news.

I'll test it asap.

Thanks Steve

**Comment by hgomez** [comment]
NIST data seems to hosted on IIS and sadly didn't activate compression : 

```
* Adding handle: conn: 0x1474f20
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x1474f20) send_pipe: 1, recv_pipe: 0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to static.nvd.nist.gov port 80 (#0)
*   Trying 129.6.13.18...
* Connected to static.nvd.nist.gov (129.6.13.18) port 80 (#0)
> GET /feeds/xml/cve/nvdcve-2.0-modified.xml HTTP/1.1
> User-Agent: curl/7.32.0
> Host: static.nvd.nist.gov
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 200 OK
< Content-Type: text/xml
< Last-Modified: Wed, 13 Nov 2013 06:00:51 GMT
< Accept-Ranges: bytes
< ETag: "b8a6e6b435e0ce1:0"
* Server Microsoft-IIS/7.5 is not blacklisted
< Server: Microsoft-IIS/7.5
< X-Powered-By: ASP.NET
< X-Frame-Options: SAMEORIGIN
< Date: Wed, 13 Nov 2013 10:21:48 GMT
< Content-Length: 2269594
< 
{ [data not shown]
100 2216k  100 2216k    0     0   302k      0  0:00:07  0:00:07 --:--:--  259k
* Connection #0 to host static.nvd.nist.gov left intact
```

Weird when hosting MB of XML contents ;(

**Comment by jeremylong** [comment]
Mirrors of the NVD are supported; this issue is being closed.
