### ISSUE TITLE
Consider breaking up the repository

### ISSUE THREAD

**Issue by willis7** [dependency-check/DependencyCheck#291]
The clone times on the repo are a little high. This may be an indication it's a good time to slice up the repository.

I'm particularly interested in helping with the development of the Gradle plugin, and I think this can be separated easily as no hard dependencies are present (dependencies are taken from maven central).

This can be done fairly easily with the `git subree` command. See:
[Detach subdirectory into separate Git repository](http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/17864475#17864475)

**Comment by jeremylong** [comment]
The clone times are high due to some test resources that are used by almost all of the modules. I have recently cleaned up the repo's history and I have also documented a shallow clone in issue #283.

I prefer to keep all of the modules together and release them all as a single release using the same version number. If a module (the CLI, Maven, or Ant task) has a minor bug that needs to be fixed that doesn't involve modification to the core we just release that by adding an additional revision number: 1.2.11.1. Once the gradle plugin is a little more complete my intent would be to use the same numbering sequence as the other modules.

I have no plans to split the repo up (yet).

--Jeremy
