### ISSUE TITLE
Research issue with Dependency#hashCode

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck#293]
A bug was reported on the mailing list that we need to confirm:

https://groups.google.com/forum/?fromgroups=#!topic/dependency-check/VjW9Er7TzYI

--Jeremy

**Comment by sellersj** [comment]
Tested again with version 1.3.0 and the problem is still there.

My guess is that there is some circular dependency that only shows up when the cli script is run against everything on our CI server.

I've "fixed" it by commenting out the use of "relatedDependencies" in org.owasp.dependencycheck.dependency.Dependency hashcode / equals to break the loop.

Are relatedDependencies really needed to determine a hashcode or equality of a dependency? I would have thought that the actualFilePath and / or md5sum would be enough.

**Comment by jeremylong** [comment]
A patch to remove the related dependencies from both equals and hashCode has been committed to master. While in my opinion this is not the best solution it does work. Related dependencies aren't really needed in these methods. However, the bigger issue is why are there circular dependencies? Or are there just so many JAR files in your report that the O(N^N) (or maybe its worse then that) loop would hang for an hour or more appearing to be in an endless loop. 

Regardless, a patch that resolves the issue will be included in the next release.

**Comment by sellersj** [comment]
Thank you for applying the fix, even though it's not the best solution.

The script is being run against all the different projects so that
1) all project didn't have to update their maven config (at the time)
2) provide a view across all projects where the security issues were
3) to quickly get this info for all projects, from a centrally controlled script

This clearly was a stop-gap solution. I would prefer to have a bamboo plugin, similar to the jenkins one, but have not had any time to work on it.

Thanks again for your hard work and for accommodating a non-optimal solution.
