### ISSUE TITLE
False Positive on any artifact with an ID or group ID that contains the name of a vulnerable library

### ISSUE THREAD

**Issue by mikaelcarlstedt** [dependency-check/DependencyCheck#2995]
Looks like something has happened to the library pattern matching recently.

Example:

False positive CVE-2005-2311 on one of our internal library dependencies - reported as `cpe:2.3:a:sms:sms:0.1.0:snapshot:*:*:*:*:*:*`

```xml
<dependency>
  <groupId>com.sinch.sms</groupId>
  <artifactId>msisdn-validation-management-api</artifactId>
  <version>0.1.0-SNAPSHOT</version>
</dependency>
```

Same thing with another internal library named ha-scheduled-message-grpc, which was reported to contain an old vulnerability in GRPC library from 2017.

**Comment by gbloggs** [comment]
Is this related or should I raise another bug?

Tried against v 6.0.3 and 6.0.2 fails with both.
Gradle v 6.7.1
Spring Boot 2.3.6.RELEASE brings in micrometer-core which is failing with:

micrometer-core-1.5.7.jar (pkg:maven/io.micrometer/micrometer-core@1.5.7, cpe:2.3:a:vmware:ace:1.5.7:*:*:*:*:*:*:*, cpe:2.3:a:vmware:vmware_ace:1.5.7:*:*:*:*:*:*:*) : CVE-2008-1392, CVE-2009-0177, CVE-2009-0908, CVE-2009-1146, CVE-2009-1147, CVE-2009-1244, CVE-2009-1805

**Comment by theHilikus** [comment]
Not sure if this is the same issue but we also noticed recent builds crashing (on Dec1 things were building, on Dec2 things started crashing) due to old CVEs, including GRPC libraries with CVEs from 2017
```
[ERROR] opencensus-contrib-grpc-util-0.24.0.jar: CVE-2017-8359, CVE-2017-7861, CVE-2017-9431, CVE-2017-7860
[ERROR] proto-google-cloud-firestore-v1beta1-0.88.1.jar: CVE-2017-8359, CVE-2017-7861, CVE-2017-9431, CVE-2017-7860
[ERROR] proto-google-cloud-logging-v2-0.84.2.jar: CVE-2017-8359, CVE-2017-7861, CVE-2017-9431, CVE-2017-7860
[ERROR] proto-google-iam-v1-0.13.0.jar: CVE-2017-8359, CVE-2017-7861, CVE-2017-9431, CVE-2017-7860
[ERROR] 
[ERROR] See the dependency-check report for more details.
```

**Comment by mikaelcarlstedt** [comment]
@theHilikus That first filename containing grpc indicates it's the same issue.

**Comment by stevehipwell** [comment]
@jeremylong are you seeing this as an issue or expected behaviour?

**Comment by jeremylong** [comment]
@stevehipwell this is expected behavior.  See [How dependency-check works](https://jeremylong.github.io/DependencyCheck/general/internals.html). I've cleaned up the ones I could - a better solution for grpc is likely needed.

**Comment by stevehipwell** [comment]
@jeremylong I've read how this works but I'm unsure as to if the expected behaviour is for a lib whos name contains another lib name to be identified as this often unrelated lib. For example unless a postgres driver has a version over 9.x it's constantly flagged as vulnerable against postgres. The most common ones are things like grpc, json, xml, etc.

**Comment by jeremylong** [comment]
expected behavior - use suppression rules.

**Comment by Chr1stian** [comment]
@jeremylong What is a good way to write a suppression rule that ignores the warnings related to grpc version, but still will warn about any new OWASP positives for the given package/dependency?

My current attempt after reading the docs/wiki, but really unsure if it works as intended:
```
<suppress>
        <notes><![CDATA[
        This suppresses false positives identified on gRPC security. https://github.com/jeremylong/DependencyCheck/issues/2995
        ]]></notes>
        <packageUrl regex="true">^pkg:maven/com\.lightbend\.akka\.grpc/akka\-grpc\-runtime_2\.13@.*$</packageUrl>
        <cpe>cpe:/a:akka:akka</cpe>
        <cpe>cpe:/a:grpc:grpc</cpe>
        <cpe>cpe:/a:lightbend:akka</cpe>
        <cpe>cpe:/a:lightbend:akka-http</cpe>
        <cpe>cpe:/a:lightbend:akka_http</cpe>
    </suppress>
```

**Comment by FyiurAmron** [comment]
@jeremylong 4 years later, I still don't understand how this can actually be considered "expected" behaviour. Why, instead of using suppression rules, not handle those CPE co-ords the other way around? Instead of flagging every package that has a matching substring as vulnerable, at least provide a required maven package group for the matching to work against maven artifacts in Java ecosystems? Those group are well-known and basically unchanging, and I don't see how that would harm the users, which currently need to use suppressions to opt out of completely bogus notifications.

**Comment by FyiurAmron** [comment]
@Chr1stian & @mikaelcarlstedt

Looking at the suppressions, I see that we simply need:

```
    <suppress base="true">
        <notes><![CDATA[
        FPs from #2995 (grpc)
        ]]></notes>
        <packageUrl regex="true">^pkg:maven\/(?!io.grpc\/).*$</packageUrl>
        <cpe>cpe:/a:grpc:grpc</cpe>
    </suppress>
    <suppress base="true">
        <notes><![CDATA[
        FPs from #2995 (sms)
        ]]></notes>
        <packageUrl regex="true">^pkg:maven\/.*$</packageUrl>
        <cpe>cpe:/a:sms:sms</cpe>
    </suppress>
```
note for `sms` - that one is due to https://bugs.gentoo.org/97187 ; it's 20 years old and no maven package exists that physically can have it, thus an umbrella suppression for `pkg:maven` can be added.

BTW this pattern (negative regex) has been used some times already ( [here](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck-base-suppression.xml#L2775) , [here](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck-base-suppression.xml#L2882) , [here](https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck-base-suppression.xml#L3643) etc. etc.)

I created #7250 & #7251 for reference, though I see the CI bot chokes on FP reports created with regexes :}
