### ISSUE TITLE
JSON Output Report Yields Invalid JSON (Truncated) In v6.0.3 and 6.0.4-SNAPSHOT

### ISSUE THREAD

**Issue by MarkAMartin** [dependency-check/DependencyCheck#3009]
The JSON output report is resulting in a truncated file that is not valid JSON.  Behavior began in v6.0.3 and persists in 6.0.4-SNAPSHOT. v6.0.2 will create a non-truncated file that is valid JSON.

**Comment by jeremylong** [comment]
Appears to only be a problem if using the prettyPrint feature. Apparently someone forgot to flush the output stream (and by someone - that was likely me).

**Comment by MarkAMartin** [comment]
Thank you!  I do use the prettyPrint feature.

**Comment by jody-mcdonnell** [comment]
Is it possible that this issue persists into version 6.1.0? We are calling the maven plugin directly from our maven command line in Jenkins--and thus we're always on the latest released version--and we just started having all of our Spring Boot builds fail with a JSONParseError:

09:48:43  [ERROR] Failed to execute goal [32morg.owasp:dependency-check-maven:6.1.0:aggregate[m [1m(default-cli)[m on project [36mmatchengine-jsb-svc[m: [1;31mOne or more exceptions occurred during dependency-check analysis[m: One or more exceptions occurred during analysis:
09:48:43  [ERROR]      ReportException: Error generating the report for matchengine-jsb-svc
09:48:43  [ERROR]              caused by ReportException: Unable to generate json report
09:48:43  [ERROR]              caused by JsonParseException: Unexpected character (',' (code 44)): expected a value
09:48:43  [ERROR]  at [Source: (FileInputStream); line: 1, column: 81259]

Like @MarkAMartin we also have -DprettyPrint=true on our command line.

**Comment by jody-mcdonnell** [comment]
Update - we removed -DprettyPrint=true from the Maven command line in our Jenkins build pipeline and the problem went away. We didn't really need this option--we just want the JSON file to be consumed by the SonarQube ODC plugin (which works).

Not sure what was causing this--either an issue in the ODC plugin or a problem with some CVE data--but it does _not_ happen when specifying ODC plugin version 6.0.4 on the command line with the pretty print option enabled. 

Since an equivalent path to a successful build was to simply remove the pretty print option from the command line, we chose that option.
