### ISSUE TITLE
False Positive on Quarkus

### ISSUE THREAD

**Issue by sberyozkin** [dependency-check/DependencyCheck#3270]
Quarkus (registered in NVD as `quarkus:quarkus`) `1.12.0.Final` depends on:

```xml
<dependency>
   <groupId>io.quarkus</groupId>
   <artifactId>quarkus-security</artifactId>
   <version>1.1.3.Final</version>
</dependency>
```

(Note we also have `io.quarkus/quarkus-http` and `io.quarkus/gizmo` Maven dependencies - these are registered in NVD as `quarkus:quarkus-http` and `quarkus:gizmo`)

Before `quarkus-security` has been registered in NVD, we were seeing `quarkus-security:1.1.3.Final` matching [CVE-2017-18640](https://nvd.nist.gov/vuln/detail/CVE-2017-18640) - which was opened before Quarkus projtect has been created.

After registering it as `quarkus:quarkus-security` in NVD we have started seeing it matching the main `quarkus:quarkus` CPE:

https://github.com/quarkusio/quarkus/issues/2611#issuecomment-804060800 

Please see  https://github.com/quarkusio/quarkus/issues/2611 for more information.

**Comment by nhumblot** [comment]
Hi @sberyozkin :wave: 

I looked at your request, and the links you provided. Thank you for all this information! If I understand correctly, you want all quarkus packages with the following group ids:
* `io.quarkus.security`
* `io.quarkus.http`
* `io.quarkus.gizmo`

not being attached to CPE `quarkus:quarkus` because they have their own. Am I right? This is what I am looking from the NVD website.

I have prepared a commit following this rule. I will wait for your confirmation before opening a PR to be sure I'm not going to submit an undesired configuration.

Please correct me if I'm wrong. I will adapt my changes to what is needed.

**Comment by sberyozkin** [comment]
Hi @nhumblot and @jeremylong 

Sorry I have missed your ping - yes, exactly, these 3 group IDs have their own CPE qualifiers.
Thanks for looking into it and adding this rule :-)

We'll wait for the release of `6.1.7`

Cheers

**Comment by sberyozkin** [comment]
Sorry, see you are planning it for `6.2.0` - that is fine, thanks
