### ISSUE TITLE
False positive CVE-2021-26987

### ISSUE THREAD

**Issue by ethesx** [dependency-check/DependencyCheck#3358]
Reported via Jenkins v5.1.1 plugin

`cpe:2.3:a:pivotal_software:spring_boot:*:*:*:*:*:*:*:*`

False positive on built spring-boot uber-jar
```xml
<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>1.5.22.RELEASE</version>
<relativePath />
</parent>
```

Full sping-boot dependency hierarchy (filtered by "spring-boot"):
![image](https://user-images.githubusercontent.com/2558082/117327122-4608b000-ae60-11eb-8c55-8d0a39fdddae.png)

**Comment by aikebah** [comment]
This FP appears to be caused by improper items in your project's Manifest. Spring-boot-starter-parent sets a few pom variables that you should override to obtain proper metadata in your uberjar manifest:

```
  <url>{{your project url}}</url>
  <organization>
    <name>{{your org}}</name>
  </organization>
```

without these overrides your MANIFEST.MF will hold (based on inheritance from the parent):
```
Implementation-URL: https://projects.spring.io/spring-boot/{{your project artifactId}}/
Implementation-Vendor: Pivotal Software, Inc.
```
which IMO is incorrect metadata that you would like to avoid in your own artifacts, which is also the metadata that (when no better match can be found) links your spring-boot uber-jar to the spring boot CPE

**Comment by aikebah** [comment]
Caused by bad metadata in pom, needs to be corrected in the pom of the project or suppressed by the end-user
