### ISSUE TITLE
False Positive on hibernate-validator 6.2.0.Final

### ISSUE THREAD

**Issue by meyer-r** [dependency-check/DependencyCheck#3359]
CVE-2020-10693 might be a false positive on library for org.hibernate:hibernate-validator:6.2.0.Final.

It's reported as: 
hibernate-validator-6.2.0.Final.jar (pkg:maven/org.hibernate.validator/hibernate-validator@6.2.0.Final, cpe:2.3:a:hibernate:hibernate-validator:6.2.0:*:*:*:*:*:*:*, cpe:2.3:a:redhat:hibernate_validator:6.2.0:*:*:*:*:*:*:*) : CVE-2020-10693

```xml
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-validator</artifactId>
    <version>6.2.0.Final</version>
</dependency>
```

**Comment by msmsimondean** [comment]
https://nvd.nist.gov/vuln/detail/CVE-2020-10693 says: 

```
cpe:2.3:a:redhat:hibernate_validator:*:*:*:*:*:*:*:*

Up to (excluding)
6.0.20
```

Given the `excluding` reference on that page, the issue seems to be fixed in 6.0.20.  I.e. the issue does not affect 6.0.20.  

Oddly this version of the library is listed as `6.0.20.Final` (with `.Final` on the end) and not `6.0.20` on https://search.maven.org/artifact/org.hibernate.validator/hibernate-validator

@meyer-r it might be worth changing the title of this GitHub issue to replace `[library]` with `org.hibernate:hibernate-validator:6.2.0.Final`?

**Comment by isaki** [comment]
The descriptions on the CVE page list all versions up to 6.0.20, and 6.1.2-6.1.5. The false positive reported by @meyer-r is for 6.2.0.Final, which is a minor version after the listed affected versions. The title of this should also be fixed; I came here to report this myself and found this issue (which was not obvious by the title). I can create a new issue if we need with a proper title.

**Comment by aikebah** [comment]
@meyer-r appears to be resolved by updated upstream vulnerability data as I cannot reproduce it anymore. Can you please verify and confirm?

**Comment by DeGuitard** [comment]
@aikebah This has indeed been fixed: https://github.com/advisories/GHSA-rmrm-75hp-phr2
The affected versions have been updated.

Additionally, I don't face the issue anymore.
