### ISSUE TITLE
false positive on wss4j-1.5.7.jar

### ISSUE THREAD

**Issue by domak** [dependency-check/DependencyCheck#34]
Hi,

The scan of org.apache.ws.security:wss4j:jar:1.5.7 detects the vulnerability CVE-2012-5784. 

I think it is a false positive:
During the information collection, the scanner detects that:
- there is an axis package name in the lib
- the manifest Bundle-version is 1.0.0 (don't sure that it is important in CPE search)

The project identifiers found are (wss4j is not present in CPE):
- cpe: cpe:/a:apache:axis:1.0
- cpe: cpe:/a:apache:xml_security_for_java:1.5.7
  and the CVE-2012-5784 is attached to cpe:/a:apache:axis:1.0

I've used the 1.0.5 version (and checked with current development version).

By the way, it is a nice project. Thanks.

**Comment by jeremylong** [comment]
Unfortunately, some of these false positives will happen - the tool was designed with a "best effort" using pattern matching rather then trying to maintain a massive vulnerability database. I will be implementing a feature request (https://github.com/jeremylong/DependencyCheck/issues/21) soon so that one can designate specific CVE or CPE as false positives so that they stop showing up in your scan. As part of this I will also add a "confidence" score to the identified CPE (and subsequent CVEs) and if one wanted to they could suppress the "low" quality findings.

I'll am going to leave this ticket open and when I have time I will look more in detail with regard to this specific JAR file to see if there is something that could be done in the identification phase that would reduce the false positives listed above without introducing false negatives in other libraries.

**Comment by domak** [comment]
Hi Jeremy. Thanks for your response. I understand and agreed with the design of the tool. I will post my thoughts on thread for #21 but I think that based evidence on package will give a lot of false positives, except if the confidence is marked as low. I've found some other cases with jboss. Are you interested? If yes, do you prefer that I open a new issue or add on this one?

**Comment by jeremylong** [comment]
You can post additional false positives to this thread. Some I might be
able to do something about, others the only way to fix is to hard-code the
false positive (or to put them in the upcoming suppression filters). One
thing that would be helpful - if the JAR is hosted in maven central, please
provide the group:artifact:version.

Best Regards,

--Jeremy

**Comment by domak** [comment]
`org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar:1.0.0.Final`
and 
`org.jboss.logging:jboss-logging:jar:3.1.0.CR2`
are matched with jboss:
`cpe:/a:jboss:jboss` and associates CVE-2007-1157

These jars come with hibernate:

```
[INFO] +- org.hibernate:hibernate-entitymanager:jar:4.0.1.Final:compile
[INFO] |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar:1.0.0.Final:compile (version managed from 1.0.0.Final)
[INFO] |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  \- xml-apis:xml-apis:jar:1.0.b2:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.1.0.CR2:compile
```

**Comment by jeremylong** [comment]
Additional false positives have been reported for:
batik-util.jar
xstream-1.4.2.jar

**Comment by jeremylong** [comment]
The last reported false positive is related to hiberanate3.jar. This will be tackled soon.

**Comment by jeremylong** [comment]
All known false positives have been patched.
