### ISSUE TITLE
Question about multiple parallel executions

### ISSUE THREAD

**Issue by ngeor** [dependency-check/DependencyCheck#3526]
Hello,

We're experiencing some random failures when using the dependency-check-cli in parallel jobs in CI. More specifically, we have a Bazel monorepo and we have a custom Bazel rule to trigger dependency-check-cli.

When running 112 jobs in parallel (all running dependency check cli), 64 of them fail with a weird message about "Middleman failed" (most likely this is Bazel reporting the error).

We divided the 112 jobs in groups and it seems this improves the success rate. e.g. when allowing only 4 jobs to run in parallel, all dependency-check-cli invocations succeed, when allowing 10 jobs to run in parallel, 2 jobs fail, etc.

We don't think this is a problem with our CI infrastructure. Each job runs in a Docker container.

Do you know how we can further investigate what is causing the failures? e.g. is there some way to increase the logging verbosity (although, I think we should already be seeing errors and we don't...)

Do you have any idea on what might be causing this in general? Could there be some API rate limiter on the OWASP side (I think you're calling them to get a fresh list of issues to check against?)

**Comment by jeremylong** [comment]
When calling ODC you can add `--log odc.log` and ensure that you keep this log as part of the output from the build.

Unless you are doing something with caching I'd bet you are getting rejections from the NVD as ODC attempts to update the local database. Options would be to mirror the NVD locally. Another option would be to instead of using the ODC CLI use the ODC Docker Image.  We haven't advertised this as much as we probably should - but https://hub.docker.com/r/owasp/dependency-check-action is built daily with a full local database so it is more useful in a CI environment.

Another area that could be failing is the calls out to the OSS Index. Options are to disable the OSS Index Analyzer (which could cause an increase in false negatives) or don't run as many jobs in parallel. The logs should help you figure out exactly what is failing though.

**Comment by ngeor** [comment]
No we're not caching anything unfortunately. We discussed at some point to mirror NVD data (back when they accidentally published NVD data in a corrupt format) but didn't go through with it. Thank you very much for the reply!
