### ISSUE TITLE
undertow-websockets-jsr-2.2.9.Final.jar and CVE-2021-33880

### ISSUE THREAD

**Issue by des-moines** [dependency-check/DependencyCheck#3560]
I don't understand why this java dependency 

      <dependency>
        <groupId>io.undertow</groupId>
        <artifactId>undertow-websockets-jsr</artifactId>
        <version>2.2.9.Final</version>
      </dependency>

is being flagged with CVE-2021-33880, which appears to relate to a python library.

**Comment by aikebah** [comment]
It's because there is no direct matching of maven coordinates to CPEs in the NIST NVD database. So DependencyCheck does a best-effort text-based match on known CPEs versus discovered evidences on a dependency (see all of the evidences listed in the report). For this library unfortunately the 'best' match found within the NVD for this library on a text-based search is the CPE of that python library.

**Comment by jeremylong** [comment]
See [How dependency-check works](https://jeremylong.github.io/DependencyCheck/general/internals.html) for more information.

**Comment by des-moines** [comment]
That makes sense. Thanks!

**Comment by aikebah** [comment]
FP Will be resolved with 6.2.3 as this FP is a duplicate of #3460
