### ISSUE TITLE
 Unable to read yarn audit output.

### ISSUE THREAD

**Issue by rituraj-gaur** [dependency-check/DependencyCheck#3604]
**Describe the bug**
Unable to read yarn audit output.
exception: org.owasp.dependencycheck.exception.InitializationException: Unable to read yarn audit output.

**Version of dependency-check used**
The problem occurs using version 6.2.2 of the _cli_)

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by mprins** [comment]
Your report is missing key information for debugging and/or analysis. Please use the issue template provided.

**Comment by brileyd** [comment]
I'm experiencing this issue as well.

**Describe the bug**
I am using the command line version and running it with TeamCity.  This occurred after updating from 6.0.4 to 6.4.1.  Here is the last piece of the log showing the error:

> [12:37:44]
> 01:50  INFO: Vulnerability found: jquery below 3.5.0
> [12:37:44]
> [INFO] Finished RetireJS Analyzer (110 seconds)
> [12:37:52]
> [INFO] Finished Sonatype OSS Index Analyzer (7 seconds)
> [12:37:56]
> [INFO] Finished Vulnerability Suppression Analyzer (3 seconds)
> [12:38:31]
> [INFO] Finished Dependency Bundling Analyzer (34 seconds)
> [12:38:53]
> [INFO] Analysis Complete (349 seconds)
> [12:38:53]
> [INFO] Writing report to: C:\BuildAgent1\work\2134b79919eb318\.\dependency-check-report.html
> [12:39:07]
> [INFO] Writing report to: C:\BuildAgent1\work\2134b79919eb318\.\dependency-check-report.json
> [12:39:20]
**> [ERROR] Unable to read yarn audit output.**
> [12:39:21]
> Process exited with code -14
> [12:39:21]
> Process exited with code -14 (Step: Dependency Check (Command Line))
> [12:39:21]
> Step Dependency Check (Command Line) failed

**Version of dependency-check used**
The problem occurs using version 6.4.1 of the cli.

**To Reproduce**
Steps to reproduce the behavior:
I'm not sure.  I don't believe we even have yarn dependencies.  Here is the command used:
> c:\tools\dependency-check\bin\dependency-check.bat --project= "t4cp" --scan=. --disableAssembly --disableBundleAudit -f HTML -f JSON

For now, I will add the --disableYarnAudit option.

**Additional context**
As I said, this is part of a TeamCity project and occurs after a maven build.  I updated to the latest version due to another error with NIST downloads sometimes failing.

Thanks!

**Comment by jeremylong** [comment]
I believe the source of the issue was identified via https://github.com/jeremylong/DependencyCheck/pull/3700#issuecomment-945453197

I'm not sure why the 64k cap is there - I haven't dug into this enough to figure that out. However, we can use the same workaround for the yarn audit analyzer.

**Comment by jeremylong** [comment]
This should be fixed in the next release - which should be in the next few days.

**Comment by MichaelDenwood** [comment]
This appears to be happening again with version 6.5.0.

dependency-check.bat -project Redacted -s "F:\Agents\SaaSProdW4\_work\746\s" -o F:\Agents\SaaSProdW4\_work\746\TestResults\ -f SARIF --failOnCVSS 9
...
[WARN] The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
[ERROR] Exception occurred initializing Yarn Audit Analyzer.
...
[INFO] Finished RetireJS Analyzer (77 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (14 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (80 seconds)
[INFO] Analysis Complete (216 seconds)
[INFO] Writing report to: F:\Agents\SaaSProdW4\_work\746\TestResults\dependency-check-report.sarif
[ERROR] Unable to read yarn audit output.
##[debug]Exit code: -14
##[debug]Leaving Invoke-VstsTool.

I see this is already in an issue #3137
