### ISSUE TITLE
how to scan other files/libraries. Lets say you have to run on docker image or war files. 

### ISSUE THREAD

**Issue by anilmukkamala** [dependency-check/DependencyCheck#3609]
is there a way run against them using CLI or do I have to go for different approach ?

**Comment by aikebah** [comment]
Scanning content of Docker images: not supported
Scanning content of war-files: war files are zip files and as such scanned with the [archive analyzer](https://jeremylong.github.io/DependencyCheck/analyzers/archive-analyzer.html)

Typically you would want to use DependencyCheck in your build-tool-of-preference (ant/maven/gradle/sbt) as that would give the best possible matching with the lowest risk on false positives because it can take project dependency configuration into account. 
You can however use any of the tools to run a scan of a folder if you cannot run dependencycheck in your build (e.g. because you want to check some 3rd party binary software rather than your own builds for use of vulnerable libraries).

When scanning a folder, if possible in your environment, use the Central Analyzer or Nexus Analyzer as part of your scan to improve matching for any component that originated from the Maven repository.

**Comment by anilmukkamala** [comment]
Thanks @aikebah , I am in a scenario where there are no jar files to scan a file. So I am downloading the folder and running the scan against it, the results say this 
![image](https://user-images.githubusercontent.com/89027166/130853507-122f48ac-1b5b-4b50-889f-affe0ae565c8.png)
I am seeing Dependencies scanned 0, is this an issue ?

**Comment by aikebah** [comment]
`Dependencies scanned: 0` Indicates that none of the analyzers found any file that they can analyze.

Whether that's expected or not depends on the content that you put inside the folder that you scanned. See the [documentation on the various analyzers](https://jeremylong.github.io/DependencyCheck/analyzers/index.html) for which types of files DependencyCheck considers.

If you have files in the folder that would be supported by one or more of the analyzers then your scan command was not correct. In your OP you mentioned a .war file. A .war would be expected to be scanned and show up as a dependency in the report.
