### ISSUE TITLE
False Positive on hibernate:hibernate-validator-annotation-processor ?

### ISSUE THREAD

**Issue by rsworden** [dependency-check/DependencyCheck#3654]
[I'm new to OWASP Dependency-Check]

Is this what you mean by a False Positive? A vendor provided an OWASP report that lists 

DocumentQueManager.war: hibernate-validator-annotation-processor.jar
cpe:2.3:a:hibernate:hibernate-validator:5.3.5:*:*:*:*:*:*:*
pkg:maven/org.hibernate/hibernate-validator-annotation-processor@5.3.5.Final	
MEDIUM	1	Highest	23

The CPE reference is a hyper link that goes to NVD but there is no such CPE. Searches of the CPE database do not find it.
https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Ahibernate&cpe_product=cpe%3A%2F%3Ahibernate%3Ahibernate-validator&cpe_version=cpe%3A%2F%3Ahibernate%3Ahibernate-validator%3A5.3.5

The Maven hyperlink does find a valid page for the full string and version but lists no vulnerabilities.
https://ossindex.sonatype.org/component/pkg:maven/org.hibernate/hibernate-validator-annotation-processor@5.3.5.Final?utm_source=dependency-check&utm_medium=integration&utm_content=6.0.2

I see CPEs for hibernate:hibernate-validator which is a subset of the dependency shown on the OWASP report.
I also see CPEs for red-hot:hibernate_validator (wrong supplier, underscore instead of hyphen.)

Is this a case of matching on a substring? Should they just exclude it from scanning? Or is there a way to make the scanning more exact?

I worry about excluding. If a real vulnerability were later reported against hibernate-validator-annotation-processor.jar would we ever know?

**Comment by aikebah** [comment]
Gut feel is that it is both a false positive as well as an erroneously included jar in your war-file.

From [documentation](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#validator-annotationprocessor-usage) it appears that this library is meant to be used at compile-time to evaluate the correct usage of hibernate validator annotations in your code and as such is not required to be present at runtime.
For the maven build case it should suffice to define it as annotation processor in the compiler plugin configuration (annotationProcessPaths) rather than a dependency of your project.

**Comment by rsworden** [comment]
Thank you very much! I'll have the vendor see about refining their build files.
