### ISSUE TITLE
False Positive on project named my-secrets-quarkus

### ISSUE THREAD

**Issue by tassadar81** [dependency-check/DependencyCheck#3675]
**Describe the bug**
I'm analysing my project named my-secrets-quarkus using this command:

mvn -X -B -f pom.xml -Dformat=JSON org.owasp:dependency-check-maven:6.3.1:aggregate

and it reports this:

my-secrets-quarkus-0.0.4.jar (pkg:maven/it.acme.foo.libraries/my-secrets-quarkus@0.0.4, cpe:2.3:a:quarkus:quarkus:0.0.4:*:*:*:*:*:*:*) : CVE-2017-18640, CVE-2019-14900, CVE-2020-10693, CVE-2020-13692, CVE-2020-13956, CVE-2020-1714, CVE-2020-1728, CVE-2020-25633, CVE-2020-25638, CVE-2020-25649, CVE-2020-25724, CVE-2020-8908, CVE-2021-20289, CVE-2021-20328, CVE-2021-21290, CVE-2021-21295

But there aren't any quarkus dependencies on this project, it's a simple library project. Once i renamed it as my-secrets-banana and performed a rescan the previously reported CVE's have been disappeared

**Version of dependency-check used**
The problem occurs using version 6.3.1 of the maven plugin

**Expected behavior**
Do not report anything

**Comment by aikebah** [comment]
This is expected behaviour based on the [inner workings](https://jeremylong.github.io/DependencyCheck/general/internals.html) of this tool. Your case is the typical case where you'll need to put a cpe-[suppression](https://jeremylong.github.io/DependencyCheck/general/suppression.html) in place for a private project that receives a false-positive match with an existing entry of the NIST NVD.
