### ISSUE TITLE
Jar build not showing components in generated CSV/XML report but WAR build is showing components

### ISSUE THREAD

**Issue by aejazuddinam** [dependency-check/DependencyCheck#3688]
Hi Team,

I have the below example usecase, when i do a JAR build followed by dependency-check, there is only 2 components which even are duplicate in the generated CSV,XML report, but whereas if i do the same for WAR build, many components are generated and listed, could you please explain why this issue is seen. 

dependencycheck additionalArguments: '--scan "./" --prettyPrint --out build/dependency-check-report --format ALL --cveUrlModified=*/CVE/NIST/nvdcve-1.1-modified.json.gz --cveUrlBase=*/CVE/NIST/nvdcve-1.1-%d.json.gz --retireJsUrl=*/CVE/RetireJS/jsrepository.json --disableCentral true --disableCentralCache false --disableOssIndex false', odcInstallation: 'DependencyCheck'

.........
Also another scenario i used for the same with Dependency-Track as well, directly generating bom from pom.xml and publish, for JAR build and WAR build both are generating equal amount of components and vulnerability list.

Regards,
Aejaz

**Comment by jeremylong** [comment]
The problem is you are using the CLI as opposed to one of the build plugins. If you used the maven or gradle plugin you would see the same results. The reason for this is the CLI only can process what is actually present - it does not try to replicate Maven and process the pom.xml. If you only wanted to use the CLI on a Maven build that produced a JAR file you would need to do something like:

```bash
mvn package dependency:copy-dependencies
dependency-check -s target -o target
```
