### ISSUE TITLE
Making failBuildOnCVSS configurable at runtime

### ISSUE THREAD

**Issue by phsh** [dependency-check/DependencyCheck#37]
I need to run org.owasp:dependency-check-maven:1.0.7:check on a number of projects, and don't want to change the pom foreach project.

The setup would require the failBuildOnCVSS to be runtime configurable,

@Parameter(property = "failBuildOnCVSS", defaultValue = "11", required = true)
    private float failBuildOnCVSS = 11;

**Comment by jeremylong** [comment]
I apologize if I am missing something - but because there is a defaultValue of 11 this element does not actually need to be configured in the pom. This value will default to 11 which basically indicates that it will never fail the build as the CVSS scores range from 0-10.

Are you asking for a different way to configure the fail build on CVSS property?

--Jeremy

**Comment by phsh** [comment]
What I wanna do is:

mvn org.owasp:dependency-check-maven:1.0.7:check -Dcheck.failBuildOnCVSS=5

I hope that clarify me needs... Sorry for not being clear enough...

**Comment by jeremylong** [comment]
phsh,

Sorry for the delay in getting back to this. I did not incorporate your PR as you can run the following command to set the failBuildOnCVSS score argument:

mvn dependency-check:check -DfailBuildOnCVSS=4

Please let me know if I am missing something.

--Jeremy
