### ISSUE TITLE
6.4.1 is not available in homebrew.

### ISSUE THREAD

**Issue by orschaef** [dependency-check/DependencyCheck#3734]
An update would be nice since 6.4.0 is also missing. Can you update?

**Comment by jeremylong** [comment]
Please see https://github.com/Homebrew/homebrew-core/pull/87100

With 6.4.0 and 6.4.1 I added increased wait times during the download process to reduce the issues with rate limiting from the NVD. As Homebrew spins up several containers at once - I increased the wait time a little more; this is causing some of the jobs to fail because it exceeds the execution time allowed by homebrew. Working on balancing the wait times with the overall execution time in homebrew. It should be published soon.

**Comment by jeremylong** [comment]
All checks passed: https://github.com/Homebrew/homebrew-core/pull/87100

I'm hoping this will be merged today.

**Comment by orschaef** [comment]
It is now. That was timing. Thanks for the quick reply.

**Comment by orschaef** [comment]
Can be closed :)
