### ISSUE TITLE
Flagging as vulnerable even though version is OK

### ISSUE THREAD

**Issue by tsel-sbab** [dependency-check/DependencyCheck#3763]
Hi

I am using jenkins and sonar.
I am seeing that a version that should be accepted is not accepted.

![Screenshot 2021-10-25 at 10 27 36](https://user-images.githubusercontent.com/37338961/139032084-e8509a0b-4c21-45d5-b2de-ba973a352b60.png)

Note below (from sonar gui)  that version 3.1.6 is indeed newer than 2.5.3:
"Filename: ejs:^3.1.6 | Reference: CVE-2017-1000228 | CVSS Score: 9.8 | Category: | nodejs ejs versions older than 2.5.3 is vulnerable to remote code execution due to weak input validation in ejs.renderFile() function"

Logs for dependency-check.sh: https://gist.github.com/xqest/46bb76406ba7a2ae67c871377de815be

I dont know if its relevant but here is Sonar-scanner command and output:
https://gist.github.com/xqest/bea9d828b503d45ad182df52bf095887

**Comment by aikebah** [comment]
Sonar-scanner just reads the report that dependencycheck created. The interesting information can only be obtained from that report: which evidences did dependencycheck discover in relation to your ejs dependency that make it flag the dependency as vulnerable.

**Comment by tsel-sbab** [comment]
Thanks for answer @aikebah 
I cant find more info than what I posted above.
I checked dependency-check-report.json but cant find something interesting.
But you see the problem above, the versions below 2.5.3 i vulnerable. But I use 3.1.6 so it shouldnt complain. Where does that message come from, do you know?

**Comment by aikebah** [comment]
@xqest I see the ^3.1.6 referenced in the message, but that a dependency name is represented by that string does not mean that DependencyCheck established that your actual dependency is really a version 3.1.6 or above. From the detected CVE it appears that dependencycheck decides that your ejs is NOT of that version or later (as the NIST NVD lists it as version * up-to-excluding 2.5.3, which means that either DependencyCheck could not determine a version (and therefor assumes the worst), or it actually decided that the version is some semantic version lower than 2.5.3.

Can you post a git of the entire JSON-object for the ejs dependency? (The full JSON object within the "dependencies" array that belongs to the ejs dependency?)

Note: the warning may very well be at the root of the failed derivation of version number, which is why I suggested to have a look at the various evidences collected for your ejs dependency (which may be very limited), which are contained in that dependencies-entry JSON object.

**Comment by tsel-sbab** [comment]
@aikebah Ohh, sorry about that. Here is the json object:
https://gist.github.com/xqest/d430ae534d6054ca61e4a333cf6ca95b

**Comment by aikebah** [comment]
Which essentially holds the answer enclosed: DependencyCheck (by lack of the module to determine the real version that would be resolved for the "^3.1.6" version wildcard) has set the version to "^3.1.6" and OSSIndex responds when queried with such a wildcard version with a vulnerabilities for older versions.

https://gist.github.com/xqest/d430ae534d6054ca61e4a333cf6ca95b#file-gistfile1-txt-L195

Note that DependencyCheck never tries to reproduce the logic of nodejs for package version resolution, it just operates on all the evidences found in your project folder.

**Comment by aikebah** [comment]
As the possibilities in NPM's semver versioning constraints is almost endless (https://semver.npmjs.com/) you're best off ensuring that all depended-on modules have been properly resolved by the package manager before running dependency-check.

For the basic ~n.n.n and ^n.n.n cases we could strip the prefix to make OSSINDEX report appropriately for that specific version, but all other options still leave you with issues. And stripping the minor- or patch version-range indicator  could still result in false positive results (e.g. if your project had ^2.5.3 in package.json DependencyCheck would report still report the issues solved by 2.5.5, but if you let npm resolve the dependency it's likely to select 2.7.4 so your project would IRL not contain the vulnerabilities when built from scratch)

**Comment by tsel-sbab** [comment]
Thank you @aikebah We were able to move ahead thanks to your answers.
