### ISSUE TITLE
log4j vulnerabilities and delay in findings

### ISSUE THREAD

**Issue by ConRock5000** [dependency-check/DependencyCheck#3887]
I notice that with the Jenkins plugin, the first log4j vulnerability CVE-2021-44228 is still not being detected.

Just now I grabbed the latest dependency check CLI version, it downloaded the NVD files and performed a scan. The new log4j vulnerability CVE-2021-45046 is not being detected.

Are these issues with the NVD files not being as up to date as the NVD site?

There is a ticket for the Jenkins plugin finding but I don't know what the actual cause of these issues are which is why I posted these questions.
https://issues.jenkins.io/browse/JENKINS-67364

Thanks

**Comment by Janpopan** [comment]
Actuall there is no score in the nist files. So no problem is reportet. You can build your own hint file. See documentation false negative.

**Comment by ConRock5000** [comment]
The first CVE is now being reported by the Jenkins dependency-check plugin after a scan. Just took several days.

**Comment by ConRock5000** [comment]
Similar to what you said. I had checked the data feeds yesterday which were downloaded into my Jenkins workspace and the vulnerability was not in there. Not sure why that happened.

**Comment by jeremylong** [comment]
These should be being reported now. The issue was that the NVD was still awaiting analysis and did not contain the list of affected software. If you had the OSS Index Analyzer enabled - the CVE would have been flagged much earlier. However, I do know many enterprise users disable this due to needing an external connection during the analysis.
