### ISSUE TITLE
False Positive on dependent project in multi module project in Gradle

### ISSUE THREAD

**Issue by peterfigure** [dependency-check/DependencyCheck#3921]
This is the project in question: https://github.com/nefilim/kjwt

This is my identifier: `cpe:2.3:a:github:github:0.4.6:beta:*:*:*:*:*:*  (Confidence:Low)` for dependency: `core.jar (project :core)`

Evidence:

<img width="702" alt="Screen Shot 2021-12-27 at 09 58 47" src="https://user-images.githubusercontent.com/62901374/147492355-49ececa5-0e3b-4f9c-92a5-4557143b0526.png">

I've tried the following, none of which works:
```xml
    <suppress>
        <notes><![CDATA[
      let's not score any own goals
      ]]></notes>
<!--        <packageUrl regex="true">^pkg:maven/io\.github\.nefilim\.kjwt/.*$</packageUrl>-->
<!--        <filePath regex="true">.*\bcore\.jar</filePath>-->
        <gav regex="true">io\.github\.nefilim\.kjwt:.*$</gav>
        <cpe>cpe:/a:github:github</cpe>
    </suppress>
```
The recommendation in the report to suppress:
```xml
**    <suppress>
        <notes><![CDATA[
   file name: core.jar (project :core)
   ]]></notes>
        <sha1>ef6a651e56a1798611fa050d9b76db68bfaa63b8</sha1>
        <cpe>cpe:/a:github:github</cpe>
    </suppress>**
```
does work but doesn't look like a viable strategy (hash will be constantly changing)

**Comment by aikebah** [comment]
Using an aggregate scan of the entire project rather than individual scans of the composing modules would be my recommended way to get rid of this false positive.
DependencyCheck assumes that you know about and remove any vulnerabilities in your own code and by scanning the entire project set as an aggregate will not try to match your own core.jar with any known CPE.

https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration-aggregate.html

**Comment by jeremylong** [comment]
I just ran `./gradlew build dependencyCheckAggregate` on the project and could not reproduce the false positive.
