### ISSUE TITLE
CVE-2021-26291 reported for maven-core-3.0 / 3.1.1

### ISSUE THREAD

**Issue by ProofOfPizza** [dependency-check/DependencyCheck#3925]
I ran the dependency-check-maven plugin and it reported CVE-2021-26291 for 2ome packages. I cloud not find a way to mitigate it so I [asked for help on SO](https://stackoverflow.com/questions/70507859/how-to-fix-vulnerability-maven-core-3-0-in-exec-maven-plugin)
This led me to believe that is was wrongly reported, and instead of a vulnerability in that specific package, it had to do with the version of maven I am actually using to build my software. 

Is that correct ? If so could we make that more clear ?

**Comment by aikebah** [comment]
First of all: your project setup appears to be flawed.

A maven project does not 'depend on' the plugins that you use in the builds. So if, as I suspect to be the case, you have the dependencies only because your build uses the plugins: remove them from the dependencies section.
Dependencies of your maven project should reflect the build-time, test-time and runtime dependencies of your code. Any library dependencies for plugins used during build are manged seperately by maven with the plugin-section and the dependencies as documented in the plugin's pom-file.
Unless you use a plugin with pluggable subcomponents there is nothing besides the plugin-section itself that should appear in your pom.xml.
If you use a plugin with pluggable subcomponents (such as e.g. various code generation plugins that have library- or feature-specific pluggable extensions), then the dependencies on the plugin pluggable libraries would still not go into your pom's `<dependencies>` section, but rather into the plugins section (a `dependecies>` section inside the `<plugin>` tag.

So I recommend you read up some more on maven to get a better understanding of the pom in relation to plugins versus dependencies.

Regardless of that, you can always, [as documented](https://jeremylong.github.io/DependencyCheck/general/suppression.html), use a suppression filter to suppress false positives that you encounter.

The mentioned vulnerability is a build-time vulnerability of maven as a tool and, since you run on maven>3.8.1 (and on top of that use an artifact repository proxy) not applicable to your situation (presuming you have your artifact repository configured to only serve hosted repositories or proxies that are using https to obtain the proxied artifacts, otherwise you merely shift the MITM-vulnerability from the maven-to-repository connection to the connection between your mirror and the authoritive http-hosted repository.

Note that in the mentioned plugins the vulnerable libraries are configured 'provided'-scoped and get replaced in your build by their upgraded maven 3.8.2 counterparts which are part of your maven install, whereas by configuring the plugins as a dependency of your project [you drag them in at compile scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) and they retain there explicit version, causing the false positive to appear.

**Comment by ProofOfPizza** [comment]
Thank you for taking the time to respond here. It is appreciated. 
I read the docs you suggested and did some digging, and yes, I did not apply the "scopes" correctly. 
Just to be sure: I now defined scope "provided" for a bunch of dependencies, for example the openapi generation stuff.
The error indeed now does not show up anymore, even after removing it from the suppressions.

> Unless you use a plugin with pluggable subcomponents there is nothing besides the plugin-section itself that should appear in your pom.xml.

This line confuses me a bit. It seems to me that most of the stuff are dependencies, for example spring-boot things or aws-rds etc etc. How then would a project have (almost) nothing under "dependencies" and (almost) everything under "plugins" ?

**Comment by aikebah** [comment]
> > Unless you use a plugin with pluggable subcomponents there is nothing besides the plugin-section itself that should appear in your pom.xml.
> 
> This line confuses me a bit. It seems to me that most of the stuff are dependencies, for example spring-boot things or aws-rds etc etc. How then would a project have (almost) nothing under "dependencies" and (almost) everything under "plugins" ?

Projects with almost no dependencies and several plugins are perfectly possible (when the code only depends on the Java SE core classes as packaged in the JVM). However in your case most of it would likely still be dependencies rather than plugins.

Most of spring/spring-boot will be a regular dependency of your project (when you are building a spring-boot application the application code will depend on the spring-boot framework). However you likely get many of those dependencies (if you follow the standard recipes) from various spring-boot-starter dependencies, so the dependencies section could still be small (See spring-boots own getting started guide for a sample - the end state lists three spring-boot dependencies and the spring-maven-plugin)

Examples of the case I mentioned regarding 'additional dependencies of a plugin that you need to put into your pom.xml' would be the [sqlj maven plugin](https://www.mojohaus.org/sqlj-maven-plugin/usage.html), an open-source maven plugin that requires you to manually add the coordinates under which you put IBMs proprietary SQLj translator library as a `<dependency>` underneath the plugin (rather than a `<dependency>` in the `<dependencies>` section of your pom) and the [sqlenumgen-maven-plugin](https://github.com/McNetic/sqlenumgen-maven-plugin), which is built to support any jdbc compliant database, but needs you to add the appropriate jdbc driver to the plugin dependencies to make the plugin able to connect to your database to extract the configuration information for enum generation from the database.

**Comment by ProofOfPizza** [comment]
Right! That makes sense!
Again, thank you for your time and effort. 
I will close this item.
