### ISSUE TITLE
Missing artifact org.owasp:dependency-check-core:jar:1.3.2-SNAPSHOT

### ISSUE THREAD

**Issue by maxlpy** [dependency-check/DependencyCheck#401]
Hi Jeremy,
I try to import dependency-check-cli into my eclipse, the pom file reports an error "Missing artifact org.owasp:dependency-check-core:jar:1.3.2-SNAPSHOT". I guess that's because maven tool can't find it from maven central. And I tried to fix it by specify the version of dependency-check-core:jar to 1.3.1, and it works now. But I think you have a better solution to fix it. Thank you!

**Comment by jeremylong** [comment]
If you want to load just the 1.3.2-SNAPSHOT CLI into Eclipse you'll need to
install the rest of the compiled objects into your local repo.

$ git clone https://github.com/jeremylong/DependencyCheck.git
$ cd DependencyCheck
$ mvn install

That will put the 1.3.2-SNAPSHOT jars into your local repo. Let me know if
that answers your qustion.

--Jeremy

**Comment by maxlpy** [comment]
Got it. Thank you so much!

**Comment by hansjoachim** [comment]
Out of curiosity, did you import all of DependencyCheck or just the -cli module in Eclipse?

Because if I import all modules, I get some strange error messages (core doesn't seem to be buildable, and modules which depend on core refuse to build). I don't remember of the top of my head, but I can find the exact messages. Just wonder if you got it to work, and possibly how you did it?
