### ISSUE TITLE
Not able to exclude transitive dependencies from a scan?

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [dependency-check/DependencyCheck#4014]
Hi,

I am using the `./gradlew dependencyCheckAggregate` command to generate the dependency report HTML file for one of my Gradle projects. It works fine and lists both direct and transitive jar dependencies which are vulnerable as per the NVD database. However, I tried multiple ways but failed to figure out a way wherein I want to only list the direct dependencies? Is there any way through which I can list the direct dependencies only? Below is the `build.gradle` file for reference –

File snippet -
```
plugins {
    id 'org.owasp.dependencycheck' version '6.5.3'
}
repositories {
    mavenCentral()
}
subprojects {
    apply plugin: 'org.owasp.dependencycheck'

    dependencyCheck {
        outputDirectory = 'security-report'
        failOnError = true
    }
}
```
Is this some feature that is missing from this plugin? or something else? Please confirm.

**Comment by mprins** [comment]
IMHO the whole point of a tool like ODC is to scan all dependencies... if you want to scope dependencies you schould add a scope to them such as "provided" and use that to limit the scan

**Comment by beena-yatin-kanyal** [comment]
thanks, @mprins but I think dependency check is a widely accepted tool by the technology community and I think having a feature like where scan could only list direct or transitive or both dependencies could be great. at least a classification on the generated report could be an advantage where it is clear to the developers. 

sometimes I would only focus on the direct dependency fixes and not fix the transitive one for a while. thoughts?

**Comment by jeremylong** [comment]
I won't disagree that when using the maven or gradle plugin we could do better about indicating where in the dependency tree the vulnerable component is - however, how much one should worry about the transitive dependencies is complicated.

1. One can have `Used but undeclared dependencies` (see an example [dependency-analysis report](https://jeremylong.github.io/DependencyCheck/dependency-check-core/dependency-analysis.html)
2. The risk actually affects your application even if it is only a transitive dependency; which could have happened with the recent log4j event.

Yes, upgrading transitive dependencies can be difficult and sometimes impossible unless you are willing to put in a PR to the direct dependency to help them upgrade. However, just ignoring them is likely not the best option.

**Comment by beena-yatin-kanyal** [comment]
thanks, @jeremylong for answering the question. 2 questions -
1. how can I generate the [dependency-analysis report](https://jeremylong.github.io/DependencyCheck/dependency-check-core/dependency-analysis.html)? can you please help with the documentation to generate the report?
2. I agree with your opinion however I was thinking of it more as functionality where sometimes I would only want to generate the report containing the vulnerabilities for direct dependencies or sometimes indirect dependencies or sometimes even both. I am hoping if a flag could manage that or something else I can try. Any luck with that?

p.s. - just exploring the different possibilities with this tool.

**Comment by aikebah** [comment]
@beena-yatin-kanyal 
regarding 1) The report Jeremy referenced is one that is out-of-the-box available as a report in maven (https://maven.apache.org/plugins/maven-dependency-plugin/analyze-report-mojo.html). 

For gradle there seems to be nothing like it (there is a [gist](https://gist.github.com/kellyrob99/4334483) that wraps the maven plugin , used by someone else in a [plugin](https://github.com/gradle-dependency-analyze/gradle-dependency-analyze) that breaks the build on undeclared used dependencies/declared-unused dependencies) they might give you some pointers on how to generate a similar report for gradle.

Regarding 2) I'm with Jeremy that allowing to only list the vulnerabilities of direct dependencies would defeat the goal of this project. I see no sense in distinguishing reports on direct versus transitive dependencies (reporting might be improved to help you asses how the vulnerable transitive dependency was brought into your dependency tree, but it should always be reported. Because in the end your project is to be considered vulnerable unless proven to be unaffected due its vulnerable classes on your project classpath)

**Comment by jeremylong** [comment]
@aikebah I have been trying to come up with an easier way for Maven and Gradle to display the dependency tree for transitive deps.  Something like adding a row above related dependencies that shows the path: 

Hierarchy
`org.junit.jupiter:junit-jupiter-api -> org.apiguardian:apiguardian-api`
