### ISSUE TITLE
PostgreSQL JDBC driver vulnerability CVE-2022-21724 not reported

### ISSUE THREAD

**Issue by ahubold** [dependency-check/DependencyCheck#4085]
**Describe the bug**

The vulnerability CVE-2022-21724 isn't reported when using postgresql jdbc driver version 42.2.24 (org.postgresql:postgresql:42.2.24) from https://github.com/pgjdbc/pgjdbc

The report shows the following discovered identifiers for the postgresql-42.2.24.jar file:

```
pkg:maven/org.postgresql/postgresql@42.2.24 (Confidence:High)
cpe:2.3:a:postgresql:postgresql:42.2.24:*:*:*:*:*:*:* (Confidence:Highest)
cpe:2.3:a:postgresql:postgresql_jdbc_driver:42.2.24:*:*:*:*:*:*:*  (Confidence:Low)
```

When I download https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.json.gz, I can see that CVE-2022-21724 is associated with a different CPE `cpe:2.3:a:postgresql:pgjdbc:*:*:*:*:*:*:*:*`, which sounds like that could be the issue?

**Version of dependency-check used**
The problem occurs using version 6.5.3 of the maven plugin.

**Log file**
Skipped, sorry. I can provide one if needed.

**To Reproduce**
1. Have a maven project with dependency on org.postgresql:postgresql:42.2.24
2. Run "mvn org.owasp:dependency-check-maven:6.5.3:aggregate"

**Expected behavior**
CVE-2022-21724 is reported

**Comment by ahubold** [comment]
maybe also related to #1712

**Comment by aikebah** [comment]
It's more likely related to NVD CPE identifiers maintenance/cleanup - I expect the pgjdbc to be the future-proof replacement of the postgresql_jdbc_driver - so we need to help DependencyCheck establish the relationship between the `org.postgresql:postgresql` maven GA-coordinate and the `postgresql:pgjdbc` CPE-coordinate. Such cases is what we have the [hints-file](https://jeremylong.github.io/DependencyCheck/general/hints.html) for, so that should be doable to include in the base-hints of a future release (meanwhile you could get rid of this false negative locally by a well-written hintsfile)

Thanks for bringing it to our attention.

**Comment by aikebah** [comment]
Looks like currently both coordinates (`postgresql:postgresql_jdbc_driver` and `postgresql:pgjdbc`) are still active non-deprecated CPE coordinates at the NVD
