### ISSUE TITLE
CVE detection and "package" (gav) identifiers notation

### ISSUE THREAD

**Issue by srius** [dependency-check/DependencyCheck#4091]
Hi all,

I currently work on a project based on Java Quarkus framework, using Dependency Check CLI via Jenkins plugin. I recently updated to last 6.5.3 version as a lot a Quarkus FP were fixed in previous releases.

Nevertheless, I am not able to get it works as my dependencies are not tagged with a "package" identifier, whereas recent Quarkus FP fixes use "gav" (ie. package) notation. That is my explanation of the behavior, but maybe I am wrong.

For example, see https://github.com/jeremylong/DependencyCheck/issues/3945 fix
```
    <suppress base="true">
        <notes><![CDATA[
            fp per #3945 & #3943
            ]]></notes>
        <packageUrl regex="true">^pkg:maven/io\.quarkus/quarkus\-hibernate\-orm.*$</packageUrl>
        <cpe>cpe:/a:hibernate:hibernate_orm</cpe>
    </suppress>
```

Unfortunately no "package" identifier is set in the report, what I think it is the explanation for the CVE to be reported and not suppressed as per the fix. Am I right ?
I deliberately put an old log4j2 dependency in my project to compare the analysis behavior. You can see the result in the attached HTML & XML reports. [reports.zip](https://github.com/jeremylong/DependencyCheck/files/8099414/reports.zip)

Am I doing something wrong ?

**Comment by aikebah** [comment]
From the looks of it you run the dependency-check CLI on a project folder? 

In that case it is recommended to have either the Nexus- [1] or the Central-analyzer [2] enabled in order to be able to determine the maven coordinates of libraries if the officially published binary build is used by your project.

Without maven coordinates the CLI can only go by the evidences discovered inside the jar. As many projects don't include the pom in the jar-file searching on Maven Central or an on-premise Nexus to establish the maven coordinates can greatly reduce the FP rate.
Without the maven coordinates the only way to suppress them would be by filehash or filename pattern, both of which are much more error-prone than the established maven gav-coordinate. The filehash would have to be included for each and every non-vulnerable version of a falsely matched library and a filename pattern is much more likely to be too broad than a pattern for the maven coordinates of a library. This is why we mostly use the maven gav-coordinates for the out-of-the-box internal suppressions.

[1] https://jeremylong.github.io/DependencyCheck/analyzers/nexus-analyzer.html
[2] https://jeremylong.github.io/DependencyCheck/analyzers/central-analyzer.html

**Comment by srius** [comment]
You were right.
I found that the team in charge of my underlying PaaS CI disabled those options (despite the CLI documentation warning), leading to no packages detection. Tested OK with "central" activated.

Thanks for your help !
