### ISSUE TITLE
[Jenkins plugin] Can't exclude files from scanner

### ISSUE THREAD

**Issue by Bekz7** [dependency-check/DependencyCheck#4182]
Hi,

With Jenkins plugin, I'm scanning the app, but the problem is I can't exclude files from the scanner.
I've tried by using ant pattern:  **--exclude "**/app-core/app-sniffer/app-plugin/**"**
and also by:  **--exclude "../test/app/src/app-core/app-sniffer/app-plugin/**"**
Both examples are on the provided screen. So what I'm doing wrong?

![image](https://user-images.githubusercontent.com/32139703/157847925-56ac71d1-4019-4c3f-a3df-6b7199d35c80.png)

**Comment by Bekz7** [comment]
Hi,
I am bringing up the above topic again, can anyone help with this topic?

**Comment by aikebah** [comment]
You are scanning the contents of the app-core folder. I don't think you have an app-core folder nested in there, nor a folder test alongside your app-core folder, so both patterns will not match any of your files.

So try what happens if you use a proper relative path from the app-core folder. Pretty sure that your files will be excluded as expected.

**Comment by aikebah** [comment]
So that would be `--exclude "app-sniffer/app-plugin/**"`
