### ISSUE TITLE
Deletion of released versions / tags

### ISSUE THREAD

**Issue by hashworks** [dependency-check/DependencyCheck#4276]
A few minutes ago, you released 7.0.2, which I subsequently implemented in various templates and build scripts. Shortly after that, you removed that tag, causing them to fail.

Could you avoid this in the future? To me, tags/versions are immutable references to a commit. If you need to adjust something, a new tag/version would be better.

**Comment by jeremylong** [comment]
if you were paying attention - the release build failed, no artifacts were published, etc. your upgrade would have failed. Instead of watching for the tags you should watch for the actual release https://github.com/jeremylong/DependencyCheck/releases. 

Also, the 7.0.2 release is occurring right now...

**Comment by hashworks** [comment]
Alright. I've adjusted my monitoring to your releases.
