### ISSUE TITLE
backward compatibility database ?

### ISSUE THREAD

**Issue by kaimago** [dependency-check/DependencyCheck#429]
Is it possible to use one external DB for different versions of DC ?
For example version 2.9 and 3.0.

In my company a lof of people use DC with different versions. 
So it's a lot of work to provide a new database for every DDL change.

**Comment by jeremylong** [comment]
Schema changes have been rare. I will look into changing the schema version check to be more of a minimum version. Initial thoughts we would ensure any instance of DC using the 3.x schema could use any higher 3.x schema. If we had to implement a breaking change we would increment to 4.x.

**Comment by jeremylong** [comment]
A change has been made so that if the major schema version number is the same and the expected minor database schema number is less then or equal to the expected minor version the database can be used.  Not sure if that reads correctly - so here are a few examples.

dependency-check 1.3.5-SNAPSHOT uses a schema version of `3.0`. When new schema versions are released with new versions of dependency-check (this is rare) 1.3.5-SNAPSHOT will be able to use databases with a schema version of 3.1, 3.2, 3.3, .... However, when the database schema version is changed to 4.0 dependency-check 1.3.5-SNAPSHOT will not be able to use the database.

Note, only a version of dependency-check with the exact same schema version can perform an update on the database.

**Comment by jeremylong** [comment]
This functionality will be released with 1.3.5.
