### ISSUE TITLE
[FP]: reload4j-1.2.19.jar: CVE-2020-9493, CVE-2022-23307

### ISSUE THREAD

**Issue by arshadmohammad** [dependency-check/DependencyCheck#4316]
### Package URl

pkg:maven/ch.qos.reload4j/reload4j@1.2.19

### CPE

cpe:2.3:a:apache:log4j:1.2.19:*:*:*:*:*:*:*

### CVE

CVE-2020-9493, CVE-2022-23307

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

6.5.3

### Description

As per below information both CVE-2020-9493 and CVE-2022-23307 are fixed in reload4j release 1.2.19
https://github.com/qos-ch/reload4j/issues/21
https://github.com/qos-ch/reload4j/commit/64902fe18ce5a5dd40487051a2f6231d9fbbe9b0

But those two CVEs are still reported in dependency check.
Pls correct the CVE database for reload4j  or lets us know if the mentioned changes are not considered as the fix for those CVEs

References:
https://issues.apache.org/jira/browse/ZOOKEEPER-4510

**Comment by aikebah** [comment]
Awaiting an update from NIST NVD before processing this FP, as suppressing the log4j CPE right now would yield false negatives on the CVEs that reload4j fixed only in the 1.2.18.x releases with x>0. Based on earlier experience with them expect that I can process this FP within a few business days. For local use you can temporarily add the listed suppression in case of reload4j 1.2.18.3 or newer to your suppression filter.

**Comment by arshadmohammad** [comment]
No worries, we will prefer waiting few business days over suppressing the CVEs.
Thanks @aikebah for working on this issue.

**Comment by arshadmohammad** [comment]
The CVEs are still reported. is there anything still pending in this issue?

**Comment by aikebah** [comment]
As you can see in this ticket it's fix is scheduled for the 7.1.0 release, which means it will be reported by ODC until release 7.1.0 is made.
False positives do not magically disappear. Scheduling its suppression at first had to wait for NVD to add reload4j (versions lower than 2.19) to the applicable log4j1 CVEs, otherwise we would creating false negatives. As NVD is updated we scheduled addition of suppressing the FP CPE match for the next release.

**Comment by arshadmohammad** [comment]
ok, thanks for the details.
