### ISSUE TITLE
MySQL Connector/J Misidentified as MySQL Server

### ISSUE THREAD

**Issue by InfoSec812** [dependency-check/DependencyCheck#434]
A project I have uses MySQL's Connector/J for JDBC and is included via Maven. When I use the DependencyCheck maven plugin, it identifies the MySQL JDBC driver artifact as being vulnerable, but all of the referenced vulnerabilities are for the MySQL server application and not in any way related to the JDBC driver. 

[Dependency-Check Report.pdf](https://github.com/jeremylong/DependencyCheck/files/78002/Dependency-Check.Report.pdf)

**Comment by InfoSec812** [comment]
And it misses the 1 CVE for MySQL Connector/J that I DID find manually:

https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-2575

**Comment by delgurth** [comment]
@InfoSec812 that CVE it misses is correct, since that CVE is about 5.1.34 and below and you are using 5.1.38. But indeed it's very annoying that the MySQL connector is checked against all mysql server CVE's.

But I'm afraid that DependencyCheck itself can't deal with this problem since it's NVD that is using the same identifier for the mysql server as the mysql java connect component, as you can see in the same CVE:

 cpe:/a:mysql:mysql:5.1.34 and previous versions

For a server component CVE (for example: https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-0437) the same identifier is used:

 cpe:/a:mysql:mysql:5.1.38

And this is why it's matched.

**Comment by jeremylong** [comment]
@delgurth Thanks for the great explanation - I've been tied up with life so haven't been able to respond as quickly as I like to the issues.

The other reason that we have left the connectors being flagged as the server is that it may show an issue in your environment (i.e. using an older version of the DB itself that is vulnerable).

**Comment by asbachb** [comment]
Anyone tried to get in contact with NVD in order to ask them to create an own cpe for the connectors? For **mariadb-java-client** it's the same problem.

**Comment by jeremylong** [comment]
This is a common issue for all db drivers/connectors. I have not contacted the NVD regarding separate CPEs for the database vs. the connector/client. The reasons I don't blanket suppress these across the board is that sometimes they are valid and sometimes they show an issue in your environment.

**Comment by asbachb** [comment]
I understand this but I think it would be a more convenient way to add a reference to the real database you're using instead of using the client for mapping.

I wrote a mail to the nvd cpe contact address. When I get them right they just need an xml according their cpe definition spec.
