### ISSUE TITLE
[FP]: CVE-2019-10782, CVE-2019-9658 on com.pinterest:ktlint:0.45.2

### ISSUE THREAD

**Issue by ipat500** [dependency-check/DependencyCheck#4344]
### Package URl

pkg:maven/com.pinterest.ktlint/ktlint-reporter-checkstyle@0.45.2

### CPE

`cpe:2.3:a:ktlint_project:ktlint:0.45.2:*:*:*:*:*:*:*`

### CVE

CVE-2019-10782, CVE-2019-9658

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.0.4.1

### Description

This seems to be a false positive to me, but I am not 100% sure.

The HTML report lists the CPEs as the following, however I wasn't sure if I should enter both above:
```
cpe:2.3:a:checkstyle:checkstyle:0.45.2:*:*:*:*:*:*:*
cpe:2.3:a:ktlint_project:ktlint:0.45.2:*:*:*:*:*:*:*
```

**Comment by aikebah** [comment]
The CPE to fill in the field would've been the other one - the CPE that is falsely identified by dependencycheck for the library. 

The suppression listed above by the automated workflow is now wrongfully suppressing the ktlint CPE. Had you filled CPE with the checkstyle CPE the suppression listed above would hold the proper suppression.
In any case - the fix is expected to be delivered in the 7.1.0 release.
