### ISSUE TITLE
Hard coded spring CPE namespace has changed

### ISSUE THREAD

**Issue by jasonparallel** [dependency-check/DependencyCheck#4354]
NVD has moved from cpe:2.3:a:springsource:spring_framework to cpe:2.3:a:vmware:spring_framework

The old CPE looks to be hard coded several places in the plugin https://github.com/jeremylong/DependencyCheck/blob/3ed3ee06e84c5c086b960ae80364a68e910b66ca/core/src/main/java/org/owasp/dependencycheck/analyzer/FalsePositiveAnalyzer.java#L168

**Comment by aikebah** [comment]
@jeremylong This code appears to be effectively dead after 0e1540627cce1dc6ff85f2bbd10206b3e7dad05e. IIUC the softwareIdentifier for maven libraries would be a packageURL after that, so it's value would no longer start with `org.springframework.`, but with `pkg:maven/org.springframework.`

Is my understanding correct, or are there cases that would still hit with a SoftwareIdentifier beginning with `org.springframework.`? 

If those cases exist the existing code would require change, as there is an unintended off-by-one index for the start of the mustContains: `org.springframework.retry:spring-retry:1.3.2` would yield `.retry` rather than `retry`. It worked for the intended suppression of spring_framework, but it would also trigger false negatives (as the CPEs for the non-spring_framework spring libraries would not contain the dot and thus also get suppressed would this code still work).

If they don't exist I think it's better to remove the code and work with the regular suppressions to get rid of the FP matches.

**Comment by OrangeDog** [comment]
This suppression seems to work well for the moment
```xml
<suppress>
    <notes>Prevent all sub-groups from being detected as part of the core Spring Framework</notes>
    <gav regex="true">org\.springframework\.[^:]+.*</gav>
    <cpe>cpe:/a:vmware:spring_framework</cpe>
</suppress>
```

**Comment by aikebah** [comment]
`[^:]+` is not even needed `<gav regex="true">org\.springframework\..*</gav>` should suffice. There will never be a trailing dot on the groupId of spring_framework libraries, so there is no need to check for anything following the dot before the colon. The scheduled fix of the FPs in the PR uses the packageUrl instead of the gav. IIRC gav-based suppression only works reliably for the maven plugin.

To avoid hitting a historical CPE of spring_framework from the older datastreams (not sure whether all have been updated by now by NVD) I included the historical CPEs in the suppression.

```xml
  <suppress>
      <notes><![CDATA[
     Spring-framework libraries always have groupId org.springframework with no further extension, so suppress the
     spring_framework CPE on other Spring libraries
     ]]></notes>
      <packageUrl regex="true">^pkg:maven/org\.springframework\..*$</packageUrl>
      <cpe>cpe:/a:springsource:spring_framework</cpe>
      <cpe>cpe:/a:pivotal_software:spring_framework</cpe>
      <cpe>cpe:/a:vmware:spring_framework</cpe>
  </suppress>
```
