### ISSUE TITLE
How do I know if it is a false positive?

### ISSUE THREAD

**Issue by lako12** [dependency-check/DependencyCheck#4375]
Hello,

I have recently started using dependency-check.

I don't understand how I know if a dependency is a false positive.
I've seen a lot of issues but I can't interpret them. What does the response from the bot mean with the maven dependency and the reference to a test result?
If the test result is success, does this mean it is a false positive?

Thanks

**Comment by aikebah** [comment]
The results of the bot are just a help for inclusion of the false-positive into our suppressions. They are not a judgement on the validity (if the automation could decide on that we would have coded DependencyCheck differently to take the same evaluation into account).

To determine whether a hit by dependency-check is a false-positive or not you need to evaluate the evidences and identifiers provided.

Most of the reported false positives fall into the category 'dependencycheck clearly linked the library to some completely different piece of software (CPE)' so that the false-positive is obvious. 
In other, less obvious cases libraries may have similar names that would require more investigation whether it's a misidentification or a valid classification. Both would be suppressed with a CPE-suppression.

Another type of false positives (which requires more detailed insight in the librarystructure of a project) are vulnerabilities that apply to a set of libraries jointly identified with a single identifier (CPE) in the vulnerability dataset of the NIST NVD, but are known to apply only to a specific sublibrary that you don't depend on (for example: a CVE is in the server-side library and you only depend on the client-side library).
These you would suppress with a vulnerability-suppression (cve, cwe or vulnerabilityName) so that you avoid suppressing other vulnerabilities registered on the same CPE that actually do apply to the library you depend on.

All of these require some research and human judgement. Often starting off from the identified software (CPE) and the various references in the report.

See also [How to read the report](https://jeremylong.github.io/DependencyCheck/general/thereport.html) in our documentation.

**Comment by lako12** [comment]
@aikebah So if I believe a dependency is a false-positive, should I open an issue and you will check if it really is?
How do I know if the outcome of my report is positive or negative?
If the outcome is positive then in a future version that dependency will not be reported in the report?

Thanks

**Comment by aikebah** [comment]
If you believe that a vulnerability is a false positive and the library is an open and freely available library (private/proprietary libraries are typically up to the users to include in their own suppression file) you can file a FP report and me or one of the other maintainers will judge whether we agree and then either fix that false positive, or provide feedback in the ticket why we don't agree.
When the outcome is positive the ticket will be closed when the fix enters the main branch. It will then no longer be reported in the report starting with the first version of dependencycheck released after closing the ticket (typically the version in which it will be fixed will be indicated in the milestone of the ticket upon closure)

**Comment by lako12** [comment]
Perfect! thank you very much! all very clear

**Comment by jeremylong** [comment]
Also note - many users of dependency-check maintain their own suppression list rather then wait for suppressions to be incorporated into the core product.

**Comment by areguru** [comment]
We handle this by checking if the component is flagged as vulnerable in sonatype oss-index, which is as far as I know the most up-to-date source for this:
https://ossindex.sonatype.org/

For instance today we got the following error:

> One or more dependencies were identified with known vulnerabilities in ...:
`spring-session-core-2.6.1.jar` (pkg:maven/org.springframework.session/spring-session-core@2.6.1, `cpe:2.3:a:vmware:spring_framework:2.6.1:*:*:*:*:*:*:*) `: CVE-2022-22965

This version of spring-session core does not have any vulnerabilities:
https://ossindex.sonatype.org/component/pkg:maven/org.springframework.session/spring-session-core

You can also see that the cpe specifies spring_framework:2.6.1, which is not the same as spring-session-core, which explains the false positive error.

We will then have to make a new suppress-element in `src/main/maven/dependency-check-suppression.xml`
to suppress the warning. 
Then it would be nice to post the bug here if nobody else has done it.

You should also read the CVE-description which will also tell you that it is a false positive warning.

The local suppression element today as an example:
```
  <suppress>
         <notes><![CDATA[
         2022-04-22 <reference to jira-issue to have 'paper trail'>
         Short description
         ]]></notes>
         <cpe>cpe:2.3:a:vmware:spring_framework:2.6.1:*:*:*:*:*:*:*</cpe>
         <cve>CVE-2022-22965</cve>
   </suppress>
```

This is a bit lazy, taking the cpe and CVE in the false positive, and it's important to note that this is only safe because we use version 5.3.19 of org.springframework-components. 
CVE-2022-22965 is a serious vulnerability for springframework versions < 5.3.18!
https://help.sonatype.com/docs/important-announcements/find-and-fix-springshell

If somebody reading this know best practice for a suppression-case like this please comment.

Since suppressing an error locally is quite serious if you make an error, we always make a local jira-issue as reference, and make a Pull Request before merging this into production. This also makes it easier to remove entries later. Dependency-check will probably fix the error in time and we will move on with other versions.

Then you should test that this works by running something like this command-line, depending on your local configuration:
`mvn -Duse-dependency-check-maven dependency-check:check`

**Comment by aikebah** [comment]
@areguru You don't want to use the suppression that you quote as there is no guard under which conditions you would want to suppress the FP - which means the suppression is **ALWAYS** applied, even when the CVE is a true positive (or the CPE the proper match).

With what you propose 
```
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-beans</artifactId>
                <version>5.3.16</version>
            </dependency>
```
as a dependency will not yield CVE-2022-22965 as a vulnerability.
You don't want to build your filters in a way that assumes that Spring-framework is in an up-to-date version beyond the fix of a suppressed vulnerability.

**Comment by areguru** [comment]
@aikebah Yes, I agree, and as I wrote:

> This is a bit lazy, taking the cpe and CVE in the false positive, and it's important to note that this is only safe because we use version 5.3.19 of org.springframework-components.
...
If somebody reading this know best practice for a suppression-case like this please comment.

So what would be the right suppression? It's easy and lazy to do the example, but what I really would want to express is that 
a transitive dependency of  `org.springframework.session:spring-session-data-redis:jar:2.6.1`or higher should never trigger CVE-2022-22965

**Comment by aikebah** [comment]
@areguru The clean way is along the way that multiple false-positive Spring libraries get fixed in 7.1.0 for their incorrect linking to Spring-framework (as they are from other projects than the core framework project, which get different CPEs):

```
   <suppress>
        <notes><![CDATA[
       Spring-framework libraries always have groupId org.springframework with no further extension, so suppress the
       spring_framework CPE on other Spring libraries
       ]]></notes>
        <packageUrl regex="true">^pkg:maven/org\.springframework\..*$</packageUrl>
        <cpe>cpe:/a:springsource:spring_framework</cpe>
        <cpe>cpe:/a:pivotal_software:spring_framework</cpe>
        <cpe>cpe:/a:vmware:spring_framework</cpe>
    </suppress>
```

The crucial part of it is finding a fitting packageUrl that will not trigger suppressions of true-positives (which is something you definitely want to avoid as it would result in a false-negative, which can be considered worse than a false positive as you would assume to not be vulnerable while in fact you are)

In the case of Spring framework that was easy, as the core framework libraries always use `org.springframework` groupId and other spring projects have `org.springframework.<something>` as the groupId. So if there is a dot after the org.springframework part of the groupId it is for certain not part of the framework itself and therefor not subject to the vulnerabilities listed in NVD data for the Spring framework.

Note that you can never assert that 'transitive dependencies of a specific library version x or above' are not vulnerable to a certain CVE as you can never tell which transitive dependencies will emerge over time. You can only assert that certain libraries are not affected by a CVE.

**Comment by mehradn7** [comment]
@aikebah Thank you for your clear explanations, these are really helpful. 
What if there is no CPE for `org.springframework.<something> ` in the NVD database? Can you guarantee that all packageUrls suppressed this way have an associated existing CPE?

**Comment by aikebah** [comment]
Based on Spring's project naming libraries with a groupId of `org.springframework.<something>` will be something else than the core of spring-framework and therefor it will be considered by NIST a different product, which gets it's own product name in the CPE

**Comment by mehradn7** [comment]
@aikebah I have just ran a Dependency-Check CLI scan (v7.1.0), the org.springframework.plugin dependencies are indeed not associated anymore with spring_framework CPE, however they are not affected to any CPE at all: 

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/35630862/167118566-e21c745c-1960-4c92-bd28-de46745c9363.png">

Thus if a vulnerability on spring-plugin-core appears tomorrow, it means that it will not be detected by Dependency-Check because there is no associated CPE entry in the NVD database?

**Comment by aikebah** [comment]
@mehradn7 If a vulnerability is found in one of the org.springframework.plugin projects the NIST NVD will allocate a CPE that can be expected to include the 'plugin' phrase which is very likely to trigger the CPE guessing logic in DependencyCheck to associate it with the library. Guarantees can no be given (see also the documentation on the False negatives), but for this specific scenario it is very likely to be associated as the CPE will likely include spring/springframework and plugin.
That it is currently not associated to any is because there is no sufficiently fitting CPE in the CPEs present in the vulnerability datastreams of the NVD.

**Comment by mehradn7** [comment]
Thanks for the answer. I hope in such case NIST NVD will be reactive to create an associated CPE.
