### ISSUE TITLE
Stuck after promting "[INFO] Skipping NVD check since last check was within 4 hours."

### ISSUE THREAD

**Issue by ebraheem95** [dependency-check/DependencyCheck#4413]
I installed the certificates and the update when smoothly but its always stopping after the org.owasp.dependencycheck.data.update.EngineVersionCheck:143.
[logs.txt](https://github.com/jeremylong/DependencyCheck/files/8562300/logs.txt)

**Comment by aikebah** [comment]
@ebraheem95 From the symptoms I suspect that you have a (proxied) network connectivity issue. It appears you can connect (otherwise you should get a connectTimeout after ten seconds), but never receive data when trying to obtain the 'latest version' information from `https://jeremylong.github.io/DependencyCheck/current.txt`.

**Comment by aikebah** [comment]
While the root cause appears to be in your network connectivity it also classifies as a bug, as there should be a (configurable) timeout on the reads in addition to the timeout on the connect. DependencyCheck should not wait indefinitely for data that never shows up.

**Comment by ebraheem95** [comment]
Thanks a lot, its true that was the issue. I changed the network and everything worked fine.
