### ISSUE TITLE
[FP]: CVE's on internal subprojects

### ISSUE THREAD

**Issue by jelmerdeboer** [dependency-check/DependencyCheck#4479]
### Package URl

pkg:maven/internal.proj/file-import@0.10.4 & pkg:maven/internal.proj/data-model@0.10.4

### CPE

`cpe:/a:file_project:file`, `cpe:/a:file:file` & `cpe:/a:model_project:model`

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

7.1.0

### Description

We're using a multi-project setup in gradle. When executing the `dependencyCheckAggregate`, the jars of the internal projects used triggers the CPE and it produces false positive results.

**Comment by aikebah** [comment]
See documentation - for internal projects you'll have to create your own suppressions

**Comment by chris-melman** [comment]
Hi @aikebah the problem is that its a but that it matches while the name of the project is differently.
the name is file-import while the cpe has only the name file part in the name (cpe:/a:file_project:file). So I think its a bug it is doing partial matches on internal projects

**Comment by aikebah** [comment]
Not a bug, it is by design doing partial matches on the components of dash/underscore separated names as these are often composites that include the name under which the 'vendor' and/or 'product' is known.

**Comment by chris-melman** [comment]
And the only way to exclude checks on your own sub-projects is by suppressing them?  It is a pity that this is not configurable to exclude gradle sub-projects by default but thanks for explanation.

**Comment by aikebah** [comment]
Either suppress the CPEs, or ensure in other ways that you don't use internal project versions that depend transitively on vulnerable libraries and exclude the dependency (as excluding dependencies als excludes their transitive dependencies you need some other way to ensure that your project does not depend on a version of an internal project that itself depends transitively on a vulnerable version of a public library).

Depending on your internal naming conventions you may be able to do something along the likes of (as cpe matching is a prefix-match):

```xml
<suppress>
      <notes><![CDATA[
      Internal project, no CPE in NVD database will be applicable to it, so suppress any match as a FP
      ]]></notes>
      <packageUrl regex="true">^pkg:maven/com.mycompany.*$</packageUrl>
      <cpe>cpe:/a:</cpe>
   </suppress>
```

which you could either store locally in a project suppression file, or publish somewhere on the intranet and reference as one of the suppressionFiles in the project configuration (you can configure more than one and you can use URLs, they are merged together into the overall suppression rules set used by the scan).

In my day-job we have a central suppression file which takes common false positives found in multiple projects (and would include such company internal projects where applicable), maintained by a team of lead developers hosted on the intranet (maintained under version control, so that its full version history is audited) and a dedicated project suppression file checked in with the sources of a project for the left-overs where the project team can store its triaged project-specific false positives and 'mitigated by compensating controls' vulnerabilities.
