### ISSUE TITLE
[FP]: CVE 2022-22965 on all org.springframework packages instead of spring-webmvc and spring-webflux

### ISSUE THREAD

**Issue by mehradn7** [dependency-check/DependencyCheck#4510]
### Package URl

pkg:maven/org.springframework/spring-tx@5.3.9

### CPE

`cpe:2.3:a:pivotal_software:spring_framework:5.3.9:*:*:*:*:*:*:*`

### CVE

CVE-2022-22965

### ODC Integration

{"label"=>"CLI"}

### ODC Version

7.1.0

### Description

The Spring4Shell CVE (CVE-2022-22965) is associated with all Maven packages from org.springframework (e.g. spring-tx, spring-core, spring-aop, ...) whereas according to the official Spring communication, only spring-webmvc, spring-webflux (and possibly spring-beans) are affected (see the 'Am I impacted' section): https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement

I was wondering if we could add a suppression rule to restrict CVE-2022-22965 to only these 3 packages rather than having all the packages with groupId "org.springframework" considered as vulnerable.

**Comment by aikebah** [comment]
We don't have an intention to micromanage the vulnerabilities of a large framework that is always released as a whole with one version resulting in a single CPE vendor/product classification at the NIST NVD.
When you want to stay on unpatched versions of the framework for components unaffected by a vulnerability in another part you have to revert to your own suppression files.

Note that in 2021 the OWASP Top 10 changed 'using components with known vulnerabilities (A09 in 2017)' to 'vulnerable or outdated components (A06)' to reflect the need to remain up-to-date with your components on a regular basis so that you can respond quickly when a critical security fix is only released for the latest version of a component.
So the better response from security perspective would be an upgrade of the framework version, even if the components you currently depend on are not the ones in which the current new vulnerability exists.
