### ISSUE TITLE
Scan Gradle dependencies with the Docker image

### ISSUE THREAD

**Issue by Samuel-Schober-USU** [dependency-check/DependencyCheck#4556]
Is it possible to scan Gradle dependencies by using the Docker image?
My use case would be a CI job which executes the dependency check without knowing the project type.

I already implemented this, but the only dependency which was found, was the `gradle-wrapper.jar`. 
Following CI script is basically just executed inside a `owasp/dependency-check` container
```sh
/usr/share/dependency-check/bin/dependency-check.sh --project $CI_PROJECT_PATH --out dependency-check-reports --scan . --enableExperimental --data dependency-check-database
```

Am I missing something or is there no way around using the Gradle plugin for scanning Gradle dependencies?

**Comment by aikebah** [comment]
The CLI scans files in folder(s) as the apparent dependencies of your project. So unless you force your regular CI to always copy all dependencies of a project into some folder of the workspace there is no way around using the gradle plugin.
Supporting analysis of gradle buildfiles would require the CLI to re-implement the entire gradle dependency resolution system. Similarly it also doesn't support scanning a maven project for that matter.

Using the gradle plugin will also improve the proper allocation of CPEs to the discovered dependencies, resulting in fewer FPs due to CPE-mismatch. The CLI has only the filenames and metadata to go by, while the gradle plugin can also involve the dependency coordinate information obtained from the gradle dependency management.

**Comment by Samuel-Schober-USU** [comment]
Okay, than I will have to rethink this global CI job.

Thank you for the quick answer :)
