### ISSUE TITLE
[FP]: spring-core-5.3.19.jar CVE-2016-1000027

### ISSUE THREAD

**Issue by urld** [dependency-check/DependencyCheck#4558]
### Package URl

pkg:maven/org.springframework/spring-core@5.3.19

### CPE

`cpe:2.3:a:vmware:spring_framework:*:*:*:*:*:*:*:* versions up to (excluding) 6.0.0`

### CVE

CVE-2016-1000027

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.1.0

### Description

According to https://nvd.nist.gov/vuln/detail/CVE-2016-1000027#VulnChangeHistorySection the cpe version range was recently changed to 6.0.0 but it is not clear why. The description text still mentions 5.3.16.

**Comment by wolframhaussig** [comment]
I also stumbled over this vulnerability. In the Spring Repo there is a discussion ongoing: https://github.com/spring-projects/spring-framework/issues/24434

After reading the thread I think this is not a false positive because the vulnerability is there and was only removed in the Spring 6.x branch. For version 4.x and 5.x only the user can decide if the vulnerability may be used by an attacker: https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#remoting-httpinvoker

**Comment by aikebah** [comment]
A suppression of this FP (for among others spring-core) is scheduled for the next release. You can use a similar suppression until it's released:

```xml
    <suppress>
        <notes><![CDATA[
   Issue is in spring-web and will only be fixed by Spring in their next major release.
   So suppressing it for the spring-framework components other than spring-web.
   https://github.com/spring-projects/spring-framework/issues/25379 (deprecation only in current 5.x versions)
   https://github.com/spring-projects/spring-framework/commit/5822f1bf85b94fd15f9829914b065b1c61910c7d (removal in 6.0.0-M1)
   ]]></notes>
        <packageUrl regex="true">^pkg:maven/(?!org\.springframework/spring\-web@).*$</packageUrl>
        <cve>CVE-2016-1000027</cve>
    </suppress>
```

**Comment by nickstolwijk** [comment]
I just updated to 7.1.1 but it still fails if I remove my manual suppression. Should this ticket be reopened or should I log a new ticket?
