### ISSUE TITLE
The command line and plug-in execution results are different

### ISSUE THREAD

**Issue by other-shore-f** [dependency-check/DependencyCheck#4607]
The result of using command line and Gradle plugin to scan the same project is different. What is the reason

**Comment by mprins** [comment]
Since grade has a notion of dependencies and the commandline doesn't (it only knows files) that can be expected

**Comment by other-shore-f** [comment]
OK， thank

**Comment by other-shore-f** [comment]
Excuse me, is there any way to make the scanning result of the command line the same as that of the gradle plug-in

**Comment by aikebah** [comment]
> Excuse me, is there any way to make the scanning result of the command line the same as that of the gradle plug-in

No guarantees, as the CLI is likely to get false positives, but the only way to potentially get close is to make gradle copy all dependencies to some folder and then scan that folder with the CLI.

There is a reason these integrations with build tools exist: knowledge within the build tool libraries on how to interpret dependency configuration in project definitions like build.gradle.
 There is no use in trying to replicate gradle's own dependency resolution mechanisms instead of  building an integration into the gradle plugin ecosystem and getting proper dependency resolution 'the gradle way' for free.

**Comment by aikebah** [comment]
The CLI is just some sort of 'last resort' to scan binary distributions if project sources are not available. Not a tool to scan project sources.

**Comment by other-shore-f** [comment]
OK，Thank you very much.

**Comment by other-shore-f** [comment]
Hello, excuse me. When the Maven plug-in is executing, it will exit after detecting a high-risk vulnerability. Is this the setting

**Comment by other-shore-f** [comment]
Hello, excuse me. When I execute MVN install, when the dependency check plug-in executes, the execution exits after detecting high-risk vulnerabilities. Is this the setting

**Comment by other-shore-f** [comment]
Hello, excuse me. When I execute `mvn install`, when the `dependency check` plug-in executes, the execution exits after detecting high-risk vulnerabilities. Is this the setting

**Comment by other-shore-f** [comment]
@aikebah 
Hello, excuse me. When I execute `mvn install`, when the `dependency check` plug-in executes, the execution exits after detecting high-risk vulnerabilities. Is this the setting

**Comment by aikebah** [comment]
If it exits (fails the build) on discovery of a vulnerability then you have a configuration that includes a 'failBuildOnCvss' value.

The default is to only report and not break (unless there were fatal errors running the analysis)

**Comment by other-shore-f** [comment]
thank  @aikebah
