### ISSUE TITLE
ERROR: Job failed: exit code 137

### ISSUE THREAD

**Issue by john047** [dependency-check/DependencyCheck#4609]
Hello,

Pipeline failed with exit code 137.
Version of DependencyCheck is 7.1.0.
gitlab-runner version 14.8.2.
job:
```
owasp:
  stage: dependency-check
  image: ${DOCKER_REGISTRY}/owasp:7.1.0
 
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^release-.*$/

  script:
    - /bin/sh /src/dependency-check/bin/dependency-check.sh --project ${CI_PROJECT_NAME} --scan ${CI_PROJECT_DIR} --out owasp
  artifacts:
    paths:
      - owasp
    expire_in: 2 weeks
```

During merge branch I got following logs:
```
[INFO] Download Complete for NVD CVE - 2019  (4049 ms)
[INFO] Download Started for NVD CVE - 2020
[INFO] Processing Complete for NVD CVE - 2002  (120013 ms)
[INFO] Processing Started for NVD CVE - 2006
[INFO] Download Complete for NVD CVE - 2020  (4042 ms)
[INFO] Download Started for NVD CVE - 2021
[INFO] Download Complete for NVD CVE - 2021  (3638 ms)
[INFO] Download Started for NVD CVE - 2022
[INFO] Download Complete for NVD CVE - 2022  (1989 ms)
[INFO] Processing Complete for NVD CVE - 2005  (68390 ms)
[INFO] Processing Started for NVD CVE - 2007
[INFO] Processing Complete for NVD CVE - 2006  (94337 ms)
[INFO] Processing Started for NVD CVE - 2008
Killed
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 137
```

Also this service consumed a lot of runner resources about 70% of the processor and the rest of the work was paralyzed.
What is it connected with and what are the system requirements for this tool?

**Comment by aikebah** [comment]
Exit 137 indicates that your gitlab runner infrastructure killed the process. Most likely due to exceeding some resource limit.

At the time it was killed it was still busy creating the CVE database with all historical vullnerability data of the NIST NVD datastreams.

Best approach with the container would be mounting in a persistent data folder, to avoid that each time you run the container you need to recreate the database (or if you have no way to mount a folder but can host a relational database somewhere use the 'central database' approach)

**Comment by aikebah** [comment]
BTW your processing speed of importing the CVE database appears unusually slow to me, likely due to your virtualization environment (I assume it's gitlab runners using docker containers on virtualized servers in a datacenter).

On native Apple M1 pro processing (openjdk17 aarch) the 2006 dataset is processed in `[INFO] Processing Complete for NVD CVE - 2006  (5327 ms)`, on virtualized processing (Apple M1 Pro, Rosetta x64 emulation, openjdk8 x64) in `[INFO] Processing Complete for NVD CVE - 2006  (14883 ms)`, your processing is taking 8 times as much as the x64 Rosetta run and 18 times at much as the native run `[INFO] Processing Complete for NVD CVE - 2006  (94337 ms)`.

As the process of importing NVD data does many small inserts/updates to the H2 database the prime suspect to look into would be relatively high I/O latencies.

**Comment by john047** [comment]
Thanks for your reply.

**Comment by KazakhSpy** [comment]
@john047 hello!
I also ran into this problem. How did you fix it?
