### ISSUE TITLE
The dependency check doesn't report the security issue

### ISSUE THREAD

**Issue by ThanhTuan1695** [dependency-check/DependencyCheck#4618]
Hi All, 

I have 2 projects, 

project 1 is a component that is delivery as the library.

Project 2 is a project will use project 1 as a jar file. 

For both 2 projects, i do the compile and have the same way to run the dependency-check scan
When i do the dependency-check for both projects. Project 1 returns no cve after scanning.
But the weird thing that  project 2 returned a lot of cves which is belong to project 1. 
i tried to figure out the problem but could not find the reason. 

i would love to ask for advice. what should i check here? 

Big Thanks

**Comment by aikebah** [comment]
If you read the part on "how dependencycheck works" you should get some clarity on how this may happen.

The project1 dependency of project2 is searched for all kinds of strings (metadata) that may hint at what the vendor / product / version of the library (jar file) are in order to try and establish the CPE that would be used in the NIST NVD vulnerability database. Most likely your project1 has textual similarity with some products.

Also note that dependencycheck is notdesigned to look for "known vulnerabilities in your project", but for "known vulnerabilities in the dependencies of your project"

**Comment by ThanhTuan1695** [comment]
Thanks @aikebah for the answer. 

I think you misunderstand with this sentence "But the weird thing that project 2 returned a lot of cves which is belong to project 1.". I mean the running dependency check in project2 is  reporting  the cve belong to dependency that was using in project1 which was not found in the project1's scan.

**Comment by aikebah** [comment]
Then you likely scan project1 in the wrong way, e.g. use the CLI to scan a maven or gradle project source dir.

**Comment by ThanhTuan1695** [comment]
I would say the same way to build and running the scan.
I ran it on my local machine to check as the same ressult. 

I just follow the step for 2 both projects: 
1. mvn install
2. dependency check with the full source as root directory.

THen i got result. 
I think this is very basic. that why i have no clue why this happen. 
Thanks for your advice but seem i would love to have more advice from other.

**Comment by aikebah** [comment]
run the maven plugin instead of the CLI:

`mvn org.owasp:dependency-check-maven:7.1.1:check install`

instead of `mvn install` followed by dependencycheck CLI

if you must use the CLI (not recommended as it increases the chances of false positives), then you need to `mvn dependency:copy-dependencies` before running the dependencycheck CLI and run the CLI on the project root (so that source+target folders are scanned)

**Comment by ThanhTuan1695** [comment]
Hi @aikebah, thanks for your answers.
it helps solve the problem.
