### ISSUE TITLE
Wrong CVE identified for bundle with manifest-header that contains string "liquibase"

### ISSUE THREAD

**Issue by sennew** [dependency-check/DependencyCheck#4623]
Hi All,

We are using the dependency-check plugin in our osgi-project. 

But we are experiencing some issues when we specify a custom manifest-header in the MANIFEST.MF file that contains the string "liquibase".
When we specify a custom manifest-header that contains the string "liquibase", the bundle/jar is identified as a liquibase bundle and we get the CVE issue CVE-2022-0839.

`proefrol-domain-2.1.29.jar (pkg:maven/be.cipal.proefrol/proefrol-domain@2.1.29, cpe:2.3:a:liquibase:liquibase:2.1.29:*:*:*:*:*:*:*) : CVE-2022-0839
`

Can anybody help me with this issue? Is this a bug in the source or is this expected behavior? 

Thanks in advance!

**Comment by aikebah** [comment]
Expected behaviour - [How dependency check works](https://jeremylong.github.io/DependencyCheck/general/internals.html)

**Comment by sennew** [comment]
@aikebah, i don't really understand why it is expected behavior. The bundle has no dependency to liquibase. 
There is just a property manually added to the MANIFEST.MF of this bundle that contains the string "liquibase".
I also don't understand why the dependency-check complains about a liquibase issue with the version of my bundle.

`proefrol-domain-**2.1.29**.jar (pkg:maven/be.cipal.proefrol/proefrol-domain@2.1.29, cpe:2.3:a:liquibase:liquibase:**2.1.29**:*:*:*:*:*:*:*) : CVE-2022-0839`

If i may be honest this can't be expected behavior.

**Comment by aikebah** [comment]
Beacause, as explained in the linked documentation DC gathers 'evidences' from various files among which is the MANIFEST.MF file and then does a text search trying to find 'the best possible matches' among the actual CPEs found in Nist NVDs datastreams.

It is, as documented, known to produce false positive matches to unrelated CPEs as it will just pick the 'best available textual matches' from the known CPEs, which in your case makes it hit the liquibase CPE due to the match on the manifest property.
