### ISSUE TITLE
Is there a false positive about "set-value 2.0.1"

### ISSUE THREAD

**Issue by NPC-RX** [dependency-check/DependencyCheck#4626]
In a recent dependency check, we noticed a puzzling report.
The "set-value 2.0.1" is flagged as a vulnerable version , but the CVE details for the vulnerability indicate that "2.0.1" is a version outside the scope of the vulnerability.
Is this a false positive?
![dependency-version](https://user-images.githubusercontent.com/20533538/175865212-b188d91a-fad1-4066-99fc-2d07ef9f4c13.png)
![report-set-value2 0 1](https://user-images.githubusercontent.com/20533538/175865426-273e30ea-f0c7-4ae4-9e37-5e600e3cbf3b.png)
https://nvd.nist.gov/vuln/detail/CVE-2021-23440
![CVE-details](https://user-images.githubusercontent.com/20533538/175865438-39358d60-fbbc-496a-a475-dc40e4e9c406.png)

**Comment by aikebah** [comment]
Gut feel: reported as `CVE-2021-23440 (OSSINDEX)`

OSSINDEX has their own security researchers and they judge whether something was really fixed in a certain version, and if not, they register the CVE in their vulnerability database to also affect the versions released after the vulnerability was found. They don't take a documented 'do not use X' or a deprecation as a solution, as those still expose the developers to the potential risk and require further inspection to determine whether or not your project is affected by the risk embedded in your dependency.

Only if 'upgrade to version X' with no further action either resolves ot or make your build fail (when you were using the removed vulnerable method) they consider it fixed.

**Comment by aikebah** [comment]
Note: based on the comments in the PR the fix appears to not have been backported to the 2.x releases and only fixed in 4.x, so at first glance it appears OSSINDEX is right on marking 2.0.1 as vulnerable and NVD wrong on excluding it.
