### ISSUE TITLE
OWASP Dependency Check - gradle Plugin: JFrog/Artifactory artifactory repo which requires authorisation

### ISSUE THREAD

**Issue by elbaer** [dependency-check/DependencyCheck#4656]
Hi Jeremy,
regarding the issue https://github.com/jeremylong/DependencyCheck/issues/3028 I had a similar problem with  the grade plugin for the OWASP Dependency Check.
I did not find anything useful regarding the documentation https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html.

So I tried the following configuration which worked somehow:

```
cve {
  urlBase='authorization_required_artifactory_url'
  urlModified='authorization_required_artifactory_url'
  user='artifactory_username'
  password='artifactory_apitoken'
}
```

1. Question: Did this work by accident or did I stumble over the correct configuration?
2. Question: How to update the gradle plugin configuration documentation so future dudes like me don't run into the same problem? 

I hope this is the correct way to ask?

Regards,
Christian

**Comment by aikebah** [comment]
Regarding 1) I would have to consult the [sources of the plugin](https://github.com/dependency-check/dependency-check-gradle), but suspect that you managed to guess the appropriate configuration by accident.

Regarding 2) might be done by a PR against its source: https://github.com/jeremylong/DependencyCheck/blob/main/src/site/markdown/dependency-check-gradle/configuration.md

Currently preparing for the summer holidays, otherwise I might have picked up the source-digging to verify that your config 'works according to the intentions of the siurce', but if you've got the skill you might give it a try to research deeper with these references.

**Comment by elbaer** [comment]
I'm glad you kind of confirmed my assumption. Regarding the digging task: unfortunately I'm not a developer so my groovy knowledge is quiet limited.

**Comment by aikebah** [comment]
Back from holiday I checked and you did indeed succeed in guessing the correct and intended config
