### ISSUE TITLE
Python product evidence "__init__.py" source is more accurate than "file" source, but has lower confidence

### ISSUE THREAD

**Issue by biancajiang** [dependency-check/DependencyCheck#466]
The python API for spark from spark/python (spark download available from: http://spark.apache.org/downloads.html) has two dependencies identified: "pyspark" and "py4j".  Each package has two product evidences.  In both cases, the Evidence from source "**init**.py" is more accurate and relevant, but only "MEDIUM" confidence.  The value from "file" source is always "**init**" which is not helpful but it has "HIGH" confidence:

[Evidence{name=PackageName, source=**init**.py, value=pyspark, confidence=MEDIUM}, Evidence{name=name, source=file, value=**init**, confidence=HIGH}]

[Evidence{name=PackageName, source=**init**.py, value=py4j, confidence=MEDIUM}, Evidence{name=name, source=file, value=**init**, confidence=HIGH}]

we rely on confidence level to get the most relevant evidence and it works well so far. But this is a case where it does the opposite.  Should the "**init**.py" source get a higher confidence? Is there other considerations or a better way to get the most relevant evidence?  

If "**init**.py" in deed deserves a higher confidence, I'd be happy to provide a fix for it. 

Thanks.

**Comment by colezlaw** [comment]
I haven't looked at the Python analyzers yet, but will voice an opinion
anyway...

If an analyzer finds an **init**.py, it should add evidence for the
immediate parent folder. For example:
foo/
  bar/
    **init**.py

Should add a pretty high confidence finding that this is something called
"bar".

IDEALLY, it might recurse backwards and add evidence for any containing
folders which also contain an **init**.py. e.g.:

foo/
  bar/
    **init**.py
    baz/
      **init**.py
    frobozz/
      fizz/
        **init**.py

I see there should be the following evidences:

bar.baz (because baz and its immediate parent both contain **init**.py)
fizz (because fizz has **init**.py, but frobozz does not)

Any other .py files should have a lower confidence than the package
folders.

So looking at the example you provided, my opinion concurs with yours -
that both sets of evidence are correct, it's just that the confidence (IMO)
is reversed of what it should be. Or maybe if the FileAnalyzer didn't add
evidence at all if the filename is **init**.py - since the **init**.py
source already produces the desired result.

**Comment by jeremylong** [comment]
Completely agree; however, _I_ won't be able to get to this soon. If either of you want to look into fixing this it would be much appreciated.

--Jeremy

**Comment by biancajiang** [comment]
Thanks colezlaw!  The change looks exactly what we needed.  Although haven't tried until I figure out how to get the patch.

The parent folder is what we do on our own as a post-process after all analyzers are done. We do two things:
1. For configuration files identified (like configure, **init**.py files, etc, but not .jar files), if it's part of a compressed file, traverse to the closest parent compress file and take that as the package.
2. If the configuration files is not under a compressed file, take its immediate parent folder .

So it is more generic than unique to just Python.  Not sure if this is a desirable use case for other people as well.   For sure it can be discussed in a separate issue from this one.

**Comment by biancajiang** [comment]
This is working now.  Thanks!
