### ISSUE TITLE
Feature request: ignore potentially erroneous overly permissive software configurations

### ISSUE THREAD

**Issue by ascopes** [dependency-check/DependencyCheck#4675]
**Is your feature request related to a problem? Please describe.**

As many people may be aware, https://nvd.nist.gov/vuln/detail/CVE-2022-31569 (part of https://github.com/github/securitylab/issues/669) was opened a couple of days ago which opens a CVE related to Flask path traversal (Python lib). The CVE itself has been marked with an overly permissive configuration pattern of `cpe:2.3:a:projects_project:projects:*:*:*:*:*:*:*:*`. This is clearly not intended, as it is very unlikely that a CVE would be so wide in scope that it should be able to match every version of every library that exists, across all programming languages. 

For example, the following dependencies get flagged because of this pattern:

```
[ERROR] jakarta.annotation-api-1.3.5.jar: CVE-2022-31569(9.3)
[ERROR] spring-cloud-commons-3.1.2.jar: CVE-2022-31569(9.3)
[ERROR] spring-kafka-2.8.6.jar: CVE-2022-31569(9.3)
[ERROR] spring-security-rsa-1.0.10.RELEASE.jar: CVE-2022-31569(9.3)
```

**Describe the solution you'd like**

I am wondering if it would be possible to consider implementing a feature that allows ignoring patterns that are match-all without any consideration as to the thing being matched. A starting point would probably be ignoring anything marked as purely wildcards to prevent this.

While this might sound like a poor solution, this would act as a failsafe to prevent countless production-ready systems being unable to deploy due to build failures when a mistake such as this occurs. The benefit of suppressing clearly erroneous mistakes such as this would prevent developers from considering temporarily disabling OSA scanning, which would be putting them at greater risk.

This feature could be toggled using a configuration flag in the Maven plugin `<configuration />` block.

**Describe alternatives you've considered**

- Manually suppress these issues - this is okay to do if you have only a few repositories. For
  organisations with hundreds or even thousands of repositories, this creates a large amount of
  work for having to suppress irrelevant CVEs.
- Vulnerability database should probably be preventing full wildcard CVEs - this is out of scope
  for this project as it is managed by a different organisation.
- Skipping OSA builds where possible until this issue is resolved - there is no time frame on
  when the overly permissive configuration will be amended, as this is down to the author or 
  another entity to consider. Disabling OSA is also highly undesirable because it may hide other
  potentially important and relevant vulnerabilities in the process.

**Comment by sjamaan** [comment]
As I understand it, this pertains specifically to the Flask vulnerability [as used in this repository](https://github.com/RipudamanKaushikDal/projects). The problem here is that this is just some random person's personal projects repository. It's not a proper *product*, but a CVE was nevertheless requested.

IIUC, the name "project" or "projects" got matched with anything that has "project" in its name. In the case for a project at my day job, it was a dependency being developed by the "Android Open Source Projects" team (which is the "developer name" or "vendor"). i.e.:

```
<evidence type="vendor" confidence="MEDIUM">
  <source>pom</source>
  <name>developer name</name>
  <value>The Android Open Source Projects</value>
</evidence>
```

**Comment by sjamaan** [comment]
Is this even considered good practice, to issue separate CVEs for every project using a subcomponent, which already had a CVE assigned to it?

**Comment by Horcrux7** [comment]
Such a pattern seems not very exotic. For example `cpe:2.3:a:apache:log4j:*:*:*:*:*:*:*:*` in https://nvd.nist.gov/vuln/detail/CVE-2021-44228

The problem is that `projects` has no significance. The risk that there are valid CVEs are ignored is high.

**Comment by skavanagh** [comment]
@Horcrux7 Agree with pattern point

> The problem is that projects has no significance. 

Really CVE itself has no significance. Like @sjamaan pointed out it's just some [random person's project](https://github.com/RipudamanKaushikDal/projects). It looks like just a throw away repo with everything but the kitchen sink in it. And the submitter didn't have good details to generete the CPE (cause there aren't any since it's not consumable) and it somehow was approved and published.

**Comment by skavanagh** [comment]
[CVE-2022-31569](https://nvd.nist.gov/vuln/detail/CVE-2022-31569) has been rejected. All is well!
