### ISSUE TITLE
setting autoUpdate to false causes "Old database schema identified", but schema is up to date

### ISSUE THREAD

**Issue by vrevelas** [dependency-check/DependencyCheck#4733]
**Describe the bug**
When running "mvn dependency-check:check" using version 7.1.1 of the plugin with `<autoUpdate>false</autoUpdate>`, I get "DatabaseException: Unable to connect to the dependency-check database". If I set `<autoUpdate>true</autoUpdate>` it works fine. Reverting back to `<autoUpdate>false</autoUpdate>` causes the error to reappear. Running "mvn dependency-check:update-only" succeeds but doesn't fix the issue.

I have tried dropping the database and re-creating it using the [initialize_postgres.sql](https://github.com/jeremylong/DependencyCheck/blob/e52aea2bab23efb568f29100543f49d6420fce91/core/src/main/resources/data/initialize_postgres.sql) file on the 7.1.1 tag and populating it with dependency-check:update-only using the 7.1.1 plugin, but running dependency-check:check with `<autoUpdate>false</autoUpdate>` continues to produce the same error.

**Version of dependency-check used**
The problem occurs using version 7.1.1 of the maven plugin with a postgresql 14.0 database. The version of the postgresql dependency used is 42.3.0, and the same issue occurs on the latest 42.4.1.

**Log file**
```
$ mvn dependency-check:check
...
[ERROR] 	DatabaseException: Unable to connect to the dependency-check database
[ERROR] 		caused by DatabaseException: Database schema does not match this version of dependency-check
[ERROR] 		caused by DatabaseException: Old database schema identified - please execute dependency-check without the no-update configuration to continue
...
```
I can provide the complete log if needed.

**To Reproduce**
* Create a postgres database using [initialize_postgres.sql](https://github.com/jeremylong/DependencyCheck/blob/e52aea2bab23efb568f29100543f49d6420fce91/core/src/main/resources/data/initialize_postgres.sql)
* create a pom.xml containing the following entry in `<plugins>`:
```
      <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>7.1.1</version>
        <dependencies>
          <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.4.1</version>
          </dependency>
        </dependencies>
        <configuration>
          <databaseDriverName>org.postgresql.Driver</databaseDriverName>
          <connectionString>jdbc:postgresql://hostname.of.database.server/dependencycheck</connectionString>
          <databaseUser>dcuser</databaseUser>
          <databasePassword>notTheRealPassword</databasePassword>
          <autoUpdate>false</autoUpdate>
        </configuration>
      </plugin>
```
* run `mvn dependency-check:update-only`
* run `mvn dependency-check:check`

**Expected behavior**
A successful run of the plugin - instead I get the error message in the logs section.

**Additional context**
I'm happy to provide any extra information if needed

**Comment by 13CSherman** [comment]
I am having a similar issue with upgrading to 7.1.1. I use our own mirror hosted on a postgres database. But I use the cli tool. I see the postgres.sql file hasn't been updated in 13 months.

**Comment by albertwangnz** [comment]
I think the bug is caused by this commit https://github.com/jeremylong/DependencyCheck/commit/811a9ebdb5f62e278612690b56836b6eb2b11389.

In the commit, @aikebah updated the data.version in [core/src/main/resources/dependencycheck.properties](https://github.com/jeremylong/DependencyCheck/blob/562a4b3b5efdc496f57c0f623add5cea374461f0/core/src/main/resources/dependencycheck.properties) to 5.2.1. Meanwhile, he updated the database schema file and its version in [core/src/main/resources/data/initialize.sql](https://github.com/jeremylong/DependencyCheck/blob/562a4b3b5efdc496f57c0f623add5cea374461f0/core/src/main/resources/data/initialize.sql) to 5.2.1 as well.

However, he didn't update the other initialize files, like [core/src/main/resources/data/initialize_postgres.sql](https://github.com/jeremylong/DependencyCheck/blob/562a4b3b5efdc496f57c0f623add5cea374461f0/core/src/main/resources/data/initialize_postgres.sql).

Therefore, when you install your Dependency Check by using [core/src/main/resources/data/initialize_postgres.sql](https://github.com/jeremylong/DependencyCheck/blob/562a4b3b5efdc496f57c0f623add5cea374461f0/core/src/main/resources/data/initialize_postgres.sql), and when you run the goal check, your data.version is 5.2.1, but your database schema version is 5.2. And if you configure autoUpdate to false, an exception will be thrown in the file [core/src/main/java/org/owasp/dependencycheck/data/nvdcve/DatabaseManager.java](https://github.com/jeremylong/DependencyCheck/blob/562a4b3b5efdc496f57c0f623add5cea374461f0/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/DatabaseManager.java) in the method [ensureSchemaVersion](https://github.com/jeremylong/DependencyCheck/blob/562a4b3b5efdc496f57c0f623add5cea374461f0/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/DatabaseManager.java#L484), from the line [512](https://github.com/jeremylong/DependencyCheck/blob/562a4b3b5efdc496f57c0f623add5cea374461f0/core/src/main/java/org/owasp/dependencycheck/data/nvdcve/DatabaseManager.java#L512).
