### ISSUE TITLE
RubyBundleAuditAnalyzer only report dependencies with vulnerabilities

### ISSUE THREAD

**Issue by biancajiang** [dependency-check/DependencyCheck#477]
RubyBundleAuditAnalyzer works great to report vulnerabilities.  But it ignores other dependencies.

RubyGemspecAnalyzer, FileNameAnalyzer(?) and other analyzers tries to report on all dependencies it can find.  

So for Ruby, RubyBundleAuditAnalyzer and RubyGemspecAnalyzer compliments each other, rather than overlap.  RubyGemspecAnalyzer also provides Vendor evidences (that we use) while RubyBundleAuditAnalyzer does not.

So instead of disable RubyGemspecAnalyzer when bundle-audit is available, maybe the better thing to do is to make RubyBundleAuditAnalyzer precedes RubyGemspecAnalyzer.  So that when Evidence from both exist, RubyBundleAuditAnalyzer can take precedence.   Similar to Jar file of a maven package:  when multiple evidence from multiple analyzers exist, the order of sources is consistent - central always tops the list.

If this sounds reasonable, I'd be happy to provide a PR for it.

**Comment by biancajiang** [comment]
RubyBundleAuditAnalyzer also seems to find dependencies from Gemfile.lock's code only, and not actual gems present.  Thus dependencies found by bundle-audit tends to be all from one Gemfile.lock file on the file system (hence #476).  This is different from dependencies from other analyzers that each dependency tends to map to a unique file on the file system.

**Comment by biancajiang** [comment]
I realized when both RubyBundleAuditAnalyzer and RubyGemspecAnalyzer are present, they will be creating different Dependency objects for the same package b/c they are based on different config files (Gemfile vs .gemspec).  Hence the "noise".

One option can be to make one as the "relatedDependencies" of the other to remove the "noise" but still able to keep the evidences from both sides.

Thoughts?

**Comment by jeremylong** [comment]
I believe it was implemented to disable the Gem Spec Analyzer  when the Bundle Audit exists because it was _easy_ and we expect Bundler Audit to be much more accurate (with regards to false negatives and false positives). However, you are 100%  correct and I believe we should be running both analizers. This will provide a complete bill of materials for a Ruby project.

If you have time to work on mergining the dependency artifacts produced by both engines (this might require a new analyzer that runs in the [PRE_IDENTIFIER_ANALYSIS](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/analyzer/AnalysisPhase.java#L42) that looks at the dependencies and tries to bundle them together. There would be similarities to the [DependencyBundlingAnalyzer](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/analyzer/DependencyBundlingAnalyzer.java). It might be easier to add a flag in the dependency object to flag that it originated from gemspec vs the bundler audit.  

Thanks for pointing this out!

--Jeremy

**Comment by biancajiang** [comment]
Jeremy, thanks for your reply on this one and #466.

For Ruby bundler, in addition to bundle-audit analyzer which only report on vulnerable dependencies, the bundler itself actually creates completely resolved specifications/*.gemspec files during installing the dependent gems.  Either of these two commands:

`bundle install --deployment`  (if Gemfile.lock exists)
`bundle install --path vendor/bundle`   (if Gemfile exists but not Gemfile.lock)

installs the dependent gems from where the Gemfile is, under:
_vendor/bundle/<ruby>/<version>/gems/_
_vendor/bundle/<ruby>/<version>/specifications/*.gemspec_

So leveraging Ruby bundler installed gems can give a pretty good picture of the Ruby app's dependencies, especially given not every gem comes with a fully resolved .gemspec file (many of them are scripts with no regex'able text values.

I created a new analyzer for Ruby bundler which extends the existing Gem Spec Analyzer.  And as you suggested, used  DependencyBundlingAnalyzer to merge the gems found by gem spec analyzer (based on original .gemspec files under _vendor/bundle/<ruby>/<version>/gems/_)  and the new Ruby bundler analyzer (based on resolved .gemspec files under _vendor/bundle/<ruby>/<version>/specifications)_.   The result looks pretty good so far.

However merging the dependencies from these .gemspec based analyzers and those from bundle-audit analyzer is tricky, since bundle-audit's output does not include any file, path or id to track back to the scanned resources.  I'm trying to see any support from bundle-audit: https://github.com/rubysec/bundler-audit/issues/141

I need more polishing and test cases for the Ruby improvements before creating a PR.  It's under branch right now:
https://github.com/biancajiang/DependencyCheck/tree/ruby_dependency
