### ISSUE TITLE
[FP]: CVE-2020-36448 incorrectly detected on pkg:maven/com.github.ben-manes.caffeine/caffeine@2.9.1

### ISSUE THREAD

**Issue by RichardBradley** [dependency-check/DependencyCheck#4780]
### Package URl

pkg:maven/com.github.ben-manes.caffeine/caffeine@2.9.1

### CPE

`cpe:2.3:a:cache_project:cache:2.9.1:*:*:*:*:*:*:*`

### CVE

CVE-2020-36448

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

5.3.0

### Description

I have a Java / Maven project that's using caffeine@2.9.1

Maven dependency check has flagged this as CVE-2020-36448 , but that's a Rust vuln, not a Java vuln. So I think this is a false positive.

I don't really see how the "cpe" matches the maven package here, so I don't understand how this has come about.

My dep tree to caffeine looks like this:

```
[INFO] +- io.dropwizard:dropwizard-jdbi3:jar:1.3.29:compile
[INFO] |  +- io.dropwizard:dropwizard-db:jar:1.3.29:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-jdbc:jar:9.0.41:compile
[INFO] |  |     \- org.apache.tomcat:tomcat-juli:jar:9.0.41:compile
[INFO] |  +- org.jdbi:jdbi3-core:jar:3.18.0:compile
[INFO] |  |  +- org.antlr:antlr4-runtime:jar:4.7.2:compile
[INFO] |  |  +- io.leangen.geantyref:geantyref:jar:1.3.7:compile
[INFO] |  |  \- com.github.ben-manes.caffeine:caffeine:jar:2.9.1:compile
```

See also https://github.com/jeremylong/DependencyCheck/issues/3968 which looks similar

Your bot seems to have a problem with the pkg: url. Here's the linked URL from my report: [pkg:maven/com.github.ben-manes.caffeine/caffeine@2.9.1](https://ossindex.sonatype.org/component/pkg:maven/com.github.ben-manes.caffeine/caffeine@2.9.1?utm_source=dependency-check&utm_medium=integration&utm_content=5.3.0)

**Comment by aikebah** [comment]
@RichardBradley note that even at the time of your report 5.3.0 was already a very outdated version of DependencyCheck

**Comment by RichardBradley** [comment]
Thanks, good point.

I can confirm that updating to DependencyCheck v7.2.1 has cleared this false positive, so I'll close this issue.

I was invoking with just:

```
mvn --batch-mode \
    -DfailBuildOnAnyVulnerability=true \
    -DsuppressionFiles=dependency-check-maven-suppressions.xml \
    compile \
    org.owasp:dependency-check-maven:check
```

... which was using the version found in ~/.m2, i.e. the version that was current when I first ran this on my machine.
I have fixed by changing this to:

```
mvn --batch-mode \
    -DfailBuildOnAnyVulnerability=true \
    -DsuppressionFiles=dependency-check-maven-suppressions.xml \
    compile \
    org.owasp:dependency-check-maven:LATEST:check
```

**Comment by aikebah** [comment]
@RichardBradley that's likely because you have version 5.3.0 in your pom-file or one of it's parents, as maven would otherwise check the repository for the latest release. So make sure (if the project defining the version of the plugin is under active development) to also bump the version there.

The strategy we use in our company (not sure whether it would equally apply to your project) is to have a central parent pom `<pluginManagement>` use a property for the version.
Within that central parent pom we define its default value to the latest available version of DependencyCheck at the time of its release.

For the (local or CI/Buildserver) build one can override the version of DependencyCheck that will be used by setting that same property in the maven settings.xml (~/.m2/settings.xml). 
By editing the central settings.xml in our CI we can make sure that all builds will run with the latest version we have accepted for our internal use (typically updated to the latest version soon after we've seen notice of its release and verified that it should not break our CI. 

We have the central parent + CI server settings.xml configured such that during our CI builds dependency-check will always run as part of the verify phase, with a configured CVSS threshold that will fail the build, forcing the developers to triage the issue and either suppress or upgrade to get a passing build.
Developers on their local system can either run it explicitly on demand or add some further configuration in their settings.xml to always run it on verify (and they can use the same property to set the version to use for all of the local runs of dependency-check)

**Comment by RichardBradley** [comment]
> that's likely because you have version 5.3.0 in your pom-file or one of it's parents, as maven would otherwise check the repository for the latest release

I don't have dependency-check at any version referenced in any of my pom files; I was solely invoking it from command-line mvn by name. It appears that in that usage, mvn will use a version you already have in ~/.m2 without checking for updates (if you don't specify a version).
