### ISSUE TITLE
Malfunctionel dependency-of-dependency check

### ISSUE THREAD

**Issue by Moeth** [dependency-check/DependencyCheck#4793]
We have a maven project with dependencies to (belong others)
- org.vaadin.addon:easyuploads:jar:8.0.1:compile (see https://mvnrepository.com/artifact/org.vaadin.addon/easyuploads/8.0.1) 
- and com.vaadin:vaadin-server:jar:8.15.2:compile (see https://mvnrepository.com/artifact/com.vaadin/vaadin-server/8.15.2)

If we execute "mvn org.owasp:dependency-check-maven:7.1.2:check -DfailBuildOnCVSS=7" we get errors like

[ERROR] easyuploads-8.0.1.jar: CVE-2021-31409(7.5)

but if I see this correctly, this is only marked as insecure, because it has a dependency to com.vaadin:vaadin-server:8.6.0 (see https://mvnrepository.com/artifact/org.vaadin.addon/easyuploads/8.0.1) -> but we arent using this version! How can we disable this useless dependency-of-dependency check and check only these dependencies we are really using? Or are we doing something completely wrong?

**Comment by mprins** [comment]
please read the documentation at https://jeremylong.github.io/DependencyCheck/general/internals.html and specifically how to add a suppression file https://jeremylong.github.io/DependencyCheck/general/hints.html

**Comment by Moeth** [comment]
I am not sure what you want to tell me. Maintain suppression-files for obvious false-positives is not the way I want to go. Especially this is only an example and we have multiple projects which are affected. Shall we maintain these all manually only because we havent configured the tool not correctly?

**Comment by aikebah** [comment]
@Moeth What @mprins is trying to get across is that 'because of how dependencycheck works' (see the documentation linked) your library `easyuploads` is identified by the logic of dependencycheck as the product `vaadin`. Your library `easyuploads` has version 8.0.1 so that triggers DependencyCheck to report any CVE-issues on product `vaadin` up to (including) versions 8.0.1 as vulnerabilities related to your library.

That your project also happens to have a dependency on vaadin has nothing to do with it as the vaadin library that you depend on will be analysed/reported on separately.

For cases like this (since there is a good chance that multiple of your projects also transitively depend on internal projects that trigger these false positives) I would recommend a centrally hosted (fileshare/folder or webpage are both viable options) suppression-file that you include in the project configuration. That way you have to investigate/code the suppressions only once and can re-use them for each internal project).
We use a similar approach, where we host the central suppressions on an internal web-url and have inclusion of that suppressionfile and, if present, a local project suppressionfile, in a top-level company-wide parent-pom. See https://github.com/jeremylong/DependencyCheck/issues/3947#issuecomment-1005024826 for an example of such a setup.

**Comment by Moeth** [comment]
Hi @aikebah 

I was afraid to hear this. Of course, declaring an suppressionlist is a possible solution. And declaring it company-wide is better than declaring it for each project. Better would be declaring it on a global place. 

But this sounds me too much handworking and error phrone for a problem where a technical solution shouldnt be a problem.

In any case, thank you very much @aikebah @mprins

**Comment by jeremylong** [comment]
This is a FP that should be resolved in core. I've opened #4806.  @Moeth for FP like this please use the false positive issue type.

**Comment by aikebah** [comment]
@jeremylong Thanks for correcting my misreading the issue as a 'company private' false-positive
