### ISSUE TITLE
Use of CPE information to reduce false positives

### ISSUE THREAD

**Issue by swapnilsm** [dependency-check/DependencyCheck#483]
Dependency Check on finding `org.apache.hive:hive-ant` jar reports the vulnerability which is actually the vulnerability in the main Apache Hive product and not the jar. 
Can we somehow get the information about the reported CPE whether it's about the jar or a product? 
If we could then we will be able to reduce the false positives by very high margin. I did some evaluation of dependency check against one of the commercial products available for vulnerability check in market. And I found the above reported issue being the main cause of false positives.

**Comment by jeremylong** [comment]
The problem lies with how [dependency-check works](http://jeremylong.github.io/DependencyCheck/general/internals.html) and the available [information in the NVD](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-7521). The best option to resolve some of these FP (at the moment) is to submit a PR updating the [base suppression xml](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/resources/dependencycheck-base-suppression.xml) file or open an issue and post sufficient details that I can reproduce the FP.

Trust me, I completely understand the issues with false posittives and I am trying to figure out a better solution. However, what causes the FP is also what allows ODC to identify true positives that some of the commercial tools miss - but take that with a grain of salt, there are pluses and minuses to all of these tools. I'm sure there are instances where the commercial tools flag something that ODC misses.

So back to your comment - do you think there is something in the CPE that can be used to reduce false positives more then what is already being done?

**Comment by swapnilsm** [comment]
@jeremylong I completely agree with you on that. I also tried finding something which could help us in reducing false positives but didn't find anything promising. 

After that I went on performing an exercise myself. I went through all the vulnerabilities published in month of March'16 in NVD. And here are the statistics I came across. 
- _Total vulnerabilities:_ **330**
- _Vulnerabilities related to JARs available on mvnrepository.com:_ **6 (1 in every 55)**
- _Average time to map a vulnerability to JAR based on available information:_ **10 minutes**
- _Average time to reject a vulnerability because of not being related to any JAR:_ **30 seconds**
- _Overall time to map vulnerabilities in a month:_ **172 minutes ~3 hours (less than an hour per week)**

Looking at above numbers, I strongly feel that maintaining such DB where we map JARs to CVEs is neither difficult nor time consuming plus then the results will be almost 100% correct. 

What do you think about it? Was there some other reason of not adopting this approach of having JAR to CVE mapped DB?

**Comment by jeremylong** [comment]
While this may not sound like a lot of time, it adds up. I work on this project in my spare time. If one started maintaining a database like this it becomes a commitment that would get very old after a year.

I actually have another idea on how to make this more accurate over time using automated community feedback... more to come on this later.
