### ISSUE TITLE
Dependency check cli tool html data missing in csv format

### ISSUE THREAD

**Issue by Teja1805** [dependency-check/DependencyCheck#4868]
Hi

When we analysie the jar file using the tool and geerate the report i have noticed that some data from html report is missing in csv format.

for example in html report there is a related dependencies option if we eexpand that we get instances of vulnerabilities that data is missing in csv report format.

Kindly look into it and fix it

**Comment by aikebah** [comment]
It is on purpose. The CSV format doesn't lend itself for a hierarchical nested set of information like we can do in the HTML report.
The 'related dependencies' mechanism is built to not report the same set of CVEs for each detected component of a framework. In the HTML report the other libraries are mentioned hierarchically nested inside the library that was taken as the 'representer libray' of the framework.

If libraries are improperly bundled together as being the same product (CPE) we would like to know, but not reporting the CVEs duplicate for each related library is by design. When upgrading a framework to a newer version it can be expected that all libs of that framework (the related dependencies as listed in the HTML and omitted from the CSV) will be upgraded at the same time.

If the related dependencies are of interest to you you should use one of the hierarchical report formats (HTML, JSON, XML).

**Comment by Teja1805** [comment]
Hi Team,

Thanks for the quick reply!

is it possible for your team to develop a script to actually pass the html
data/json/xml in to csv which will implement the functionality as described
above

Regards,
Teja.
