### ISSUE TITLE
Scope of support for C-based libraries

### ISSUE THREAD

**Issue by richardabarker** [dependency-check/DependencyCheck#492]
Hi, I get very few results when running dependency-check (mostly against C library code). For example, zlib is not recognised, but there are 18 versions of gnu:zlib in the database. (Admittedly not the latest version -- 1.2.8 from April 2013 -- but I also tried it against 1.1.4, which is in there.)

Is there a list of libraries that can be detected anywhere please?

Cheers.
__
Rich.

**Comment by jeremylong** [comment]
I was hesitant about adding any C/C++ support as I was concerned that not enough "evidence" could be collected from the build files (currently autoconf and CMake files are scanned, see documentation [here](http://jeremylong.github.io/DependencyCheck/analyzers/index.html). Please see [How dependency-check works](http://jeremylong.github.io/DependencyCheck/general/internals.html). Because only a limited amount of textual information is available in the build files the ability to match the textual evidence against the CPEs in the NVD would be limited.

Can you tell me when you ran dependency-check was any evidence collected against zlib?

**Comment by richardabarker** [comment]
Yeah, I appreciate it's difficult to do. That's why I was wondering if there was a list of known detections.

To answer your question - for zlib 1.2.8 (the latest) it collects the evidence of:
- file name configure
- file name CMakeLists
- CMakeLists.txt Project zlib

The version is available in the CMakeLists.txt file (`set(VERSION "1.2.8")`), which is missed, but configure extracts it from zlib.h, so it's fair that it does not detect that without a specific zlib analyzer.

I think the older zlib I tried it with didn't clearly define the project or the version in CMakeLists.txt, but I'd have to rerun it to double check.

P.S. zlib is only an example here - I ran it on a directory containing twelve third-party libraries and only two were correctly identified. (Although the "fault" here is seemingly more on a lack of standardisation than detection errors.)

**Comment by jeremylong** [comment]
The only library that a specific analyzer was written for was OpenSSL. The work effort to create analyzers for each library would be significant.

Due to the false positive rates associated with a  few a the analyzers I am going to flag them as  experimental and require specifically turning on the experimental flag. See issue #498.
