### ISSUE TITLE
Not finding dependency

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#4970]
Latest version not finding dependencies in my build,

1. catalina-ha.jar
2. catalina-ssi.jar
3. catalina-storeconfig.jar
4. catalina-tribes.jar
These are present in my build but tool not finding them. But 5.2.3 found them.

Can u please help me regarding this....

**Comment by jeremylong** [comment]
We would need to see an example project that demonstrates the issue. I'm not sure how your project is configured, what integration you are using (maven, gradle, cli)?

**Comment by parimala-kathir** [comment]
For the same build 5.2.3 provides those dependencies but 7.1.2 not

**Comment by jeremylong** [comment]
And I have a ton of projects that produce the same dependency list from 5.2.3 to 7.1.2. Do you have a project that can be shared that shows the problem? Otherwise there isn't much we can do...

**Comment by parimala-kathir** [comment]
May i get 5.2.3 source and document for How to run that source

**Comment by parimala-kathir** [comment]
Need release zip for 5.2.3

**Comment by jeremylong** [comment]
5.2.3 is no longer supported and when bintray was taken offline - so where the releases. The oldest available release is: https://github.com/jeremylong/DependencyCheck/releases/tag/v5.3.2

You could try building it locally: https://github.com/jeremylong/DependencyCheck/tree/v5.2.3

However, the changes made since 5.2.3 - I don't even know how someone is using ODC 5.2.3 as the datasources used no longer exist: https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.0
