### ISSUE TITLE
which "configurations" dependencies are built?

### ISSUE THREAD

**Issue by 2013kaa** [dependency-check/DependencyCheck#4994]
Hey
If I understand correctly, then in the case of using the plugin for gradle, "gradle dependencies" are launched.
Can you tell me for which "configurations" dependencies are built? Probably it makes no sense to collect for "jacocoAnt", "testRuntime" and others.

**Comment by aikebah** [comment]
Not a gradle user myself, but see [the documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html) in our github-pages.

It depends on your usage (or not, for projects using the factory defaults) of the skipConfigurations/scanConfigurations/skipTestGroups properties. By default it scans all configurations.

**Comment by 2013kaa** [comment]
@aikebah  You are right)) all configurations are scanned.
My real purpose of the question was to find out what configuration to scan so that only the dependencies of the application itself remain.

**Comment by 2013kaa** [comment]
Will it be enough if I only specify "skipTestGroups"?

**Comment by aikebah** [comment]
Well, in my personal view you want to avoid known vulnerable libraries anywhere in the development pipeline (read: hooks for supply-chain attacks) as well as application runtime. 
It's just a matter of priority and those in the 'build' stages of my software typically would end up lower on the priority list than comparable vulnerabilities that are also used by the final product at runtime (as the attack surface for the running application is typically larger than that of the software development pipeline)

For build-breaking setups I would prefer skipping the test-related dependencies, which matches with the default settings, as most (including me for most purposes) will use the tool with the purpose of scanning the final product.
The default for 'skipTestGroups' is already true, so that would not require explicit configuration. If you still get unwanted reported vulnerabilities in items 'just for test' that would mean that either it's not part of the testGroups concept (dependency groups beginning with 'test', so e.g. your 'jacocoAnt' will not match) or the testGroups filtering has a bug.

**Comment by 2013kaa** [comment]
@aikebah Thank you for your attention and reply!)
