### ISSUE TITLE
NIST Api Key to solve intermittent fail to download

### ISSUE THREAD

**Issue by lorirava** [dependency-check/DependencyCheck#4998]
I can't see how to use the NIST Api Key. 
It's very important to reduce download error due to the rate limit imposed by the NIST: https://nvd.nist.gov/developers/start-here

I'm having intermittent fail due to _Unable to download NVD CVE 2010_

Am I doing something wrong?
I'm running dep check for a lot of projects every night.

**Comment by jeremylong** [comment]
We are not yet using the NVD APIs; we are currently using the NVD Data Feeds which will be retired in September 2023 (might have the date slightly off).

See https://jeremylong.github.io/DependencyCheck/data/index.html. One of the options would be to mirror the NVD locally so that you do not have these issues. If you are using the CLI or Docker image - consider shifting to use `owasp/dependency-check-action`. This is an image that is updated nightly with the latest data.

Another mistake a lot of people make is not caching the data directory. If you save the data directory you won't have to re-download all of the NVD data every day.

**Comment by lorirava** [comment]
it's very very useful your comment. I will check owasp/dependency-check-action in future for sure. 
About caching data, I saw something about this, but I didn't find anythings in doc. is it enought caching the data folder?

**Comment by jeremylong** [comment]
Yes - just keep the data folder between executions.
