### ISSUE TITLE
Error on importing CVE-2008-2079 from NVD XML files into MySQL database

### ISSUE THREAD

**Issue by xthk** [dependency-check/DependencyCheck#503]
Hi all,

while running:

```
dependency-check.sh \
  --cveValidForHours 0 \
  --log dependency-check.log \
  --dbDriverName com.mysql.jdbc.Driver \
  --dbDriverPath mysql-connector-java-5.1.39/mysql-connector-java-5.1.39-bin.jar \
  --connectionString="jdbc:mysql://localhost:3306/dependencycheck" \
  --updateonly
```

I got these errors (in the logfile):

```
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '30517-47953' for key 'PRIMARY'
```

and

```
DEBUG - Unable to update details for org.owasp.dependencycheck.data.update.NvdCveUpdater org.owasp.dependencycheck.data.update.exception.UpdateException: org.xml.sax.SAXException: Error updating 'CVE-2008-2079'
```

Which on the console produces:

```
[WARN] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
```

Return code of dependency-check.sh is "0", but that is another issue (#215) I think.

Logs (console and debug log) are attached. Please let me know if further information is needed.
- [output.txt](https://github.com/jeremylong/DependencyCheck/files/281869/output.txt)
- [dependency-check.log.txt](https://github.com/jeremylong/DependencyCheck/files/281867/dependency-check.log.txt)

**Comment by jabbrwcky** [comment]
So I dug a bit into the problem which turns out to be some paradoxon apparently, as the TreeSet of Vulnerability contains two entries for CPE `cpe:/a:mysql:mysql:5.1.28a`: one with `previousVersion = null` and one with `previousVersion="1"`.

This is baffling as the previousVersion apparently is not used in the compareTo() implementation of VulnerableSoftware, which just compares the CPE strings. The CPE strings are completely the same.

I tried adding some unit tests with the data from CVE-2008-2079 but in the unit tests TreeSet behaves as expected.

It is somehow connected to the fact that TreeSet utilizes compareTo instead of equals to find duplicates, because the issue vanishes if I change the implementation in Vulnerability from SortedSet/TreeSet to Set/HashSet (which uses equals to prevent duplicates).

If sorting is not really crucial, the fastest fix would to use a HashSet for storing the vulnerabilities and sort it on the fly  whenever it is required.

**Comment by jeremylong** [comment]
I've been able to replicate the problem on my side and I am trying to figure out exactly what is going on.

Thanks for reporting this!

**Comment by jabbrwcky** [comment]
Fun fact is, this apparently _only_ happens in the update when the previous version is read from the database.
The XML does not contain duplicate versions in the software versions list in the affected vulnerability.

**Comment by jeremylong** [comment]
I modified the compareTo method to resolve the issue. Some improvements could still be made in the compareTo to improve speed (such as use a loop to check for the first difference in the strings using charAt and only go into the more complicated sorting after the first difference).

**Comment by davidjahn** [comment]
Hi, we are experiencing this exact issue (with the same error message) on Dependency Check  1.4.2.

Is it possible that the above fix was not propagated into the release? We are running on Linux with openjdk 1.8.91 JRE, using mysql-connector-java-5.1.39 to connect to a MySQL database.

**Comment by jeremylong** [comment]
If you go back to the previously used version of ODC - does this issue still show up?

**Comment by davidjahn** [comment]
Yes, if we try to create the dependency-check MySQL database from scratch with Dependency Check 1.4.0 it creates without issue (although we recently started getting the error `Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.` along with data loss in the DB creations, which is why we tried to upgrade to 1.4.2)

**Comment by shayke** [comment]
It seems to be happening only when batch support is enabled.
I've tried disabling it manually and the update works.

**Comment by jeremylong** [comment]
This issue has been resolved with the above referenced patch.
