### ISSUE TITLE
[FP]: npm loader-utils@1.4.1

### ISSUE THREAD

**Issue by Felk** [dependency-check/DependencyCheck#5044]
### Package URl

pkg:npm/loader-utils@1.4.1

### CPE

cpe:2.3:a:webpack.js:loader-utils:1.4.1:*:*:*:*:*:*:*

### CVE

CVE-2022-37601

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

7.3.0

### Description

CVE-2022-37601 was also fixed in loader-utils@1.4.1 via backport, as per https://github.com/webpack/loader-utils/issues/218 and https://github.com/webpack/loader-utils/releases/tag/v1.4.1

**Comment by aikebah** [comment]
@Felk This was due to the vulnerability data at the NIST NVD datastreams. It has been updated meanwhile (at 11/17/2022 9:14:18 AM), but in future you can directly reach out to them using the "[Are we missing a CPE here? Please let us know]" link of the NVD page of the vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2022-37601)

**Comment by Felk** [comment]
ah, good to know thanks!
