### ISSUE TITLE
[FP]: Minimal Jar with no content

### ISSUE THREAD

**Issue by paulsamuels** [dependency-check/DependencyCheck#5117]
### Package URl

pkg:maven/com.github.tony19/logback-android@2.0.1

### CPE

`cpe:2.3:a:jetbrains:kotlin:0.1.1:*:*:*:*:*:*:*`

### ODC Integration

{"label"=>"CLI"}

### ODC Version

7.4.0

### Description

The full report is actually 5 CVEs with an evidence count of 197. The smallest reproduction I can create is scanning [this](https://github.com/paulsamuels/cve-false-positive-example/raw/main/example-jvm.jar) jar file from the command line `dependency-check --scan ...`. The jar file itself when unzipped has a single file named `META-INF/MANIFEST.MF` with the contents `Manifest-Version: 1.0`.

**Comment by aikebah** [comment]
@paulsamuels 'minimal reproduction' jars are useless. False positives are a result of how this project works. Packageurls and falsely matched CPEs are what we need for mitigation - assuming projects themselves are public so that we can evaluate the evidences (as is the case for logback-android, though the v2.0.1 is yet to arrive at maven central, hence the github action failure)).
For private projects (projects that are not publicly available) mitigation of the false positives is left for the teams themselves to manage with a private suppression file as documented.

**Comment by paulsamuels** [comment]
@aikebah sorry I might have used the wrong template for this. I'll close this FP report and open as a bug report
