### ISSUE TITLE
How can DependencyCheck flag a package as a completly wrong package?

### ISSUE THREAD

**Issue by XSpielinbox** [dependency-check/DependencyCheck#5159]
I have a project including commons-beanutils-1.9.4.jar, commons-collections-3.2.2.jar, commons-io-2.11.0.jar, commons-logging-1.2.jar, commons-text-1.10.0.jar, xml-apis-1.4.01.jar, xml-apis-ext-1.3.04.jar and xmlgraphics-commons-2.6.jar as well as others.

Some of the named dependencies are direct, most of them are transitive dependencies.
However, DependencyCheck flags all of the above as [cpe:2.3:a:apache:commons_net:*:*:*:*:*:*:*:* versions up to (excluding) 3.9.0](https://web.nvd.nist.gov/view/vuln/search-results?adv_search=true&cves=on&cpe_version=cpe%3A%2Fa%3Aapache%3Acommons_net) and therefore [CVE-2021-37533](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-37533), because e.g. commons-text-1.10.0.jar get's identified as [cpe:2.3:a:apache:commons_net:1.10.0:*:*:*:*:*:*:*](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aapache&cpe_product=cpe%3A%2F%3Aapache%3Acommons_net&cpe_version=cpe%3A%2F%3Aapache%3Acommons_net%3A1.10.0)  (Confidence:Highest).

How can these packages be identified as a completely wrong package? And how can this even be identified wrong with HIGHEST confidence not only once but so many times?
After all my project does NOT use Apache Commons Net in any way and can NOT find any relationship between the above packages and Apache Commons Net.

I know how I can suppress false positives, but this does not seem right to me here. 

I do not see this as a false positive (me using a package, that actually has a vulnerability, just that I use it in a way, the vulnerability does not apply to me), but this rather looks like a bug in the package identification mechanism/regex to me.

[tested with DependencyCheck Maven plugin version 7.4.0]

**Comment by aikebah** [comment]
If you test again with 7.4.1 you'll see it disappear (as it was already reported in #5121 and subsequently fixed).

How it can happen is because of how dependency check works (a text-search from evidence strings to find the best-matching CPE (as there is no authoritive source for packageURL to CPE translation and we also don't intend to build/maintain such a translation).

**Comment by aikebah** [comment]
> I do not see this as a false positive (me using a package, that actually has a vulnerability, just that I use it in a way, the vulnerability does not apply to me), but this rather looks like a bug in the package identification mechanism/regex to me.

This is a proper false-postive (it's even featured as an example cause for false positives on our github pages: https://jeremylong.github.io/DependencyCheck/general/suppression.html) due to how the tool works. 

It's why there are various types of suppressions. The are FP suppression options for the cases where a vulnerability does not apply to your usage (`<cve>....</cve>` and `<vulnerabilityName>...</vulnerabilityName>`) and for the case where this tool maps it to an improper CPE (`<cpe>...</cpe>`).
The cases for the latter, in case of publicly available libraries, we would like to see reported as FP report issues (after checking they've not already been reported and will be resolved by a next release) so that we can mitigate them.

When version 8 gets released internet-connected scans will automatically benefit from the published suppressions that result from (most of) these FP reports (see #4723). If your setup is internet-connected you can configure [that same suppressions file](https://github.com/jeremylong/DependencyCheck/issues/4723#issuecomment-1242722895) as an additional suppression file to benefit from any mitigations that are already in there, but not yet in the suppressions packaged with the latest release (new additions are typically synchronized to the packages suppressions shortly before a release in order to also be of benefit to 'offline' uses of the tool).

**Comment by XSpielinbox** [comment]
> If you test again with 7.4.1 you'll see it disappear (as it was already reported in #5121 and subsequently fixed).
> 
> How it can happen is because of how dependency check works (a text-search from evidence strings to find the best-matching CPE (as there is no authoritive source for packageURL to CPE translation and we also don't intend to build/maintain such a translation).

Ah, thank you very much! Yes indeed it does not happen with the new version any more. Yesterday 7.4.0 was the newest version I could find on maven central, wherefore I thought this was the latest version already - whatever was the issue there.

**Comment by XSpielinbox** [comment]
> This is a proper false-postive (it's even featured as an example cause for false positives on our github pages: https://jeremylong.github.io/DependencyCheck/general/suppression.html) due to how the tool works.

Ah, I must have miss understood that page.

> It's why there are various types of suppressions. The are FP suppression options for the cases where a vulnerability does not apply to your usage (`<cve>....</cve>` and `<vulnerabilityName>...</vulnerabilityName>`) and for the case where this tool maps it to an improper CPE (`<cpe>...</cpe>`). The cases for the latter, in case of publicly available libraries, we would like to see reported as FP report issues (after checking they've not already been reported and will be resolved by a next release) so that we can mitigate them.

Ah, this makes sense! This was not clear to me before. Perhaps you should state this in this explicit way somewhere more prominent.

> When version 8 gets released internet-connected scans will automatically benefit from the published suppressions that result from (most of) these FP reports (see #4723). If your setup is internet-connected you can configure [that same suppressions file](https://github.com/jeremylong/DependencyCheck/issues/4723#issuecomment-1242722895) as an additional suppression file to benefit from any mitigations that are already in there, but not yet in the suppressions packaged with the latest release (new additions are typically synchronized to the packages suppressions shortly before a release in order to also be of benefit to 'offline' uses of the tool).

Great! I'm looking forward to it! Thank's a lot for building this awesome tool!
