### ISSUE TITLE
Missing Report for jar

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#5163]
[jar_ana.zip](https://github.com/jeremylong/DependencyCheck/files/10258594/jar_ana.zip)

The attached zip has 5 jars. By running report for this in ODC version 7.4.1 will get only result for 4 jars.

Jars In a folder : 
--------
jedis-4.3.1.jar
dd-plist-1.8.jar
spring-core-5.3.24.jar
spring-beans-5.3.23.jar
spring-context-5.3.23.jar --->  Not getting result for this jar

But if the 'spring-context-5.3.23.jar' moved into a subfolder inside a main folder then will get report for all 5. I don't know why?

Explain what is the issue  here?

**Comment by aikebah** [comment]
Take a closer look at your report.... there's a section 'related dependencies' That's Dependency-check seeing that spring-beans and spring-context are both part of the Spring Framework version 5.3.23. Were you to use spring-core-5.3.23.jar instead of 5.3.24 then all three spring jars would be accounted for under a single entry
