### ISSUE TITLE
Database lock 

### ISSUE THREAD

**Issue by andrealcobia** [dependency-check/DependencyCheck#5199]
Hi all,
I've implement the DependencyCheck via gradle plugin. When i run the task the first time the report is generated and dependencies are downloaded. However we started to get some errors regarding database locks when trying to run the dependency task.
Example:
build	22-Dec-2022 12:24:24	Checking for updates and analyzing dependencies for vulnerabilities
error	22-Dec-2022 12:24:34	org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to retrieve id for new vulnerability for 'CVE-2022-4564'
error	22-Dec-2022 12:24:34	org.owasp.dependencycheck.data.update.exception.UpdateException: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to retrieve id for new vulnerability for 'CVE-2022-4564'
...
error	22-Dec-2022 12:24:34	Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.VULNERABILITY(CVE NULLS FIRST) VALUES ( /* 5 */ 'CVE-2022-4564' )"; SQL statement:
error	22-Dec-2022 12:24:34	INSERT INTO VULNERABILITY (description, v2Severity, v2ExploitabilityScore, v2ImpactScore, v2AcInsufInfo, v2ObtainAllPrivilege, v2ObtainUserPrivilege, v2ObtainOtherPrivilege, v2UserInteractionRequired, v2Score, v2AccessVector, v2AccessComplexity, v2Authentication, v2ConfidentialityImpact, v2IntegrityImpact, v2AvailabilityImpact, v2Version, v3ExploitabilityScore, v3ImpactScore, v3AttackVector, v3AttackComplexity, v3PrivilegesRequired, v3UserInteraction, v3Scope, v3ConfidentialityImpact, v3IntegrityImpact, v3AvailabilityImpact, v3BaseScore, v3BaseSeverity, v3Version, cve) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]

I've tried to change the data directory and also disable the autoUpdate like this:

  outputDirectory = "build/security-report"
  autoUpdate=false
  cveValidForHours=6
  //failBuildOnCVSS=7
  data {
    directory="build/security-data"
    connectionString="jdbc:h2:file:%s;FILE_LOCK=FS;AUTOCOMMIT=ON;"
  }

But with no success. This is happening locally and also in Jenkins. I'm missing something ? Via gradle is there another thing else i should do ?

If I erase all the folders created in the gradle build process every time before running the dependency tasks it will work, but i don't understand why it remains lock after every task run.

Thanks in advanced for any advice.

**Comment by aikebah** [comment]
That's not a database lock, but a database consistency issue: the database runs into duplicate CVE-id.
```
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation
```
somehow you manage to try to insert the CVE twice. My gut feel (no direct proof, but just supsicion) would be due to Gradle running multiple updates in parallel for submodules and H2 allowing you to do that on same DB because your OS native file-locking on 'build/securitydata' is non-functional allowing H2 to open the database twice in parallel (and therefor in effect identical to 'FILE_LOCK=NO' )

I would suggest to retry with H2's default FILE_LOCK (=FILE)

**Comment by aikebah** [comment]
Browsing through our code I would expect the only case where this might happen be a scenario where the modified timestamps of your files are also out-of-sync with the system-local current time (e.g. due to timezone travelling), as there should be an `odc.update.lock` alongside your H2 database when (before) ODC starts the updates in order to rule out other ODC processes from modifying the database at the same time (those other instances would print a message `Existing update in progress; waiting for update to complete` when properly locked out).
Final confirmation of such a time-shift would be to run it with debug-logging enabled and check the debug log for messages starting with `An old write lock file was found`, which would indicate that the lock-file according to the process trying to obtain it is more than 30 minutes old and considered stale and thus ignored (deleted and recreated).

**Comment by andrealcobia** [comment]
Hi. Thanks for all the insight you give me. But unfortunately i haven't been able to fix this. I've used the plugin in the past, via maven, or via npm script with great success. But via gradle it continues to give problems in the pipelines and locally. My main configuration looks like this:
dependencyCheck {
  cve {
    urlBase="https://(custom_artifactory)/nvd-nist-public/json/cve/1.1/nvdcve-1.1-modified.json.gz"
    urlModified="https://(custom_artifactory)/nvd-nist-public/json/cve/1.1/nvdcve-1.1-2022.json.gz"
    }
  analyzers {
    retirejs {
      retireJsUrl="https://(custom_artifactory)/github-retirejs/master/repository/jsrepository.json"
    }
    ossIndex {
      enabled=false
      }
    nodeAudit {
      enabled=false
      }
    archiveEnabled = true
    jarEnabled = true
    opensslEnabled = false
    nuspecEnabled = false
    assemblyEnabled = false
    nodeEnabled = true
    centralEnabled=false
  }
  outputDirectory = "build/security-report"
  autoUpdate=true
  cveValidForHours=6
  //failBuildOnCVSS=7
  data {
    connectionString="jdbc:h2:file:%s;AUTOCOMMIT=ON;FILE_LOCK=FILE;"
  }
}

In the logs I didn't find any of the outputs you gave but i've noticed thats like you said, there is a parallel access to the H2. I've deleted the custom data directory but I continues to have the same error.

**Comment by aikebah** [comment]
```
urlBase="https://(custom_artifactory)/nvd-nist-public/json/cve/1.1/nvdcve-1.1-modified.json.gz"
urlModified="https://(custom_artifactory)/nvd-nist-public/json/cve/1.1/nvdcve-1.1-2022.json.gz"
```

I sure hope that's a bunch of typos//copy-paste-errors as they show:
1) mix-up of the modified and base URLs
2) absence of a year-placeholder in what from format perspective would be the real base-URL for the 2022 CVE datastream

the proper config should look like
```
urlBase="https://(custom_artifactory)/nvd-nist-public/json/cve/1.1/nvdcve-1.1-%s.json.gz"
urlModified="https://(custom_artifactory)/nvd-nist-public/json/cve/1.1/nvdcve-1.1-modified.json.gz"
```

**Comment by aikebah** [comment]
loading the same datastream for every year between 2002 and 2023 (as urlBase has no `%s` for the spot where the year appears) surely can explain the symptom you see.... as you indeed load the same datastream multiple times.

**Comment by andrealcobia** [comment]
Hi @aikebah ! Thanks a lot. I have corrected the custom urlBase and it's now working.
