### ISSUE TITLE
CVE-2016-3674: xstream threat not detected

### ISSUE THREAD

**Issue by adioss** [dependency-check/DependencyCheck#522]
Tested on DC v1.4.0 and xstream v1.4.8.
The cve https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-3674 is not detected. You can see that the configuration is:

> cpe:/a:x-stream:xstream:1.4.8 and previous versions

so the product vendor here is "x-stream". But the vendor has changed for current version. Now it is "com.thoughtworks.xstream" (you can see the changes here: http://mvnrepository.com/artifact/xstream/xstream).
So in my opinion, CVE is not correctly reported for the moment because the CPE is not correct (or partially complete?). 

To validate this assumption, in org.owasp.dependencycheck.analyzer.CPEAnalyzer#determineCPE, using a debugger, I dynamically changed the vendors value to append "com.thoughtworks.xstream" and it works: CVE is reported.

**Comment by jeremylong** [comment]
Yes, this is a problem with the data from the NVD when vendor names change. Pretty sure Spring 3.0 has three distinct CPE identifiers (SpringSource, vmware-SpringSource, and Pivatol). I can add something to the [HintAnalyzer](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/analyzer/HintAnalyzer.java) for this situation when I find out about it (I should also convert the analyzer to use a configuration file at the same time).

Thanks for pointing this false negative out!

--Jeremy

**Comment by jeremylong** [comment]
The final resolution to this issue was with the configuration/setup of the Lucene index. Previously, the indexing and searching used different field analyzers. The indexing analyzer was not using the TokenConcatenatingFilter and this resulted in the underlying tokens of `x stream` (instead of `x xstream stream`. When the search for xstream occurred no match was identified. Both searching and indexing now use the same field analyzer that contains the TokenConcatenatingFilter.

This will likely resolve other false negatives. The patch will be included in the next release.
