### ISSUE TITLE
Tips for vulnerability mitigation plan

### ISSUE THREAD

**Issue by mahzad** [dependency-check/DependencyCheck#5249]
For the vulnerability mitigation plan, in addition to the latest vulnerable dependency, is it possible to announce in which version this vulnerability has been fixed?
Now that this information is not available, does the update to the latest version have recommended?

**Comment by mprins** [comment]
In general no, because the NVD data does not provide data about releases

**Comment by mahzad** [comment]
What is best practice to fix vulnerability in the type of dependencies?

**Comment by aikebah** [comment]
Best practice is to keep your dependencies current, which means upgrading to latest major where possible, latest minor where needed for backwards compatibility in regular maintenance (in line with [OWASP top 10 A06:2021 – Vulnerable and Outdated Components](https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/))
Not only vulnerable dependencies, but also outdated dependencies are nowadays recognized as a potential issue (as they may block the ability to quickly update to a patched version when a new critical vulnerability appears)

**Comment by mahzad** [comment]
OK , for testing backwards compatibility, developer update a dependency to last version if code compile correctly , there is no more task but if code does not compile replace a non-vulnerable version of that.  Is this plan verified?

**Comment by jeremylong** [comment]
I did a talk on this https://www.youtube.com/watch?v=qVVZrTRJ290

I'm a huge fan of automating the upgrades of all components. We use `dependabot` and we get PRs whenever a new version of a dependency is released (see example [PRs here](https://github.com/jeremylong/DependencyCheck/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdependabot)). However, there is a risk to automated PRs and it is something you would need to evaluate for your project. if you have sufficient test coverage the risk is minimized. That being said I have heard stories about subtle bugs that went undetected because of an automated upgrade that was merged.

**Comment by mahzad** [comment]
Thanks for your response.

**Comment by mahzad** [comment]
@jeremylong I did a study on your YouTube link, I have a question?
 for unreported vulnerabilities in NVD/CVE , your recommend is using commercial DB or using commercial darkweb solution to find exploits ?
our concern is finding a vulnerability as soon as possible for opensource third parties.  please help me if any other recommendations exist.

**Comment by jeremylong** [comment]
If your goal is to know as soon as possible - that requires a research team. For instance, Snyk has a research team and actually sells access to their vulnerability data (or you could use their commercial SCA offering). Other vendors also have research teams to build a database of vulnerabilities. ODC is open source - we do the best we can with the volunteer time we have.

**Comment by mahzad** [comment]
Thanks  for responding.  what is your opinion about owasp dependency
tracker for detect vulnerabilities as soon as possible ( It seem analyzers
do every 24 h )

**Comment by aikebah** [comment]
For 'as-soon-as-possible': Subscribe to the security announces of the libraries that you use. All other methods will introduce latencies for processing of the vulnerability-information into the vulnerability feeds that DependencyCheck is using.

E.g. NIST NVD:
* can lag behind before new entries are sufficiently analyzed to have the affected configurations listed (typically the weekly overview of new CVEs of the past week has a significant amount of 'severity not yet assigned' vulnerabilities, which are likely to also not-yet have the affected configurations linked to CPEs in the NVD)
* can lag even more behind if the CVE-registration is not yet properly finalized when the fix or vulnerability info is out as the record will only  enter the input-queue of NVD when the CVE itself reaches the formal published state (https://www.cve.org/ResourcesSupport/FAQs#pc_cve_recordsreserved_signify_in_cve_record / https://www.cve.org/ResourcesSupport/FAQs#pc_cve_recordswhy_cve_record_marked_RESERVED_when_being_publicly_used).

Given the typical lag / periodic publishing the analyzers have sensible default times to make dependencyCheck try and behave like a gentleman in a trade-off of being up-to-date and playing nice with the publishers of vulnerability data. 
Most, if not all of the analyzers expose the update delays via `xxxValidForHours` configuration settings.

Note that configuring these delays to lower values may make your infrastructure be considered 'hostile' by the feed publishers and may make them decide to block you from access to avoid overloading their service.

E.g. for NIST NVD they publicly announce that their modified feed is updated at 2 hour intervals and the year feeds updated at a daily interval (if any changes were made). Their idea on 'gentlemans behaviour' essentially comes down to

> This approach should result in a reasonable use of less than 200 requests per day
(https://nvd.nist.gov/vuln/data-feeds#keepUpdated)

**Comment by mahzad** [comment]
I mean owasp dependency track project

**Comment by aikebah** [comment]
Ah.. sorry, was missing that aspect of your remark. Though most of my reply would still hold: There is an inherent delay in this type of tools as they do not have a security research team, but compare software components to vulnerability-lists published by others. Before they can flag an issue:

1) someone must have found the issue (this is the moment to measure ASAP against)
2) they most have registered a vulnerability record for it
3) at least one of the used vulnerability sources of the tool must notice the new issue
4) at least one of the used vulnerability sources of the tool must publish their assessment of the vulnerability in their vulnerability-feed
5) the tool must have updated its internal state with the updates to  the vulnerability-feed

Typically (excluding discovery of zero-day exploits) at the point of one of the first two the authors of the vulnerable software are (in private) notified and may already publish an announcement in coordination with the reporter of the issue, depending on its severity/exploitability or wait with going public until a fix is available.

For continuous monitoring of 'released/installed' product versions DependencyTrack is a good tool, and when you integrate all of its available vulnerability-sources you will have more of those available than DependencyCheck, increasing the chances of quicker arrival at stage 4). Especially since several of the feeds originate from teams that are also involved at stage 1), meaning that they're typically ready to go live on their feed the instant that agreement has been reached with the vendor on publication (or sometimes faster: when they deem the vulneribility worthy of immediate publication, even without a fix available)

DependencyCheck in my view is targeted at the development-workflow to continuously re-evaluate the dependencies of the in-development version of software. 
DependencyTrack is in my view primarily targeted at monitoring 'a know, stable, composition of components' aka released software / installed production systems for emerging new vulnerabilities.
