### ISSUE TITLE
dependency-check fails when scanning Mindscape.LightSpeed.dll in .NET project 

### ISSUE THREAD

**Issue by ldavisindg** [dependency-check/DependencyCheck#527]
```
dependency-check.
bat --project <projectname> --scan .
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Check for updates complete (1923 ms)
[INFO] Analysis Starting
[Fatal Error] :1:1: Premature end of file.
[WARN] An error occurred while analyzing '...\bin\Libs\Minds
cape\Mindscape.LightSpeed.dll'.
[Fatal Error] :1:1: Premature end of file.
[WARN] An error occurred while analyzing '...\bin\Mindscape.LightSpeed.dll'.
```

Environment specifics
Windows Server 2012 R2
Using command line utility
Version commons-cli-1.3.1

**Comment by owangen** [comment]
Same thing happens to me when scanning Aspose.Pdf.dll. Anyone know why causes this error?

**Comment by jeremylong** [comment]
Unfortunately, I have not had time to dig into this problem. However, the error appears to be reported from the Grok Assembly tool (https://github.com/colezlaw/GrokAssembly) that is used to extract properties from DLLs. Some updates to the error handling were made and the new exe has not been incorporated into dependency-check yet.

**Comment by colezlaw** [comment]
I put in a PR with an updated GrokAssembly.exe . They do some code obfuscation and so there end up with non-UTF-8 encodable characters in the type names. I added a method to replace non-printables with a ?, and then stripped out the type information since DC doesn't use it, and I don't believe anybody else is, either.

There is a remaining problem with these specific DLL's (all the aspose DLL's). They use an obfuscation tool which actually produces assemblies that aren't valid according to Microsoft's standards for assemblies, but they exploit known bugs in the Microsoft assembly parsers to work anyway. Mono's assembly parsing is far more strict, so if you analyze these with mono, you'll get a warning before the XML output:

```
Unknown heap type: SmartAssembly
```

This error comes on stdout, not stderr, and so there's not really anything I can do about it without some more serious gymnastics (writing the GrokAssembly output to a file, which requires updating the AssemblyAnalyzer to handle dealing with the files, TOCTOU issues, and so on.)

**Comment by jeremylong** [comment]
@colezlaw Thanks!

PR #545 has been merged and the will be included in the next release. As such, this issue is considered closed.
