### ISSUE TITLE
File path for suppression is not file path on file system

### ISSUE THREAD

**Issue by Hallot** [dependency-check/DependencyCheck#5279]
**Describe the bug**
I am sorry, I am not entirely sure whether this is a bug or a question.

I am trying to suppress a vulnerability via the suppressions file, using the `filePath` attribute.
E.g., I have the following vuln reported:
```
wheel:0.29  
File Path: 
/tmp/dev/.cache/bazel/_bazel_test/45687a9fc51e3180e3ee6f957bfa2b6a/external/com_github_grpc_grpc/requirements.txt:wheel/0.29
```

I am trying to suppress it using something like:
```
<suppress>
        <notes><![CDATA[
        Suppress vulnerabilities in gRPC requirements.txt
        ]]></notes>
        <filePath regex="true">.*grpc/requirements\.txt</filePath>
        <cpe regex="true">.*</cpe>
</suppress>
```

But this does not work.
However, if I use `<filePath regex="true">.*grpc/requirements\.txt.*</filePath>` or `<filePath regex="true">.*grpc/requirements\.txt:wheel/0.29</filePath>`, then it works.
So apparently, the path to use is not the path on the file system, but something created by DependencyCheck where the vulnerability is appended. This is a bit unexpected, and as far as I can tell, undocumented.

**Version of dependency-check used**
The problem occurs using version 7.4.4 of the cli.

**Log file**
[INFO] Suppression Rule had zero matches: SuppressionRule{filePath=PropertyType{value=.*grpc/requirements\.txt, regex=true, caseSensitive=false},cpe={PropertyType{value=.*, regex=true, caseSensitive=false},}}

**Expected behavior**
I would expect that using the path of the file on the file system would work, or that the behaviour exhibited here is documented.

**Comment by aikebah** [comment]
For requirements.txt listed dependencies DependencyCheck uses `<full path to the requirements.txt>:package/version` as the dependency's filepath in PipfileAnalyzer. 
Using just requirements.txt (the only filepath the PipfileAnalyzer has available) would mean that any suppression would hold for all dependencies listed in that requirements.txt file. So indeed, for findings of the PipfileAnalyzer you need to extend the regex to include the `:package/version` part.

In this case the FP is due to the transitive dependency (obtained from requirements.txt of gRPC) being linked to the CPE of the depending bundle (the bundle that hosts the requirements.txt) so the wildcard regex is likely appropriate (as in: none of the _dependencies_ of gRPC package is gRPC itself)

The `<filePath>` element of the suppression rule matches one-on-one to the `File Path` of the dependency as recorded by DependencyCheck and reported on in the reports.

**Comment by Hallot** [comment]
Thanks for the explanation.
