### ISSUE TITLE
ODC ans Sonatype CSS index results varies

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#5358]
[
![Screenshot from 2023-01-20 17-25-27](https://user-images.githubusercontent.com/72544136/213689584-2c144956-9eae-464a-81db-da84f55c00a2.png)
![Screenshot from 2023-01-20 17-25-18](https://user-images.githubusercontent.com/72544136/213689600-9a25167e-2466-44cc-b4f6-ef830dfda47c.png)
](url)

**Comment by aikebah** [comment]
@parimala-kathir See the CPEs listed in the report... 
your aar file is identified by DependencyCheck as being
Axis1 1.6.2 as well as 
Axis2 version 1.6.2

Whether any of those is a valid CPE for the version-1.6.2.aar file....
That is something only you can tell

BTW dependency check uses more than just OSSIndex - vulnerabilities can also come from NIST NVD.

**Comment by aikebah** [comment]
NIST NVD is listing Apache Axis2 up to (including) 1.6.2 as vulnerable to the CVE

https://nvd.nist.gov/vuln/detail/CVE-2012-5785

**Comment by aikebah** [comment]
The reason that OSSINDEX is not showing any vulnerabilities for the version-1.6.2.aar is because they're a large company that can do detailed linking of CVEs to the individual components of a large framework like Apache Axis2 and the issue of the CVE is in another part of the Axis2 framework.
This project takes the approach to spent the limited resources where they are best spent and therefor does not build the large dataset required to be able to link at the individual subcomponents to the CVEs raised against a framework. Therefor the CVEs of Apache Axis2 framework found in NIST NVD are raised for every component that is part of the framework.
