### ISSUE TITLE
Not sure if this is a specific problem or problem with my config that is causing flakiness

### ISSUE THREAD

**Issue by jainishan** [dependency-check/DependencyCheck#5382]
I have several repositories and in them I use dependency check plugin. All of these projects are built via a jenkins server.
My configuration and what I was trying to do earlier is described here - https://github.com/jeremylong/DependencyCheck/issues/5257

I only changed my config to now pick up the suppressions file from a common dependency. I started merging my changes today and many of the build started failing with following exact message:

```
Failed to execute goal org.owasp:dependency-check-maven:8.0.1:check (default-cli) on project my-project: Fatal exception(s) analyzing my-project: One or more exceptions occurred during analysis:
11:10:58  [ERROR] 	DatabaseException: Unable to connect to the database - if this error persists it may be due to a corrupt database. Consider running `purge` to delete the existing database
11:10:58  [ERROR] 		caused by DatabaseException: Unable to connect to the database
11:10:58  [ERROR] 		caused by JdbcSQLNonTransientException: General error: "Chunk 111 not found [2.1.214/9]"; SQL statement:
11:10:58  [ERROR] CREATE CACHED TABLE "PUBLIC"."KNOWNEXPLOITED"(
11:10:58  [ERROR]     "CVEID" CHARACTER VARYING(20) NOT NULL,
11:10:58  [ERROR]     "VENDORPROJECT" CHARACTER VARYING(255),
11:10:58  [ERROR]     "PRODUCT" CHARACTER VARYING(255),
11:10:58  [ERROR]     "VULNERABILITYNAME" CHARACTER VARYING(500),
11:10:58  [ERROR]     "DATEADDED" CHARACTER(10),
11:10:58  [ERROR]     "SHORTDESCRIPTION" CHARACTER VARYING(2000),
11:10:58  [ERROR]     "REQUIREDACTION" CHARACTER VARYING(1000),
11:10:58  [ERROR]     "DUEDATE" CHARACTER(10),
11:10:58  [ERROR]     "NOTES" CHARACTER VARYING(2000)
11:10:58  [ERROR] ) [50000-214]
11:10:58  [ERROR] 		caused by MVStoreException: Chunk 111 not found [2.1.214/9]
```

Re building has the same effect and nothing else changed on these repos. 
What I am wondering is:

- what exactly is this error ?
- I think by default the H2 DB is created and that is what I have. Is it going to download everything everytime if I clean my jenkins workspaces ? Is it possible possible that sometimes the DB files gets corrupted easily ?
- What would be the simplest solution if I do not want all my jenkins builds to not download all the information everytime and yet not give me flaky test results sometimes only ?

**Comment by aikebah** [comment]
Regarding the root cause of your issue I have no clue, but regarding your third bullet:

Assuming that you already have a persisted Maven local repository (dependency check data is stored within the maven local repository by the maven plugin) on your jenkins build slaves you can configure all your builds with the auto-update disabled (add `<autoUpdate>false</autoUpdate>` to the plugin configuration block in your poms, or to the properties of your build-server settings.xml or change the mvn invocation in your build adding it as a command-line property (`-DautoUpdate=false`)

And then schedule a new periodic build-job that runs `mvn org.owasp:dependency-check-maven:8.0.1:update-only` (no pom.xml required) to ensure that data remains up-to-date.

If you have more than one Jenkins slave make sure to schedule such a job for each slave.

To resolve issues like the one you mentioned you could add an additional manual job that includes the purge: `mvn org.owasp:dependency-check-maven:8.0.1:purge org.owasp:dependency-check-maven:8.0.1:update-only` that you run in case the DB got corrupted.

The latter only as a manual one-off remedy job, because in-between purge and completion of the update your jobs might break on unavailability of the data.


Whether or not your jobs always create the database depends on how your build-server handles the maven local repository: if that is not retained between builds it would redownload and rebuild always (just as your build would each time have to download all project- and plugin dependencies from the maven repository in that case, a massive waste of network and I/O resources, so I would expect your Jenkins infrastructure to have a maven local repo as a shared resource between builds)

**Comment by jainishan** [comment]
Hello. 
Thanks for the detailed answer. I realised that the DB file is being stored in maven local cache. I removed the file and everything was fine with the builds.
Just out of curiosity, why does all the versions reuse the same folder ? In my case the DB file would always be created in .m2/repository/org/owasp/dependency-check-data/7.0/oss_cache/ folder

**Comment by aikebah** [comment]
The versions re-use the same folder as long as the database scheme is backward compatible. If you were to spin up a really old version you would see a different database folder appear.
