### ISSUE TITLE
False positive on spring-core-4.2.0.RC3.jar

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#5416]
**Maven link :**
https://mvnrepository.com/artifact/org.springframework/spring-core/4.2.0.RELEASE

**CPE from ODC7.4.1 report  :** 
cpe:2.3:a:pivotal_software:spring_framework:4.2.0:rc3:*:*:*:*:*:*
cpe:2.3:a:springsource:spring_framework:4.2.0:rc3:*:*:*:*:*:*
cpe:2.3:a:vmware:spring_framework:4.2.0:rc3:*:*:*:*:*:*

Maven CVEs:
CVE-2022-22971
CVE-2022-22970
CVE-2022-22968
CVE-2022-22965
CVE-2022-22950
CVE-2018-15756
CVE-2018-1275
CVE-2018-1272
CVE-2018-1271
CVE-2018-1270
CVE-2018-1257
CVE-2016-9878
CVE-2016-5007
CVE-2015-5211

ODC CVEs:
CVE-2016-1000027
CVE-2018-1270
CVE-2022-22965
CVE-2015-5211
CVE-2016-5007
CVE-2016-9878
CVE-2018-11040
CVE-2018-15756
CVE-2018-1257
CVE-2020-5421
CVE-2022-22950
CVE-2018-11039
CVE-2022-22968
CVE-2022-22970

 Why this variation?

**Comment by aikebah** [comment]
Because of difference in which vulnerability sources are consulted by the maintainers of mvnrepository.org compared to the sources that DependencyCheck uses (NIST NVD and OSSIndex would be the sources consulted for Spring libraries by DependencyCheck). 

No clue what sources and which process mvnrepository uses for their listed vulnerabilities.

**Comment by aikebah** [comment]
The extras found by ODC are all valid CVEs for this spring version, gut feel is that whatever process is used for mvnrepository is not taking `and older unsupported versions` properly into account. Regarding `CVE-2016-1000027`: that is due to the fact that OSSIndex considers that vulnerability only resolved in Spring 6.x, as before that it is up to the developers to ensure that the vulnerable method is not used (it was only deprecated in the minor revisions of Spring framework before 6.x to ensure backward compatibility with projects that used the method)

**Comment by aikebah** [comment]
`CVE-2018-1272` is also reported by ODC (not in your list)

**Comment by aikebah** [comment]
`CVE-2018-1271` is attributed to spring-webmvc and spring-webflux by OSSINDEX and has an incomplete list of vulnerable spring-framework versions at NIST NVD (it ignores the `and older unsupported versions` part, listing only versions starting at 4.3.0)
`CVE-2022-22971` and `CVE-2018-1275` is attributed to spring-messaging by OSSINDEX and has an incomplete list of vulnerable spring-framework versions at NIST NVD (it ignores the `and older unsupported versions` part, listing only versions starting at 4.3.0 / 5.2.0)

They appear to be false positives for the spring-core library, but thanks to the incorrect version range for affected spring framework versions at NIST NVD you don't have to resort to a suppression file right now to prevent getting them reported by ODC.
