### ISSUE TITLE
[FP]: Release 8.1.0 is throwing a lot of old Springboot Framework CVEs against spring-retry

### ISSUE THREAD

**Issue by rseeton** [dependency-check/DependencyCheck#5450]
### Package URl

pkg:maven/org.springframework.retry/spring-retry@1.3.3

### CPE

`cpe:2.3:a:pivotal_software:spring_framework:1.3.3:*:*:*:*:*:*:*`

### CVE

CVE-2018-1270

### ODC Integration

{"label"=>"CLI"}

### ODC Version

8.1.0

### Description

This may be an issue with 8.1.0, as we don't see this with the 8.0.2 package and the relevant CVE has not changed June 2022.

There are a number of other/relate issues reported against the spring-retry-1.3.3.jar in our package.

(Retrying after failed processing of initial ticket)

**Comment by aikebah** [comment]
Appears to be caused by #5421

8.0.2 CLI report still has an ill-formed package-URL 
`pkg:maven/org.springframework.retry/spring-retry@%24%7Brevision%7D`

which makes the 'spring libraries that are not spring-framework' suppression to step in and prevent the FP up to 8.0.2 CLI

8.1.0 no longer has a package-url
