### ISSUE TITLE
Possible to exclude dependencies from check with wildcard on GAV?

### ISSUE THREAD

**Issue by JWT007** [dependency-check/DependencyCheck#5453]
Hello,

I am just getting started with the dependency-check as it is now part of our build pipeline.  So I fall under "noob" on this subject and apologize in advance for stupid questions. :/ 

I have read how to suppress specific false-positives.

However, in our scenario we import at least 100 third-party libraries (not from Maven Central) for a backend-system.  These are used in different versions for different platforms and are *all* vulnerable. :/  But we can't do anything to fix that.

But our dependency-check is reporting 870+ critical errors and most of them are from these third-party libraries.  Multiple CVEs for each of these JARs.  Creating and maintaining a suppression report for each of these would be a massive undertaking.

Is there anyway to exclude any artifacts with a groupId 'a.b.c.*' from the check / report?  

Or at least an option to generate a suppression report from a normal report where I could just cut out the relevant parts where we want checks and leave all these "false-positives" in.

**Comment by aikebah** [comment]
You don't indicate which of the tools you use, each of them has different options for inclusion/exclusion; see https://jeremylong.github.io/DependencyCheck/ the links to the individual build-process integrations for their specific configuration options.

An option that might be relevant for your stated scenario is that you can skip certain dependency sets. 
I would expect your backend system provides the libraries for you already, so e.g. on maven you would be able to ignore those by enabling the `skipProvidedScope` flag as you would configure the backend libraries as having `<scope>provided</scooe>` in your pom.xml

If for whatever reason that's not feasible in your scenario you could create a generic suppression. The packageurl supports a regex expression and cpe suppression uses prefix-matching.

You could start off  with something along the lines of

```
<suppress until="....">
        <notes><![CDATA[
            Cannot upgrade these libraries due to backend  xxxx forcing us to depend on these vulnerable libraries
            ]]></notes>
        <packageUrl regex="true">^pkg:a\.b\.c.*$</packageUrl>
        <cpe>cpe:/a:</cpe>
    </suppress>
```

With until set to a date in the relatively near future when you re-evaluate whether you still want to fully ignore the vulnerabilities forced upon you by the backend system. (without an until date in the near future for re-evaluation I would consider such suppressions an abuse of the suppression system)

The vulnerabilities will still be reported in the report, under section of suppressed vulnerabilities (which is rendered collapsed by default) and will resurface as 'regular' vulnerabilities when the 'until' date has passed.

Once your 'independent of the backend' vulnerable dependencies have been mitigated you could work on changing these rules to be more specific to the individual CVEs, so that you can do a proper risk evaluation of each of the known CVEs in the backend as well as get alerted about new vulnerabilities arising in it that you've never assessed for the risk to your specific scenario.
While you should strive to not have any vulnerable code on your classpath it does make sense to give priority to those that you can (easily) update and those that you assess to affect the parts of the library that your application makes use of.

But be aware that any code on the classpath could be used in a chaining attack. Your application not using it doesn't mean that injected evil payloads don't abuse it. Various deserialization attacks in the past required a code-execution capable deserialization gadget to be present on the classpath (e.g. https://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/)
