### ISSUE TITLE
False positives because of same artifact ids?

### ISSUE THREAD

**Issue by Josef-Kainz-Reichardt** [dependency-check/DependencyCheck#550]
Hi,

as mentioned on stackoverflow (http://stackoverflow.com/q/39221268/4864870) i don't understand the following warning for my project.

For example: I have a Maven multi module project with three modules: `war`, `links` and `indesign` (all with the same `groupId` "de.mygroup")
The `war` (for which the dependency check is executed through the maven plugin) has dependecies on the two other modules.
I've got two warnings with the latest relesed version of the `dependency-check-maven` plugin:

```
links-5.0.0-SNAPSHOT.jar (cpe:/a:hot_links:hot_links:5.0.0, cpe:/a:links:links:5.0.0, de.mygroup:links:5.0.0-SNAPSHOT) : CVE-2006-7086
```

and

```
indesign-5.0.0-SNAPSHOT.jar (cpe:/a:adobe:indesign:5.0.0, de.mygroup:indesign:5.0.0-SNAPSHOT) : CVE-2006-0525
```

As I understood this warnings appears because the dependency check doesn't know which candidate is used. So I think the `groupId` is ignored for determining the dependencies.

I have tried the same with the current snapshot from `master` branch on GitHub and the warning for the `links` module is gone but the warning for the `indesign` dependency is still there.

Did I understand that incorrectly? Or did I something wrong?

**Comment by jeremylong** [comment]
@CptS dependency-check will have false positives due to the way that the tool performs library identification. I would highly recommend reading the following short articles:
- [How dependency-check works](http://jeremylong.github.io/DependencyCheck/general/internals.html)
- [Reading the report](http://jeremylong.github.io/DependencyCheck/general/thereport.html)
- [Suppressing false positives](http://jeremylong.github.io/DependencyCheck/general/suppression.html)

You can likely create a suppression file (you can use the HTML report to help generate this) and use the following suppression rule (of course you'll need to modify this):

``` xml
    <suppress base="true">
        <notes><![CDATA[
        Suppresses false positives for com.google:.*
        ]]></notes>
        <gav regex="true">de\.mygroup:.*</gav>
        <cpe>cpe:/a:hot_links:hot_links</cpe>
        <cpe>cpe:/a:links:links</cpe>
        <cpe>cpe:/a:adobe:indesign</cpe>
    </suppress>
```
