### ISSUE TITLE
org.slf4j.impl.StaticLoggerBinder causes duplicate classes

### ISSUE THREAD

**Issue by gertjanal** [dependency-check/DependencyCheck#552]
A dependency should be used to make LoggerFactoryBinder available instead of a copy of the class

[INFO] --- duplicate-finder-maven-plugin:1.2.1:check (default) @ common-util ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[WARNING] Found duplicate and different classes in [org.owasp:dependency-check-maven:1.4.2, org.slf4j:slf4j-log4j12:1.7.10]:
[WARNING]   org.slf4j.impl.StaticLoggerBinder
[WARNING]   org.slf4j.impl.StaticLoggerBinder
[WARNING] Found duplicate classes/resources in runtime classpath.
[WARNING] Found duplicate and different classes in [org.owasp:dependency-check-maven:1.4.2, org.slf4j:slf4j-log4j12:1.7.10]:
[WARNING]   org.slf4j.impl.StaticLoggerBinder
[WARNING] Found duplicate classes/resources in test classpath.
[ERROR] Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:1.2.1:check (default) on project X: Found duplicate classes/resources! -> [Help 1]

**Comment by gertjanal** [comment]
working on it

**Comment by gertjanal** [comment]
OK, so the StaticLoggerBinder is not the original StaticLoggerBinder. Why would we need a patched version and why is it in a package of a different party?

**Comment by colezlaw** [comment]
`StaticLoggerBinder` is the class that you rewrite for SLF4J to be able to find the logging implementation being used. This is the black magic and witchcraft it uses to prevent other classloader issues. In other words, this class **must** be named this. We wrote our version of it so that the DC internals that log via SLF4J calls make it to the Maven logger.

Evidently, some other plugin you're using also uses SLF4J, so they did the same thing to make their own custom logger.

Is there an option to for Dependency Check to fork?

**Comment by jeremylong** [comment]
Currently there is no option to fork dependency-check (within the plugin itself). The proposed PR is not the correct solution as libraries should not define a [binding](http://www.slf4j.org/codes.html#multiple_bindings). However, @colezlaw isn't that what we've done by defining a `StaticLoggerBinder`? Instead of adding a logging binding via the pom we've added one via code. That being said, I'm not sure how else one would route all logging from a library to the base Maven logging mechanism...

**Comment by jeremylong** [comment]
Okay, more research on this has been done. The `StaticLoggerBinder` is required to support older versions of Maven (3.0.x). This class, and other supporting classes, are  not needed if using Maven 3.1.x (see https://maven.apache.org/maven-logging.html). For now, I think we will leave this in as the core Maven binding will take precedent over the binding within ODC.

**Comment by jeremylong** [comment]
@colezlaw Thoughts on moving the maven logging tools to a separate module? Then users of Maven 3.1.x or higher could exclude it if they wanted to?

**Comment by colezlaw** [comment]
I had thought about either that or actually contributing the Maven and Ant
logic back to the respective projects. I assume the Maven one wouldn't get
accepted since Maven 3.1 uses SLF4J already. I need to find some time to
test things out to see what the consequences of just removing it entirely
are in pre-3.1 environments. (At worst, all the internal logging from DC
won't make it into _any_ log, but maybe the Maven plugin already handles
most of the corner cases). And then, there's Ant.... (do people still use
that?)

**Comment by jeremylong** [comment]
As the only solution I could come up with to solve the report aggregation problem in Maven required the use of APIs in 3.1; a maven prerequisite of 3.1.0 has been added and the `StaticLoggerBinder` has been removed (along with the other related logging classes). As such, the duplicate class def has been resolved.

**Comment by gertjanal** [comment]
Thanks for the quick response, got it working in our current project now! :smile:
