### ISSUE TITLE
[FP]: False positive against H2 Database for CVE-2022-45868

### ISSUE THREAD

**Issue by ccerrillo** [dependency-check/DependencyCheck#5608]
### Package URl

pkg:maven/com.h2database/h2@2.1.214

### CPE

cpe:2.3:a:h2database:h2:2.1.214:*:*:*:*:*:*:*

### CVE

CVE-2022-45868

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.1.2

### Description

The developer states "This is not a vulnerability of H2 Console ... Passwords should never be passed on the command line and every qualified DBA or system administrator is expected to know that." [see h2database issue #3686](https://github.com/h2database/h2database/issues/3686)

**Comment by aikebah** [comment]
It's perfectly fine for the developer to state that it does not consider it a vulnerability, and it's just as fine for vulnerability databases/researchers to disagree and stick to considering it a vulnerability until that functionality is removed or switched-off by default.

DependencyCheck is just reporting what the decision by the various vulnerability databases used is.

Suppression of the issue is up to the development teams using the library. 

DependencyCheck will keep reporting it as longs as NVD/OSSIndex flag the library as vulnerable.

**Comment by ccerrillo** [comment]
It makes sense to me, the h2 developers don't seem to be removing this functionality, so we'll either have to exclude it locally or use another library like HSQLDB.

**Comment by pradeepanchan** [comment]
The fix could have been to not accept this parameter via CLI : `-webAdminPassword` . But rather as a separate user-prompt.

Can we reopen this ?

**Comment by aikebah** [comment]
@pradeepanchan No reason whatsoever to re-open, it will remain a "won't fix". 

* The issue is present (even acknowledged by its maintainer) in the H2 library
* The vulnerability sources used by DependencyCheck  decided to keep the issue acknowledged as a valid CVE

Which means it is not a false positive and DependencyCheck should report it out-of-the-box as an active CVE linked to  the H2 library by the consulted vulnerability sources.

The users of H2 need to judge whether their use of the library exposes them to the CVE (which in many cases would yield a **no**, so they can validly suppress it) and whether they would want to continue usage of a library where the maintainer opinion essentially comes down to 'even though nobody in there sane mind should use it, for the reasons raised by the reporter, I see no reason to remove the feature'.

**Comment by pradeepanchan** [comment]
@aikebah - i would like to know how can someone disable this feature. I understand that "nobody should be doing it", but... unfortunately, everyday, people die in road accidents.

So, it trickles down to how we design the software and limit the chances of users making mistakes. 

I understand the the option is useful for automation. What i can suggest is that we can a separate executable which accepts this parameter and let people download it separately; and remove this feature from the main distribution.

Anyway, i leave the decision to you. Probably, some food for thought.

**Comment by aikebah** [comment]
> @aikebah - i would like to know how can someone disable this feature. I understand that "nobody should be doing it", but... unfortunately, everyday, people die in road accidents.
> 

By not taking the offical h2 as a dependency, but your own fork of it in which you take the offending code out (or by convincing the h2 maintainer to take the feature out of the codebase of the official version)
