### ISSUE TITLE
Upgrading the Server from 7.4.4 to 8.x results in Jenkins build error

### ISSUE THREAD

**Issue by kaszuster** [dependency-check/DependencyCheck#5616]
**Describe the bug**
I am using dependency-check as a step in my build pipeline. Upgrading the server from 7.4.4 to 8.x (tested on 8.2.1 and 8.0.?) results in a build error. The report is created and the build still finishes, but is marked as failed.

**Version of dependency-check used**
The problem occurs using version 8.x of the cli tool installed via Jenkins plugin.

**Log file**
```
2023-03-29T08:12:38.632Z] [INFO] Finished Unused Suppression Rule Analyzer (0 seconds)
[2023-03-29T08:12:45.222Z] [INFO] Analysis Complete (126 seconds)
[2023-03-29T08:12:45.360Z] [INFO] Writing report to: /xxx/workspace/xxx/./dependency-check-report.xml
[2023-03-29T08:12:49.508Z] [ERROR] Archive contains a file (/) that would be extracted outside of the target directory.
[2023-03-29T08:12:49.587Z] ERROR: Mark build as failed because of exit code 242
[Pipeline] dependencyCheckPublisher
[2023-03-29T08:12:49.593Z] Collecting Dependency-Check artifact
[2023-03-29T08:12:49.892Z] Parsing file /xxx/workspace/xxx/dependency-check-report.xml
```

**Expected behavior**
The errors
```
[2023-03-29T08:12:49.508Z] [ERROR] Archive contains a file (/) that would be extracted outside of the target directory.
[2023-03-29T08:12:49.587Z] ERROR: Mark build as failed because of exit code 242
```
should not happen and the build should finish successfully. 

**Additional context**
- Its a Java Projekt.
- Not sure but i think the exit code changes between 242 and 14

**Comment by aikebah** [comment]
The error log indicates that one of the archives contained in your project cannot be properly analyzed as it would trigger writing to arbitrary (`/`) locations on your filesystem instead of being constrained to the target temporary extraction folder. This error is signalled by the CLI as a nonFatal error, resulting in exit code 14 for v8+,  in version < 8 the exit code used for the same was -14, which would translate to 242 when taken modulo 256.

So my suspicion is that the Jenkins plugin (not maintained by us) is doing some analysis from the exit codes and has not been updated to support the new exit-codes of ODC 8.x.

**Comment by kaszuster** [comment]
After a coupe more runs i have to say, that this error is occurring in all Versions i have tested (7.x and 8.x). Maybe the first Build of the day does not trigger this one? 

I'll try to gather more information.

@aikebah Thanks for the explanation, I'll update the Jenkins Plugin (currently we are not using the newest one) and Post my results.

**Comment by aikebah** [comment]
Also good to be aware that what the Jenkins plugin uses to run dependencyCheck is the CLI. If your Java project uses maven or gradle to build you're better off running the maven- respectively gradle-plugin to perform the analysis as it is much better at avoiding false-positive matches because it takes the dependency artifact information of the build-tool into account when guessing the CPE of each dependency and uses the transitive dependency-tree. The CLI analysis requires you to ensure that in your build you copy all (transitive) dependency artifacts to the Jenkins workspace to have proper coverage of the projects dependencies.

**Comment by kaszuster** [comment]
Thanks for the recommendation, i'll definitely consider using the maven plugin. Since we are using the same Jenkins Pipeline for a lot of projects i thought its a better idea to implement ODC into that shared pipeline than adding ODC to all the projects separately. Anyway, i'll check that one more time.

Updating the jenkins plugin didn't solve my problem. 

Don't know why, but it looks like my jar archive is kinda broken. I tried to extract it with "Engrampa" resulting in:
```
warning:  stripped absolute path spec from /
mapname:  conversion of  failed
warning:  stripped absolute path spec from /cxf-rt-3.5.5.pom
```
I think thats the root of the Problem. Extracting only this file works just fine.

**Comment by kaszuster** [comment]
I checked some older releases of that jar, because i didn't expect any changes in the last couple of months and that was exactly the case, all the jars have the same problem, but ODC didn't care as much before.

After that i did a couple of scans with different version of ODC. My Tests show, that starting from Version 8.0.2 i see my builds fail. After checking the changelog i noticed #5371, wich seems to be responsible for this change in behavior resulting in the following question:

Is my jar broken (it looks like it was properly scanned, because a report was generated) or is it a "bug" in the jenkins DC plugin, because it considers `[ERROR] Archive contains a file (/) that would be extracted outside of the target directory.` as a fatal error. Any recommendations? 

I have also checked why my previous tests on jenkins with ODC < 8.x did end up throwing the same error. It looks like the plugin didn't downgrade ODC properly. So my Comment `After a coupe more runs i have to say, that this error is occurring in all Versions i have tested (7.x and 8.x). Maybe the first Build of the day does not trigger this one?` is actually wrong.

**Comment by jeremylong** [comment]
The check for absolute paths was put in to avoid [Zip Slip](https://security.snyk.io/research/zip-slip-vulnerability) vulnerabilities. In previous versions we may not have "failed" due to this error and it may have only been visible in the logs. One thing you can do is configure the `failOnError=false`. Additionally, consider opening a defect for the JAR file indicating that the JAR file should not have an absolute path.

**Comment by kaszuster** [comment]
Since i do not use the Maven plugin but CLI (via Jenkins Plugin), i do not have the option of `failOnError=false` or am i missing the CLI param? Additionally the build is not failing, everything works just fine but the Jenkins build ends up in an error state.

Since the jar is build by my team i have to dig deeper into why this file is packed with an absolute path. 

I am just wondering if "not being able to extract the jar that contains my code" actually IS a fatal error or not? This is the jar i created and i want to scan, not any kind of embedded archive that could lead to a zip slip.

I am definitely not an export when it comes to this kind of topics, so maybe i misunderstood parts of the concept.

**Comment by aikebah** [comment]
For the CLI it is not a fatal error, but the Jenkins plugin treats all non-zero exit codes equal and fails the build:

https://github.com/jenkinsci/dependency-check-plugin/blob/fe6fc13cb5e3f9b467aa975781f038645baf3675/src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckToolBuilder.java#L158

**Comment by aikebah** [comment]
exit code 0 signals success with no vulnerable dependencies detected
exit code 15 indicates a successful run with one or more vulnerable dependencies detected
exit code 14 indicates non-fatal errors occurred during analysis

other (1 through 13) indicate various errors that I think are all to be considered fatal errors.

**Comment by kaszuster** [comment]
@aikebah thanks for the clarification! 

I opened a ticket for the Jenkins Plugin Team (https://issues.jenkins.io/browse/JENKINS-70900). 

I think this one here can be closed.
