### ISSUE TITLE
[FP]: CVE-2023-26119 htmlunit flagged as neko-htmlunit

### ISSUE THREAD

**Issue by cula011** [dependency-check/DependencyCheck#5656]
### Package URl

pkg:maven/net.sourceforge.htmlunit/neko-htmlunit@2.66.0

### CPE

`cpe:2.3:a:htmlunit_project:htmlunit:2.66.0:*:*:*:*:*:*:*`

### CVE

CVE-2023-26119

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

8.2.1

### Description

According to https://nvd.nist.gov/vuln/detail/CVE-2023-26119 not an issue in neko-htmlunit itself.

**Comment by amousset** [comment]
~It seems affected according to https://github.com/HtmlUnit/htmlunit-neko#cve-2023-26119~ Given the [fix](https://github.com/HtmlUnit/htmlunit/commit/641325bbc84702dc9800ec7037aec061ce21956b) is in htmlunit and neko-htmlunit is an htmlunit dependency, this looks indeed like a false positive.

**Comment by chadlwilson** [comment]
For what it's worth, while I had the same initial instinct here, I don't think the suppression here is appropriate as neko-htmlunit is a fork of the original project that is now _built, maintained and packaged with htmlunit, and versioned alongside it_. https://github.com/HtmlUnit/htmlunit-neko

This particular CVE was fixed inside htmlunit https://github.com/HtmlUnit/htmlunit/commit/641325bbc84702dc9800ec7037aec061ce21956b and they consider it an htmlunit CVE, along with some others. 

So while this particular CVE is in in wider htmlunit rather than Neko-htmlunit, there is only one CPE, and there are CVEs that affect neko-htmlunit (categorised by NVD under htmlunit) and suppressing the whole CPE would create false negatives since there appears to not be a separate CPE for the Neko html parser.

**Comment by chadlwilson** [comment]
There are a few additional CVEs flagged too, which are in a similar boat, some of which are specifically referred to on the neko-htmlunit github or wider htmlunit release notes. I.e some apply to neko AND the wrapping htmlunit, and some to htmlunit only.

CVE-2022-28366 (fixed in `2.27`) affects Neko + htmlunit
CVE-2022-29546 (fixed in `2.61`) affects Neko + htmlunit
CVE-2023-2798 (fixed in `2.70`) affects htmlunit only
CVE-2023-26119 (fixed in `3.0.0`) affects htmlunit only
CVE-2023-49093 (fixed in `3.9.0`) affects htmlunit only

https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=cpe%3A2.3%3Aa%3Ahtmlunit%3Ahtmlunit%3A*%3A*%3A*%3A*%3A*%3A*%3A*%3A*&search_type=all&isCpeNameSearch=true

**Comment by dmitry-weirdo** [comment]
The same problem for me, `org.htmlunit:neko-htmlunit:jar:3.6.0:compile` fails with 

```
[ERROR] One or more dependencies were identified with vulnerabilities that have a CVSS score greater than or equal to '8.0': 
[ERROR] 
[ERROR] neko-htmlunit-3.6.0.jar: CVE-2023-49093(9.8)
```

Although https://nvd.nist.gov/vuln/detail/CVE-2023-49093 applies to `org.htmlunit.htmlunit`, NOT to `org.htmlunit.neko-htmlunit`.

My transient dependency comes from `org.owasp.esapi:esapi:jar:2.5.3.1`:
```
+- org.owasp.esapi:esapi:jar:2.5.3.1:compile
|  +- xom:xom:jar:1.3.9:compile
|  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
|  |  +- commons-logging:commons-logging:jar:1.2:compile
|  |  \- commons-collections:commons-collections:jar:3.2.2:compile
|  +- commons-configuration:commons-configuration:jar:1.10:compile
|  +- commons-lang:commons-lang:jar:2.6:compile
|  +- org.apache-extras.beanshell:bsh:jar:2.0b6:compile
|  +- org.owasp.antisamy:antisamy:jar:1.7.4:compile
|  |  +- org.htmlunit:neko-htmlunit:jar:3.6.0:compile
````

This is a definitive false-positive. Please fix.

**Comment by aikebah** [comment]
As indicated by @chadlwilson the neko-htmlunit library is one of the components of the Common Platform Enumeration code `cpe:2.3:a:htmlunit_project:htmlunit` (and always released together with htmlunit itself). 
As a policy this project does not attribute the NVD sourced vulnerabilities to individual components of a product seen as one by the maintainers of the NVD (a single CPE for multiple libraries). 
As such, this false-positive will not be suppressed by us and it is left to the maintainers of software products using only neko-htmlunit to decide between upgrading to the current release or adding a suppression of their own.
