### ISSUE TITLE
False positive on tomcat-embed-logging-log4j v7.0.70

### ISSUE THREAD

**Issue by gary-kupferle** [dependency-check/DependencyCheck#571]
False positive on tomcat-embed-logging-log4j v7.0.70 - reported as cpe:/a:apache:tomcat:4.0.0

<dependency>
    <groupId>org.apache.tomcat.embed</groupId>
    <artifactId>tomcat-embed-logging-log4j</artifactId>
    <version>7.0.70</version>
</dependency>

I noticed this because I also have an app under OWASP dep check that uses tomcat-embed-logging-log4j v7.0.69 and v7.0.70 (newer) has many more reported violations (4 of same suppressions in both projects, so the count for this lib should be roughly the same).

I created a STLP (stupid little test project) that scanned both. I've attached a screenshot of that report that shows tomcat-embed-logging-log4j v7.0.70 reported as apache:tomcat:4.0.0 (vs 7.0.69 version of same lib being correctly processed).

Not familiar with source of this project, but if someone can point me in the right direction, I'm happy to attempt a fix in a PR.

Thanks,
Gary

![depcheck-tomcat7_0_70_issue](https://cloud.githubusercontent.com/assets/457003/18732216/19e10052-8027-11e6-930f-24173d31af9d.PNG)

**Comment by jeremylong** [comment]
This error is due to the version number matching performed in the `org.owasp.dependencycheck.analyzer.CPEAnalyzer`. I already have a plan for how this type of incorrect match needs to be fixed and I will hopefully be able to implement it soon.  The root of the problem lies in the [determineIdentifiers](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/analyzer/CPEAnalyzer.java#L545). The purpose of this function is to identify the vulnerable version number of the identified product. However, I believe it needs to be completely re-written.

1) At the start of this routine we know that the vendor & product match a Common Platform Enumeration (CPE); we just do not know the exact version number. The result of this search could be a CPE value that does not actually exist in the NVD (because no known vulnerabilities exist for the version).
2) If we have a single version number present multiple times in the version evidence collection with highest or high confidence we should be fairly confident that this is the correct version number and not allow a match due to lower confidence version number evidence. Thus, we should create an algorithm to refine the version number list obtained from the version evidence.
3) To accomplish the match we should then generate a list of version numbers from the NVD CVE data and sort them (rather then using the current nested looping mechanism) and identify where in the list the dependency version number falls (it may be a newer version number and as such have no vulnerabilities).

The above is my initial thoughts on how to re-write the matching algorithm. However, this may cause incorrect matches as it is possible that we come up with a vendor/product match with a guess on the version number - when the vendor/product match is actually not correct. So we should cycle through all of the confidence levels (for vendor/product matches) and determine if there is a better match of the entire CPE value at a lower confidence.

Some implementation and testing work will need to occur; one of the reasons I have not touched this yet is I wanted to completely think through what changing a core algorithm like this will due to the matching of evidence to CPE identifiers.

**Comment by jeremylong** [comment]
A version number filter was added that resolves this false positive.
