### ISSUE TITLE
Running Central DB

### ISSUE THREAD

**Issue by pteichner** [dependency-check/DependencyCheck#5730]
1. I have created a MariaDB and ran the initialization script on it.
2. I have a dedicated job that mirrors the CVE and other sources from the internet and runs maven in update-only mode

Q1: I'm a bit confused if I need to use the custom properties file?
Q2: I'm getting an error that I've attached is there something missing?
Q3: When using the CLI the JDBC driver is still needed to be pulled down, correct?

Thanks

**Comment by pteichner** [comment]
![Untitled(1)](https://github.com/jeremylong/DependencyCheck/assets/92022180/34b0f6fa-e661-4f11-ac2b-f798f2921d91)

**Comment by aikebah** [comment]
Q1: You don't need a custom properties file for the maven plugin, you can configure the dependency-check-maven-plugin in the pom-file
Q2: The error (as indicated in #5733) appears to be caused by a file encoding issue with non-representable characters having been replaced by the 'replacement character' U+FFFD, an issue that appears to have been resolved by an updated known exploited vulnerabilities JSON file.
Q3: Yes, for the CLI you would need to download the mysql/mariadb jdbc driver and configure the CLI with the proper `--dbDriverPath` (but the CLI is expected to run into the same error had the known exploited vulnerabilities file not been modified)
