### ISSUE TITLE
[FP]: bazaarvoice json-utils confused for utils_project:utils

### ISSUE THREAD

**Issue by chadlwilson** [dependency-check/DependencyCheck#5753]
### Package URl

pkg:maven/com.bazaarvoice.jolt/json-utils@0.1.8

### CPE

`cpe:2.3:a:utils_project:utils:0.1.8:*:*:*:*:*:*:*`

### CVE

CVE-2023-2972

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

8.2.1

### Description

This one is essentially another variant of https://github.com/jeremylong/DependencyCheck/issues/5213 - another CVE raised against a [different utils project](https://github.com/antfu/utils), but unhelpfully [tagged to a generic CPE](https://nvd.nist.gov/vuln/detail/CVE-2023-2972) by the NVD folks as if they are one cohesive product.

We might want to consider again if we should put a generic CPE suppression in place for `utils_project:utils` as NVD keep tagging it to random stuff as I imagine there will be many of these.

Alternatively, we could add the specific CVE to the rule at https://github.com/jeremylong/DependencyCheck/commit/04438ecf5e732c2bdb0c4747b9d7bb81a5a77804 - will take @aikebah guidance here.

**Comment by aikebah** [comment]
@chadlwilson The CPE assignment for the CVE in the NVD is clearly wrong (as project antfu utils is a published npm packge it should've received its own unique CPE).

As such we should not add the CVE to the rule you mentioned, which is just blindly suppressing a CVE that was raised on a repository with a collection of scripts that was never meant to be ever released as a package of some kind to depend upon.

`@antfu/utils`, being an npm package that others can be expected to build upon, should not get the same treatment.

I have contacted NVD in order to try and get the record updated to use a proper CPE which would hopefully also remove this FP match once they've processed my mail.

**Comment by chadlwilson** [comment]
OK, fair enough, but there is still a fundamental CPE mismatch on dependency check side here. Just because a mvn package has `utils` in the name does not make it `cpe:/a:utils_project:utils`, but that is how it currently behaves.

**Comment by aikebah** [comment]
approved


@chadlwilson hope to take a look later to review whether we should put a broader suppression in place in a next release for the tool-embedded suppressions, but this will get it out of the way for this lib for now
