### ISSUE TITLE
[FP]: Libraries with 'utils' in name are detected as 'utils_project'

### ISSUE THREAD

**Issue by ghost** [dependency-check/DependencyCheck#5829]
### Package URl

pkg:maven/com.exactpro.th2/netty-bytebuf-utils@0.0.1

### CPE

`cpe:2.3:a:utils_project:utils:0.0.1:*:*:*:*:*:*:*`

### CVE

CVE-2023-2972

### ODC Integration

{"label"=>"Gradle Plugin"}

### ODC Version

8.2.1

### Description

The same issue is with our own library that also has `utils` in name.

`task-utils-0.1.2.jar (pkg:maven/com.exactpro.th2/task-utils@0.1.2, cpe:2.3:a:utils_project:utils:0.1.2:::::::*) : CVE-2023-2972`

**Comment by aikebah** [comment]
approved

@vdonadze For your internal lib, I would suggest to internally publish the suppression, as we typically only add suppressions for libraries that are openly available so that we can assess whether we agree that the given library does not match the associated CPE. 
ODC can be offered multiple suppression files, e.g. a centrally hosted one maintained by some core team and a project-specific one stored with the project in version control.

A generic solution for this specific CPE (and a few similar CPE cases) may potentially be added in some future release of ODC if we can find a good way of rooting out FP matches while continuing to discover the product at hand (that is not introducing a false negative). There are a couple of similar issues with very generic `xxx_project:xxx` type CPE that trigger similar issues due to the generic nature of the `xxx`.
