### ISSUE TITLE
When unable to retrieve CVE updates, a warning is shown, and the goal fails

### ISSUE THREAD

**Issue by karstenspang** [dependency-check/DependencyCheck#5831]
**Describe the bug**
When dependency-check-maven tries to update the CVE list, it often fails. I get
```
[ERROR] Error retrieving https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta; received response code 503; Service Unavailable
```
a number of times.
Then I get
```
[WARNING] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
```
But after that the `check` goal fails with
```
[ERROR] Unable to continue dependency-check analysis.
```
**Version of dependency-check used**
The problem occurs using version 8.3.1 of the maven plugin.

**Log file**
https://gist.github.com/karstenspang/48be2322794b88ec0d250789f8e7dfc3

**To Reproduce**
After running successfully, so the cache is reasonably fresh, run again when NVD has problems.

**Expected behavior**
Since I get a warning, I expect the analysis to continue.

**Additional context**
The cache was updated the day before.
`failBuildOnCVSS` is set to 9. No other configuration is set.

**Comment by aikebah** [comment]
That's what the http://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html `failOnError` is meant for if you want to continue regardless of the failure to update vulnerability-data (as long as older, cached data is available for use)

**Comment by karstenspang** [comment]
Thanks for the clarification

**Comment by propertius** [comment]
> That's what the http://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html `failOnError` is meant for if you want to continue regardless of the failure to update vulnerability-data (as long as older, cached data is available for use)

Would it be possible to change the documentation? I find that the following description does not quite transmit what you are stating above:

_Whether the build should fail if there is an error executing the dependency-check analysis._

**Comment by aikebah** [comment]
@propertius Does not cover the specialist case of this issue, but the generic case of 'a non-fatal error anywhere in the analysis'. 

The specific case here is the failure to perform an update of the vulnerability-sources used in the analysis. There are more cases of (non-fatal) errors that get suppressed by it when disabled.

By default these non-fatal errors make dependency-check 'fail-at-end' (with a report on anything that, despite the errors, could be extracted) as the analysis is considered to be likely incomplete due to the errors.

There is a limited set of errors that are considered so fatal for running that even the 'failOnError' setting will not prevent ODC from failing.
