### ISSUE TITLE
[FP]: CVE-2017-16055 affecting a C# project

### ISSUE THREAD

**Issue by kipusoep** [dependency-check/DependencyCheck#5841]
### Package URl

None

### CPE

cpe:2.3:a:sqlserver_project:sqlserver:*:*:*:*:*:node.js:*:*

### CVE

CVE-2017-16055

### ODC Integration

{"label"=>"CLI"}

### ODC Version

8.3.1

### Description

The message I get is:

> location: /home/vsts/work/1/s/<redacted>/tools/<redacted>/<redacted>.csproj, project-references: [  ]

The thing is, it's a C# project, so I'm not sure why this CVE is triggered.
The contents of the project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId><redacted></UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="MediatR" Version="12.1.1" />
    <PackageReference Include="Dapper" Version="2.0.143" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog" Version="3.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
    <PackageReference Include="<redacted>.<redacted>.<redacted>" Version="1.0.45308" />
    <PackageReference Include="<redacted>.<redacted>.<redacted>.<redacted>" Version="0.1.45500" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.35.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\<redacted>.csproj" />
    <ProjectReference Include="..\..\src\<redacted>.csproj" />
    <ProjectReference Include="..\..\src\<redacted>.csproj" />
  </ItemGroup>

</Project>
```

**Comment by aikebah** [comment]
@kipusoep removed FP Report label to prevent our FP evaluation github action from running uselessly.

Are there any signs of sqlserver in the 'Evidences' section of your HTML report? The sources of that would be likely to trigger this FP issue

**Comment by aikebah** [comment]
looking again at your project file (overlooked it on first read) I suspect     `<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.9" />` will trigger it

But nevertheless interested in what evidences are present in your report that have sqlserver in their value.

**Comment by kipusoep** [comment]
I'm unable to find an HTML report to be honest. We're running it in Azure DevOps and it produces 3 files AFAIK:
- Standard_Console_Output.log
- Standard_Error_Output.log
- dependency-check-junit.xml

I don't see anything called evidence inside those files. Can you guide me in the right direction?

**Comment by aikebah** [comment]
Which would mean the Azure DevOps is configured to only produce the junit-format report, one of the worst for further analysis due to the restrictions on the junit format.

Assuming your integration is https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck you should be able to add additional formats (they have their screenshot sample to create HTLM, JSON and JUNIT format reports). The HTML format is the most useful one for human interpretation (may have to be downloaded to make the embedded Javascript routines work properly to show and hide the various sections).

**Comment by kipusoep** [comment]
Thanks @aikebah!
This is the evidence part of the report:
![image](https://github.com/jeremylong/DependencyCheck/assets/1866549/a7222a69-d16f-4c07-9013-5d5c8033d785)

**Comment by aikebah** [comment]
@kipusoep From that I would suspect that you have a file CosmosDb2SqlServerMigration_2.dll or CosmosDb2SqlServerMigration-2.dll in your project that the analyzers (typically AssemblyAnalyzer and the experimental PEAnalyzer) could not extract information from so that you're left with only the information extracted by the FileNameAnalyzer.

(could also be something else than a DLL, but DLL would be my best guess based on your project type and the fact that often there are DLLs that create issues in the analysis by the Assembly- and PE-Analyzers. The clear symptom is that only the FileNameAnalyzer manages to extract some evidences, where the `CosmosDb2SqlServerMigration` is expected to be the part before a `_` or `-` separating the filename part from the version part in the filename)

**Comment by kipusoep** [comment]
It doesn't seem like I have a file called like that.
Anyway, it's a FP right? Or should I do something to fix it?

**Comment by aikebah** [comment]
As you have a C# project it will definitely be a FP. 
On the html report there is a 'suppress' button next to the CPE. That should give you a suppression rule to suppress it. My gut feel based on the evidences you listed would be that it's going to suppress by sha1 hash, which means it will only work as long as the file on which it hits retains its sha1 hash checksum.

If it's listed for a file that is expected to frequently change that could be found to be problematic.

As long as you do not add any node.js to the project it would be possible to create a generic CPE suppression to suppress the sqlserver_project:sqlserver CPE. in such a case I would advice adding an expiry on it so that periodically it's re-evaluated that the project is indeed a pure C# project not using any node.js.

**Comment by kipusoep** [comment]
Hmm I would like to be able to surpress, the downside is that our pipeline calling the dependency check is a template, so shared for all our repositories (micro services).
I've just tested supplying a `--suppression` argument with a file that doesn't exist (so we can opt-in by creating a file in the repo root, or leave it as-is), but it complains about the file missing unfortunately.
So that would mean we have to check with bash or powershell if the file exists and adapt the argument with that.
