### ISSUE TITLE
[FP]: multiple vaadin CVEs report FP on vaadin-swing-kit-flow

### ISSUE THREAD

**Issue by ZheSun88** [dependency-check/DependencyCheck#5860]
### Package URl

pkg:maven/com.vaadin/vaadin-swing-kit-flow@2.1.0

### CPE

cpe:2.3:a:vaadin:flow:2.1.0:*:*:*:*:*:*

### CVE

CVE-2021-31411, CVE-2020-36321, CVE-2021-31405, CVE-2021-31407, CVE-2021-31412, CVE-2021-31404, CVE-2021-33604

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

8.3.1

### Description

vaadin-swing-kit-flow is using vaadin-flow 24.x, which should not be reported with the given CVEs

**Comment by aikebah** [comment]
approved

@ZheSun88 I'll close your PR. The PR-based changes are not getting reflected in the hosted suppressions, which means approving the FP report is the better option (PR-based suppressions require a new release to become effective, FP-report flow based hosted suppressions take effect immediately (with a delay of 2hrs for hostedSuppressions validForHours configuration) for all internet connected users.

Periodically we integrate the hosted suppressions into the packaged suppression file so that also users in an internet-restricted environment can benefit from the suppressions after a new release.
