### ISSUE TITLE
[FP]: grpc-kotlin-stub-1.3.1.jar triggers CVE-2023-33953

### ISSUE THREAD

**Issue by rseeton** [dependency-check/DependencyCheck#5917]
### Package URl

pkg:maven/io.grpc/grpc-kotlin-stub@1.3.1 

### CPE

cpe:2.3:a:grpc:grpc:1.3.1:*:*:*:*:*:*:*

### CVE

CVE-2023-33953

### ODC Integration

{"label"=>"CLI"}

### ODC Version

8.4.0

### Description

As far as I can tell, the CPE for the CVE-2023-33953 is incorrectly picking up various GRPC helper files.  

We have the same issue with two packages: 

- pkg:maven/io.grpc/grpc-stub@1.46.0
- pkg:maven/io.grpc/grpc-kotlin-stub@1.3.1 

Thanks.

**Comment by aikebah** [comment]
approved

@rseeton if you could be so kind to file the other two as well as separate FP reports I'll fast-track them into the hosted suppressionsfile for all to benefit

**Comment by rseeton** [comment]
@aikebah  - As requested, I've filed as second issue (https://github.com/jeremylong/DependencyCheck/issues/5918) for the related grpc-stub-1.46.0 report. 

Related question - both jars are also triggering a CVE-2023-32732 issue as well - Do we want 2 more tickets for those as well?

(I don't have an issue with spawning more issues - let me know what approach you prefer.)

**Comment by aikebah** [comment]
@rseeton,

I'm going to backout the already added suppression. I misread the artifact as something outside of the grpc libraryset, but it is part of it.

As a project we opted to not do detailing of issues per individual library of a set released as a whole that get a single CPE in the NIST NVD.

The strategy of this project is to take jar, establish the coordinates of the project it belongs to in the coordinate system of open vulnerability databases. 
For NVD (CPE) this can have errors due to fuzzy text matching logic.
For OSSindex it is typically correct as that is the package-url derived from maven coordinates).

Sorry for the confusion, but I genuinely thought last night that the libraries were similar to the various projects in the Spring ecosystem (where individually release projects interacting with/supporting Spring which are separate from the Spring framework get linked to the Spring Framework CPE while they have a fully independend release schema (as well as versions)
