### ISSUE TITLE
EOSL of Version : 8.1.0

### ISSUE THREAD

**Issue by Mridula03g** [dependency-check/DependencyCheck#5934]
Hi @jeremylong 

Can you please confirm what is EOSL of version : 8.1.0

Thank you,
Mridula U

**Comment by jeremylong** [comment]
We generally don't backport any bug fixes. I'm working on 9.0.0 right now - which will support the NVD API instead of the NVD data feed. I expect to publish 9.0.0 within a month.

The NVD has announced the data feed will be retired Dec 15th, 2023: https://nvd.nist.gov/vuln/data-feeds. 8.1.0 will continue to work until that time.

**Comment by Mridula03g** [comment]
Thanks for the quick response @jeremylong
