### ISSUE TITLE
[FP]: CVE-2023-40743 org.apache.axis2/addressing@1.8.0

### ISSUE THREAD

**Issue by rochish-suresh** [dependency-check/DependencyCheck#5945]
### Package URl

`pkg:maven/org.apache.axis2/addressing@1.8.0`

### CPE

`cpe:2.3:a:apache:axis:*:*:*:*:*:*:*:* versions up to (excluding) 2023-08-01`

### CVE

CVE-2023-40743

### ODC Integration

None

### ODC Version

8.2.1

### Description

[CVE description](https://www.cve.org/CVERecord?id=CVE-2023-40743) says the package is org.apache.axis group, but the CVE is been reported in org.apache.axis2. 
Recommendation in the CVE database asks to use axis2 package instead of axis as workaround. 
Does this mean the CVE is reported false positive or a valid one?

Gradle code: 
`implementation group: 'org.apache.axis2', name: 'addressing', version: '1.8.0', classifier: 'classpath-module'`

**Comment by aikebah** [comment]
CVE description says nothing about the group, only that it's about Axis 1, but your derivation that Axis 1 is the org.apache.axis groupId and Axis 2/Java is the org.apache.axis2 groupId is correct, so it is indeed a false-positive.

**Comment by raghulvishnudhinesh** [comment]
Any Updates to resolve this false positive?

**Comment by lbruun** [comment]
I believe the issue is that of **Library Identification** (i.e. the link between a CVE and then mapping that to actual Maven GAV coordinates). 

AFAIK, the OWASP Dependency Checker doesn't have any such information so it simply makes a guess based on some text matching. The reason for that is that such mapping hasn't existed ..until the folks at Google decided to do something about it and launched their OSV.dev initiative. The OSV can indeed do the mapping between this particular CVE and to the exact Maven coordinates that are vulnerable. See [CVE-2023-40743 in OSV database](https://osv.dev/vulnerability/GHSA-rmqp-9w4c-gc7w). But the OWASP DependencyChecker doesn't use this information. (to be fair Google's initiative has only launched recently)

I've created Enhancement Request [6039](https://github.com/jeremylong/DependencyCheck/issues/6039) to this end.

**Comment by herohung093** [comment]
The same CVE is reported on package `pkg:maven/org.apache.axis2/mex@1.6.4-impl` Do we have any update on when this will be resolved.

**Comment by cabutler-7** [comment]
Any updates on this false positive?

**Comment by cabutler-7** [comment]
Any updates on this false positive?
