### ISSUE TITLE
How do I know which version of the dependency has the CVE resolved?

### ISSUE THREAD

**Issue by Kim-Young-Joon** [dependency-check/DependencyCheck#5987]
I would like to find the CVE for the dependency I am using and use a version that has this CVE resolved.
Is there a way to find out which version a specific CVE is addressed in?
If so, I would appreciate it if you could let me know.

** The dependency I'm talking about is Maven GAV

**Comment by Kim-Young-Joon** [comment]
The dependency I'm talking about is Maven GAV

**Comment by aikebah** [comment]
When you run dependencycheck on a project it will typically result in an html file dependency-check-report.html. If you open that in your webbrowser you can find 'references' alongside the CVE. Typically the information you're looking for can be found in one or more of those references. Many times it's even already in the CVE description itself.

**Comment by aikebah** [comment]
Note however that as a general rule-of-thumb it is advisable to stay up-to-date with your dependencies during regular maintenance in order to avoid having a hard time upgrading from version a.b.c to x.y.z (skipping multiple major versions) in future should a vulnerability be uncovered in a dependency (which only got fixed on the more recent versions).

That's one of the reasons why OWASP top 10 has been updated from 'using known vulnerable components' (A9 in 2017) to 'vulnerable and outdated components' (A7 in 2021) as the security-issue with regards to dependencies/components of your applications.

So it should most of the time not matter that much to you which exact version fixed it. Your default instinct should be 'update to latest stable' along with 'remain up-to-date with dependencies on each maintenance activity'. The exact version in which it was resolved should only start to matter when you discover that it's not possible or very hard to upgrade to latest stable (which, most of the time, will have the patch in).
