### ISSUE TITLE
Full Path in Vulnerability report

### ISSUE THREAD

**Issue by sivaswami** [dependency-check/DependencyCheck#599]
Hi I am using Dependency Check CLI to generate XML and HTML reports. I am doing a scan for a folder structure with multiple copies of same file and at various locations.  In the Vulnerability report, Is there any way to include Relative/Absolute Path of the file

**Comment by jeremylong** [comment]
See the [sample report](http://jeremylong.github.io/DependencyCheck/general/SampleReport.html#l10_fd59331a4bbc734c290744316e627ea343329f49) for axis2-kernel-1.4.1.jar. In the summary you have the relative path, if there are more then one of the same file look at the related dependencies (click to expand) - each should have the relative path listed.  Does this help?

**Comment by sivaswami** [comment]
@jeremylong , thanks for your quick reply.  I thought of including full path and Vulnerabilities only as seen in VULN report or parse xml to generate custom report. I also see from code that we can generate custom xml report and html report using velocity templates. do I need to pass any additional parameters for this in CLI ?

**Comment by jeremylong** [comment]
The code to use external report templates is likely no longer working. I'd have to re-visit this to get it working again.  In reality though, due to the possibilities of false positives I would highly recommend using the standard HTML report to vet findings. Basically, ensure that the CPE (not the CVE) matches the dependency and create any suppression files if necassary.

**Comment by jeremylong** [comment]
The full path has been added as a tooltip to the vulnerability report.
