### ISSUE TITLE
Updated dependency still reports vulnerabilities 

### ISSUE THREAD

**Issue by orarch** [dependency-check/DependencyCheck#6009]
Hi,

https://github.com/google/flogger has updated its dependency on grpc to one without any vulnerabilities as part of its 0.8 release.

However, running mvn dependency-check:aggregate with the owasp dependency-check-maven plugin (8.4.0) still returns error for this dependency: 

> [ERROR] One or more dependencies were identified with vulnerabilities:
> [ERROR]
> [ERROR] flogger-grpc-context-0.8.jar: CVE-2017-8359(9.8), CVE-2023-33953(7.5), CVE-2023-32732(5.3), CVE-2020-7768(9.8), CVE-2017-7861(9.8), CVE-2017-9431(9.8), CVE-2017-7860(9.8)
> [ERROR]
> [ERROR] See the dependency-check report for more details.

Can you please assist in understanding why's that?

**Comment by aikebah** [comment]
The reason for it can be derived from the ['How it works'](http://jeremylong.github.io/DependencyCheck/general/internals.html) in our documentation: CPE's, which are the key towards CVEs from the NVD vulnerabilities datasource, are derived from various evidence strings collected from the dependency. For various frameworks that have there name repeated in independently released libraries this will trigger false positives like the one you encountered.

From the evidences DependencyCheck wrongly derives that your library is (a part of) grpc 0.8, rather than an independent library in version 0.8 that is designed to work with up-to-date grpc.

**Comment by orarch** [comment]
Thanks! Very helpful!
