### ISSUE TITLE
CVEs shown despite fixed version

### ISSUE THREAD

**Issue by TobiElo** [dependency-check/DependencyCheck#6083]
**Describe the bug**
The dependency check shows 3 CVEs for moment.js: CVE-2022-24785, CVE-2022-31129, CVE-2023-22467
All of these are fixed in the Version of moment.js I use (2.29.4).
The Identifier seems to have the right version: pkg:javascript/moment.js@2.29.4%5Cmoment-with-locales.min

**Version of dependency-check used**
I use the newest version of the gradle plugin.

**Comment by chadlwilson** [comment]
I can't replicate this.

@TobiElo Could you please close this and re-raise as a "false positive" report if you still have a problem (this template asks you to provide the required information to figure out where the problem is coming from).

I suspect this is coming from retirejs and if it's still a problem may need to be fixed with their rules.
