### ISSUE TITLE
Suppress button not working

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#609]
Hi

I am trying to suppress false possitives on my application, but the suppress button doesnt seem to work. When clicking on it, no dialog box or similar is displayed

I am using version 1.4.3

Thanks

**Comment by jeremylong** [comment]
What browser/version are you using?

**Comment by javixeneize** [comment]
I have tried it with firefox, iexplore and chrome. Inspecting the button i
can see the copy action, but nothing is copied

As its the first time i am using this, i also tried the complete xml doc,
and nothing happens there too

**Comment by stevespringett** [comment]
If you're viewing the dependency-check HTML report from a Jenkins workspace, then this is expected behavior as Jenkins introduced CSP filters that prevent inline Javascript from executing. Workaround is to save the file locally and view it that way or relax the CSP filter.

**Comment by javixeneize** [comment]
Thanks Steve. Will check that

What should happen when i do this? Will it generate a xml?

If so, maybe its easier to create that xml manually

Let me explain the issue i have and what i want to achieve

I have a job that updates the vulnerability DB every day

I have 6 jobs that read from that DB and analyse my files. In all those
jobs i have the same false possitive.

I want to remove this false possitive to make from all the jobs. Do i need
to do that one by one?

Note that i am deleting the workspace before running my jobs, so if the
false possitive file is stored in this directory, it will be removed when
the job runs

thanks

**Comment by stevespringett** [comment]
If you're scanning with the Jenkins plugin, the XML will always be generated. The HTML report can optionally be generated and like I said, the CSP policy in newer Jenkins versions breaks the suppress button and many other things.

Ensure that each of the 6 jobs have "Disable NVD auto-update" checked.

You can host the suppression file on a web server and instead of supplying the path to the file, simply specify the URL. This allows you to have a single suppression file in a global scanning environment.

**Comment by jeremylong** [comment]
@stevespringett To solve the CSP issue within Jenkins we could create a slightly customized report for Jenkins. Where we put a copy of the JS into a second file that gets written to disk, leave the inline script so that the report is still viable (when loaded from Jenkins the CSP would block this), and add a script tag to load the external JS. We could likely get the report to work - might have to think about the JS being loaded twice in some cases if the report and script are outside of Jenkins.

Thoughts?

**Comment by javixeneize** [comment]
Maybe theres an easier option. Who will need to read that exclussion list?
Why dont just create a properties file?

I am an owasp member. I am happy to help with this if needed

Another thing i have noticed is false possitives based on the name. Maybe
an md5 validation will solve this. Do you want me to raise another issue
for that?

Apart from that, guys, the tools is fantastic. Well done!

**Comment by jeremylong** [comment]
Doing a little more research on the [CSP set by Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy) the only way to make the HTML report work correctly (being served from Jenkins) would be to modify the CSP header by following the instructions in the article linked to above.

As @stevespringett provided the correct answer, host the suppression file on a different server, and there is nothing we can do regarding the CSP header I am going to close this issue.

Steve - the only thing we may want to do is provide a link on the Jenkins wiki pointing back to the CSP article above.

**Comment by javixeneize** [comment]
Hi

I have found a workaround that doesnt need to modify jenkins. Its just
editing the served page and removing the CSP headers ;)

Based on my experience, i can recommend one improvement

 Looks like the tool is just detecting the name and the version. If there
is a vulnerabilty in apache 1.4, and i create a jar called apache1.1, the
plugin tells me that this jar is vulnerable. I am not sure if a MD5 check
could be added to reduce the number of false possitives

On top of that, instructions for the exclussion xml are a bit unclear. It
only explains how to generate the exclussion xml, but there are no
instructions about how to reference and configure it, etc..

Thanks
