### ISSUE TITLE
Upgrade guide for programmatic users?

### ISSUE THREAD

**Issue by vemv** [dependency-check/DependencyCheck#6164]
Hi! 

For context I maintain https://github.com/rm-hull/nvd-clojure which uses DependencyCheck programatically.

We'd appreciate an upgrade guide for 8.x -> 9.x. It doesn't appear to be immediately obvious how to start using the API instead of traditional DB downloads.

I also perceived some Java-level breaking changes, like:

* `Settings.KEYS.CVE_CHECK_VALID_FOR_HOURS` was dropped
* `.getScore` / `.getBaseScore` are now named `.getExploitabilityScore` / `.getImpactScore`

These would be great to document in the changelog. While from nvd-clojure side we can certainly make a best-effort adaptation, having an upgrade guide would increase our confidence.

Thanks - V

**Comment by jeremylong** [comment]
I would look at the changes made: https://github.com/jeremylong/DependencyCheck/pull/5978/files

It might be easier to look at a single integration for the changes - possibly the gradle plugin: https://github.com/dependency-check/dependency-check-gradle/pull/363/files

Also, due to all of the issues with the NVD API - I might hold off a little in case things change due to direction from the NVD.

**Comment by jeremylong** [comment]
see #6149 for the ongoing saga of performance issues. I believe this should be resolved soon. For now I'll close this issue. Let me know if you disagree.

**Comment by vemv** [comment]
It's alright! Thanks much for the links.
