### ISSUE TITLE
Problem with External Access ? (V 1.4.4)

### ISSUE THREAD

**Issue by blacksmithbrew** [dependency-check/DependencyCheck#631]
Hello,
I 've got an issue with LOCK of system users when running periodically the dependency check for our Java projects:
- use of local NVD data
- setting **_centralAnalyzerEnabled_** to false
- trigger check via Jenkins/Maven

Nevertheless sometimes the user of the windows system gets locked when running that process.
Can you imagine some other external access that is tried from the tool or something different which could cause the problem ?

Many thx in advance,
Markus

**Comment by jeremylong** [comment]
By LOCK do you mean it is completely hung or that people were impatient and after 5 minutes killed the process?  I only say that because I have seen the update take a while on some systems - this is normally not a problem if you keep the database and run DC at least once a week to keep the data fresh. For more help with this issue I would need to see a log file...

Another option, if it is related to the update, might be to setup a central DB server to host the DC data, set one node to update the database daily and then have all the other nodes run with the noupdate flag set. More information can be found [here](http://jeremylong.github.io/DependencyCheck/data/database.html).

**Comment by blacksmithbrew** [comment]
LOCK means that the system user on windows which runs jenkins and hence the dependency maven plugin is locked by the windows domain. That machine has no internet access and therefor we managed to download the database files separately and configured it with the plugin. But we wondered if there are more tries to access something outside because we recognized unsuccessful proxy access.
For now we introduced network tracing and wait until it occurrs again.

**Comment by jeremylong** [comment]
The only thing that reaches out to the Internet is the [EngineVersionCheck](https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/data/update/EngineVersionCheck.java). The only thing this check does is pull down `https://jeremylong.github.io/DependencyCheck/current.txt` and then compare the version number contained in the current.txt with the current version number of the plugin. This is very similar to FindBugs (see issue #82).

 Unless you disable the updates there is currently no way to disable this check.

**Comment by blacksmithbrew** [comment]
Yes, that might be the reason. But people who are using the **cveUrl*** parameters of the plugin do not have internet access and hence can't reach the version site. 
So maybe you could enhance the plugin with configurable version check someday !?

Thx and kind regards,
Markus

**Comment by colezlaw** [comment]
You can host the CVE NVD data internally, so make a process to fetch those
and update them internally periodically. Then internal users will need to
use the cveUrl parameters to point to your internal mirror of the extracts.

**Comment by jeremylong** [comment]
@MarkusS75 even if the call fails to check for the current version of the plugin - it does not affect the execution of the plugin at all. I suppose we can add a property to enable/disable the check when we get to #612 - where we will be adding additional properties to enable/disable several other analyzers.

**Comment by jeremylong** [comment]
A property has been added to disable the engine version check. This was not exposed, but can be set using `-D`.  However, most will not need the property even if they want the engine version check disabled because:

1. If auto-update is disabled the engine version check will not occur
2. If the NVD CVE URLs are modified from the original (i.e. the user has pointed them to a copy of the NVD CVE) then the engine version check will not occur

These changes will be included in the next release.

**Comment by blacksmithbrew** [comment]
Thanks a lot.
