### ISSUE TITLE
CVE-2023-36478 - MetaDatabuilder is not used in the environment.

### ISSUE THREAD

**Issue by bhaskar-s-019** [dependency-check/DependencyCheck#6344]
OWASP Dependency Checker (8.4.1) is ran on a production environment, and it identifies a HIGH vulnerablitliy talking about the CVE mentioned in the title. 

It talks about the file MetaDataBuilder file which is part of microprofile-metrics package which is not used in the environment.
Only HTTP2 libraries ( server, hpack and common ) libraries are used.

Can this be considered as False Positive, please share your comment.

**Comment by aikebah** [comment]
You provide far too little information on your scan results to be able to tell...
You'll have to judge for yourself from the information in the report, taking into account the [internals of how dependency check works](http://jeremylong.github.io/DependencyCheck/general/internals.html) and the documentation on [interpreting the report](http://jeremylong.github.io/DependencyCheck/general/thereport.html)

**Comment by bhaskar-s-019** [comment]
Thank you for your reply.
I have 5 categories to mark this vulnerability, out of which I feel FP or NA suits better.  I stick with FP (Tool found something that is not there in environment) as it appears to be an indirect dependency.

May I know what information you are expecting.

**Comment by aikebah** [comment]
(part of) the html report itself, indicating which files were discovered that were identified to be the CPE  to which the CVE is linked and what their discovered 'evidences' are that made ODC link the CPE and therfir list the vulnerability.
As indicated in the internals/report documentation the way that dependencycheck works may trigger an incorrect link between a CPE (key to find vulnerabilities listed in the NVD) due to textual similarity with (part of the) discovered evidences.
