### ISSUE TITLE
[FP]: Jetty-websocket-server/client matched with CVE-2023-36478

### ISSUE THREAD

**Issue by karthickm512** [dependency-check/DependencyCheck#6469]
### Package URl

pkg:maven/org.eclipse.jetty.websocket/websocket-server@9.4.50.v20221201

### CPE

`cpe:2.3:a:eclipse:jetty:9.4.50:20221201:*:*:*:*:*:*`

### CVE

CVE-2023-36478

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

9.0.9

### Description

The mentioned CVE impacts HTTP2 components of Jetty but not the websocket server or client components as seen in https://mvnrepository.com/artifact/org.eclipse.jetty.websocket/websocket-server and https://mvnrepository.com/artifact/org.eclipse.jetty.websocket/websocket-client. Dependency checker has flagged these components as vulnerable to this CVE. This seem to be because of pattern matching all jetty-* components.

**Comment by aikebah** [comment]
DependencyCheck project takes all libraries under one CPE as a whole and makes by design no attempt to map the CVEs registered against those in the NVD to the subcomponent that it applies to.

As the jetty project is released as a whole NVD does not allocate individual CPEs to the libraries, so this is an expected FP you'll need to deal with individually if you don't want to or can't upgrade to a version of the jetty project that fixed the flaw in their http2 component.
