### ISSUE TITLE
Vulnerabilities appear and disappear randomly

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#647]
Hi

I have a project for training porpouses that contains some vulnerable versions of dependencies

Randomly, those vulnerabilities are being picked by the tool. It is, if i analyse that now, the vulnerability is detected, but, if i rerun that the next day over the same app, it is not found

I have checked the .db and i can see that the cve for the vulnerability is there

Is there any configuration or similar needed to fix this?

Thanks

**Comment by jeremylong** [comment]
I've never run into this issue. Any chance you could provide more
information about your sample application or even the entire app? How are
you running dependency-check, what OS/version and version of Java is being
used? Also, what version of dependency-check are you using?

Also, are the different executions done online vs. offline?  I.e. when you
are connected to the Internet and dependency-check can access Maven Central
vs. doing the scan offline?  If this is the case, I'm curious if you can
share what dependencies are causing the problem?

--jeremy

**Comment by javixeneize** [comment]
Hi Jeremy

Can i write you the details to your email address?

Thanks

**Comment by jeremylong** [comment]
Sure - jeremy.long@gmail.com.

**Comment by SMUnlimited** [comment]
I have also seen this sort of issue but may not be directly related to the above issue. I have noticed when I had multiple maven projects (different projects) running owasp at the same time as each other on the same machine with the same data directory there was sometimes exceptions with temp files which caused owasp to fail early and not report all dependencies. I don't have the exception to hand anymore though, but weirdly it didn't fail the build.

As a workaround when I changed data directories to be unique for each project the issue hasn't occurred again, but I don't know if that is luck as the projects have to be timed perfectly to run at the same time and run owasp concurrently.

As an aside I'm not sure what happens if two jobs run on the same data directory and both decide to update the data folder at the same time or the data folder doesn't yet exist and both create it.

**Comment by jeremylong** [comment]
@SMUnlimited I don't think what you are describing is the same (see issue #100 for historical reference). The best would be to use a real database server (documentation [here](http://jeremylong.github.io/DependencyCheck/data/database.html)) if you have a CI server building multiple projects. I guess this is showing the real need to put our long time planned enterprise deployment guide together.

Another option that you can try is to run H2 in [automatic mixed mode](http://h2database.com/html/features.html#auto_mixed_mode) by adding `;AUTO_SERVER=TRUE` to the connection string.

**Comment by SMUnlimited** [comment]
@jeremylong: Thanks I will look into those options as contains alot of useful info in there. Using a Database server is probably the way to go as we will have multiple other machines running builds too.  

I guess the only issue to raise is that it was not noticeable at first glance. In the linked issue it hanged but in my experience it just returned less results with the error hidden in logs even though the "failOnError" flag is supposed to be on by default. 
If I can get the errors I had to happen again I will create a new issue for it.
