### ISSUE TITLE
Query on dependency check jenkins plugin usage

### ISSUE THREAD

**Issue by Ahmed-A-Syed** [dependency-check/DependencyCheck#648]
As per the docs, OWASP dependency-check’s core analysis engine can be used as:

Ant Task , Command Line Tool , Gradle Plugin , Jenkins Plugin
, Maven Plugin  and SBT Plugin.

We were planning to intergrate dependency check in jenkins. Using jenkins plugin directly is sufficient enough to run the scan and display the results (or) Do we need to run ant task /command line etc.. to generate the results and then jenkins plugin is only used to display it?

**Comment by jeremylong** [comment]
The Jenkins plugin, CLI, and Ant task (because Ivy is not yet supported) are equivalent. The Maven and Gradle plugins may give slightly better results as they are incorporated into the build process and extract the dependency information at build time. Whereas the other tools only scan the dependencies that are contained within a directory. Additionally, the build time analysis of the Maven and Gradle allow for a tiny bit of additional `evidence` to be collected (why that matters see [how it works](http://jeremylong.github.io/DependencyCheck/general/internals.html)).
