### ISSUE TITLE
Issue with dependencyCheck not detecting CVE-2023-7104 compared to other scanning tools

### ISSUE THREAD

**Issue by qw1212** [dependency-check/DependencyCheck#6495]
I have encountered an issue where other scanning tools can detect CVE-2023-7104, but dependencyCheck fails to identify it. Why this discrepancy exists? 

DependencyCheck:
![image](https://github.com/jeremylong/DependencyCheck/assets/62467963/7a0cd6e0-4e93-4405-9edf-08932fcd97a3)
another nvd tool:
![企业微信截图_17091917472499](https://github.com/jeremylong/DependencyCheck/assets/62467963/d886b6dd-e86a-4cf3-9e2d-2587293511dc)

The scan command I am using is as follows.
/opt/dependency-check/bin/dependency-check.sh --project "sqlite-jdbc-3.36.0.3.jar" --scan "sqlite-jdbc-3.36.0.3.jar" --junitFailOnCVSS 7    --disableGolangDep --disableGolangMod  --format ALL  --nvdValidForHours 24  --nvdApiKey xxxxx --nvdDatafeed http://nvdmirror.xxxxx.com/nvdcve-{0}.json.gz  --retireJsUrl http://maven.xxxxx.com/repository/tizi/Retirejs/jsrepository.json 

How to address this issue within the dependencyCheck tool? Could anyone lend a hand?

**Comment by aikebah** [comment]
Discrepancy appears to be due to an error in your other tool wrongly attributing the JDBC driver to `cpe:2.3:a:sqlite:sqlite` instead of `cpe:2.3:a:sqlite_jdbc_project:sqlite_jdbc`

https://www.sqlite.org/cves.html documents the CVE to exist in an extension that needs to be explicitly enabled on compile.

The CVE is neither listed by OSSINDEX (which would make it reported by the OSSINDEX analyzer), nor Snyk (another easily googleable vulnerabilities resource, which is not consulted by dependencycheck as their API is only accesible for customers) for your exact version of the library.
