### ISSUE TITLE
With the latest release version 10.0.0, unable to show the vulnerabilities list found in jenkins UI, Any reason? ,  with the previous dependency check version used to show all the vulnerabilities with all severity levels, please check

### ISSUE THREAD

**Issue by pavanbakkani** [dependency-check/DependencyCheck#6786]
[INFO] Writing XML report to:  dependency-check-report.xml
[Pipeline] dependencyCheckPublisher
12:11:08  Collecting Dependency-Check artifact
12:11:08  Parsing filedependency-check-report.xml
20:47:00 ERROR: Unable to parse dependency-check-report.xml

**Comment by henk-van-der-vaart** [comment]
Also on my side I noticed the same error with Dependency Check 10.0.0 (since 10.0.1 was not yet available in Jenkins via dl.bintray.com). After checking for update (still with lot of NVD API retries) that took 40 minutes the analysis was started.
But the "dependencyCheckPublisher" action resulted in:
[DependencyCheck] Unable to parse ....\dependency-check-report.xml
[DependencyCheck] Unsupported Dependency-Check schema version detected

I can supply you the dependency-check-report.xml file if needed. Please let me know.

**Comment by aikebah** [comment]
Last change on the report itself was with version 9.0.3, so unless you upgraded from a lower version of DependencyCheck than that this would be unexpected in my view.

**Comment by aikebah** [comment]
Likely you are hit by https://issues.jenkins.io/browse/JENKINS-73382

**Comment by jeremylong** [comment]
I really think JENKINS-73382 is confused. The reports have not changed (yet) to include CVSSV4 - only the parsing of the NVD data and updating the database. They are likely hitting something related to https://github.com/jeremylong/DependencyCheck/issues/6758

**Comment by Menschomat** [comment]
We are experiencing the problem aswell. Upgraded vom 9.2.0 to 10.0.1. Unfortunatly I am not allowed to provide you with reports.

**Comment by jeremylong** [comment]
Note - the maintainers of ODC do not support or contribute code to the jenkins plugin. Reporting the problem here will do you no good.

**Comment by Jonathanczh** [comment]
I got the same error which i think is due to the parsing of the xml file.

[INFO] Writing XML report to: /home/jenkins/agent/workspace/project/./dependency-check-report.xml
[INFO] Writing HTML report to: /home/jenkins/agent/workspace/project/./dependency-check-report.html
[ERROR] Unable to read yarn audit output.
Post stage
[Pipeline] dependencyCheckPublisher
Collecting Dependency-Check artifact
Parsing file /home/jenkins/agent/workspace/project/dependency-check-report.xml
ERROR: Unable to parse /home/jenkins/agent/workspace/project/dependency-check-report.xml

I'm using version 10.0.1 currently. But version 10.0.0 seems to give the same result

Edit:
I ran dependency check using the following:
        stage('OWASP Dependency-Check Vulnerabilities') {
            steps {
                dependencyCheck(additionalArguments: '--format XML --format HTML', odcInstallation: 'OWASP-Dependency-Check', nvdCredentialsId: 'nvd-api-key')
            }
            post {
                always {
                    dependencyCheckPublisher(pattern: '**/dependency-check-report.xml')
                }
            }
        }

**Comment by aikebah** [comment]
> I really think JENKINS-73382 is confused. 

@jeremylong Some of the comments in the ticket are spot-on, others are confused. 

The plugin is deriving 'report version' from the first digit of `engineVersion` in the report in an attempt to prevent processing of reports generated by the versions 1, 2, 3 and 4 of this project (reports for XSD versions before report XSD 2.0). As the first digit of 10 is identical to that of 1 it now thinks that the report is from an extremely old version of dependencyCheck.

**Comment by linsomniac** [comment]
@aikebah You are absolutely right here, I've been able to get the Jenkins job to parse the report correctly by adding the following after my gradle run which generates the report output: `sed -i 's/Version>10.0.1/Version>9.0.4/' $(find . -name dependency-check-report.xml)`

In other words, changing the Version string in the report from 10.0.1 to 9.0.4 allows the report to be processed.

**Comment by UlrichLohrmann** [comment]
@linsomniac Thanks for this workaround. With this workaround we can continue to generate OWASP Reports in Jenkins until final fix is available from Jenkins Plugin.

**Comment by aikebah** [comment]
I spotted in Jenkins JIRA that the issue is scheduled to be fixed in the next release of the Jenkins plugin (v5.5.1)

**Comment by aikebah** [comment]
@linsomniac @UlrichLohrmann @Menschomat any of you able to provide info whether the Jenkins plugin update is out there and resolves the issue? I see the plugin site mentioning 5.5.1 is out, a tag in github, but not a release in github. So I would appreciate feedback from any of you whether this issue is now ready to be closed or the 5.5.1 plugin is still somehow half-baked and unavailable to Jenkins users.

**Comment by linsomniac** [comment]
@aikebah Yes, we have updated to the new Jenkins plugin and it seems to be working fine.
