### ISSUE TITLE
Higher retry count than configured + multiple retries

### ISSUE THREAD

**Issue by petersone-netic** [dependency-check/DependencyCheck#6787]
**Describe the bug**
I configured:
`<nvdMaxRetryCount>4</nvdMaxRetryCount>`

Running the aggregate goal, I get:
[INFO] --- dependency-check:10.0.1:aggregate (default) @ commons ---
[INFO] Checking for updates
[INFO] NVD API has 5.218 records in this update
[WARNING] NVD API request failures are occurring; retrying request for the 2 time
[WARNING] NVD API request failures are occurring; retrying request for the 2 time
[WARNING] NVD API request failures are occurring; retrying request for the 3 time
[WARNING] NVD API request failures are occurring; retrying request for the 3 time
[WARNING] NVD API request failures are occurring; retrying request for the 4 time
[WARNING] NVD API request failures are occurring; retrying request for the 4 time
[WARNING] NVD API request failures are occurring; retrying request for the 5 time
[WARNING] NVD API request failures are occurring; retrying request for the 5 time
[WARNING] NVD API request failures are occurring; retrying request for the 2 time
[WARNING] NVD API request failures are occurring; retrying request for the 3 time
[WARNING] NVD API request failures are occurring; retrying request for the 4 time
[WARNING] NVD API request failures are occurring; retrying request for the 5 time
[ERROR] Error updating the NVD Data

**Version of dependency-check used**
The problem occurs using version 10.0.1 of the maven plugin.

**Expected behavior**
1: "retrying request for the 5 time" - why this, when I have set nvdMaxRetryCount=4 ?
2: "
[WARNING] NVD API request failures are occurring; retrying request for the 2 time
[WARNING] NVD API request failures are occurring; retrying request for the 2 time
"
Why there double retries?
3: "
[WARNING] NVD API request failures are occurring; retrying request for the 5 time
[WARNING] NVD API request failures are occurring; retrying request for the 2 time
"
Why these "restarts" in the counter?

**Additional context**
Newer seen any problems - only since "NVD Returned Status Code: 503"

**Comment by aikebah** [comment]
It's reporting the total number of attempts, which is one higher than the re-try count (the initial try is included).

Whether or not the current behaviour combined with requiring at least 1 retry (maxRetry is not allowed to be set to `0`) is something that might be open to debate, but the flag operates in a way consistent with the naming.

The double retries are because the NVD-API is queried using multiple individual paged requests (2k records at a time IIRC). Some directly succeed, others may reach up to maxRetries retries, also depending on the overall load on the NVD API infrastructure. Each individual request is retried maxRetries attempts before failing it. The first failing request for maxRetries+1 attempts will break the process fatally.
