### ISSUE TITLE
Newtonsoft.JSON not showing CVE-2024-21907 in the vulnerability report 

### ISSUE THREAD

**Issue by bsuchorowskiandea** [dependency-check/DependencyCheck#6789]
**Describe the bug**
We don't see any vulnerability in the report for Newtonsoft.JSON 12.0.3

**Version of dependency-check used**
Dependency-Check Core version 10.0.1

**Log file**

dotnet build results:
Warning NU1903: Package 'Newtonsoft.Json' 12.0.3 has a known high severity vulnerability,
https://github.com/advisories/GHSA-5crp-9r3c-p9vr

OWASP:
no results

**Expected behavior**
Vulnerability should be visible. To my best knowledge it is published in NVD: https://nvd.nist.gov/vuln/detail/CVE-2024-21907

**Comment by chadlwilson** [comment]
It might help if you share from the ODC report whether the library is being detected as as which CPE?

In the HTML report you can click "Showing Vulnerable Dependencies (click to show all)" to toggle and then look for the library. If the dependency isn't detected it's a different problem to if it's detected, but shows no vulnerabilities.

**Comment by bsuchorowskiandea** [comment]
![image](https://github.com/jeremylong/DependencyCheck/assets/170729334/8c02973d-2e37-4d7d-82ea-04eac1894ab5)

It is detected and it is on the list but with no vulnerabilities at all

![image](https://github.com/jeremylong/DependencyCheck/assets/170729334/44638dc6-c406-489a-a8fd-2662470def46)

**Comment by chadlwilson** [comment]
It looks like it hasn’t been mapped to a CPE (common product enumeration) which is why no vulnerabilities appear. ODC doesn’t know the product the NuGet package refers to.

I suspect this is because of NvD data problems. If you look at https://nvd.nist.gov/vuln/detail/CVE-2024-21907 and click “show matching CPEs” there are none.

You probably need to contact the NVD to fix this via the email they link: [cpe_dictionary@nist.gov](mailto:cpe_dictionary@nist.gov)

**Comment by jeremylong** [comment]
This is a false negative. To fix this you would need a hint file adding ".net" to the evidence for newtonsoft. This is one of the problems with the way ODC detects CPEs/CVEs.
