### ISSUE TITLE
stanford-corenlp-4.5.1.jar false positive

### ISSUE THREAD

**Issue by parimala-kathir** [dependency-check/DependencyCheck#6946]
stanford-corenlp-4.5.1.jar is vulnerable. In description, it is mentioned that only v3.9.2 and below have the vulnerability

**Comment by aikebah** [comment]
ODC does not parse descriptions, but reports what various vulnerability sources publish about affected ranges.

You give to little detail on what is found to be able to tell whether it's a deviation by one of the vulnerability sources from the published CVE or whether maybe the CVE text is incomplete.

**Comment by aikebah** [comment]
I presume you mean CVE-2023-39020, in which case it is OSSINDEX that marks exactly that version of the library as also affected.
That is either an error on their side (which you would have to take up with them), or a finding of their research that the patch made for the issue is insufficient and therefor the CVE still applies to 4.5.1.

**Comment by aikebah** [comment]
Going by their repository the first version with a definite patch is likely 4.5.5, where the feature that was at the root of the vulnerability was removed.

**Comment by aikebah** [comment]
https://github.com/stanfordnlp/CoreNLP/commit/897231bed0efb24574c80c875c0b5f2225c145bc

**Comment by aikebah** [comment]
which matches with their release notes

https://github.com/stanfordnlp/CoreNLP/releases/tag/v4.5.5

**Comment by aikebah** [comment]
NVD data is now also properly reflecting the affected range up to (excluding) 4.5.5
