### ISSUE TITLE
[FP]: keycloak-pax-web-undertow-18.0.2 mapped to CVE-2024-7341

### ISSUE THREAD

**Issue by rajeeviiit2108** [dependency-check/DependencyCheck#7012]
### Package URl

pkg:maven/org.keycloak/keycloak-pax-web-undertow@18.0.2

### CPE

cpe:2.3:a:keycloak:keycloak:18.0.2:*:*:*:*:*:*:*

### CVE

CVE-2024-7341

### ODC Integration

{"label"=>"Maven Plugin"}

### ODC Version

{"label"=>"Maven Plugin"}

### Description

While scanning against our Karaf 4.4.4 image, Dependency Checker reports incorrectly matching mvn:org.keycloak/keycloak-osgi-features/18.0.2 to redhat keycloak that is affected by the mentioned CVE

**Comment by aikebah** [comment]
keycloak-pax-web-undertow is part of the multi-library product keycloak, and was EOLed in version 19.0.0

https://www.keycloak.org/docs/23.0.7/release_notes/#fuse-6-and-7-openid-connect

DependencyCheck project takes all libraries under one CPE as a whole and makes by design no attempt to map the CVEs registered against those in the NVD to the subcomponent that it applies to.
