### ISSUE TITLE
False Positive for netty-*-4.0.37.Final

### ISSUE THREAD

**Issue by stliss** [dependency-check/DependencyCheck#706]
CVE-2016-4970 is reported for multiple netty-*-4.0.37.Final.jars, CPE is cpe:/a:netty_project:netty:4.0.37.

The CVE says that "Netty 4.0.x **before** 4.0.37.Final" is affected, so 4.0.37.Final looks like a False Positive.

Example jar (netty-codec-4.0.37.Final.jar) can be found here:
http://search.maven.org/#search|ga|1|1%3A%22fbc8d248adc1ef17847817b67b8050b14e95b7e2%22

Affected are multiple netty-*-4.0.37.Final.jars:

- netty-buffer-4.0.37.Final.jar
- netty-codec-4.0.37.Final.jar
- netty-common-4.0.37.Final.jar
- netty-handler-4.0.37.Final.jar
- netty-transport-4.0.37.Final.jar

Example for netty-codec-4.0.37.Final.jar (reported as cpe:/a:netty_project:netty:4.0.37)
```xml
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-codec</artifactId>
    <version>4.0.37.Final</version>
</dependency>
```

**Comment by jeremylong** [comment]
Unfortunately, this false positive is due to inaccurate data within the NVD. See https://nvd.nist.gov/vuln/detail/CVE-2016-4970, if you look at the affected software it clearly lists cpe:2.3:a:netty_project:netty:4.0.37:*:*:*:*:*:*:* as a vulnerable instance.  I have emailed the folks at the NVD, but there is little I can do to resolve this in dependency-check. If the CVE entry gets updated in the NVD then this FP should go away. Alternatively, you can add a suppression rule.

**Comment by jeremylong** [comment]
FYI - the NVD has been updated and 4.0.37 was removed from the vulnerable software list:

https://nvd.nist.gov/vuln/detail/CVE-2016-4970

--Jeremy

**Comment by stliss** [comment]
Thanks,
Stefan
