### ISSUE TITLE
Error updating the NVD Data - Caused by: java.lang.IllegalArgumentException: PROOF-OF-CONCEPT

### ISSUE THREAD

**Issue by robtimus** [dependency-check/DependencyCheck#7067]
**Describe the bug**

After downloading version 11 I tried to update the database. That failed as documented, so I deleted the `data` folder. I tried to run an update-only. After 94% I got the following error (irrelevant stack trace elements omitted):
```
[ERROR] Error updating the NVD Data
org.owasp.dependencycheck.data.update.exception.UpdateException: Error updating the NVD Data
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.processApi(NvdApiDataSource.java:397)
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.update(NvdApiDataSource.java:117)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:906)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:878)
        at org.owasp.dependencycheck.App.runUpdateOnly(App.java:431)
        at org.owasp.dependencycheck.App.run(App.java:175)
        at org.owasp.dependencycheck.App.main(App.java:90)
Caused by: io.github.jeremylong.openvulnerability.client.nvd.NvdApiException: Failed to parse NVD data
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient._next(NvdCveClient.java:363)
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:331)
        at org.owasp.dependencycheck.data.update.NvdApiDataSource.processApi(NvdApiDataSource.java:353)
        ... 6 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.github.jeremylong.openvulnerability.client.nvd.CvssV4Data$ExploitMaturityType`, problem: PROOF-OF-CONCEPT
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 802007] (through reference chain: io.github.jeremylong.openvulnerability.client.nvd.CveApiJson20["vulnerabilities"]->java.util.ArrayList[357]->io.github.jeremylong.openvulnerability.client.nvd.DefCveItem["cve"]->io.github.jeremylong.openvulnerability.client.nvd.CveItem["metrics"]->io.github.jeremylong.openvulnerability.client.nvd.Metrics["cvssMetricV40"]->java.util.ArrayList[0]->io.github.jeremylong.openvulnerability.client.nvd.CvssV4["cvssData"]->io.github.jeremylong.openvulnerability.client.nvd.CvssV4Data["exploitMaturity"])
        (omitted: Jackson)
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient._next(NvdCveClient.java:358)
        ... 8 common frames omitted
Caused by: java.lang.IllegalArgumentException: PROOF-OF-CONCEPT
        at io.github.jeremylong.openvulnerability.client.nvd.CvssV4Data$ExploitMaturityType.fromValue(CvssV4Data.java:974)
        at jdk.internal.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:118)
        at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:194)
        ... 37 common frames omitted
```

**Version of dependency-check used**
The problem occurs using version 11.0.0 of the CLI

**To Reproduce**
1. Start with a clean installation
2. Run `<install-dir>/bin/dependency-check.sh --updateonly --nvdApiKey <api-key>`
3. Wait for the error to appear

**Expected behavior**
No errors and a successfully updated database.

**Additional context**
https://github.com/jeremylong/Open-Vulnerability-Project/blob/2f35ed14c6028c93d36471188f32e92f4d0d7433/open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV4Data.java#L942 shows that the supported constants for `CvssV4Data.ExploitMaturityType` are `UNREPORTED`, `PROOF_OF_CONCEPT`, `ATTACKED` and `NOT_DEFINED`. Apparently one of the sources contains `PROOF-OF-CONCEPT` instead of `PROOF_OF_CONCEPT`.

**Comment by THausherr** [comment]
Same here with maven (using 10.0.4):

--stacktrace removed--

**Comment by bmeier-pros** [comment]
We can confirm that this affects both 10.0.4 and 11.0.0

**Comment by AeroSecGeek** [comment]
10.0.0.3 is affected as well...

**Comment by robtimus** [comment]
So it seems that NVD has included an unexpected value in one of the latter updates.

**Comment by omolina0984** [comment]
I  have the same problem  using version 11.0.0 


--stacktrace removed--

**Comment by robtimus** [comment]
I've done some investigation. If I call https://services.nvd.nist.gov/rest/json/cves/2.0/?lastModStartDate=2024-10-21T16:00:00.000%2B01:00&lastModEndDate=2024-10-21T21:00:00.000%2B01:00 there are three entries with `PROOF-OF-CONCEPT`:
* [CVE-2024-49366](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49366)
* [CVE-2024-49367](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49367)
* [CVE-2024-49368](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49368)

I've found the spec that defines the allowed values: https://csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v4.0.json. This clearly lists the following allowed values:
* "UNREPORTED"
* "PROOF_OF_CONCEPT"
* "ATTACKED"
* "NOT_DEFINED"

In other words - the NVD API is returning data that doesn't match their own spec.

**Comment by ric777** [comment]
Same in 10.0.2:

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:10.0.2:check (default) on project tahi-contract-migration: Fatal exception(s) analyzing tahi-contract-migration: One or more exceptions occurred during analysis:
[ERROR] 	UpdateException: Error updating the NVD Data
[ERROR] 		caused by NvdApiException: Failed to parse NVD data
[ERROR] 		caused by ValueInstantiationException: Cannot construct instance of `io.github.jeremylong.openvulnerability.client.nvd.CvssV4Data$ExploitMaturityType`, problem: PROOF-OF-CONCEPT
[ERROR]  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 803924] (through reference chain: io.github.jeremylong.openvulnerability.client.nvd.CveApiJson20["vulnerabilities"]->java.util.ArrayList[357]->io.github.jeremylong.openvulnerability.client.nvd.DefCveItem["cve"]->io.github.jeremylong.openvulnerability.client.nvd.CveItem["metrics"]->io.github.jeremylong.openvulnerability.client.nvd.Metrics["cvssMetricV40"]->java.util.ArrayList[0]->io.github.jeremylong.openvulnerability.client.nvd.CvssV4["cvssData"]->io.github.jeremylong.openvulnerability.client.nvd.CvssV4Data["exploitMaturity"])
[ERROR] 		caused by IllegalArgumentException: PROOF-OF-CONCEPT
[ERROR] 	NoDataException: No documents exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by ElvenSpellmaker** [comment]
> I've done some investigation. If I call [services.nvd.nist.gov/rest/json/cves/2.0?lastModStartDate=2024-10-21T16:00:00.000%2B01:00&lastModEndDate=2024-10-21T21:00:00.000%2B01:00](https://services.nvd.nist.gov/rest/json/cves/2.0/?lastModStartDate=2024-10-21T16:00:00.000%2B01:00&lastModEndDate=2024-10-21T21:00:00.000%2B01:00) there are three entries with `PROOF-OF-CONCEPT`:
> 
>     * [CVE-2024-49366](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49366)
> 
>     * [CVE-2024-49367](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49367)
> 
>     * [CVE-2024-49368](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49368)
> 
> 
> I've found the spec that defines the allowed values: [csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v4.0.json](https://csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v4.0.json). This clearly lists the following allowed values:
> 
>     * "UNREPORTED"
> 
>     * "PROOF_OF_CONCEPT"
> 
>     * "ATTACKED"
> 
>     * "NOT_DEFINED"
> 
> 
> In other words - the NVD API is returning data that doesn't match their own spec.

For those are posting stack traces and their versions, it'll affect ***ALL*** versions that use the new API as they're returning `PROOF-OF-CONCEPT` when their spec says `PROOF_OF_CONCEPT`, notice `-` vs `_`.

**Comment by chadlwilson** [comment]
@jeremylong do you have one of your magical NVD contacts to check in with to see whether this is an accident/but or a spec/docs problem?

Might also be good to pin this issue temporarily for visibility.

**Comment by diegobayshanntech** [comment]
Depending on how fast the NVD can fix this compared to the fact that most users of DependencyCheck would be blocked by this: could one consider allowing `PROOF-OF-CONCEPT` as an accepted value when deserialising ?

**Comment by chadlwilson** [comment]
Anything's possible I suppose, but it's complicated by ODC 11 being just released with breaking changes. Probably don't want to force everyone to update again like happened with 10.x (my personal view)

**Comment by rogerhendriks** [comment]
I entered the NVD contact form with a link to this. Hopes that helps...

**Comment by vschurink** [comment]
it's always fun when the people putting out normalized lists are not following their own normalizations.

Since this is not the first time this has happened, is it a good idea to allow dependency check to skip these specific records when schema validation failures are detected when importing NVD records with an (optional) setting ?

Maybe also introduce something like a fail-safe, a skip counter of a max number of failed validations (100/1000?) to offset trying to load thousands of bad records when you do skip records that are not valid perhaps?

This would allow dependency-check to keep loading records and skip the 'failed' ones and maybe try to reload them in at a future date when the records are fixed? 

Because it seems silly to not load 270k-ish records because there are 3 bad apples in the bunch. Especially when it's not the first, second or LAST time this will probably happen.

**Comment by ugurberkecan** [comment]
Why are we encountering this issue now without updating the dependency ?

**Comment by rob-spoor** [comment]
> Why are we encountering this issue now without updating the dependency ?

Because there is an error in the source, not the dependency checker.

**Comment by ElvenSpellmaker** [comment]
> Why are we encountering this issue now without updating the dependency ?

Because the external database from NIST has some bad records which break their own schema, this tool downloads the database and rightly compares the types to the schema and finds some records not in the schema.

See: https://github.com/jeremylong/DependencyCheck/issues/7067#issuecomment-2427891379

However having some way to optionally ignore the error records would be good for situations like this as @vschurink suggests.

**Comment by chadlwilson** [comment]
> Because it seems silly to not load 270k-ish records because there are 3 bad apples in the bunch. > Especially when it's not the first, second or LAST time this will probably happen.

@vschurink While that's a valid perspective, the problem to resolve is that if you ignore the records you now have a local DB/cache which is out of sync with NVD and no obvious way to know this has happened, and that you may have false negatives/positives etc. This becomes indeterministic and thus difficult for people to reason about/support, e.g "why does this host say this CVE applies but this other host does not?" and adds further possibility to add a burden to maintainers.

There was a similar discussion about this back when CVSSv4 was added as the thought process was similar "should the 1) tool break when it doesn't understand CVSSv4 or 2) just ignore the CVSSv4 fields?". A decision to go with #1 forced a need for everyone to upgrade, and then bugs with the CVSSv4 support to be fixed over the subsequent days/weeks with the community following along trying to get their setups working again.

Personally I am in the latter camp, combined with a suggestion to allow a "ratchet" within ODC which will force clients to re-retrieve records from NVD after a given YYYY-MM-DD (e.g when new support is added to ODC) to clean up potentially incomplete caches when/if a fix is made within ODC or NVD. But that also requires work, and cache invalidation is notoriously difficult :-)

**Comment by vschurink** [comment]
@chadlwilson I get what you're saying.

I see a few ways to the out of date cache/DB issue. 

One solution is by keeping a record of failed validations, however, if the record is malformed due to misconfigured source data, you might not even get the unique reference to that record to store to retry if you were going to implement some kind of recordkeeping.

An easier alternative to this could also be something like a reconciliation run, where you just force the reload of all records after say a x definable period, say a month or 2 by default, which would try to (force) refresh all records in the local DB. 

This has a few benefits that I can think of:
* namely that it's hands-off.
* it's a process that can auto-recover by itself. And I do love me systems that can self-heal. 

We use that process in our own data streaming services extensively and I can report it works quite well.

Ultimately though, since we have no 'direct' way of influencing / reporting issues with the source data (yay for bureaucracy), it depends on @jeremylong and if that is something he is willing to entertain in his software.

I guess the other alternative is to keep it as is, and for every NVD error in source data we get issues created and red monitoring alerts that data failed to load (at least we do:)). At least it lets us test our monitoring solutions for DependencyCheck every once in a while, so there is that I guess :)

**Comment by jeremylong** [comment]
I've emailed the nvd and a couple of contacts I've discussed the API with already.

**Comment by nicon89** [comment]
10.0.3 affected as well.

**Comment by giacgbj** [comment]
> 10.0.3 affected as well.

See https://github.com/jeremylong/DependencyCheck/issues/7067#issuecomment-2427891379.

**Comment by jeremylong** [comment]
@vschurink - glad the "test" of your monitoring system worked.

I do have https://dependency-check.github.io/DependencyCheck_Builder/nvd_cache/ set to update nightly. What is interesting, the specific CVEs are not in this cache and I'm not seeing errors in the job logs. It looks like it may be silently swallowing the errors. I'll have to re-create the cache entirely once the problem is resolved.

**Comment by chadlwilson** [comment]
@jeremylong the first scheduled run just started since the 'bad' CVEs were added upstream, and does have the same errors.

https://github.com/dependency-check/DependencyCheck_Builder/actions/runs/11459025936/job/31882656809

**Comment by jeremylong** [comment]
I just received the email indicating the failure. Well, that data feed can be used for now I guess. It will just be missing new entries until the data issue is resolved.

**Comment by rob-spoor** [comment]
A quick and dirty solution is to add some extra code at https://github.com/jeremylong/Open-Vulnerability-Project/blob/2f35ed14c6028c93d36471188f32e92f4d0d7433/open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV4Data.java#L972 to replace `-` with `_` if the first lookup fails. That would be a workaround for a problem that shouldn't be there, but it would allow a quick fix in case NVD can't or won't solve the issue soon.
```java
ExploitMaturityType constant = CONSTANTS.get(value);
if (constant != null) {
    return constant;
}
// Workaround for PROOF-OF-CONCEPT instead of PROOF_OF_CONCEPT
constant = CONSTANTS.get(value.replace('-', '_'));
if (constant != null) {
    return constant;
}
throw new IllegalArgumentException(value);
```

**Comment by ElvenSpellmaker** [comment]
> > Because it seems silly to not load 270k-ish records because there are 3 bad apples in the bunch. > Especially when it's not the first, second or LAST time this will probably happen.
> 
> @vschurink While that's a valid perspective, the problem to resolve is that if you ignore the records you now have a local DB/cache which is out of sync with NVD and no obvious way to know this has happened, and that you may have false negatives/positives etc. This becomes indeterministic and thus difficult for people to reason about/support, e.g "why does this host say this CVE applies but this other host does not?" and adds further possibility to add a burden to maintainers.
> 
> There was a similar discussion about this back when CVSSv4 was added as the thought process was similar "should the 1) tool break when it doesn't understand CVSSv4 or 2) just ignore the CVSSv4 fields?". A decision to go with #1 forced a need for everyone to upgrade, and then bugs with the CVSSv4 support to be fixed over the subsequent days/weeks with the community following along trying to get their setups working again.
> 
> Personally I am in the latter camp, combined with a suggestion to allow a "ratchet" within ODC which will force clients to re-retrieve records from NVD after a given YYYY-MM-DD (e.g when new support is added to ODC) to clean up potentially incomplete caches when/if a fix is made within ODC or NVD. But that also requires work, and cache invalidation is notoriously difficult :-)

I understand you don't want to force people to upgrade, but currently all versions of this plugin that use the newer API are broken and we have quite a lot of pipelines now broken as a result of this which is blocking work unless we go around and disable each of them.

**Comment by nusmanov** [comment]
> I've done some investigation. If I call https://services.nvd.nist.gov/rest/json/cves/2.0/?lastModStartDate=2024-10-21T16:00:00.000%2B01:00&lastModEndDate=2024-10-21T21:00:00.000%2B01:00 there are three entries with `PROOF-OF-CONCEPT`:
> 
> * [CVE-2024-49366](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49366)
> * [CVE-2024-49367](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49367)
> * [CVE-2024-49368](https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-49368)


Is it possible to configure the plugin to ignore those broken CVEs? (At least our pipelines could work.

**Comment by ryandel13** [comment]
> A quick and dirty solution is to add some extra code at https://github.com/jeremylong/Open-Vulnerability-Project/blob/2f35ed14c6028c93d36471188f32e92f4d0d7433/open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV4Data.java#L972 to replace `-` with `_` if the first lookup fails. That would be a workaround for a problem that shouldn't be there, but it would allow a quick fix in case NVD can't or won't solve the issue soon.
> 
> ```java
> ExploitMaturityType constant = CONSTANTS.get(value);
> if (constant != null) {
>     return constant;
> }
> // Workaround for PROOF-OF-CONCEPT instead of PROOF_OF_CONCEPT
> constant = CONSTANTS.get(value.replace('-', '_'));
> if (constant != null) {
>     return constant;
> }
> throw new IllegalArgumentException(value);
> ```

I would suggest to replace 'PROOF-OF-CONCEPT' with 'PROOF_OF_CONCEPT' in order to not break future Constants with a legal '-' ....

**Comment by xtermi2** [comment]
> I understand you don't want to force people to upgrade, but currently all versions of this plugin that use the newer API are broken and we have quite a lot of pipelines now broken as a result of this which is blocking work unless we go around and disable each of them.

@ElvenSpellmaker When your pipelines depend on this that much, you should consider to have a replicated nvd DB and run your pipeliens with `autoUpdate = false` and create a scheduled pipeline which e.g. once a day updates your nvd database with `autoUpdate = true` and gradle task `dependencyCheckUpdate` (or equivalent if gradle is not used)

https://jeremylong.github.io/DependencyCheck/data/database.html

Then your pipelines can still run successfully (with an outdated nvd DB) and only your "update job" fails

**Comment by jeremylong** [comment]
Alternatively - host a copy/cache of the NVD data. Options are listed here: https://jeremylong.github.io/DependencyCheck/data/index.html (items 2-4 under The NVD Database).

**Comment by rob-spoor** [comment]
> I would suggest to replace 'PROOF-OF-CONCEPT' with 'PROOF_OF_CONCEPT' in order to not break future Constants with a legal '-' ....

That's why I kept the initial mapping. A constant with a legal `-` will yield a constant as part of the first map lookup. Only if that fails will the `-` to `_` mapping be attempted. If that fails again the result is what we have now - a failure.

**Comment by somera** [comment]
> Is it possible to configure the plugin to ignore those broken CVEs? (At least our pipelines could work.

This will be the best solution for the feature. Who knows when NVD will produce new problem.

**Comment by sellersj** [comment]
Works for me again.

**Comment by vschurink** [comment]
our monitoring solution also just turned green again for the dependency check load.
I'm rerunning a test pipeline to visually confirm, but it seems NVD API is very busy, I wonder why... 😄

**Comment by aikebah** [comment]
Spotted a passing update on our systems as well, looks like the issue is resolved in NVD API data now

**Comment by seancorfield** [comment]
Confirming a full download just succeeded for me so NIST seems to have fixed their data.

Thank you for DependencyCheck!

**Comment by foxracle** [comment]
It has already been fixed! Thank you all guys! @jeremylong

**Comment by DominikAmon** [comment]
Confirmed, it is working again - I'd like to add a feature request @jeremylong : 
There where three out of one hundred thousand entries in the project were corrupt. Currently, the process fails entirely due to these corrupt entries.

I'd like to propose a feature that would allow the process to continue even if corrupt entries are encountered. Instead of failing, the process could skip these entries with a warning message. Alternatively, there could be an option to configure this behavior.

This would enable projects to be scanned without being halted by a small number of corrupt entries.

Thank you for your time and consideration.

**Comment by mainching** [comment]
We're still getting the following when trying to use Dependency Check in our azure pipelines:

> `[ERROR] Incompatible or corrupt database found. To resolve this issue please remove the existing database by running purge
`

Anyone else experiencing similar?

**Comment by aikebah** [comment]
@mainching if you are using a datafolder shared by different versions of dependency-check you may run into it if a job running ODC 10.x has created the DB. Version 11.0 uses a newer H2 library that has updated the binary format of the database files. (the maven and gradle plugins have taken this into account and are by default using a new persistent folder in v11 (when not overridden by the advanced configuration properties for it); I don't know how the azure pipelines have organized their setup, but I can imagine it's configured in a way that makes multiple versions of the tool use the same shared datafolder)

**Comment by rogerhendriks** [comment]
> We're still getting the following when trying to use Dependency Check in our azure pipelines:
> 
> > `[ERROR] Incompatible or corrupt database found. To resolve this issue please remove the existing database by running purge `
> 
> Anyone else experiencing similar?

We used the dependency check .bat file and then run it from the pipeline on our local server. So luckily only 1 purge needed....
This is the command: dependency-check.bat --purge.

**Comment by rogerhendriks** [comment]
Just FYI that you actually get feedback when filling in the form. 
This is not a black hole but real support, kudo's for the NIST!

--
Good afternoon,

We are aware of inconsistent availability of the API services caused by heavy load and are monitoring the situation. As stated at https://www.nist.gov/itl/nvd **we have resolved the underlying cause**. As organizations are able to successfully download the dataset, services will continue returning to normal.

V/r
National Vulnerability Database Team
National Institute of Standards and Technology (NIST) [nvd@nist.gov](mailto:nvd@nist.gov)

**Comment by rogerhendriks** [comment]
> Confirmed, it is working again - I'd like to add a feature request @jeremylong : There where three out of one hundred thousand entries in the project were corrupt. Currently, the process fails entirely due to these corrupt entries.
> 
> I'd like to propose a feature that would allow the process to continue even if corrupt entries are encountered. Instead of failing, the process could skip these entries with a warning message. Alternatively, there could be an option to configure this behavior.
> 
> This would enable projects to be scanned without being halted by a small number of corrupt entries.
> 
> Thank you for your time and consideration.
Maybe make a seperate ticket for this as this is actually a very good idea, so we dont need purges and everything gets updated automatically when nvd entries are fixed.

**Comment by jeremylong** [comment]
@rogerhendriks the reason we won't be implementing this was already answered; see https://github.com/jeremylong/DependencyCheck/issues/7067#issuecomment-2429078791

**Comment by rogerhendriks** [comment]
> @rogerhendriks the reason we won't be implementing this was already answered; see [#7067 (comment)](https://github.com/jeremylong/DependencyCheck/issues/7067#issuecomment-2429078791)

Clear, thanks ;)

**Comment by DominikAmon** [comment]
> > Confirmed, it is working again - I'd like to add a feature request @jeremylong : There where three out of one hundred thousand entries in the project were corrupt. Currently, the process fails entirely due to these corrupt entries.
> > I'd like to propose a feature that would allow the process to continue even if corrupt entries are encountered. Instead of failing, the process could skip these entries with a warning message. Alternatively, there could be an option to configure this behavior.
> > This would enable projects to be scanned without being halted by a small number of corrupt entries.
> > Thank you for your time and consideration.
> > Maybe make a seperate ticket for this as this is actually a very good idea, so we dont need purges and everything gets updated automatically when nvd entries are fixed.

I created a new feature request: https://github.com/jeremylong/DependencyCheck/issues/7097
