### ISSUE TITLE
Gradle Plugin for owasp-dependency-check version 11.0.0 not available at maven central

### ISSUE THREAD

**Issue by mjbs82** [dependency-check/DependencyCheck#7075]
Hello, gradle plugin for version 11.0.0 still not available at maven central. Any plan to upload it? https://repo.maven.apache.org/maven2/org/owasp/dependency-check-gradle/11.0.0/dependency-check-gradle-11.0.0.pom

https://github.com/jeremylong/DependencyCheck/issues/6973

**Comment by mjbs82** [comment]
Just read: https://plugins.gradle.org/plugin/org.owasp.dependencycheck

But noticed that the plugin version 11.0.0 is not currently avalaible neither at gradle:

- https://github.com/dependency-check/dependency-check-gradle/tags

- https://plugins.gradle.org/plugin/org.owasp.dependencycheck

**Comment by jeremylong** [comment]
The gradle plugin was just released - there was a bug I was trying to figure out and lost time yesterday due to the NVD issue.

11.0.0 has been published to the plugin portal. Note that with 11.0.0 the dependency-check-gradle plugin is not being released to Maven Central - the plugin portal should be sufficient.
