### ISSUE TITLE
When building a report using the maven pluging, make the maven coordinate reference displayed under section "Project: [some tile]" optional

### ISSUE THREAD

**Issue by tblaszlo** [dependency-check/DependencyCheck#7135]
The request is related to the title section of the report.

I wish to have a result similar to the one like in the sample (https://jeremylong.github.io/DependencyCheck/general/SampleReport.html) while using the maven plugin.
![image](https://github.com/user-attachments/assets/752d9705-0130-485b-b21c-a54cd85cd6b2)

A configuration option for the plugin would be nice, to allow this line to be disabled.
In the HTML template the condition is as follows

#if ($groupID && $artifactID && $applicationVersion)##<h4>$enc.html($groupID):$enc.html($artifactID):$enc.html($applicationVersion)</h4>## 

Thus there is no way to work around the problem since all values defined in the condition have to be defined in a project.

![image](https://github.com/user-attachments/assets/fa936140-ac7e-4cc4-bb64-e5bfcb69c713)

**Comment by aikebah** [comment]
Is see no good reason to make this configurable. The maven plugin is intended to be embedded in a standard maven project so it is logical and natural to include its coordinates in the report when created by the maven plugin.

But if you want to have such a report for your specific environment because you fabricate some dummy maven project to scan a series of libraries you can always make a copy and adjust it to any layout you want.

You can use your own velocity template as a report format by using its location (on the filesystem or on the classpath) instead of the various predefined report format strings.

**Comment by jeremylong** [comment]
Completely agree with @aikebah - if this is a requirement for your use you can create your own template to achieve this goal. As such, I'm closing the enhancement request.
