### ISSUE TITLE
Does scanning support source code or does it need to be packaged

### ISSUE THREAD

**Issue by topsekadmin** [dependency-check/DependencyCheck#7158]
Does scanning support source code or does it need to be packaged

**Comment by jeremylong** [comment]
That is a complicated question - depending on what you mean and what tech stack we are talking about. In general - you want to scan the project that contains the dependencies. For dotnet, you will likely get better results if you actually run `dotnet publish` prior to analysis because this forces the download of the dependencies from nuget. In other cases, ODC primarily utilizes package management files (requirements.txt, etc.). For maven or gradle - you can use the plugins to hook into the build system itself.

However, to find CVEs for Apache HTTP Client - you would not scan the source of Apache HTTP Client. You would scan the project that uses Apache HTTP Client.
