### ISSUE TITLE
Use JDK set in tools section of the pipeline instead of Jenkins JVM

### ISSUE THREAD

**Issue by joelroyer** [dependency-check/DependencyCheck#7160]
My Jenkins instance is powered by a JDK8.
The Jenkins plugin version 11.0.0 needs a jdk 11.
I have a JDK11 installed then I added to my pipeline a tools section like this
```groovy
tools {
    jdk 'JDK11'
}
```
But DependencyCheck jenkins plugin still use JDK8.

If JDK is set in tools section, DependencyCheck plugin should use it.

Because I can't change easily Jenkins JVM, the only alternative i've found is to use DependencyCheck plugin in version 10.0.4.

**Comment by aikebah** [comment]
This project does not maintain the Jenkins plugin. See https://plugins.jenkins.io/dependency-check-jenkins-plugin/

It would be that plugins task to ensure that the CLI is not started with 'system default Java', but pipeline tool Java.

**Comment by jeremylong** [comment]
please open an issue with the appropriate project as indicated by @aikebah. I'm closing this as it is not related to the core project.

**Comment by aikebah** [comment]
On a side-note: If your statement is correct about JDK8 powering your Jenkins instance itself you should update your Jenkins instance if you care about vulnerabilities. The only still maintained and fully security-patched Jenkins versions already require to be powered by more recent Java versions than 8, so if your Jenkins is powered by JDK8 it runs an out-of-date version with known security vulnerabilities.

Assuming you run LTS editions [2.346.3](https://www.jenkins.io/changelog-stable/2.346.3/) was the last version to still support running on JDK8. Multiple versions with security fixes were [released since then](https://www.jenkins.io/changelog-stable/)
