### ISSUE TITLE
Vulnerability threw exception java.lang.NullPointerException after dependency check 

### ISSUE THREAD

**Issue by usewebdownload** [dependency-check/DependencyCheck#7191]
Hello 

I was able to do dependency check last week (2024-11-21) but today (2024-11-25) I am unable to do dependency check, I am getting below error message

Execution default of goal org.owasp:dependency-check-maven:8.4.0:check failed: Invocation of method 'getHighestSeverityText' in  class org.owasp.dependencycheck.dependency.Vulnerability threw exception java.lang.NullPointerException at templates/htmlReport.vsl[line 830, column 43]

**Comment by nhumblot** [comment]
Hello, :wave: 

Dependecy Check 8.4.0 was released more than a year ago. Lots of fixes have been applied since then. Please upgrade to the latest version and look if you still face the same issue. If yes, please post the full stack trace.

Thank you :slightly_smiling_face:

**Comment by jeremylong** [comment]
Version 8.4.0 is no longer supported. See the [SECURITY.md](https://github.com/jeremylong/DependencyCheck/blob/main/SECURITY.md) for currently supported versions.

**Comment by kevin-secops-lt** [comment]
Having the same issue:
Programming Language: Scala (build.sbt)
  dependencyCheckSuppressionFiles := Seq(file("dependency-check-suppressions.xml")),
  dependencyCheckFormats := Seq("HTML", "XML", "JSON"),
  
  
  Plugin Version:
  addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "5.1.0")
  
  
  Error Message:
  15:43:31  [0m[[0m[31merror[0m] [0m[0m(app / [31mdependencyCheck[0m) org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getHighestSeverityText' in  class org.owasp.dependencycheck.dependency.Vulnerability threw exception java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "org.owasp.dependencycheck.utils.SeverityUtil.unscoredToSeveritytext(String)" is null at templates/htmlReport.vsl[line 795, column 43][0m
  
  
  This was working just fine about a 2-3 weeks ago.
