### ISSUE TITLE
[FP]: lucene-core for CVE-2024-45772

### ISSUE THREAD

**Issue by edward9944** [dependency-check/DependencyCheck#7195]
### Package URl

pkg:maven/org.apache.lucene/lucene-core@7.7.1

### CPE

cpe:2.3:a:apache:lucene:7.7.1:*:*:*:*:*:*:*

### CVE

CVE-2024-45772

### ODC Integration

None

### ODC Version

11.1.0

### Description

The real issue lies with the lucene-replicator component, but the vulnerability has been incorrectly attributed to lucene-core. Additionally, the lucene-core JAR does not include the org.apache.lucene.replicator module. Therefore, we are identifying this as a false positive.

**Comment by nhumblot** [comment]
Hi :wave: 

Thank you for raising the topic. I am not sure excluding permanently and globally `org.apache.lucene:lucene-core` from the `a:apache:lucene` CPE is the way to go here. `lucene-core` is the main product known as Apache Lucene so CVEs on this application are attached to this CPE it is requested to exclude.

I did not find any CPE other than `lucene` in the NVD database. Maybe the best way to solve this would be to reach the Apche Lucene team to ask them to [declare more fine grained CPEs](https://nvd.nist.gov/products/cpe) so if a CVE purely located into the `lucene-replicator` tool is raised, then it would be attached to this dedicated CPE?

**Comment by aikebah** [comment]
DependencyCheck project takes all libraries under one CPE as a whole and makes by design no attempt to map the CVEs registered against those in the NVD to the subcomponent that it applies to.

So indeed as @nhumblot indicates the only way to resolve this would be to convince NVD to use more finegrained CPEs that allow to distinguish between the composing libraries of a framework like Lucene.

On top of it: your issue is a duplicate of #7049, so closing it as a duplicate

**Comment by aikebah** [comment]
Note: as you can see in the other issue [ASF has indicated](https://github.com/jeremylong/DependencyCheck/issues/7049#issuecomment-2476346430) that they're reaching out to NVD to try and get a separate CPE registered for lucene-replicator.

**Comment by edward9944** [comment]
Thank you so much for your response
