### ISSUE TITLE
JCS dependency tries to load log4j2 backend

### ISSUE THREAD

**Issue by laurentgo** [dependency-check/DependencyCheck#7241]
**Describe the bug**

dependencycheck depends on jcs (caching library) which seems to use some facade for logging. It seems it uses service loader to find log backend implementation, and the log4j2 backend seems to be included, but as the log4j2 classes are not present, JCS output a full stack trace as a debug message before trying the next backend

**Version of dependency-check used**
The problem occurs using version 11.1.1 of the maven plugin

**Log file**

https://gist.github.com/laurentgo/cb678fb2bdfc40efdf57693f90f7a644

**To Reproduce**
1. Run a plugin goal with Maven debug logs enabled

**Expected behavior**

No debug message

**Additional context**

it's a debug message, so the issue is minor but it may be a sign that log configuration need to be checked.

**Comment by Aswinr24** [comment]
Hey Would Like to pick up this issue and fix the bug you are facing here

**Comment by jeremylong** [comment]
We use [jcs3-slf4j](https://github.com/jeremylong/jcs3-slf4j/tree/main?tab=readme-ov-file#jcs3-slf4j). How this works is documented on the JCS side here: https://commons.apache.org/proper/commons-jcs/UpgradingFrom2x.html#Logging_Abstraction

The LogFactories are loaded here: https://github.com/apache/commons-jcs/blob/c01db5a678d24f72840186bc392d4e3778038e8e/commons-jcs3-core/src/main/java/org/apache/commons/jcs3/log/LogManager.java#L48

Somehow I doubt the fix is in the dependency-check project itself.

**Comment by Aswinr24** [comment]
Hey, thanks for the explanation! Apologies for the delay in getting back to you, found the references to log4j in the POM files under maven/src/it/ directory. Would removing the log4j dependency entries from these files ensure that no transitive dependencies are included?

Since SLF4J is explicitly defined in the code to be used via the service loader ```System.setProperty("jcs.logSystem", "slf4j")```
should I remove the log4j dependencies to resolve the issue, or is there something else I should be doing?

Let me know if this is the right approach. Thanks!

**Comment by laurentgo** [comment]
> We use [jcs3-slf4j](https://github.com/jeremylong/jcs3-slf4j/tree/main?tab=readme-ov-file#jcs3-slf4j). How this works is documented on the JCS side here: https://commons.apache.org/proper/commons-jcs/UpgradingFrom2x.html#Logging_Abstraction
> 
> The LogFactories are loaded here: https://github.com/apache/commons-jcs/blob/c01db5a678d24f72840186bc392d4e3778038e8e/commons-jcs3-core/src/main/java/org/apache/commons/jcs3/log/LogManager.java#L48
> 
> Somehow I doubt the fix is in the dependency-check project itself.

Yes, thanks for pointing it out, it looks like the core module has both the [JUL](https://github.com/apache/commons-jcs/blob/c01db5a678d24f72840186bc392d4e3778038e8e/commons-jcs3-core/src/main/java/org/apache/commons/jcs3/log/JulLogFactory.java) and [log4j2](https://github.com/apache/commons-jcs/blob/c01db5a678d24f72840186bc392d4e3778038e8e/commons-jcs3-core/src/main/java/org/apache/commons/jcs3/log/Log4j2Factory.java) LogFactory classes so it doesn't seem possible to avoid the error message without having to remove the classes from the core jar.

Removing log4j2 is already done, and jcs will iterate over the LogFactory providers independently of setting the system property or not, so I don't think there's anything dependencycheck can actually do to address the issue.

Sorry for the noise, closing the ticket
