### ISSUE TITLE
CVE-2015-5211 vulnerability in spring-core.jar

### ISSUE THREAD

**Issue by elrond30** [dependency-check/DependencyCheck#774]
Hello,

The CVE-2015-5211 vulnerability is being detected in the spring-core.jar dependency. But reading information about this vulnerability, it seems to affect spring-webmvc.jar:

https://pivotal.io/security/cve-2015-5211

Can it be a false positive? Have this vulnerability be detected in spring-webmvc.jar dependency?

Thanks and best regards

**Comment by jeremylong** [comment]
Freely available vulnerability information, such as the link you just posted, is generally a little light on being able to differentiate between related components. This is just another example - the vulnerability information specifies Spring Framework, which could cover spring-mvc, spring-core, spring-etc... The best option is to analyze the specific finding/vulnerability and if you feel that this is a false positive for your application you can create a suppression file so that it is no longer showing up in your results.

In this specific case, if you are not using spring-mvc I would suggest create a suppression on the CVE itself. In general, I recommend suppressing by CPE - but as the identifier match was correct (just not as specific as we would like due to available information) suppressing by CPE for this match could create future false negatives (i.e. hide risks that could affect your application).

**Comment by elrond30** [comment]
Hello,
Thanks for your support.
But the problem that I'm watching, is that I have an application with spring-core.jar and spring-webmvc.jar. The vulnerability is detected in the spring-core.jar, and for dependency check, spring-webmvc.jar, haven't any vulnerability. This vulnerability, if it is really a spring-webmvc vulnerability, should not be detected in spring-webmvc.jar?

Thanks in advance

**Comment by jeremylong** [comment]
Thanks for pointing this out. A fix has been put in place and will be included in the next release.
