### ISSUE TITLE
"Error resolving X in project Y" for pom dependencies

### ISSUE THREAD

**Issue by TorstenKruse** [dependency-check/DependencyCheck#837]
When we use something like
`        <dependency>`
`            <groupId>org.springframework</groupId>`
 `           <artifactId>spring-framework-bom</artifactId>`
`            <version>4.3.8.RELEASE</version>`
`            <type>pom</type>`
`            <scope>import</scope>`
`        </dependency>`

in the dependencies (not dependencyManagement) section, the maven plugin logs an error "Error resolving X in project Y" for each such dependency.

It looks like the dependencies in the pom are analyzed anyway, but I'm not sure, if the error has any other consequences for the analysis result.

**Comment by jeremylong** [comment]
Thanks for reporting the issue!  Unfortunately, the original error message was a bit misleading. The actual issue is that no analyzer could be found that can analyzer just a pom.xml by itself - as such you would get the error message about the imported bom. However, if you application then used any of the components from the bom (i.e. they are defined in the dependency section of the pom) then they would be included in the ODC report.  

The error message has been updated; the change will be included in the next release.

**Comment by TorstenKruse** [comment]
Thanks for clarifying this and changing the message. 

But is this still logged as ERROR? If yes, what can we do to avoid this error in our build logs?

**Comment by jeremylong** [comment]
This should now logged as a warning. Are you seeing something different in version 2.1.1?

**Comment by TorstenKruse** [comment]
We did not update already. So I really just asked. :-)
Warning is not perfect, since we cannot avoid ist, but it's much better than having ERRORs in the build log. Thanks again.
