### ISSUE TITLE
Persistent XSS vulnerability in OWASP Dependency-Check Plugin

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#841]
Hi

Jenkins has reported that version 2.0.1 of depcheck contains a  persistent XSS vulnerability

Persistent XSS vulnerability in OWASP Dependency-Check Plugin
SECURITY-577 / CVE-2017-1000109

The "Details" view of the OWASP Dependency-Check Plugin, which is based on Static Analysis Utilities, was vulnerable to a persisted cross-site scripting vulnerability: The plugin showed issue descriptions verbatim without sanitizing or escaping, so that "sample" cross-site scripting exploits as part of an identified issue’s description were actually being executed.

The plugin now escapes HTML in all messages on the Details view

More info here -- https://jenkins.io/security/advisory/2017-08-07/

Are you aware of this?

**Comment by stevespringett** [comment]
All DC versions (1.0.0 - 2.0.1.1) had the defect inherited from analysis-core, but only 2.0.0, 2.0.1 & 2.0.1.1 were affected by it. 2.0.1.2 corrected the issue as does 2.1.0. There was a 17 day window where the vulnerable DC Jenkins plugin was available. The issue was resolved within 6 days of initial report.

It’s CVSS score was 3.5 making it low severity since the payload was controlled by Node Security Platform. Adversaries could not easily create their own payload, so the exploitation was limited to XSS examples in NSP such as alert("xss”);

Although this issue was largely benign from a security perspective, it caused more of a UX issue than anything. The XSS could be accidentally triggered simply by viewing the details page in the Jenkins plugin. 

The issue has been resolved in the DC plugin as well as analysis-core (used by FindBugs, PMD, Checkstyle, etc plugins).
