### ISSUE TITLE
Pipeline report

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#852]
Hi

I am struggling a bit with the reports from the pipeline plugin for dependency check

When you were running a standalone job, you have a html file that contains all the info about the report, which dependencies have been analysed, etc... (dependency-check-report.html)

In a pipeline world, the workspace is not available and that file is not easily accessed from jenkins, although its in the server

Would it be a good improvement to the plugin to have a link to those files from the jenkins interface?

Thanks

**Comment by stevespringett** [comment]
There nothing the Jenkins plugin can change about this fact, however, I think you simply need to archive the artifacts.

Here's a very simple example:
```
node("master") {
    stage("Dependency Check") {
        dependencyCheckAnalyzer datadir: 'dependency-check-data', isFailOnErrorDisabled: true, hintsFile: '', includeCsvReports: false, includeHtmlReports: false, includeJsonReports: false, isAutoupdateDisabled: false, outdir: '', scanpath: '', skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''

        dependencyCheckPublisher canComputeNew: false, defaultEncoding: '', healthy: '', pattern: '', unHealthy: ''
    
        archiveArtifacts allowEmptyArchive: true, artifacts: '**/dependency-check-report.*', onlyIfSuccessful: true
    }
}
```

When this is run, your artifacts (dependency-check-report.html/xml/json/csv) will be accessible from the main job page as well as the individual job number page. Failure to archive the artifacts will make the report files really difficult to find.

**Comment by javixeneize** [comment]
Good point! It solves my problem.

Thanks

**Comment by sharmeelamn2018** [comment]
Hi Steve,

I ran into this error when running Dependency Checker as a pipeline script. I am not using Ruby and would like to disable auditBundle.
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.exception.InitializationException
[DependencyCheck] Cause: bundle-audit initialization failure; this error can be ignored if you are not analyzing Ruby. Otherwise ensure that bundle-audit is installed and the path to bundle audit is correctly specified

I checked your other posts where you've advised to have the auditBundle disabled. But I could not find the alternative groovy command for "analyzer.bundle.audit.enabled=false (or) `-Danalyzer.bundle.audit.enabled=false'". Could you please help me with this. Thanks!
