### ISSUE TITLE
database storage

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#853]
Hi

The plugin downloads a h2 db file. Is there any chance of loading this data to a structure database (postgres or similar) and run the plugin against that database instead of pointing to the h2 file?

Thanks

**Comment by stevespringett** [comment]
Dependency-Check creates a h2 db file, but it can use Oracle, PostgresL, MySQL, or MSSQL. It can also use a shared h2 data directory. Refer to https://github.com/jeremylong/DependencyCheck/tree/master/dependency-check-core/src/main/resources/data

If using a centralized database, you'll need to ensure that:

- updates to the database block all reads from the database otherwise you'll get inconsistent and unreliable results
- every dc execution has autoupdate disabled
- every dc instance is running the same dc version
- plan for additional dba effort to maintain the external database

**Comment by javixeneize** [comment]
Thanks!

Can i download the db script from nvd page directly, or do i need to build a script to load the db from the h2 file?

**Comment by stevespringett** [comment]
Simply initialize the target database with one of the scripts here https://github.com/jeremylong/DependencyCheck/tree/master/dependency-check-core/src/main/resources/data and setup dependency-check to use the external database. Refer the to the CLI or plugin docs on specifics on how to do that.

**Comment by javixeneize** [comment]
Great help Steve. Thanks!
