### ISSUE TITLE
dependency-check-vulnerability.html not generated in the pipeline

### ISSUE THREAD

**Issue by javixeneize** [dependency-check/DependencyCheck#873]
Hi

I have noticed that using the pipeline, the file dependency-check-vulnerability.html is not generated as a report

Any advise on how can i generate it?

thanks

**Comment by stevespringett** [comment]
Its not generated by default, only the XML. Have you specified to have the html report created in your pipeline script?

**Comment by javixeneize** [comment]
Yes, but it generates just the main html report, not the vulnerability.html

**Comment by stevespringett** [comment]
To my knowledge, the core does not support the individual configuration of creating the standalone vulnerability report. This report is only created when Format.ALL is specified. Since the Jenkins plugin no longer supports that, in favor of the configuration of the individual report formats, this appears to be an enhancement request to the core.

I see two possible solutions:

1.  Automatically create the vulnerability report in addition to the standard report when Format.HTML is specified
2. Have a separate format that is specific to this report (i.e. Format.HTML_VULNERABILITY)

The first option would be an enhancement to only the core. The second option would need to be supported in both the core and the Jenkins plugin.

@jeremylong thoughts?

**Comment by stevespringett** [comment]
Actually, I just looked at https://github.com/jeremylong/DependencyCheck/blob/master/dependency-check-core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java and it appears that Format.VULN is an option. So support in the core is already there.

I'll add this support to the next release of the Jenkins plugin

**Comment by javixeneize** [comment]
Beautiful!

Whats the expected date for that release?

**Comment by stevespringett** [comment]
3.0.0 is currently in the works (core and Jenkins). Support for thread safety is a major theme of this release and work is ongoing. Not sure when this will be complete.

**Comment by rudyde** [comment]
Hi guys, I'm using OWASP Dependency-check Version 3.0.2 but I still can't generate dependency-check-vulnerability.html as a report in pipeline. 

Any idea when this will be fixed ?
Thanks a lot

**Comment by jeremylong** [comment]
@rudyde if you are having an issue I would suggest opening up a new ticket rather then posting to a closed issue.

**Comment by rudyde** [comment]
sorry it was a mistake. The parameter "includeVulnReports" was not set to "true". Now it works fine
Thanks for the help
