### ISSUE TITLE
Vulnerability identified in patched library

### ISSUE THREAD

**Issue by ChristopherSchultz** [dependency-check/DependencyCheck#890]
DependencyCheck correctly identifies `commons-fileupload-1.3.3.jar` as `cpe:/a:apache:commons_fileupload:1.3.3`, but then reports that it is vulnerable to [CVE-2016-1000031](https://nvd.nist.gov/vuln/detail/CVE-2016-1000031). commons-fileupload 1.3.3 was specifically released to fix that CVE (versions *prior* to 1.3.3 are affected, 1.3.3 and later are not), so I believe the version-matching is off somewhere in the process.

**Comment by stevespringett** [comment]
It appears the MITRE made a change on July 17 to include "before 1.3.3" in the description but did not update the CPE to reflect this change. Dependency-Check uses the CPE information to determine what versions are affected.

**Comment by jeremylong** [comment]
The issue is that dependency-check really relies on the data sources (in this case the NVD) to provide accurate information - especially regarding the vulnerable `Vulnerable Software and Configurations` section. As @stevespringett pointed out the the NVD has not been updated with the more specific information and as such, ODC will continue to flag this vulnerability.  The best that can be done is contacting Mitre and/or NVD and requesting the record be updated.

**Comment by OlivierJaquemet** [comment]
@ChristopherSchultz @stevespringett Have a look at issue https://github.com/jeremylong/DependencyCheck/issues/910 in which I contacted the NVD to request a DB update for CVE-2016-1000031. 
The update was performed on friday 2017/10/13 with the correct information. You should no longer see any false report and can probably close this issue.

**Comment by jeremylong** [comment]
Thanks

**Comment by ChristopherSchultz** [comment]
Just circling-back... this library no longer triggers a false-positive. Thanks.
