### ISSUE TITLE
 java.lang.ClassCastException on v2.1.1

### ISSUE THREAD

**Issue by dspringer** [dependency-check/DependencyCheck#918]
Using Dependency Check v2.1.1
Using Jenkins v 2.32.3

I previously saw a very similar error pre-v2.1.1, but after upgrading, that project passed. Now I am seeing this error.

```
[DependencyCheck] Analyzing Dependencies
[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: java.lang.ClassCastException
[DependencyCheck] Message: javax.json.JsonValue$1 cannot be cast to javax.json.JsonNumber
[DependencyCheck] java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonNumber
[DependencyCheck] at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonNumber(JsonObjectBuilderImpl.java:189)
```
Any help would be greatly appreciated!

**Comment by stevespringett** [comment]
This is an issue with the NSP data feed. There is one NSP advisory ([533](https://nodesecurity.io/advisories/533) that we know of) that does not have a CVSS score associated with it. Dependency-Check assumes every vulnerability will have a score so it can figure out the severity. 

The issue has been fixed in https://github.com/jeremylong/DependencyCheck/commit/9c0a166b7d54b26cb366d94e0c29f557fd75f89e#diff-0d61e60306b3c0e9b03d47117a1ef08d and will be available in the next release.

**Comment by dspringer** [comment]
Thanks @stevespringett when do you think that will be?

**Comment by stevespringett** [comment]
Realistically, I think we're a week away, maybe two.
