### ISSUE TITLE
Adding Support for External DB

### ISSUE THREAD

**Issue by mystel09** [dependency-check/DependencyCheck#920]
I am trying to connect my internal Hadoop cluster to Dependency Check instead of using the local file paths for NVD or connecting to the NVD db. Do I need another init file other than the ones online / what do I need to make this happen. It uses SQL.

**Comment by jeremylong** [comment]
You would need to follow the instructions about the init scripts found [here](https://jeremylong.github.io/DependencyCheck/data/database.html). Since this is a Hadoop cluster - you may need to create your own init scripts (which you would execute outside of ODC). In addition, if the SQL statements found in the `dbStatements.properties` file (found [here](https://github.com/jeremylong/DependencyCheck/tree/master/dependency-check-core/src/main/resources/data)) then you would likely need to create a dialect (similar too the `dbStatements_mysql.properties` to provide the correct SQL statements to ODC. To utilize the dialect you would likely need to recompile ODC locally or submit a PR to include the dialect.
