### ISSUE TITLE
False positive: MySQL JDBC driver reported as cpe:/a:mysql:mysql

### ISSUE THREAD

**Issue by OlivierJaquemet** [dependency-check/DependencyCheck#952]
False positive :
- reported by `dependency-check-maven 3.0.1`
- on library `mysql-connector-java-5.1.41.jar`
- reported as `cpe:/a:mysql:mysql:5.1.41`

`mysql-connector-java-5.1.41.jar (cpe:/a:mysql:mysql:5.1.41, cpe:/a:oracle:connector%2fj:5.1.41, cpe:/a:sun:mysql_connector/j:5.1.41, cpe:/a:oracle:mysql:5.1.41, mysql:mysql-connector-java:5.1.41, cpe:/a:oracle:mysql_connectors:5.1.41) :  ...`

```xml
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.44</version>
</dependency>
```
https://mvnrepository.com/artifact/mysql/mysql-connector-java

**Comment by milo-minderbinder** [comment]
I ran into this issue as well, and was wondering if someone more knowledgable than me could provide some guidance on how to use a hints file and/or suppression file to manually add the correct mysql server version, since connector 5.1.X supports MySQL 4.1 and 5.[1-7]  [as documented here](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-versions.html). It seems to be especially challenging to do so due, to the base hints which add vendor identifiers for oracle and sun mysql products (including connectors). It didn't seem possible to suppress cpe:a/:oracle:mysql without unintentionally suppressing cpe:a/:oracle:mysql_connector.

**Comment by jeremylong** [comment]
I will look into this and try to include a patch in the next version (likely a combination of suppression and/or hint rules).

**Comment by felipythondev** [comment]
Hi! Would like to know if there is any update about this false positives eve with the most updated version of it without breaking changes.

I have a report with 444 vulnerabilities and not sure if this is right or not.
![image](https://user-images.githubusercontent.com/5021565/33397422-b6b1a61e-d532-11e7-9ca3-ecab8e5dd9de.png)

@OlivierJaquemet @jeremylong any tip?

**Comment by jeremylong** [comment]
@lipemorais I'm working on a new release now - but in the meantime I would highly recommend creating your own suppression file locally to deal with FP when they arise.
