### ISSUE TITLE
dependency-check.sh should have an option for plain-text results, too.

### ISSUE THREAD

**Issue by ka7** [dependency-check/DependencyCheck#979]
currently, i find the output of the shell-script it hard to quick-understand, as the xml/json are hard to read, and the html with all the JS even harder ( with cmdline tools like ´more´).

An option to have similar output like generated by the gradle-plugin or so would be nice.

**Comment by jeremylong** [comment]
There is a CSV version of the report that might work for you?

**Comment by aw-was-here** [comment]
Let's acknowledge that CSV is a pretty terrible format without a higher-level language involved.  However, in some circumstances, that's all one has to rely on.

That said...

The current format of the CSV output is actually very tricky/near impossible to read from tools like awk due to the ordering of the fields and the inconsistency of quoting.  The naive approach shows just how difficult this is:

```bash
awk -F, '{print $4":"$13":"$18}' dependency-check-report.csv
```

Field 4 only prints the jar when the ScanDate is in a US format.  By the time awk gets to field 13, it has already crossed through Description, License, and CPE which may or may not have commas in it. CWE may or may not have content in it. One is at the mercy of the submitter in the Vulnerability field.  By the time awk finally gets to Severity, one of the most important fields, it has crossed through a minefield.

Making the awk smarter by using a fairly complex FPAT helps, but isn't much better.  Pushing fixed fields (the ones without commas or the ones guaranteed to have a certain number of commas) to the front, offering a format without the extra text descriptions, and/or allowing users to specify what fields they want in the CSV would help tremendously.  Chances are if someone is forced to read the CSV file, they have fairly limited amounts of data they want out of it.
