### ISSUE TITLE
resolution of vulnerability ( dependency check ) 

### ISSUE THREAD

**Issue by ammy1999** [dependency-check/DependencyCheck#981]
Please, how can I resolve vulnerability 
I integrate the plugin dependency check in jenkins , the dashboard appear, but Now how can I resolve especially the high priority vulnerability !! 
any help please , thanks

**Comment by jeremylong** [comment]
I am a lot less familiar with the Jenkins plugin - so @stevespringett may need to correct me. When dependency-check is executed data goes to the dashboard which is what you are seeing. In addition, an HTML report should be generated in the workspace. That [HTML report](https://jeremylong.github.io/DependencyCheck/general/thereport.html) can be used to determine if any of the findings are [false positives](https://jeremylong.github.io/DependencyCheck/general/suppression.html). After a first pass at the report you can then upgrade the vulnerable components.

**Comment by stevespringett** [comment]
@ammy1999 What do you mean by _resolve_?

The Jenkins plugin behaves nearly identical to the Dependency-Check command line interface. It scans a directory inside your project workspace and outputs a report. The Jenkins plugin will always output an XML report for use in the publisher, but can also output an optional HTML report as well. You'll have to download this file locally however in order to view it. The default Content Security Policy in Jenkins will prevent the HTML report from being viewed correctly.

The Jenkins plugin has two parts, the builder (scans the workspace) and the publisher (publishes the results to the job console and is responsible for trending).

**Comment by ammy1999** [comment]
thanks @stevespringett  
par exemple , I have this vulnerability CVE-2010-2542 , Severity: High Stack-based buffer overflow in the is_git_directory function in setup.c in Git before 1.7.2.1 allows local users to gain privileges via a long gitdir: field in a .git file in a working copy. how can i resolve it , !!

**Comment by stevespringett** [comment]
If this is a true positive, then upgrade the version of the affected component, in this case git. If this is a false positive, then suppress it so it doesn't show up any more in the reports.

**Comment by ammy1999** [comment]
what is the difference exactly between  true positive and alse positive please ?? then how can I suppress false positive, where i must add the code !

**Comment by stevespringett** [comment]
Refer to https://jeremylong.github.io/DependencyCheck/general/internals.html for how dependency check works and https://jeremylong.github.io/DependencyCheck/general/suppression.html for suppressing false positives.

**Comment by ammy1999** [comment]
thanks @stevespringett  :)

**Comment by ammy1999** [comment]
when I upgrade the version , the vulnerability still exist, so what should I do !!

**Comment by jeremylong** [comment]
@ammy1999 what are you scanning? A Java application? What dependency is being flagged as being vulnerable to `CVE-2010-2542`?

**Comment by ammy1999** [comment]
@jeremylong  I scanning a maven project , par example , I Have a high vulnerability  CVE-2006-0550
( plugin dependency check jenkins) ,  the vulnerability related to  jersey-apache-client4-1.19.1 ( I upgraded the version to 1.19.4 , but the vulnerability still exist. Then, jersey-apache-client4-1.19.1 is related to spring-cloud-starter-ribbon.

**Comment by jeremylong** [comment]
The issue is still being flagged because it is a false positive. Jersey Apache Client is not the same thing as Oracle Client that is listed in [CVE-2006-0550](https://nvd.nist.gov/vuln/detail/CVE-2006-0550).

Please read [How dependency-check works](https://jeremylong.github.io/DependencyCheck/general/internals.html), [Reading the report](https://jeremylong.github.io/DependencyCheck/general/thereport.html), and [Suppressing False Positives](https://jeremylong.github.io/DependencyCheck/general/suppression.html).

**Comment by ammy1999** [comment]
No , it is the same, /lib/jersey-apache-client4-1.17.jar , CVE-2006-0550 , Severity: High 
Buffer overflow in an unspecified Oracle Client utility might allow remote attackers to execute arbitrary code or cause a denial of service. NOTE: due to the lack of relevant details from the Oracle advisory, a separate CVE is being created since it cannot be conclusively proven that this issue has been addressed by Oracle. It is possible that this is the same issue as Oracle Vuln# DBC02 from the January 2006 CPU, in which case this would be a duplicate of CVE-2006-0283. However, there are enough inconsistencies that the mapping can not be made authoritatively.

**Comment by jeremylong** [comment]
I'm pretty confident that `jersey-apache-client4` is not the same as `Oracle Client Utility`; this is a false positive that should be suppressed.

**Comment by ammy1999** [comment]
@jeremylong  yes it is a false positive, but I can't unterstand why this vulnerability appear ??, I check the code source in 
dependencycheck-base-suppression.xml
`<suppress base="true">
        <notes><![CDATA[
        Supresses false positives on jersey-apache-client4
        ]]></notes>
        <gav regex="true">com\.advyteam\.jersey\.contribs:jersey-apache-client.*</gav>
        <cpe>cpe:/a:apache:httpclient</cpe>
    </suppress>`

So , how can I add the suppression file to work automatically ??? 
help please , thanks

**Comment by jeremylong** [comment]
@ammy1999 simply use the HTML report to generate the suppression file (this is generally the easiest as there are suppress buttons for either CPE or CVE matches - the popup dialog has the ability to generate the "complete" xml file so that it includes the correct namespace).  Note, if using Jenkins - the default CSP prevents the HTML report from working correctly when loading the report directly from the workspace; you must download the report to your desktop and open the HTML report there for the suppression buttons to work.

Once you have the file, simply reference it in the configuration of dependency-check (if using the CLI there is a command line argument, if using one of the other build plugins there is a configuration option).  Take a look at the [documentation site](https://jeremylong.github.io/DependencyCheck/).

**Comment by ammy1999** [comment]
Hello, Thanks for your response , but just a question , per exemple I have a vulnerability in ognl-3.0.8.jar 
When I update the version ,or when I add  `<suppress>
        <notes><![CDATA[
   file name: ognl-3.0.8.jar
   ]]></notes>
        <gav regex="true">^ognl:ognl:.*$</gav>
        <cpe>cpe:/a:ognl_project:ognl</cpe>
    </suppress>
    <suppress>
        <notes><![CDATA[
   file name: ognl-3.0.8.jar
   ]]></notes>
        <gav regex="true">^ognl:ognl:.*$</gav>
        <cve>CVE-2016-3093</cve>
    </suppress>`
in suppressions.xml , the vulnerability is removed , so can I know the priority !!

**Comment by jeremylong** [comment]
I'm not entirely sure what you are asking?

**Comment by ammy1999** [comment]
I should update the version of the dependency or add the suppress code in suppressions.xml to delete the vulnerability ??

**Comment by jeremylong** [comment]
I'd suggest both ;) .  In reality, it is always a good idea to keep up with the latest dependencies. That being said, you can just add the suppression file to suppress the vulnerability.

**Comment by ammy1999** [comment]
Hello, When I add the suppression file and update the version, the vulnerability disappear,  then when I add the plugin in jenkins, dependency check plugin doesn't appear ( in the right of the screen ) , I can't understand why !!! I need to appear the table , also when the number of vulnerability equal  0

**Comment by stevespringett** [comment]
@ammy1999 You can specify the path and filename to the suppression file in the Jenkins job configuration. Click on the advanced button and you'll see something like this:
<img width="954" alt="screen shot 2018-01-02 at 10 20 28 am" src="https://user-images.githubusercontent.com/3878933/34491013-651bc76e-efa7-11e7-9db3-f61980b1161c.png">

The suppression file path is relative to the project workspace. So specifying suppressions.xml is the same as specifying ${WORKSPACE}/suppressions.xml

**Comment by ammy1999** [comment]
Thanks @stevespringett  for your response, 
Yes, I specify the suppressions file name and I stage named dependency check in the pipeline, and it works fine, at first , it appears the plugin 
![screenshot from 2018-01-02 17 41 23](https://user-images.githubusercontent.com/20085759/34491582-46a6dc28-efe4-11e7-8c82-bc79b018508a.png) 

but then when I modify the suppression file with the suppress code and I update the version, this plugin not appear 
![screenshot from 2018-01-02 17 38 46](https://user-images.githubusercontent.com/20085759/34491619-6fe64e52-efe4-11e7-9fbe-e9b38fc60de9.png)

So , when there is no vulnerabilities , the plugin doesn't appear !!

**Comment by stevespringett** [comment]
That is expected behavior. All plugins built on analysis-core (FindBugs, PMD, CheckStyle, Twistlock, Dependency-Check, etc) behave the same way. 

If you go into the actual build number however, you'll see that 0 vulnerabilities are found.
<img width="960" alt="screen shot 2018-01-02 at 10 52 44 am" src="https://user-images.githubusercontent.com/3878933/34491981-4ce9e8ac-efab-11e7-908e-fce26a546313.png">

**Comment by ammy1999** [comment]
Thanks @stevespringett  :) 
please ,  How can I add the suppress code when the project is not maven  ( so I can't add plugin maven dependency check , then the page html is not generated ) ,where can I find the suppress code of the vulnerability ? thanks

**Comment by stevespringett** [comment]
@ammy1999 If you go into 'voir la configuration', you should see the build steps. If you are using the Jenkins plugin as a build step, you should see something similar to the screenshot I posted earlier. 

<img width="954" alt="screen shot 2018-01-02 at 10 20 28 am" src="https://user-images.githubusercontent.com/3878933/34491013-651bc76e-efa7-11e7-9db3-f61980b1161c.png">

You will need to have rights to edit the job. If you do not have rights, you may only be able to view the configuration, not edit it. You'll need to contact your Jenkins administrator if this is the case.
